/** BCM1 bcm1_a12–a21 × 12 — node scripts/append_flashcards_bcm1_m2_part2.js */
const fs = require('fs');
const path = require('path');
const OUT = path.join(__dirname, '..', 'data', 'flashcards.json');
function c(t, f, v, e, cat, o, tags) {
  return { materia: 'bcm1', tema: t, frente: f, verso: v, explicacao: e || '', dificuldade: 2, categoria: cat, origem: o, tags: tags || [] };
}
const LOTS = [
  [ // bcm1_a12
    c('bcm1_a12', 'PCR: após n ciclos, amplificação teórica?', '2ⁿ cópias da região-alvo.', '', 'definicao', 'material', ['pcr']),
    c('bcm1_a12', 'RT-PCR: etapa extra vs PCR de DNA?', 'Transcrição reversa RNA→cDNA antes da amplificação.', '', 'diferenciacao', 'material', ['rt-pcr']),
    c('bcm1_a12', 'qPCR: como quantifica?', 'Fluorescência em tempo real proporcional ao produto.', '', 'definicao', 'material', ['qpcr']),
    c('bcm1_a12', 'Eletroforese em agarose: DNA migra para qual polo?', 'Polo positivo (DNA negativo).', '', 'prova', 'material', ['gel']),
    c('bcm1_a12', 'Fragmentos menores no gel migram?', 'Mais rápido.', '', 'definicao', 'material', ['gel']),
    c('bcm1_a12', 'Sanger usa ddNTPs para?', 'Terminar cadeia em bases específicas — leitura da sequência.', '', 'mecanismo', 'material', ['sanger']),
    c('bcm1_a12', 'NGS vs Sanger em volume?', 'NGS paraleliza milhões de leituras; Sanger lê um fragmento por vez.', '', 'diferenciacao', 'material', ['ngs']),
    c('bcm1_a12', 'WES significa?', 'Exoma — sequenciamento dos exons.', '', 'definicao', 'material', ['exoma']),
    c('bcm1_a12', 'VCF em bioinformática?', 'Variant Call Format — arquivo de variantes.', '', 'definicao', 'material', ['vcf']),
    c('bcm1_a12', 'CRISPR-Cas9: função básica?', 'Corte dirigido de DNA guiado por RNA (editing genômico).', '', 'definicao', 'material', ['crispr']),
    c('bcm1_a12', 'LAMP: vantagem prática?', 'Isotérmica — menos dependência de termociclador (campo).', '', 'clinica', 'extra', ['lamp']),
    c('bcm1_a12', 'Southern blot detecta?', 'DNA específico após digestão/hibridização (vs Northern RNA, Western proteína).', '', 'extra_livro', 'extra', ['blot']),
  ],
  [ // bcm1_a13
    c('bcm1_a13', 'Quadrado no heredograma?', 'Masculino.', '', 'definicao', 'material', ['heredograma']),
    c('bcm1_a13', 'Autossômico dominante: transmissão típica?', 'Vertical — geração a geração; 50% se um progenitor heterozigoto afetado.', '', 'prova', 'material', ['ad']),
    c('bcm1_a13', 'AR: risco se ambos portadores?', '25% afetado; 50% portador; 25% normal (cada gestação).', '', 'prova', 'material', ['ar']),
    c('bcm1_a13', 'XLR: homem afetado transmite mutação do X aos filhos?', 'Filhos recebem Y — não transmite o X afetado aos filhos; filhas são portadoras.', '', 'prova', 'material', ['xlr']),
    c('bcm1_a13', 'Consanguinidade aumenta risco principalmente em?', 'AR — aumenta chance de homozigose do mesmo alelo.', '', 'clinica', 'material', ['consanguinidade']),
    c('bcm1_a13', 'Penetrância incompleta?', 'Portador do alelo mas sem fenótipo — percentual <100%.', '', 'definicao', 'material', ['penetrancia']),
    c('bcm1_a13', 'Expressividade variável?', 'Mesmo genótipo, grau de fenótipo diferente entre indivíduos.', '', 'definicao', 'material', ['expressividade']),
    c('bcm1_a13', 'Herança mitocondrial: transmissão?', 'Exclusivamente materna (na maioria).', '', 'definicao', 'material', ['mitocondrial']),
    c('bcm1_a13', 'Imprinting: o que muda?', 'Expressão depende da origem parental do alelo.', '', 'mecanismo', 'material', ['imprinting']),
    c('bcm1_a13', 'Mosaicismo germinativo vs somático?', 'Germinativo transmite à prole; somático afeta tecidos em mosaico.', '', 'diferenciacao', 'material', ['mosaico']),
    c('bcm1_a13', 'Antecipação: exemplo clássico?', 'Huntington — repetições CAG aumentam nas gerações.', '', 'clinica', 'extra', ['antecipacao']),
    c('bcm1_a13', 'Dois golpes de Knudson aplicam-se a?', 'Genes supressores tumorais (RB1 clássico).', '', 'extra_livro', 'extra', ['knudson']),
  ],
  [ // bcm1_a14
    c('bcm1_a14', 'Aneuploidia: definição?', 'Número de cromossomos não múltiplo exato do haplóide (ex.: 47).', '', 'definicao', 'material', ['aneuploidia']),
    c('bcm1_a14', 'Não-disjunção: onde ocorre erro clássico?', 'Meiose I (homólogos) ou II (cromátides) ou mitose (mosaico).', '', 'mecanismo', 'material', ['nao-disjuncao']),
    c('bcm1_a14', 'Down: cariótipo mais comum?', 'Trissomia livre 47,XX/XY,+21 (~95%).', '', 'clinica', 'material', ['down']),
    c('bcm1_a14', 'Down por translocação robertsoniana frequente?', 't(14;21) ou t(21;21) — ~4% dos casos.', '', 'clinica', 'material', ['translocacao']),
    c('bcm1_a14', 'Síndrome de Edwards: trissomia?', '18 — múltiplas malformações, alta mortalidade.', '', 'clinica', 'material', ['edwards']),
    c('bcm1_a14', 'Síndrome de Patau: trissomia?', '13.', '', 'clinica', 'material', ['patau']),
    c('bcm1_a14', 'Turner: cariótipo clássico?', '45,X — fenótipo feminino, baixa estatura, disgenesia gonadal.', '', 'clinica', 'material', ['turner']),
    c('bcm1_a14', 'Klinefelter: cariótipo clássico?', '47,XXY — hipogonadismo, infertilidade.', '', 'clinica', 'material', ['klinefelter']),
    c('bcm1_a14', 'Risco de trissomias aumenta com?', 'Idade materna (oócito em meiose I prolongada).', '', 'clinica', 'material', ['idade-materna']),
    c('bcm1_a14', 'NIPT analisa principalmente?', 'DNA fetal livre no sangue materno — rastreio de aneuploidias.', '', 'clinica', 'material', ['nipt']),
    c('bcm1_a14', 'Triploidia: viabilidade?', 'Quase sempre aborto espontâneo; raramente nascimento.', '', 'extra_livro', 'extra', ['triploidia']),
    c('bcm1_a14', 'Mosaicismo de Down implica?', 'Fenótipo possivelmente mais leve (mistura 46/47).', '', 'extra', 'extra', ['mosaico']),
  ],
  [ // bcm1_a15
    c('bcm1_a15', 'Deleção 5p: síndrome?', 'Cri-du-chat — miado de gato, RI leve/moderado.', '', 'clinica', 'material', ['cri-du-chat']),
    c('bcm1_a15', 'Translocação balanceada: risco em filhos?', 'Gametas desbalanceados → aneuploidia ou aborto.', '', 'clinica', 'material', ['translocacao']),
    c('bcm1_a15', 'Inversão paracentrica vs pericêntrica?', 'Para: não cruza centrômero; Peri: envolve centrômero.', '', 'definicao', 'material', ['inversao']),
    c('bcm1_a15', 'Isocromossomo: definição?', 'Braços idênticos — perda de material complementar.', '', 'definicao', 'material', ['isocromossomo']),
    c('bcm1_a15', 'Síndrome de Wolf–Hirschhorn: deleção?', '4p — microcefalia, epicanthus, convulsões.', '', 'clinica', 'material', ['wolf-hirschhorn']),
    c('bcm1_a15', 'DiGeorge: defeito típico?', 'Deleção 22q11 — cardiopatia, hipocalcemia, timo.', '', 'clinica', 'material', ['digeorge']),
    c('bcm1_a15', 'Cromossomo Philadelphia estruturalmente?', 't(9;22) — BCR-ABL.', '', 'clinica', 'material', ['ph']),
    c('bcm1_a15', 'Fusão gênica por translocação pode?', 'Criar oncogene (ex.: BCR-ABL).', '', 'mecanismo', 'material', ['fusao']),
    c('bcm1_a15', 'Cariótipo de alta resolução?', 'Banda mais fina — melhor ver microdeleções.', '', 'definicao', 'material', ['bandamento']),
    c('bcm1_a15', 'FISH: princípio?', 'Sonda fluorescente hibridiza região específica — visualização microdeleção/duplicação.', '', 'clinica', 'material', ['fish']),
    c('bcm1_a15', 'CNV significa?', 'Copy number variation — ganho/perda de segmento.', '', 'extra_livro', 'extra', ['cnv']),
    c('bcm1_a15', 'aCGH compara?', 'DNA do paciente vs referência em microarray — CNVs.', '', 'extra', 'extra', ['acgh']),
  ],
  [ // bcm1_a16
    c('bcm1_a16', 'Disgenesia gonadal 46,XY: risco?', 'Tumor (disgerminoma) em gônadas intra-abdominais — gonadectomia.', '', 'clinica', 'material', ['disgenesia']),
    c('bcm1_a16', 'Síndrome de Turner com mosaico Y?', 'Risco de gonadoblastoma — vigilância/cirurgia.', '', 'clinica', 'material', ['gonadoblastoma']),
    c('bcm1_a16', 'Gene SRY: onde atua?', 'Cromossomo Y — determina testículo (via SOX9).', '', 'mecanismo', 'material', ['sry']),
    c('bcm1_a16', 'Hiperplasia adrenal congênita 21-OH: herança?', 'AR — deficiência de cortisol, excesso de androgênios.', '', 'clinica', 'material', ['hac']),
    c('bcm1_a16', 'Andrógeno insensível completo: cariótipo?', '46,XY — fenótipo feminino externo, testículos intra-abdominais.', '', 'clinica', 'material', ['sai']),
    c('bcm1_a16', '5α-redutase deficiência: fenótipo na puberdade?', 'Virilização por ↑ testosterona DHT após puberdade.', '', 'clinica', 'material', ['5ar']),
    c('bcm1_a16', 'Klinefelter: tratamento hormonal comum?', 'Testosterona substitutiva na puberdade/adulto.', '', 'clinica', 'material', ['trt']),
    c('bcm1_a16', 'Ovotesticular DSD: conceito?', 'Tecido testicular e ovariano (raro).', '', 'definicao', 'material', ['ovotesticular']),
    c('bcm1_a16', 'Cariótipo 45,X/46,XY: espectro?', 'Mosaico — fenótipo variável de Turner a genitais ambíguos.', '', 'clinica', 'material', ['mosaico-xy']),
    c('bcm1_a16', 'Genitografia e estudos hormonais servem para?', 'Investigar DSD — junto com cariótipo e USG.', '', 'clinica', 'material', ['dsd']),
    c('bcm1_a16', 'Princípio ético em DSD: evitar?', 'Cirurgia cosmética precoce sem consentimento informado.', '', 'extra_livro', 'extra', ['etica']),
    c('bcm1_a16', 'AMH elevado em 46,XX DSD sugere?', 'Presença de tecido testicular (ex.: cópias SRY).', '', 'extra', 'extra', ['amh']),
  ],
  [ // bcm1_a17
    c('bcm1_a17', 'XLR: homens afetados vs mulheres?', 'Muito mais homens afetados (hemizigosidade).', '', 'prova', 'material', ['xlr']),
    c('bcm1_a17', 'Hemofilia A: fator deficiente?', 'FVIII — gene F8 (Xq28).', '', 'clinica', 'material', ['hemofilia-a']),
    c('bcm1_a17', 'Hemofilia B: fator?', 'FIX — gene F9.', '', 'clinica', 'material', ['hemofilia-b']),
    c('bcm1_a17', 'Duchenne: proteina mutada?', 'Distrofina — gene DMD (X).', '', 'clinica', 'material', ['dmd']),
    c('bcm1_a17', 'Becker vs Duchenne?', 'Becker — distrofina parcialmente funcional (mais leve).', '', 'diferenciacao', 'material', ['becker']),
    c('bcm1_a17', 'X-frágil: marcador molecular?', 'Expansão de CGG no gene FMR1 — antecipação.', '', 'clinica', 'material', ['x-fragi']),
    c('bcm1_a17', 'XLD: pai afetado transmite a filhos?', 'Filhos recebem Y — não recebem X paterno; filhas recebem X afetado — todas portadoras/afetadas conforme gene.', '', 'prova', 'material', ['xld']),
    c('bcm1_a17', 'Ret síndrome: herança típica?', 'XLD — quase só em meninas (letal em muitos XY).', '', 'clinica', 'material', ['rett']),
    c('bcm1_a17', 'Inativação do X e portadora de DMD?', 'Skewed X-inactivation pode causar sintomas leves.', '', 'clinica', 'material', ['lionizacao']),
    c('bcm1_a17', 'Terapia com concentrado de FVIII indica?', 'Hemofilia A — episódios e profilaxia.', '', 'clinica', 'material', ['fviii']),
    c('bcm1_a17', 'Emicizumabe: uso em hemofilia A?', 'Anticorpo bispecífico — profilaxia (mecanismo tipo FVIII).', '', 'extra_livro', 'extra', ['hemofilia']),
    c('bcm1_a17', 'Gene G6PD: herança?', 'XLR — deficiência — hemólise por oxidantes.', '', 'extra', 'extra', ['g6pd']),
  ],
  [ // bcm1_a18
    c('bcm1_a18', 'Anemia falciforme: mutação?', 'HBB Glu6Val — hemoglobina S.', '', 'clinica', 'material', ['falciforme']),
    c('bcm1_a18', 'Traço falciforme: fenótipo?', 'Heterozigoto geralmente assintomático (resistência à malária).', '', 'clinica', 'material', ['traco']),
    c('bcm1_a18', 'Talassemia α: genes?', 'Dois genes HBA1/HBA2 no cromossomo 16.', '', 'definicao', 'material', ['talassemia-a']),
    c('bcm1_a18', 'Talassemia β: herança?', 'AR — gene HBB.', '', 'definicao', 'material', ['talassemia-b']),
    c('bcm1_a18', 'Fibrose cística: gene?', 'CFTR — cloreto (AR).', '', 'clinica', 'material', ['cf']),
    c('bcm1_a18', 'CF: órgãos mais comprometidos?', 'Pulmão (infecções) e pâncreas (PI).', '', 'clinica', 'material', ['cf']),
    c('bcm1_a18', 'Teste do pezinho CF?', 'IRT elevado + confirmação genética/suor.', '', 'clinica', 'material', ['triagem']),
    c('bcm1_a18', 'HbE + β-talassemia: contexto?', 'Interação de alelos — fenótipo variável.', '', 'clinica', 'material', ['hb-e']),
    c('bcm1_a18', 'Hidropsia fetalis: causa α?', 'Perda de 4 alelos α (deleção).', '', 'clinica', 'material', ['hidropsia']),
    c('bcm1_a18', 'Moduladores CFTR: exemplo?', 'Ivacaftor em certas mutações gating (depende de genótipo).', '', 'clinica', 'material', ['ivacaftor']),
    c('bcm1_a18', 'Punção de cordão em AR: risco recorrência?', '25% se ambos portadores.', '', 'extra_livro', 'extra', ['aconsehamento']),
    c('bcm1_a18', 'HbS sob desoxigenação: o que ocorre?', 'Polimerização — falcização eritrocitária.', '', 'extra', 'extra', ['falcizacao']),
  ],
  [ // bcm1_a19
    c('bcm1_a19', 'PKU: enzima deficiente?', 'Fenilalanina hidroxilase (PAH) — AR.', '', 'clinica', 'material', ['pku']),
    c('bcm1_a19', 'PKU: tratamento dietético?', 'Restrição de fenilalanina desde neonato — previne RI.', '', 'clinica', 'material', ['pku']),
    c('bcm1_a19', 'Galactosemia clássica: enzima?', 'GALT — AR.', '', 'clinica', 'material', ['galactosemia']),
    c('bcm1_a19', 'Galactosemia: evitar leite por?', 'Galactose tóxica — catarata, falência hepática.', '', 'clinica', 'material', ['galactosemia']),
    c('bcm1_a19', 'Frutosemia hereditária: enzima?', 'Aldolase B — AR; evitar frutose/sacarose.', '', 'clinica', 'material', ['frutosemia']),
    c('bcm1_a19', 'Defeito de biopterina na PKU?', 'Forma não responsiva só à dieta — precisa de cofatores.', '', 'clinica', 'material', ['biopterina']),
    c('bcm1_a19', 'Triagem neonatal PKU mede?', 'Fenilalanina no sangue em papel de filtro.', '', 'prova', 'material', ['triagem']),
    c('bcm1_a19', 'Erro inato do metabolismo: padrão hereditário comum?', 'AR (muitas enzimas lisossomais e vias).', '', 'definicao', 'material', ['eim']),
    c('bcm1_a19', 'Mãe com PKU não tratada na gestação: risco fetal?', 'Teratogenicidade por fenilalanina elevada — controle pré-concepcional.', '', 'clinica', 'material', ['gestacao']),
    c('bcm1_a19', 'Sapropterina: uso em PKU?', 'Alguns casos de mutações responsivas (BH4).', '', 'clinica', 'material', ['sapropterina']),
    c('bcm1_a19', 'Mapa de metabolitos (MS/MS) no recém-nascido?', 'Amplia triagem para múltiplos EIM.', '', 'extra_livro', 'extra', ['msms']),
    c('bcm1_a19', 'Lactente com vômitos após leite: pensar?', 'Galactosemia clássica entre diagnósticos diferenciais.', '', 'extra', 'extra', ['neonato']),
  ],
  [ // bcm1_a20
    c('bcm1_a20', 'Huntington: herança?', 'AD — gene HTT com repetições CAG.', '', 'clinica', 'material', ['huntington']),
    c('bcm1_a20', 'Marfan: gene?', 'FBN1 — AD — tecido conjuntivo.', '', 'clinica', 'material', ['marfan']),
    c('bcm1_a20', 'ADPKD: genes principais?', 'PKD1 e PKD2 — AD.', '', 'clinica', 'material', ['adpkd']),
    c('bcm1_a20', 'Hipercolesterolemia familiar: receptor?', 'LDLR — AD — LDL muito elevado.', '', 'clinica', 'material', ['hf']),
    c('bcm1_a20', 'Retinoblastoma hereditário: gene?', 'RB1 — AD com alta penetrância — dois golpes na retina.', '', 'clinica', 'material', ['rb']),
    c('bcm1_a20', 'Neurofibromatose 1: gene?', 'NF1 — AD — manchas café-com-leite, neurofibromas.', '', 'clinica', 'material', ['nf1']),
    c('bcm1_a20', 'Acondroplasia: gene?', 'FGFR3 — AD — nanismo desproporcional.', '', 'clinica', 'material', ['acondroplasia']),
    c('bcm1_a20', 'Doença de Huntington: exame de imagem precoce?', 'Pode ser normal; diagnóstico molecular.', '', 'clinica', 'material', ['hd']),
    c('bcm1_a20', 'Marfan: complicação cardiovascular clássica?', 'Dilatação de raiz aórtica / dissecção — ecocardiograma.', '', 'clinica', 'material', ['aorta']),
    c('bcm1_a20', 'Estatinas em HF: mecanismo?', '↓ síntese hepática de colesterol → ↑ receptores LDL.', '', 'clinica', 'material', ['estatina']),
    c('bcm1_a20', 'Penetrância em ADPKD?', 'Quase completa ao longo da vida — vigilância renal.', '', 'extra_livro', 'extra', ['penetrancia']),
    c('bcm1_a20', 'Nova mutação em acondroplasia: frequência?', 'Maioria dos casos — pais não afetados.', '', 'extra', 'extra', ['nova-mutacao']),
  ],
  [ // bcm1_a21
    c('bcm1_a21', 'Herança poligênica vs mendeliana?', 'Muitos loci + ambiente — distribuição contínua de risco.', '', 'diferenciacao', 'material', ['poligenico']),
    c('bcm1_a21', 'Herdabilidade (h²) mede?', 'Proporção da variância fenotípica explicada por fatores genéticos na população.', '', 'definicao', 'material', ['herdabilidade']),
    c('bcm1_a21', 'GWAS identifica?', 'SNPs associados a doença (efeitos pequenos individuais).', '', 'definicao', 'material', ['gwas']),
    c('bcm1_a21', 'PRS significa?', 'Polygenic risk score — soma ponderada de alelos de risco.', '', 'definicao', 'material', ['prs']),
    c('bcm1_a21', 'Proto-oncogene ativado vira?', 'Oncogene — ganho de função.', '', 'definicao', 'material', ['oncogene']),
    c('bcm1_a21', 'Supressor tumoral: mutação típica?', 'Perda de função — dois alelos (Knudson).', '', 'definicao', 'material', ['supressor']),
    c('bcm1_a21', 'Sequência Fearon–Vogelstein: primeiro gene frequentemente?', 'APC (adenoma → carcinoma colorretal).', '', 'clinica', 'material', ['apc']),
    c('bcm1_a21', 'KRAS na sequência colorretal?', 'Adenoma avançado — após APC em modelo clássico.', '', 'clinica', 'material', ['kras']),
    c('bcm1_a21', 'TP53 no modelo coloretal tardio?', 'Carcinoma — antes de metástases em parte dos modelos.', '', 'clinica', 'material', ['tp53']),
    c('bcm1_a21', 'Mutação somática vs germinativa?', 'Somática só na célula/tumor; germinativa em todas as células (transmissível).', '', 'diferenciacao', 'material', ['somática']),
    c('bcm1_a21', 'Instabilidade cromossômica em tumor ≠ MSI?', 'CIN é aneuploidia; MSI é defeito de reparo (MMR).', '', 'extra_livro', 'extra', ['cin-msi']),
    c('bcm1_a21', 'Terapia-alvo em BRAF V600E?', 'Inibidores de BRAF/MEK em melanoma (contexto).', '', 'extra', 'extra', ['braf']),
  ],
];

const data = JSON.parse(fs.readFileSync(OUT, 'utf8'));
let id = 0;
for (const f of data.flashcards) if (f.id > id) id = f.id;
id++;
for (const lot of LOTS) for (const x of lot) data.flashcards.push({ ...x, id: id++ });
fs.writeFileSync(OUT, JSON.stringify(data, null, 2), 'utf8');
console.log('OK bcm1 part2 total', data.flashcards.length, 'last id', id - 1);
