/** MAD1 mad1_a1–a12 × 12 cards — node scripts/append_flashcards_mad1_m2_part1.js */
const fs = require('fs');
const path = require('path');
const OUT = path.join(__dirname, '..', 'data', 'flashcards.json');
function c(t, f, v, e, cat, o, tags) {
  return { materia: 'mad1', tema: t, frente: f, verso: v, explicacao: e || '', dificuldade: 2, categoria: cat, origem: o, tags: tags || [] };
}
const LOTS = [
  [ // mad1_a1
    c('mad1_a1', 'Diferença fundamental inata × adaptativa?', 'Inata: rápida e inespecífica; adaptativa: específica e com memória.', '', 'diferenciacao', 'material', ['imunidade']),
    c('mad1_a1', 'Função dos linfócitos B?', 'Produzir anticorpos (imunidade humoral).', '', 'definicao', 'material', ['linfo-b']),
    c('mad1_a1', 'Função dos CD8+?', 'Linfócito T citotóxico — mata células infectadas.', '', 'definicao', 'material', ['cd8']),
    c('mad1_a1', 'Função dos CD4+?', 'T helper — coordena resposta (citocinas).', '', 'definicao', 'material', ['cd4']),
    c('mad1_a1', 'Imunoglobulina predominante no soro?', 'IgG.', '', 'prova', 'material', ['igg']),
    c('mad1_a1', 'IgA secretora: onde atua?', 'Mucosas (imunidade de superfície).', '', 'definicao', 'material', ['iga']),
    c('mad1_a1', 'IgE: papel principal?', 'Defesa parasitária e hipersensibilidade tipo I.', '', 'mecanismo', 'material', ['ige']),
    c('mad1_a1', 'IgM: característica na resposta primária?', 'Primeira a aparecer; pentâmera.', '', 'prova', 'material', ['igm']),
    c('mad1_a1', 'Órgãos linfoides primários?', 'Medula óssea e timo (maturação).', '', 'definicao', 'material', ['linfoide']),
    c('mad1_a1', 'Baço filtra principalmente o quê?', 'Sangue (células e patógenos).', '', 'definicao', 'material', ['baco']),
    c('mad1_a1', 'Microbiota: efeito no sistema imune?', 'Treina imunidade e compete com patógenos (colonização resistente).', '', 'extra_livro', 'extra', ['microbiota']),
    c('mad1_a1', 'Citocinas são produzidas principalmente por?', 'Leucócitos e outras células — sinalização imune.', '', 'definicao', 'extra', ['citocinas']),
  ],
  [ // mad1_a2
    c('mad1_a2', 'PRRs reconhecem o quê?', 'PAMPs (padrões moleculares associados a patógenos).', '', 'definicao', 'material', ['prr']),
    c('mad1_a2', 'Exemplo de PRR de membrana?', 'TLRs (Toll-like receptors).', '', 'prova', 'material', ['tlr']),
    c('mad1_a2', 'Células apresentadoras de antígeno clássicas?', 'DCs, macrófagos, células B (contexto).', '', 'definicao', 'material', ['apc']),
    c('mad1_a2', 'NK mata células com o quê?', 'Baixa expressão de MHC-I ou “stress” (missing self).', '', 'mecanismo', 'material', ['nk']),
    c('mad1_a2', 'Neutrófilo: função principal?', 'Fagocitose bacteriana aguda (pus).', '', 'definicao', 'material', ['neutrofilo']),
    c('mad1_a2', 'Sistema complemento: via clássica inicia com?', 'Ligação de C1 a imunocomplexos IgM/IgG.', '', 'mecanismo', 'material', ['complemento']),
    c('mad1_a2', 'MAC (C5b-9) faz o quê?', 'Forma poro na membrana — lise celular.', '', 'mecanismo', 'material', ['mac']),
    c('mad1_a2', 'Opssonização: exemplos?', 'IgG e fragmento C3b facilitam fagocitose.', '', 'definicao', 'material', ['opsonizacao']),
    c('mad1_a2', 'Inflamassoma NLRP3 ativa o quê?', 'Caspase-1 → IL-1β e IL-18 (inflamação).', '', 'mecanismo', 'material', ['inflamassoma']),
    c('mad1_a2', 'Feitrição medula: neutrófilos primeiro ou monócitos?', 'Neutrófilos (primeira onda).', '', 'prova', 'material', ['medula']),
    c('mad1_a2', 'Interferon tipo I: indução típica?', 'Vírus — antiviral inato.', '', 'extra_livro', 'extra', ['ifn']),
    c('mad1_a2', 'PAMP vs DAMP?', 'PAMP: patógeno; DAMP: dano próprio (alarmins).', '', 'diferenciacao', 'extra', ['damp']),
  ],
  [ // mad1_a3
    c('mad1_a3', 'MHC I apresenta peptídeos a quem?', 'CD8+ (citotoxicidade).', '', 'prova', 'material', ['mhc-i']),
    c('mad1_a3', 'MHC II apresenta peptídeos a quem?', 'CD4+ (helpers).', '', 'prova', 'material', ['mhc-ii']),
    c('mad1_a3', 'MHC II expresso principalmente em?', 'APCs (DC, macrófago, B ativado).', '', 'definicao', 'material', ['mhc-ii']),
    c('mad1_a3', 'TCR reconhece antígeno como?', 'Peptídeo + MHC (restrição).', '', 'definicao', 'material', ['tcr']),
    c('mad1_a3', 'Imunidade humoral é mediada por?', 'Anticorpos (Ig).', '', 'definicao', 'material', ['humoral']),
    c('mad1_a3', 'Classe Ig que cruza placenta?', 'IgG.', '', 'prova', 'material', ['igg']),
    c('mad1_a3', 'Mutação somática e seleção afina o quê?', 'Afinidade de anticorpos no centro germinativo.', '', 'mecanismo', 'material', ['anticorpo']),
    c('mad1_a3', 'Memória imune: células principais?', 'Memória T e B de longa duração.', '', 'definicao', 'material', ['memoria']),
    c('mad1_a3', 'Treg (CD4+CD25+): função?', 'Suprimir autoimunidade e inflamação excessiva.', '', 'clinica', 'material', ['treg']),
    c('mad1_a3', 'Ligação BCR ao antígeno leva a?', 'Ativação, apresentação e diferenciação em plasmócito.', '', 'mecanismo', 'material', ['bcr']),
    c('mad1_a3', 'Superantígeno: mecanismo?', 'Liga MHC II a TCR fora do sulco — ativação policlonal massiva.', '', 'extra_livro', 'extra', ['superantigeno']),
    c('mad1_a3', 'Afinidade vs avidez do anticorpo?', 'Afinidade: um sítio; avidez: soma multivalente.', '', 'diferenciacao', 'extra', ['afinidade']),
  ],
  [ // mad1_a4
    c('mad1_a4', 'Sinais cardeais da inflamação (Calor, Rubor, etc.)?', 'Calor, vermelhidão, inchaço, dor, perda de função (visão clássica).', '', 'definicao', 'material', ['inflamacao']),
    c('mad1_a4', 'Mediadores vasodilatadores da inflamação aguda?', 'Histamina, prostaglandinas, óxido nítrico.', '', 'mecanismo', 'material', ['mediadores']),
    c('mad1_a4', 'Citocinas pró-inflamatórias clássicas?', 'TNF-α, IL-1, IL-6.', '', 'definicao', 'material', ['citocinas']),
    c('mad1_a4', 'Inflamação crônica: células típicas?', 'Macrófagos, linfócitos, fibrose.', '', 'diferenciacao', 'material', ['cronica']),
    c('mad1_a4', 'Granuloma: definição?', 'Agregado de macrófagos epiteloides (muitas vezes TB).', '', 'definicao', 'material', ['granuloma']),
    c('mad1_a4', 'Pirogênese endógena citada?', 'IL-1 e TNF-α (febre).', '', 'mecanismo', 'material', ['febre']),
    c('mad1_a4', 'Leucotrienos: papel?', 'Broncoconstrição e aumento de permeabilidade (asma).', '', 'clinica', 'material', ['leucotrieno']),
    c('mad1_a4', 'Resolução da inflamação envolve?', 'Lipoxinas, resolvinas (pro-resolução).', '', 'mecanismo', 'material', ['resolucao']),
    c('mad1_a4', 'CRP sobe em inflamação aguda por quê?', 'Síntese hepática estimulada por IL-6.', '', 'clinica', 'material', ['pcr']),
    c('mad1_a4', 'VSG mede o quê indiretamente?', 'Proteínas de fase aguda (fibrogênio).', '', 'definicao', 'material', ['vsg']),
    c('mad1_a4', 'NLRP3 e gota: padrão?', 'Cristais de urato ativam inflamassoma — IL-1.', '', 'clinica', 'extra', ['gota']),
    c('mad1_a4', 'Inflamação de baixo grau metabólica associa-se a?', 'Síndrome metabólica e resistência insulínica.', '', 'extra_livro', 'extra', ['metabolico']),
  ],
  [ // mad1_a5
    c('mad1_a5', 'Leucocitose: causa infecciosa comum?', 'Bacteriana aguda (neutrófilos ↑).', '', 'clinica', 'material', ['leucocitose']),
    c('mad1_a5', 'Neutrófilos >80%: termo relativo?', 'Neutrofilia (desvio à esquerda se bastonetes ↑).', '', 'definicao', 'material', ['neutrofilia']),
    c('mad1_a5', 'Linfocitose viral: padrão?', 'Linfócitos ↑ (mononucleose, etc.).', '', 'clinica', 'material', ['linfocitose']),
    c('mad1_a5', 'Eosinofilia sugere?', 'Parasitas, alergia, algumas neoplasias.', '', 'clinica', 'material', ['eosinofilia']),
    c('mad1_a5', 'Anemia microcítica hipocrômica: causa mais comum?', 'Deficiência de ferro.', '', 'clinica', 'material', ['anemia']),
    c('mad1_a5', 'Anemia macrocítica: causa metabólica?', 'B12/folato (deficiência ou uso de fármacos).', '', 'clinica', 'material', ['macrocitica']),
    c('mad1_a5', 'Plaquetopenia: risco?', 'Sangramento (mucosas, petéquias).', '', 'clinica', 'material', ['plaquetas']),
    c('mad1_a5', 'Hemograma: Ht e Hb relacionam-se como?', 'Hematócrito proporcional à concentração de hemácias.', '', 'definicao', 'material', ['ht']),
    c('mad1_a5', 'RDW alto: significa?', 'Anisocitose — variação de tamanho eritrocitário.', '', 'prova', 'material', ['rdw']),
    c('mad1_a5', 'Bastonetes ↑ em infecção bacteriana sugere?', 'Desvio à esquerda (resposta de emergência).', '', 'clinica', 'material', ['bastonetes']),
    c('mad1_a5', 'Reticulócitos ↑ em anemia hemolítica indicam?', 'Medula respondendo (produção aumentada).', '', 'clinica', 'extra', ['reticulocitos']),
    c('mad1_a5', 'VCM e RDW na classificação de anemia?', 'Micro/normo/macrocítica + homogênica ou não.', '', 'prova', 'extra', ['indices']),
  ],
  [ // mad1_a6
    c('mad1_a6', 'Imunização ativa vs passiva?', 'Ativa: induz resposta própria; passiva: anticorpos prontos.', '', 'diferenciacao', 'material', ['vacina']),
    c('mad1_a6', 'Vacina de vírus vivo atenuado: exemplo?', 'Tríplice viral (sarampo, caxumba, rubéola).', '', 'prova', 'material', ['atenuada']),
    c('mad1_a6', 'Vacina inativada: vantagem/desvantagem?', 'Não replica; pode precisar reforços.', '', 'definicao', 'material', ['inativada']),
    c('mad1_a6', 'Vacina de subunidade/recombinante: exemplo?', 'HBV recombinante, acelular pertussis.', '', 'definicao', 'material', ['subunidade']),
    c('mad1_a6', 'Vacinas mRNA: alvo?', 'Síntese de proteína viral no hospedeiro (ex.: spike SARS-CoV-2).', '', 'mecanismo', 'material', ['mrna']),
    c('mad1_a6', 'Vacina conjugada: importância?', 'Polissacarídeo conjugado a proteína — resposta T dependente em crianças.', '', 'mecanismo', 'material', ['conjugada']),
    c('mad1_a6', 'Imunoglobulina anti-Rh: tipo de imunização?', 'Passiva (profilaxia HDN).', '', 'clinica', 'material', ['anti-d']),
    c('mad1_a6', 'Herd immunity: conceito?', 'Proteção indireta quando grande parte da população é imune.', '', 'definicao', 'material', ['imunidade-coletiva']),
    c('mad1_a6', 'Calendário vacinal: objetivo central?', 'Cobertura populacional e eliminação de doenças evitáveis.', '', 'clinica', 'material', ['pnI']),
    c('mad1_a6', 'Contraindicação relativa a vacina viva em?', 'Imunossupressão grave e gravidez (conforme vacina).', '', 'clinica', 'material', ['contraindicacao']),
    c('mad1_a6', 'VIGÍLIA de eventos adversos pós-vacina: órgão?', 'ANVISA e notificações locais (sistemas nacionais).', '', 'extra_livro', 'extra', ['farmacovigilancia']),
    c('mad1_a6', 'Adjuvante de vacina: função?', 'Potencializar resposta imune inata à antígeno.', '', 'mecanismo', 'extra', ['adjuvante']),
  ],
  [ // mad1_a7
    c('mad1_a7', 'SCID: deficiência de?', 'Linfócitos T (e muitas vezes B/NK) — infecções precoces graves.', '', 'clinica', 'material', ['scid']),
    c('mad1_a7', 'Deficiência de IgA: manifestação comum?', 'Muitas vezes assintomática; infecções respiratórias/digestivas.', '', 'clinica', 'material', ['iga']),
    c('mad1_a7', 'HIV causa imunodeficiência primária ou secundária?', 'Secundária (adquirida).', '', 'diferenciacao', 'material', ['hiv']),
    c('mad1_a7', 'Deficiência de complemento C5-C9: risco?', 'Neisseria (meningococo, gonococo).', '', 'clinica', 'material', ['complemento']),
    c('mad1_a7', 'Quimioterapia causa imunodeficiência por?', 'Mielossupressão (neutropenia).', '', 'mecanismo', 'material', ['quimio']),
    c('mad1_a7', 'Asplenia: risco infeccioso?', 'Encapsulados (pneumococo, meningococo, Hib).', '', 'clinica', 'material', ['esplenectomia']),
    c('mad1_a7', 'DiGeorge: defeito típico?', 'Tímico/cardiaco — hipocalcemia, T cells ↓.', '', 'clinica', 'material', ['digeorge']),
    c('mad1_a7', 'CGD: células afetadas?', 'Fagócitos (burst oxidativo deficiente) — infecções fúngicas/bacterianas catalase+.', '', 'clinica', 'material', ['cgd']),
    c('mad1_a7', 'Uso crônico de corticoide alto: imunidade?', 'Imunossupressão (infecta oportunistas).', '', 'clinica', 'material', ['corticoide']),
    c('mad1_a7', 'Gamma globulina IV: indicação típica?', 'Hipogamaglobulinemia e algumas imunodeficiências.', '', 'clinica', 'material', ['igiv']),
    c('mad1_a7', 'Hipersensibilidade IgE a alimentos: imunodeficiência?', 'Não — resposta exagerada, não defesa baixa.', '', 'diferenciacao', 'extra', ['alergia']),
    c('mad1_a7', 'BTK deficiency (agamaglobulinemia X-linked): célula?', 'Maturação B bloqueada — ausência de anticorpos.', '', 'extra_livro', 'extra', ['btk']),
  ],
  [ // mad1_a8
    c('mad1_a8', 'Tolerância central no timo?', 'Seleção negativa de timócitos autoreativos (morte/apoptose).', '', 'mecanismo', 'material', ['timo']),
    c('mad1_a8', 'AIRE: expressa o quê no timo?', 'Antígenos tecido-específicos para deleção de T autoreativos.', '', 'prova', 'material', ['aire']),
    c('mad1_a8', 'Tolerância periférica: mecanismos?', 'Treg, deleção, anergia, checkpoint.', '', 'definicao', 'material', ['tolerancia']),
    c('mad1_a8', 'Lúpus eritematoso sistêmico: autoanticorpos?', 'Anti-DNA, anti-Sm (entre outros).', '', 'clinica', 'material', ['les']),
    c('mad1_a8', 'Doença de Hashimoto: alvo?', 'Tireoide (anti-TPO).', '', 'clinica', 'material', ['hashimoto']),
    c('mad1_a8', 'DM tipo 1: autoimunidade contra?', 'Células beta pancreáticas (anti-GAD, etc.).', '', 'clinica', 'material', ['dm1']),
    c('mad1_a8', 'CTLA-4 e PD-1: função?', 'Inibir ativação T (evitar autoimunidade; alvo oncológico).', '', 'mecanismo', 'material', ['checkpoint']),
    c('mad1_a8', 'Molecular mimicry: conceito?', 'Similaridade antigênica patógeno-hospedeiro desencadeia autoimunidade.', '', 'definicao', 'material', ['mimetismo']),
    c('mad1_a8', 'Fator reumatoide: o que detecta?', 'IgM anti-IgG (artrite reumatoide — não específico).', '', 'clinica', 'material', ['fr']),
    c('mad1_a8', 'ANCA associa-se a?', 'Vasculites (Granulomatose com poliangeíte, etc.).', '', 'clinica', 'material', ['anca']),
    c('mad1_a8', 'Pênfigo vulgar: alvo autoimune?', 'Desmogleína 3 (epiderme).', '', 'clinica', 'extra', ['penfigo']),
    c('mad1_a8', 'Miastenia gravis: alvo?', 'Receptor de acetilcolina na placa neuromuscular.', '', 'clinica', 'extra', ['miastenia']),
  ],
  [ // mad1_a9
    c('mad1_a9', 'Rejeição hiperaguda: mecanismo?', 'Anticorpos pré-existentes — minutos/horas.', '', 'definicao', 'material', ['transplante']),
    c('mad1_a9', 'Rejeição aguda celular: células?', 'CD8+ e macrófagos.', '', 'mecanismo', 'material', ['rejeicao']),
    c('mad1_a9', 'Rejeição crônica: característica?', 'Fibrose vascular e isquemia (meses/anos).', '', 'definicao', 'material', ['cronica']),
    c('mad1_a9', 'GVHD: o que ataca o quê?', 'Linfócitos do enxerto atacam tecidos do receptor.', '', 'definicao', 'material', ['gvhd']),
    c('mad1_a9', 'Sistema ABO: antígenos na superfície eritrocitária?', 'A e B (carboidratos); O sem A nem B.', '', 'prova', 'material', ['abo']),
    c('mad1_a9', 'Rh negativo recebe Rh+ na primeira vez?', 'Pode sensibilizar; segunda exposição risco HDN.', '', 'clinica', 'material', ['rh']),
    c('mad1_a9', 'Tipagem cruzada (crossmatch) testa o quê?', 'Compatibilidade receptor-doador (anticorpos anti-HLA).', '', 'definicao', 'material', ['crossmatch']),
    c('mad1_a9', 'Transfusão ABO incompatível: reação?', 'Hemólise aguda intravascular.', '', 'clinica', 'material', ['hemolise']),
    c('mad1_a9', 'Enxerto autólogo rejeita?', 'Não (mesmo indivíduo).', '', 'prova', 'material', ['autologo']),
    c('mad1_a9', 'Imunossupressores pós-transplante: classes?', 'Ciclosporina, tacrolimus, micofenolato, corticoide.', '', 'clinica', 'material', ['imunossupressao']),
    c('mad1_a9', 'HLA: cromossomo principal?', '6 — região MHC.', '', 'extra_livro', 'extra', ['hla']),
    c('mad1_a9', 'Plasmaferese em algumas rejeições serve para?', 'Remover anticorpos (contexto terapêutico).', '', 'extra_livro', 'extra', ['plasmaferese']),
  ],
  [ // mad1_a10
    c('mad1_a10', 'Hipersensibilidade tipo I: mediador principal?', 'IgE e mastócitos (histamina).', '', 'definicao', 'material', ['tipo-i']),
    c('mad1_a10', 'Tipo II: mecanismo?', 'Citotóxico — IgG/IgM contra antígeno de membrana.', '', 'definicao', 'material', ['tipo-ii']),
    c('mad1_a10', 'Tipo III: exemplos?', 'Doença do soro, lúpus (complexos imunes).', '', 'definicao', 'material', ['tipo-iii']),
    c('mad1_a10', 'Tipo IV: tempo de início?', '24–72 h (T cells, sem Ig direto).', '', 'prova', 'material', ['tipo-iv']),
    c('mad1_a10', 'Anafilaxia: tratamento imediato?', 'Adrenalina IM + suporte (via aérea, volume).', '', 'clinica', 'material', ['anafilaxia']),
    c('mad1_a10', 'Asma alérgica: tipo de hipersensibilidade?', 'Tipo I (late phase com eosinofilia).', '', 'clinica', 'material', ['asma']),
    c('mad1_a10', 'Teste de Mantoux: tipo?', 'IV (DTH) — TB.', '', 'prova', 'material', ['ppd']),
    c('mad1_a10', 'Doença hemolítica do recém-nascido: tipo?', 'II (anti-Rh IgG atravessa placenta).', '', 'clinica', 'material', ['hdn']),
    c('mad1_a10', 'Artrite reumatoide: componente imune?', 'Inflamação sinovial com autoanticorpos e citocinas (mistura II/III/IV).', '', 'clinica', 'material', ['ar']),
    c('mad1_a10', 'Alopurinol pode causar qual síndrome de hipersensibilidade?', 'DRESS (síndrome de hipersensibilidade medicamentosa tardia).', '', 'clinica', 'material', ['dress']),
    c('mad1_a10', 'Desensibilização alérgica: princípio?', 'Induzir tolerância com doses crescentes de alérgeno (imunoterapia).', '', 'extra_livro', 'extra', ['desensibilizacao']),
    c('mad1_a10', 'Shwartzman: fenômeno relacionado?', 'Resposta inflamatória sistêmica a endotoxina (contexto histórico).', '', 'extra_livro', 'extra', ['shwartzman']),
  ],
  [ // mad1_a11
    c('mad1_a11', 'Coloração de Gram: diferencia o quê?', 'Parede de peptidoglicano espessa (G+) vs membrana externa (G−).', '', 'definicao', 'material', ['gram']),
    c('mad1_a11', 'Endotoxina bacteriana clássica?', 'LPS da membrana externa de G−.', '', 'prova', 'material', ['lps']),
    c('mad1_a11', 'Exotoxinas: característica?', 'Proteínas secretadas (tetânica, diftérica).', '', 'diferenciacao', 'material', ['exotoxina']),
    c('mad1_a11', 'Capsula: função?', 'Antifagocítica e antidessecante.', '', 'definicao', 'material', ['capsula']),
    c('mad1_a11', 'Flagelo: função?', 'Motilidade químiossática.', '', 'definicao', 'material', ['flagelo']),
    c('mad1_a11', 'Conjugação bacteriana: o que se transfere?', 'Plasmídeos (genes de resistência).', '', 'mecanismo', 'material', ['conjugacao']),
    c('mad1_a11', 'Esporos: resistência?', 'Calor e dessecação (Bacillus, Clostridium).', '', 'prova', 'material', ['esporos']),
    c('mad1_a11', 'Biofilme: importância clínica?', 'Proteção contra antibióticos e imunidade (cateteres).', '', 'clinica', 'material', ['biofilme']),
    c('mad1_a11', 'Aeróbios obrigatórios: exemplo?', 'Pseudomonas aeruginosa.', '', 'definicao', 'material', ['pseudomonas']),
    c('mad1_a11', 'Anaeróbios estritos: exemplo clínico?', 'Clostridium perfringens (gasgangrena).', '', 'clinica', 'material', ['clostridium']),
    c('mad1_a11', 'Parede G+: espessura do peptidoglicano?', 'Muito espessa (teicoico ácido).', '', 'mecanismo', 'extra', ['peptidoglicano']),
    c('mad1_a11', 'Porin: localização?', 'Membrana externa G− — permeabilidade seletiva.', '', 'extra_livro', 'extra', ['porin']),
  ],
  [ // mad1_a12
    c('mad1_a12', 'Sífilis: agente e diagnóstico sorológico?', 'Treponema pallidum; VDRL/RPR + confirmação treponêmica.', '', 'clinica', 'material', ['sifilis']),
    c('mad1_a12', 'Gonorreia: agente?', 'Neisseria gonorrhoeae.', '', 'definicao', 'material', ['gonorreia']),
    c('mad1_a12', 'Clamídia uretrite/cervicite: agente?', 'Chlamydia trachomatis (obligado intracelular).', '', 'definicao', 'material', ['clamidia']),
    c('mad1_a12', 'Sífilis primária: lesão?', 'Cancro duro (indolor).', '', 'clinica', 'material', ['cancro']),
    c('mad1_a12', 'Lues secundária: achado cutâneo?', 'Roséola sifilítica palmoplantar.', '', 'clinica', 'material', ['lues']),
    c('mad1_a12', 'N. gonorrhoeae: cultura?', 'Meio Thayer-Martin (CO2).', '', 'prova', 'material', ['cultura']),
    c('mad1_a12', 'Clamídia: diagnóstico molecular?', 'PCR de urina primeiro jato ou swab.', '', 'clinica', 'material', ['pcr']),
    c('mad1_a12', 'Jarisch-Herxheimer: quando?', 'Reação a tratamento da sífilis (endotoxina/liberação).', '', 'clinica', 'material', ['jarisch']),
    c('mad1_a12', 'Penicilina benzatina: uso em sífilis?', 'Tratamento de escolha em muitos estágios (conforme protocolo).', '', 'clinica', 'material', ['penicilina']),
    c('mad1_a12', 'Resistência N. gonorrhoeae a ceftriaxona: problema?', 'Emergência de cepas multirresistentes (vigilância).', '', 'clinica', 'material', ['resistencia']),
    c('mad1_a12', 'Linfogranuloma venéreo: agente?', 'C. trachomatis serotipos L1–L3.', '', 'extra_livro', 'extra', ['lgv']),
    c('mad1_a12', 'Sífilis congênita: transmissão?', 'Transplacentária (T. pallidum).', '', 'clinica', 'extra', ['congenita']),
  ],
];

const data = JSON.parse(fs.readFileSync(OUT, 'utf8'));
let id = 0;
for (const f of data.flashcards) if (f.id > id) id = f.id;
id++;
for (const lot of LOTS) for (const x of lot) data.flashcards.push({ ...x, id: id++ });
fs.writeFileSync(OUT, JSON.stringify(data, null, 2), 'utf8');
console.log('OK part1 total', data.flashcards.length, 'last id', id - 1);
