/** SEMIO2 semio2_a1–a9 × 12 — node scripts/append_flashcards_semio2_m2.js */
const fs = require('fs');
const path = require('path');
const OUT = path.join(__dirname, '..', 'data', 'flashcards.json');
function c(t, f, v, e, cat, o, tags) {
  return { materia: 'semiologia2', tema: t, frente: f, verso: v, explicacao: e || '', dificuldade: 2, categoria: cat, origem: o, tags: tags || [] };
}
const LOTS = [
  [ // semio2_a1
    c('semio2_a1', 'Semiologia estuda?', 'Métodos de investigação dos fenômenos morbidamente modificados (signos e sintomas).', '', 'definicao', 'material', ['semiologia']),
    c('semio2_a1', 'Sintoma vs sinal?', 'Sintoma: relato; sinal: observado pelo examinador.', '', 'diferenciacao', 'material', ['sintoma']),
    c('semio2_a1', 'Inspeção cardiovascular: observa?', 'Cianose, retrações, turgência jugular, aparelho de marca-passo.', '', 'definicao', 'material', ['inspecao']),
    c('semio2_a1', 'Frequência cardíaca normal adulto em repouso?', '~60–100 bpm (ordem de grandeza).', '', 'prova', 'material', ['fc']),
    c('semio2_a1', 'Pulmão: vias aéreas superiores avaliam?', 'Nariz, boca, faringe antes de tórax.', '', 'definicao', 'material', ['vias']),
    c('semio2_a1', 'Estetoscópio: campanha vs diafragma?', 'Diafragma: altas frequências; campanha: baixas.', '', 'diferenciacao', 'material', ['estetoscopio']),
    c('semio2_a1', 'Simetria torácica na inspeção?', 'Comparar hemitóraces em repouso e na inspiração.', '', 'mecanismo', 'material', ['simetria']),
    c('semio2_a1', 'Dor torácica isquêmica típica: características?', 'Opressão, esforço, melhora com repouso/nitrato (padrão clássico).', '', 'clinica', 'material', ['angina']),
    c('semio2_a1', 'Dispneia: definição?', 'Sensação subjetiva de falta de ar.', '', 'definicao', 'material', ['dispneia']),
    c('semio2_a1', 'Exame físico segue ordem lógica?', 'Inspeção → palpação → percussão → ausculta (geral).', '', 'definicao', 'material', ['ordem']),
    c('semio2_a1', 'Hipótese diagnóstica antes do exame?', 'Direciona anamnese e exame (raciocínio clínico).', '', 'extra_livro', 'extra', ['hipotese']),
    c('semio2_a1', 'Termo ortopneia: significa?', 'Dispneia ao decúbito — melhora em ortostase (IC).', '', 'clinica', 'extra', ['ortopneia']),
  ],
  [ // semio2_a2
    c('semio2_a2', 'Anamnese cardiorrespiratória: queixa mais comum?', 'Dispneia (grau, esforço, ortopneia, paroxística).', '', 'clinica', 'material', ['dispneia']),
    c('semio2_a2', 'Classificação NYHA refere-se a?', 'Limitação funcional por IC (I–IV).', '', 'definicao', 'material', ['nyha']),
    c('semio2_a2', 'Dor torácica: perguntar OPQRST ajuda?', 'Localização, intensidade, características, fatores.', '', 'mecanismo', 'material', ['dor']),
    c('semio2_a2', 'Palpitação: investigar?', 'Início súbito/gradual, regularidade, gatilhos, sincope.', '', 'clinica', 'material', ['palpitacao']),
    c('semio2_a2', 'Tosse: tipo produtiva vs seca?', 'Diferencia causas infecciosas, asma, IC (espuma rosada).', '', 'diferenciacao', 'material', ['tosse']),
    c('semio2_a2', 'Hemoptise: diferencial com hematemesis?', 'Origem trato respiratório vs digestivo (cor, pH, náusea).', '', 'diferenciacao', 'material', ['hemoptise']),
    c('semio2_a2', 'Tabagismo: quantificar?', 'anos-maço (cigarros/dia × anos / 20).', '', 'prova', 'material', ['tabaco']),
    c('semio2_a2', 'HAS e DM: fatores de risco CV?', 'Integrar história para prevenção secundária.', '', 'clinica', 'material', ['risco']),
    c('semio2_a2', 'Antecedente familiar de morte súbita?', 'Eleva suspeita de canalopatias/ cardiomiopatias.', '', 'clinica', 'material', ['familia']),
    c('semio2_a2', 'Medicamentos: IECA/BRA: efeito colateral?', 'Tosse, hipercalemia; monitorar função renal.', '', 'clinica', 'material', ['medicamentos']),
    c('semio2_a2', 'Edema MMII bilateral simétrico sugere?', 'IC direita / venoso / hipoproteinemia (contexto).', '', 'extra_livro', 'extra', ['edema']),
    c('semio2_a2', 'Pergunta de síncope: prodroma?', 'Arritmia vs neurológico vs vasovagal.', '', 'clinica', 'extra', ['sincope']),
  ],
  [ // semio2_a3
    c('semio2_a3', 'Turgência jugular avalia?', 'Pressão venosa central / sobrecarga de direita.', '', 'definicao', 'material', ['turgencia']),
    c('semio2_a3', 'Ponto de máximo impulso (PMI) local típico?', '5º EIE medioclavicular (adulto).', '', 'prova', 'material', ['pmi']),
    c('semio2_a3', 'Frêmito palpável indica?', 'Fluxo turbulento (sopro alto) ou vibratório (ronco).', '', 'clinica', 'material', ['fremito']),
    c('semio2_a3', 'Pulso radial: avaliar?', 'Ritmo, amplitude, simetria, frequência.', '', 'definicao', 'material', ['pulso']),
    c('semio2_a3', 'Pulsos paradoxais aumentam em?', 'Tamponamento, asma grave (inspiração ↓PA sistólica).', '', 'clinica', 'material', ['paradoxal']),
    c('semio2_a3', 'Percussão cardíaca delimita?', 'Limiar da dulçidade (borda superior).', '', 'definicao', 'material', ['percussao']),
    c('semio2_a3', 'B1: momento?', 'Fechamento valvar AV — início sístole ventricular.', '', 'prova', 'material', ['b1']),
    c('semio2_a3', 'Sopro sistólico panfocal "holossistólico" em MA: IRR?', 'Regurgitação mitral (padrão típico).', '', 'clinica', 'material', ['im']),
    c('semio2_a3', 'Sopro diastólico em foco aórtico: pensar?', 'Estenose aórtica rara em diástole — IA ou misto (contexto).', '', 'clinica', 'material', ['sopro']),
    c('semio2_a3', 'Ritmo de galope S3: quando fisiológico?', 'Jovem e gestante; patológico em IC com volume ↑.', '', 'clinica', 'material', ['s3']),
    c('semio2_a3', 'Desdobramento fixo de B2: suspeita?', 'CIA (entre outras).', '', 'extra_livro', 'extra', ['split']),
    c('semio2_a3', 'Sopro vibratório inocente?', 'Comum criança/adolescente — sem cardiopatia.', '', 'clinica', 'extra', ['inocente']),
  ],
  [ // semio2_a4
    c('semio2_a4', 'Inspeção respiratória: frequência?', 'Taquipneia bradicneia; uso de musculatura acessória.', '', 'definicao', 'material', ['inspecao']),
    c('semio2_a4', 'Palpação expansibilidade: simétrica?', 'Comparar mãos nas costas.', '', 'definicao', 'material', ['expansao']),
    c('semio2_a4', 'Frêmito toracotáctil aumenta em?', 'Consolidação (pneumonia).', '', 'clinica', 'material', ['fremito']),
    c('semio2_a4', 'Percussão: som timpânico vs submaciço?', 'Ar (gás) vs tecido sólido/líquido.', '', 'diferenciacao', 'material', ['percussao']),
    c('semio2_a4', 'Ausculta respiratória: MV presente?', 'Simétrico bilateral; comparar áreas homólogas.', '', 'definicao', 'material', ['mv']),
    c('semio2_a4', 'Estertores finos (creptantes) sugerem?', 'Edema alveolar / fibrose (inspiração tardia).', '', 'clinica', 'material', ['estertores']),
    c('semio2_a4', 'Roncos: origem típica?', 'Grandes vias aéreas — secreção/edema.', '', 'definicao', 'material', ['roncos']),
    c('semio2_a4', 'Sibilos indicam?', 'Obstrução de vias aéreas inferiores (asma, DPOC).', '', 'clinica', 'material', ['sibilos']),
    c('semio2_a4', 'Atrito pleural: onde ouvir?', 'Inspiratório e expiratório — superfície inflamada.', '', 'clinica', 'material', ['atrito']),
    c('semio2_a4', 'Diminuição unilateral MV: causas?', 'Derrame, pneumotórax, obstrução brônquica.', '', 'clinica', 'material', ['mv']),
    c('semio2_a4', 'Broncofonia aumentada em?', 'Consolidação (mesmo lado de pneumonia).', '', 'extra_livro', 'extra', ['broncofonia']),
    c('semio2_a4', 'Macicez móvel em decúbito sugere?', 'Derrame pleural livre.', '', 'clinica', 'extra', ['derrame']),
  ],
  [ // semio2_a5
    c('semio2_a5', 'Correlação sopro + irradiação: IA?', 'Para carótidas (padrão clássico).', '', 'clinica', 'material', ['irradiacao']),
    c('semio2_a5', 'ICC descompensada: achados conjuntos?', 'Estertores + edema + turgência jugular + S3.', '', 'clinica', 'material', ['icc']),
    c('semio2_a5', 'TEP: sinais possíveis?', 'Taquicardia, hipoxemia, dor pleurítica, sinal de Homans (não específico).', '', 'clinica', 'material', ['tep']),
    c('semio2_a5', 'Pneumotórax hipertensivo: exame?', 'Distensão jugular, hipotensão, desvio de traqueia.', '', 'clinica', 'material', ['pneumotorax']),
    c('semio2_a5', 'Crise asmática: ausculta pode ser?', 'Sibilos difusos ou "silêncio auscultativo" grave.', '', 'clinica', 'material', ['asma']),
    c('semio2_a5', 'Derrame pleural maciço: percussão?', 'Maciço + MV abolido basal.', '', 'clinica', 'material', ['derrame']),
    c('semio2_a5', 'Endocardite infecciosa: sinais periféricos?', 'Manchas de Janeway, nódulos de Osler (não todos presentes).', '', 'clinica', 'material', ['endocardite']),
    c('semio2_a5', 'Tamponamento: tríade de Beck?', 'HIPOtensão, distensão jugular, muffling de bulhas (clássico).', '', 'clinica', 'material', ['tamponamento']),
    c('semio2_a5', 'Bronquite crônica: critério tempo?', 'Tosse produtiva ≥3 meses/ano por 2 anos.', '', 'definicao', 'material', ['bronquite']),
    c('semio2_a5', 'Espirometria pós-broncodilatador: uso?', 'Confirmar obstrução reversível (asma).', '', 'clinica', 'material', ['espirometria']),
    c('semio2_a5', 'ECG na dor torácica aguda: primeiro passo?', 'IAM vs dissecção vs PERI (contexto).', '', 'extra_livro', 'extra', ['ecg']),
    c('semio2_a5', 'D-dímero elevado: significa?', 'Não exclui nem confirma TEP sozinho — probabilidade pré-teste.', '', 'clinica', 'extra', ['ddimero']),
  ],
  [ // semio2_a6
    c('semio2_a6', 'Simulação com manequim: objetivo?', 'Treinar sequência e tempo de exame sem risco.', '', 'definicao', 'material', ['simulacao']),
    c('semio2_a6', 'Paciente padronizado: avalia?', 'Comunicação + técnica (checklist).', '', 'definicao', 'material', ['padronizado']),
    c('semio2_a6', 'Ausculta de sopro em simulador: correlacionar foco?', 'Aórtica vs mitral vs tricúspide (localização).', '', 'clinica', 'material', ['foco']),
    c('semio2_a6', 'Estertores gravados vs roncos: treinar?', 'Diferença acústica inspiratória.', '', 'mecanismo', 'material', ['ausculta']),
    c('semio2_a6', 'Pressão do estetoscópio no exame respiratório?', 'Firme mas sem abafar sons.', '', 'prova', 'material', ['tecnica']),
    c('semio2_a6', 'Simulação de taquicardia: buscar?', 'Pulso regular vs irregular.', '', 'clinica', 'material', ['ritmo']),
    c('semio2_a6', 'Feedback imediato após simulação?', 'Correção de técnica e raciocínio.', '', 'definicao', 'material', ['feedback']),
    c('semio2_a6', 'Checklist de exame físico cardiorrespiratório?', 'Garante não omitir passos.', '', 'definicao', 'material', ['checklist']),
    c('semio2_a6', 'Debriefing pós-cenário: foco?', 'Erros de técnica vs erros de diagnóstico.', '', 'definicao', 'material', ['debriefing']),
    c('semio2_a6', 'Ambiente de simulação: aquecimento?', 'Reduz ansiedade e melhora performance.', '', 'mecanismo', 'material', ['ansiedade']),
    c('semio2_a6', 'Sompatologia digital (apps): uso?', 'Treino auditivo de sopro/ruídos.', '', 'extra_livro', 'extra', ['app']),
    c('semio2_a6', 'Limitação do manequim vs humano?', 'Textura pulso, temperatura, interação verbal.', '', 'extra', 'extra', ['limite']),
  ],
  [ // semio2_a7
    c('semio2_a7', 'Consentimento antes do exame físico?', 'Explicar procedimento e buscar permissão.', '', 'definicao', 'material', ['etica']),
    c('semio2_a7', 'Privacidade e aquecimento das mãos?', 'Conforto e rapport com paciente.', '', 'definicao', 'material', ['postura']),
    c('semio2_a7', 'Exame em decúbito dorsal: inspeção abdominal?', 'Integra com tórax em exame global.', '', 'definicao', 'material', ['decubito']),
    c('semio2_a7', 'Paciente real: variabilidade dos achados?', 'Normal vs patológico — interpretar no contexto.', '', 'mecanismo', 'material', ['variabilidade']),
    c('semio2_a7', 'Documentar achados objetivamente?', 'Local, intensidade (I–VI sopro), irradiação.', '', 'definicao', 'material', ['prontuario']),
    c('semio2_a7', 'Supervisão no ambulatório: papel?', 'Segurança e feedback imediato.', '', 'definicao', 'material', ['supervisao']),
    c('semio2_a7', 'Higienização das mãos entre pacientes?', 'Prevenção de infecção cruzada.', '', 'clinica', 'material', ['higiene']),
    c('semio2_a7', 'Escuta ativa na anamnese real?', 'Constrói vínculo e aumenta adesão.', '', 'mecanismo', 'material', ['escuta']),
    c('semio2_a7', 'Exame físico normal não exclui?', 'Doença precoce ou intermitente.', '', 'clinica', 'material', ['falso-negativo']),
    c('semio2_a7', 'Encaminhar para complementar quando?', 'Suspeita de gravidade ou diagnóstico incerto.', '', 'clinica', 'material', ['encaminhamento']),
    c('semio2_a7', 'Linguagem acessível ao paciente?', 'Evitar jargão excessivo ao explicar achados.', '', 'extra_livro', 'extra', ['comunicacao']),
    c('semio2_a7', 'Chaperone em exame sensível?', 'Boas práticas conforme protocolo institucional.', '', 'extra', 'extra', ['chaperone']),
  ],
  [ // semio2_a8
    c('semio2_a8', 'Discussão de caso CV: estrutura?', 'Apresentação → hipóteses → exames → conduta.', '', 'definicao', 'material', ['caso-clinico']),
    c('semio2_a8', 'IAM com supra ST: conduta inicial?', 'Ativar emergência, AAS, anticoagulação, revascularização.', '', 'clinica', 'material', ['iam']),
    c('semio2_a8', 'FA com rápida resposta ventricular: prioridade?', 'Controle de frequência vs cardioversão (estabilidade).', '', 'clinica', 'material', ['fa']),
    c('semio2_a8', 'Endocardite: critérios de Duke?', 'Combinação clínica + micro + ecocardiograma.', '', 'prova', 'material', ['duke']),
    c('semio2_a8', 'ICC com baixo débito: diferenciar choque?', 'Perfusão, lactato, extremidades frias.', '', 'clinica', 'material', ['choque']),
    c('semio2_a8', 'Estenose aórtica grave: sopro + sintomas?', 'Indica avaliação cirúrgica/TAVI.', '', 'clinica', 'material', ['ea']),
    c('semio2_a8', 'Miocardiopatia dilatada: causa comum?', 'Isquêmica, alcoólica, familiar, periparto.', '', 'clinica', 'material', ['mcd']),
    c('semio2_a8', 'Pericardite aguda: achado em ECG?', 'Supradesnivelamento difuso PR depressão (clássico).', '', 'clinica', 'material', ['pericardite']),
    c('semio2_a8', 'Dissecção aórtica: dor típica?', 'Abrupta, retroaternal irradiando costas.', '', 'clinica', 'material', ['disseccao']),
    c('semio2_a8', 'Hipertensão arterial grave: diferenciar urgência de emergência?', 'Lesão de órgão-alvo (SNC, coração, rins).', '', 'clinica', 'material', ['hta']),
    c('semio2_a8', 'Score HEART na dor torácica?', 'Estratifica risco cardiovascular na emergência.', '', 'extra_livro', 'extra', ['heart']),
    c('semio2_a8', 'TIMI score: uso?', 'Risco em SCA (contexto de anticoagulação/invasivo).', '', 'extra', 'extra', ['timi']),
  ],
  [ // semio2_a9
    c('semio2_a9', 'DPOC vs asma: diferença semiológica frequente?', 'DPOC mais fixa obstrução; asma mais variável.', '', 'diferenciacao', 'material', ['dpoc']),
    c('semio2_a9', 'Pneumonia comunitária: critérios de internação?', 'CURB-65 / escore de gravidade.', '', 'clinica', 'material', ['pneumonia']),
    c('semio2_a9', 'Tuberculose pulmonar: suspeita?', 'Tosse >3 semanas, febre noturna, emagrecimento.', '', 'clinica', 'material', ['tb']),
    c('semio2_a9', 'Derrame pleural paraneumônico: sinais?', 'Febre + dor pleurítica + maciço.', '', 'clinica', 'material', ['derrame']),
    c('semio2_a9', 'Edema agudo de pulmão: ausculta?', 'Estertores difusos + sibilos (asma cardíaca).', '', 'clinica', 'material', ['eap']),
    c('semio2_a9', 'Embolia pulmonar: sinais em tórax?', 'Taquipneia, dor pleurítica, atrito (não específicos).', '', 'clinica', 'material', ['tep']),
    c('semio2_a9', 'Pneumotórax espontâneo primário: perfil?', 'Jovem alto e magro (contexto).', '', 'clinica', 'material', ['pneumotorax']),
    c('semio2_a9', 'Fibrose pulmonar: ausculta clássica?', 'Estertores finos bibasais (velcro).', '', 'clinica', 'material', ['fibrose']),
    c('semio2_a9', 'Carcinoma brônquico: sinais de alerta?', 'Hemoptise, perda de peso, nódulo (imagem).', '', 'clinica', 'material', ['cancer']),
    c('semio2_a9', 'Asma grave: escuta pode silenciar?', 'Obstrução extrema — "sibilos ausentes" mau sinal.', '', 'clinica', 'material', ['asma']),
    c('semio2_a9', 'Wells score: uso?', 'Probabilidade pré-teste de TEP.', '', 'extra_livro', 'extra', ['wells']),
    c('semio2_a9', 'CURB-65 letra C significa?', 'Confusão mental (entre critérios).', '', 'extra', 'extra', ['curb']),
  ],
];

const data = JSON.parse(fs.readFileSync(OUT, 'utf8'));
let id = 0;
for (const f of data.flashcards) if (f.id > id) id = f.id;
id++;
for (const lot of LOTS) for (const x of lot) data.flashcards.push({ ...x, id: id++ });
fs.writeFileSync(OUT, JSON.stringify(data, null, 2), 'utf8');
console.log('OK semio2 total', data.flashcards.length, 'last id', id - 1);
