/** BMF3 bmf3_a1–a11 × 12 — node scripts/append_flashcards_bmf3_m3_part1.js */
const fs = require('fs');
const path = require('path');
const OUT = path.join(__dirname, '..', 'data', 'flashcards.json');
function c(t, f, v, e, cat, o, tags) {
  return { materia: 'bmf3', tema: t, frente: f, verso: v, explicacao: e || '', dificuldade: 2, categoria: cat, origem: o, tags: tags || [] };
}
const LOTS = [
  [ // bmf3_a1
    c('bmf3_a1', 'Esôfago cervical inicia em?', 'Bordo superior da cartilagem cricoide (C6 aprox.).', '', 'definicao', 'material', ['esofago']),
    c('bmf3_a1', 'Hiato esofágico passa por?', 'Diafragma (vértice T10 aprox.).', '', 'prova', 'material', ['hiato']),
    c('bmf3_a1', 'Estômago: regiões?', 'Fundo, corpo, antro, piloro.', '', 'definicao', 'material', ['estomago']),
    c('bmf3_a1', 'Curvatura maior do estômago: artéria principal?', 'Gastroepiploica (direita/esquerda conforme trajeto).', '', 'definicao', 'material', ['vascular']),
    c('bmf3_a1', 'Cardia: localização?', 'Junção esofagogástrica.', '', 'definicao', 'material', ['cardia']),
    c('bmf3_a1', 'Piloro: função?', 'Regula esvaziamento gástrico para duodeno.', '', 'mecanismo', 'material', ['piloro']),
    c('bmf3_a1', 'Faringe: subdivisões?', 'Nasofaringe, orofaringe, laringofaringe.', '', 'definicao', 'material', ['faringe']),
    c('bmf3_a1', 'Úvula e palato mole: papel na deglutição?', 'Direcionam bolo alimentar e fecham nasofaringe.', '', 'mecanismo', 'material', ['degluticao']),
    c('bmf3_a1', 'Esfincter esofágico inferior fisiológico?', 'Transição esôfago-gástrica — não só músculo esquelético.', '', 'definicao', 'material', ['eei']),
    c('bmf3_a1', 'Vago inerva principalmente?', 'Músculo liso esofágico e estômago (parassimpático).', '', 'prova', 'material', ['vago']),
    c('bmf3_a1', 'Hérnia de hiato: conceito?', 'Deslizamento cardia para tórax — refluxo.', '', 'clinica', 'extra', ['hernia']),
    c('bmf3_a1', 'Barret: metaplasia?', 'Epitélio colunar no esôfago distal (GERD crônico).', '', 'clinica', 'extra', ['barret']),
  ],
  [ // bmf3_a2
    c('bmf3_a2', 'Ligamento de Treitz marca?', 'Transição duodeno–jejuno (flexura duodenojejunal).', '', 'prova', 'material', ['treitz']),
    c('bmf3_a2', 'Válvula ileocecal: função?', 'Impede refluxo cólico e regula esvaziamento ileal.', '', 'mecanismo', 'material', ['ileocecal']),
    c('bmf3_a2', 'Apêndice vermiforme: base?', 'Junção ileocecal (inferomedial).', '', 'definicao', 'material', ['apendice']),
    c('bmf3_a2', 'Cólon ascendente/descendente: peritoneal?', 'Retroperitoneais (ascendente e parte descendente).', '', 'definicao', 'material', ['colon']),
    c('bmf3_a2', 'Teniae coli e haustrações são típicas de?', 'Cólon (não do reto terminal da mesma forma).', '', 'definicao', 'material', ['haustra']),
    c('bmf3_a2', 'Flexuras cólicas principais?', 'Hepática e esplênica.', '', 'definicao', 'material', ['flexuras']),
    c('bmf3_a2', 'Reto ampola: continência?', 'Esfincter interno (involuntário) e externo (voluntário).', '', 'definicao', 'material', ['reto']),
    c('bmf3_a2', 'Linha pectínea/ano: transição?', 'Epitélio colunar → escamoso (zona hemorroidária).', '', 'prova', 'material', ['pectinea']),
    c('bmf3_a2', 'Jejuno vs íleo: diferença macro?', 'Jejuno mais vascularizado, alças mais grossas (regra prática).', '', 'diferenciacao', 'material', ['jejuno']),
    c('bmf3_a2', 'Mesentério ancora?', 'Intestino delgado à parede posterior.', '', 'definicao', 'material', ['mesentério']),
    c('bmf3_a2', 'Divertículo de Meckel: embriológico?', 'Remanescente ducto onfalomesentérico — sangramento.', '', 'clinica', 'extra', ['meckel']),
    c('bmf3_a2', 'Volvo intestinal: risco?', 'Isquemia por torção do mesentério.', '', 'clinica', 'extra', ['volvo']),
  ],
  [ // bmf3_a3
    c('bmf3_a3', 'Segmentos hepáticos de Couinaud?', '8 segmentos funcionais (cirúrgicos).', '', 'definicao', 'material', ['couinaud']),
    c('bmf3_a3', 'Triângulo de Calot limitado por?', 'Ducto cístico, hepático comum e borda hepática inferior.', '', 'prova', 'material', ['calot']),
    c('bmf3_a3', 'Ampola de Vater: confluência?', 'Colédoco + ducto pancreático principal (geralmente).', '', 'definicao', 'material', ['vater']),
    c('bmf3_a3', 'Pâncreas: parte retroperitoneal?', 'Cabeça e corpo (exceto cauda intraperitoneal).', '', 'definicao', 'material', ['pâncreas']),
    c('bmf3_a3', 'Artéria hepática vem de?', 'Tronco celíaco → hepática própria.', '', 'definicao', 'material', ['hepatica']),
    c('bmf3_a3', 'Veia porta: formação?', 'Esplênica + mesentérica superior (confluência portal).', '', 'definicao', 'material', ['porta']),
    c('bmf3_a3', 'Vesícula biliar: função?', 'Concentrar e armazenar bile.', '', 'definicao', 'material', ['vesicula']),
    c('bmf3_a3', 'Ducto cístico une-se a?', 'Hepático comum formando colédoco.', '', 'definicao', 'material', ['cistico']),
    c('bmf3_a3', 'Lóbulos hepáticos microscópicos: unidade clássica?', 'Lóbulo hexagonal com tríade portal.', '', 'definicao', 'material', ['lobulo']),
    c('bmf3_a3', 'Hepatócito polariza secreção bile para?', 'Canalículos bilifagos.', '', 'mecanismo', 'material', ['canaliculo']),
    c('bmf3_a3', 'Colelitíase: composição mais comum?', 'Colesterol (maioria no Brasil ocidental).', '', 'clinica', 'extra', ['colelitiase']),
    c('bmf3_a3', 'Pancreatite aguda: enzimas elevadas?', 'Amilase e lipase séricas.', '', 'clinica', 'extra', ['pancreatite']),
  ],
  [ // bmf3_a4
    c('bmf3_a4', 'Esôfago histologia: epitélio?', 'Escamoso estratificado não queratinizado.', '', 'definicao', 'material', ['esofago']),
    c('bmf3_a4', 'Junção esofagogástrica: mudança epitelial?', 'Escamoso → colunar (Z-line).', '', 'prova', 'material', ['z-line']),
    c('bmf3_a4', 'Mucosa gástrica: células parietais secretam?', 'HCl e fator intrínseco.', '', 'definicao', 'material', ['parietal']),
    c('bmf3_a4', 'Células principais (chief):?', 'Pepsinógeno.', '', 'definicao', 'material', ['chief']),
    c('bmf3_a4', 'Células G antrais: hormônio?', 'Gastrina.', '', 'definicao', 'material', ['gastrina']),
    c('bmf3_a4', 'Fossetas gástricas contêm?', 'Células mucosas fúndicas — muco protetor.', '', 'definicao', 'material', ['fossetas']),
    c('bmf3_a4', 'Barret: tipo de metaplasia?', 'Epitélio intestinal/colunar no esôfago distal.', '', 'clinica', 'material', ['barret']),
    c('bmf3_a4', 'Camadas da parede gástrica?', 'Mucosa, submucosa, muscularis, serosa.', '', 'definicao', 'material', ['camadas']),
    c('bmf3_a4', 'Úlcera péptica: camada típica atingida?', 'Ulcer até submucosa/muscularis (gravidade).', '', 'clinica', 'material', ['ulcera']),
    c('bmf3_a4', 'H. pylori: localização preferencial?', 'Mucosa antral (contexto ulceras).', '', 'clinica', 'material', ['pylori']),
    c('bmf3_a4', 'Metaplasia intestinal gástrica?', 'Fator de risco para adenocarcinoma (monitoramento).', '', 'extra_livro', 'extra', ['metaplasia']),
    c('bmf3_a4', 'Atrofia gástrica autoimune: alvo?', 'Células parietais — deficiência B12.', '', 'clinica', 'extra', ['autoimune']),
  ],
  [ // bmf3_a5
    c('bmf3_a5', 'Vilosidades intestinais onde?', 'Delgado (aumentam área absorptiva).', '', 'definicao', 'material', ['vilosidades']),
    c('bmf3_a5', 'Microvilosidades formam?', 'Borda em escova no enterócito.', '', 'definicao', 'material', ['microvilos']),
    c('bmf3_a5', 'Pregas de Kerckring?', 'Dobras submucosas no jejuno.', '', 'prova', 'material', ['kerckring']),
    c('bmf3_a5', 'Células de Paneth: local?', 'Base das criptas — lisozima e defensinas.', '', 'definicao', 'material', ['paneth']),
    c('bmf3_a5', 'Placas de Peyer?', 'Linfóide agregado no íleo.', '', 'definicao', 'material', ['peyer']),
    c('bmf3_a5', 'Células M (microfold)?', 'Captam antígenos da luz para imunidade.', '', 'definicao', 'material', ['celula-m']),
    c('bmf3_a5', 'Cólon: vilosidades?', 'Ausentes — criptas retas.', '', 'diferenciacao', 'material', ['colon']),
    c('bmf3_a5', 'Células caliciformes produzem?', 'Muco.', '', 'definicao', 'material', ['muco']),
    c('bmf3_a5', 'Doença celíaca: lesão típica?', 'Afinamento vilositário jejunal.', '', 'clinica', 'material', ['celiaca']),
    c('bmf3_a5', 'Crohn pode afetar?', 'Todo trato GI — transmural.', '', 'clinica', 'material', ['crohn']),
    c('bmf3_a5', 'Reto: coluna simples vs criptas?', 'Transição histológica na linha pectínea.', '', 'extra_livro', 'extra', ['reto']),
    c('bmf3_a5', 'Intussuscepção: onde comum criança?', 'Íleo–ceco.', '', 'clinica', 'extra', ['intussuscepcao']),
  ],
  [ // bmf3_a6
    c('bmf3_a6', 'Tríade portal hepática?', 'Artéria hepática ramo, veia porta ramo, ducto biliar.', '', 'definicao', 'material', ['triade']),
    c('bmf3_a6', 'Espaço de Disse?', 'Entre hepatócito e endotélio sinusoidal.', '', 'definicao', 'material', ['disse']),
    c('bmf3_a6', 'Células de Kupffer são?', 'Macrófagos sinusoidais.', '', 'definicao', 'material', ['kupffer']),
    c('bmf3_a6', 'Células de Ito (estreladas)?', 'Armazenam vitamina A — fibrose hepática quando ativadas.', '', 'definicao', 'material', ['ito']),
    c('bmf3_a6', 'Ácinos pancreáticos exócrinos secretam?', 'Enzimas digestivas (amilase, lipase, proteases inativas).', '', 'definicao', 'material', ['acino']),
    c('bmf3_a6', 'Ilhotas pancreáticas endócrinas: células β?', 'Insulina.', '', 'definicao', 'material', ['beta']),
    c('bmf3_a6', 'Ductos intercalares/striados pancreáticos?', 'Modificam eletrólitos do suco pancreático.', '', 'mecanismo', 'material', ['ducto']),
    c('bmf3_a6', 'Vesícula: epitélio?', 'Colunar com microvilosidades absorptivas.', '', 'definicao', 'material', ['vesicula']),
    c('bmf3_a6', 'Esteatose hepática: achado histológico?', 'Gotículas de gordura nos hepatócitos.', '', 'clinica', 'material', ['esteatose']),
    c('bmf3_a6', 'Cirrose: padrão?', 'Nódulos de regeneração + fibrose.', '', 'clinica', 'material', ['cirrose']),
    c('bmf3_a6', 'Pancreatite: necrose adiposa?', 'Saponificação (cálcio) em gordura peripancreática.', '', 'extra_livro', 'extra', ['pancreatite']),
    c('bmf3_a6', 'Colangite biliar primária: alvo?', 'Ductos biliares intra-hepáticos (autoimune).', '', 'clinica', 'extra', ['colangite']),
  ],
  [ // bmf3_a7
    c('bmf3_a7', 'Peristalse propaga?', 'Contração em anel que avança o bolo.', '', 'definicao', 'material', ['peristalse']),
    c('bmf3_a7', 'Segmentação no intestino delgado?', 'Mistura local sem progressão contínua.', '', 'definicao', 'material', ['segmentacao']),
    c('bmf3_a7', 'MMC (complexo motor migratório)?', 'Limpa intestino entre refeições (jejum).', '', 'definicao', 'material', ['mmc']),
    c('bmf3_a7', 'Gastrina estimula?', 'Secreção gástrica e motilidade antral.', '', 'mecanismo', 'material', ['gastrina']),
    c('bmf3_a7', 'Secretina libera?', 'Bicarbonato pancreático e bile diluída.', '', 'mecanismo', 'material', ['secretina']),
    c('bmf3_a7', 'CCK estimula?', 'Contração vesicular e enzimas pancreáticas.', '', 'mecanismo', 'material', ['cck']),
    c('bmf3_a7', 'GIP (polipeptídeo inhibitorio gástrico)?', 'Inibe secreção gástrica após glicose/lipídios no duodeno.', '', 'mecanismo', 'material', ['gip']),
    c('bmf3_a7', 'Esvaziamento gástrico: o que atrasa?', 'Lipídios e osmolaridade alta no duodeno (reflexo entero-gástrico).', '', 'mecanismo', 'material', ['esvaziamento']),
    c('bmf3_a7', 'Movimento de massa no cólon?', '3×/dia — propulsão para reto.', '', 'definicao', 'material', ['massa']),
    c('bmf3_a7', 'Reflexo gastrocolico?', 'Alimento no estômago aumenta motilidade cólica.', '', 'mecanismo', 'material', ['gastrocolico']),
    c('bmf3_a7', 'Acalasia: defeito?', 'Neurônios mientéricos — não relaxamento EEI.', '', 'clinica', 'extra', ['acalasia']),
    c('bmf3_a7', 'Diabetes gástrico: complicação?', 'Gastroparesia — atraso esvaziamento.', '', 'clinica', 'extra', ['gastroparesia']),
  ],
  [ // bmf3_a8
    c('bmf3_a8', 'Saliva: principal enzima?', 'Amilase salivar (início digestão amido).', '', 'definicao', 'material', ['saliva']),
    c('bmf3_a8', 'Secreção gástrica fase cefálica?', 'Vago estimula antes do alimento chegar.', '', 'mecanismo', 'material', ['cefalica']),
    c('bmf3_a8', 'Fase gástrica da secreção?', 'Distensão e gastrina.', '', 'mecanismo', 'material', ['gastrica']),
    c('bmf3_a8', 'Fase intestinal inibe secreção gástrica?', 'Enterogastrones (ex.: secretina, GIP).', '', 'mecanismo', 'material', ['intestinal']),
    c('bmf3_a8', 'Pepsinógeno ativa para pepsina em?', 'pH ácido (meio gástrico).', '', 'mecanismo', 'material', ['pepsina']),
    c('bmf3_a8', 'Suco pancreático rico em bicarbonato vem de?', 'Células ductais (neutraliza ácido duodenal).', '', 'definicao', 'material', ['bicarbonato']),
    c('bmf3_a8', 'Quimotripsinogênio ativado por?', 'Tripsina (cascata enzimática no duodeno).', '', 'mecanismo', 'material', ['quimotripsina']),
    c('bmf3_a8', 'Bile: componentes principais?', 'Ácidos biliares, fosfolipídeos, pigmentos.', '', 'definicao', 'material', ['bile']),
    c('bmf3_a8', 'Ciclo êntero-hepático?', 'Reabsorção de ácidos biliares no íleo terminal → fígado.', '', 'mecanismo', 'material', ['entero-hepatico']),
    c('bmf3_a8', 'Síndrome de má absorção pancreática: causa?', 'Insuficiência pancreática exócrina (CF, pancreatite crônica).', '', 'clinica', 'material', ['pancreas']),
    c('bmf3_a8', 'Omeprazol: alvo?', 'Bomba H⁺/K⁺ ATPase parietal.', '', 'extra_livro', 'extra', ['ipp']),
    c('bmf3_a8', 'Obstrução biliar: cor da urina/fezes?', 'Urina escura (bilirrubina); fezes acólicas.', '', 'clinica', 'extra', ['colestase']),
  ],
  [ // bmf3_a9
    c('bmf3_a9', 'Glicose intestinal: transporte?', 'SGLT1 (cotransporte Na) e GLUT2 basolateral.', '', 'mecanismo', 'material', ['glicose']),
    c('bmf3_a9', 'Frutose absorvida por?', 'GLUT5 apical; GLUT2 basolateral.', '', 'mecanismo', 'material', ['frutose']),
    c('bmf3_a9', 'Dipeptídeos/tripeptídeos absorvidos e hidrolisados?', 'No enterócito → aminoácidos.', '', 'mecanismo', 'material', ['proteina']),
    c('bmf3_a9', 'Quilomícrons formam-se em?', 'Enterócitos pós-absorção de lipídios — linfática.', '', 'definicao', 'material', ['quilomícron']),
    c('bmf3_a9', 'Ácidos graxos curtos absorvem-se como?', 'Difusão direta para portal (via complexo micelar para longos).', '', 'mecanismo', 'material', ['lipidio']),
    c('bmf3_a9', 'Vitamina B12: absorção exige?', 'Fator intrínseco + receptor ileal terminal.', '', 'mecanismo', 'material', ['b12']),
    c('bmf3_a9', 'Ferro: absorção principalmente em?', 'Duodeno/proximal jejuno (duodenócitos).', '', 'definicao', 'material', ['ferro']),
    c('bmf3_a9', 'Cálcio: vitamina D aumenta?', 'Absorção intestinal transcelular.', '', 'mecanismo', 'material', ['calcio']),
    c('bmf3_a9', 'Vitamina lipossolúveis absorvem-se com?', 'Lipídios e micelas biliares.', '', 'mecanismo', 'material', ['adek']),
    c('bmf3_a9', 'Ressecção íleo terminal prejudica?', 'B12, bile salts, perda água (diarreia).', '', 'clinica', 'material', ['ileo']),
    c('bmf3_a9', 'Lactase deficiência: sintoma?', 'Diarreia osmótica ao leite (lactose).', '', 'clinica', 'extra', ['lactase']),
    c('bmf3_a9', 'Esteatorreia: definição?', 'Gordura nas fezes — má digestão/absorção lipídica.', '', 'extra_livro', 'extra', ['esteatorreia']),
  ],
  [ // bmf3_a10
    c('bmf3_a10', 'Rim direito mais baixo por?', 'Fígado empurra (topografia).', '', 'definicao', 'material', ['rim']),
    c('bmf3_a10', 'Hilo renal contém?', 'Artéria, veia, pelve, linfáticos (ordem variável).', '', 'definicao', 'material', ['hilo']),
    c('bmf3_a10', 'Néfrons corticais vs justamedulares?', 'Justamedulares longos — alça profunda (concentrar urina).', '', 'diferenciacao', 'material', ['nefron']),
    c('bmf3_a10', 'Ureter: estreitamentos clínicos?', 'Junção UPJ, cruzamento ilíaco, entrada vesical (JJ).', '', 'clinica', 'material', ['ureter']),
    c('bmf3_a10', 'Trígono vesical?', 'Ureteres + colo (sem mucosa móvel).', '', 'definicao', 'material', ['trígono']),
    c('bmf3_a10', 'Uretra masculina: porções?', 'Próstática, membranosa, esponjosa.', '', 'definicao', 'material', ['uretra']),
    c('bmf3_a10', 'Uretra feminina: comprimento?', 'Mais curta — maior risco ITU ascendente.', '', 'clinica', 'material', ['uretra-f']),
    c('bmf3_a10', 'Espessamento detrusor: função?', 'Contração miccional.', '', 'definicao', 'material', ['bexiga']),
    c('bmf3_a10', 'Cápsula renal envolve?', 'Parênquima — fibrosa.', '', 'definicao', 'material', ['capsula']),
    c('bmf3_a10', 'Coluna de Bertin?', 'Córtex entre pirâmides — normal, não tumor.', '', 'prova', 'material', ['bertin']),
    c('bmf3_a10', 'Litíase ureter: dor típica?', 'Cólica lombar irradiando para virilha (peristalse).', '', 'clinica', 'extra', ['litíase']),
    c('bmf3_a10', 'Refluxo vesico-ureteral predispõe?', 'Pielonefrite (urina ascende).', '', 'clinica', 'extra', ['refluxo']),
  ],
  [ // bmf3_a11
    c('bmf3_a11', 'Podócitos envolvem?', 'Capilares glomerulares — fenda de filtração.', '', 'definicao', 'material', ['podocito']),
    c('bmf3_a11', 'Cápsula de Bowman: espaço?', 'Espaço urinário recebe filtrado.', '', 'definicao', 'material', ['bowman']),
    c('bmf3_a11', 'Túbulo contorcido proximal: reabsorve?', 'Maior parte do filtrado (Na, glicose, aminoácidos, bicarbonato).', '', 'mecanismo', 'material', ['tcp']),
    c('bmf3_a11', 'Alça de Henle: segmento espesso?', 'Reabsorve Na/K/Cl (cotransportador).', '', 'mecanismo', 'material', ['henle']),
    c('bmf3_a11', 'TCD: sensor de NaCl?', 'Mácula densa — feedback túbulo-glomerular.', '', 'definicao', 'material', ['macula']),
    c('bmf3_a11', 'Células granulosas secretam?', 'Renina (aparelho justaglomerular).', '', 'definicao', 'material', ['renina']),
    c('bmf3_a11', 'Ducto coletor: células principais?', 'Reabsorvem Na sob aldosterona; secreção K.', '', 'mecanismo', 'material', ['coletor']),
    c('bmf3_a11', 'Células intercaladas?', 'Acidez — bomba H⁺ e HCO3⁻.', '', 'definicao', 'material', ['intercalada']),
    c('bmf3_a11', 'Nefrite intersticial: alvo?', 'Interstício e túbulos (não só glomérulo).', '', 'clinica', 'material', ['intersticial']),
    c('bmf3_a11', 'Nefropatia diabética: lesão inicial?', 'Hipertrofia glomerular, depois espessamento membrana.', '', 'clinica', 'material', ['dn']),
    c('bmf3_a11', 'Síndrome nefrótica: proteinúria?', '>3,5 g/dia + hipoproteinemia + edema.', '', 'extra_livro', 'extra', ['nefrotica']),
    c('bmf3_a11', 'Lesão mínima: achado LM?', 'Pés dos podócitos achatados — LM óptica “normal”.', '', 'clinica', 'extra', ['minimal']),
  ],
];

const data = JSON.parse(fs.readFileSync(OUT, 'utf8'));
let id = 0;
for (const f of data.flashcards) if (f.id > id) id = f.id;
id++;
for (const lot of LOTS) for (const x of lot) data.flashcards.push({ ...x, id: id++ });
fs.writeFileSync(OUT, JSON.stringify(data, null, 2), 'utf8');
console.log('OK bmf3 part1 total', data.flashcards.length, 'last id', id - 1);
