/** MAD2 mad2_a1–a10 × 12 — node scripts/append_flashcards_mad2_m3_part1.js */
const fs = require('fs');
const path = require('path');
const OUT = path.join(__dirname, '..', 'data', 'flashcards.json');
function c(t, f, v, e, cat, o, tags) {
  return { materia: 'mad2', tema: t, frente: f, verso: v, explicacao: e || '', dificuldade: 2, categoria: cat, origem: o, tags: tags || [] };
}
const LOTS = [
  [ // mad2_a1
    c('mad2_a1', 'SCID: característica?', 'Defeito grave comum em linfócitos T e/ou B — infecções precoces.', '', 'clinica', 'material', ['scid']),
    c('mad2_a1', 'Bruton (XLR): deficiência de?', 'Ig (B cells) — infecções encapsuladas.', '', 'clinica', 'material', ['bruton']),
    c('mad2_a1', 'DiGeorge: defeito?', 'Tímico/aparelho faríngeo — células T baixas.', '', 'clinica', 'material', ['digeorge']),
    c('mad2_a1', 'CGD: defeito?', 'Respiração explosiva — infecções fúngicas/bacterianas catalase+.', '', 'clinica', 'material', ['cgd']),
    c('mad2_a1', 'CVID: deficiência comum variável?', 'Ig baixo heterogêneo — infecções recorrentes.', '', 'clinica', 'material', ['cvid']),
    c('mad2_a1', 'Complemento C5–C9 (deficiência): risco?', 'Neisseria (bactericida membrana).', '', 'clinica', 'material', ['complemento']),
    c('mad2_a1', 'Tratamento de reposição Ig?', 'Imunoglobulina IV/SC em deficiências de anticorpo.', '', 'clinica', 'material', ['ivig']),
    c('mad2_a1', 'Transplante de timo em DiGeorge?', 'Seções graves selecionadas.', '', 'clinica', 'material', ['timo']),
    c('mad2_a1', 'HIV causa imunodeficiência?', 'Secundária — CD4+ depleção.', '', 'diferenciacao', 'material', ['hiv']),
    c('mad2_a1', 'Hipersensibilidade a IgA: risco transfusão?', 'Reação anafilática rara em deficiência de IgA.', '', 'clinica', 'material', ['iga']),
    c('mad2_a1', 'Sequenciamento genético em imunodeficiência?', 'Confirma diagnóstico molecular.', '', 'extra_livro', 'extra', ['genetica']),
    c('mad2_a1', 'Vacinas vivas atenuadas: contraindicação?', 'Imunodeficiência grave celular.', '', 'extra', 'extra', ['vacina']),
  ],
  [ // mad2_a2
    c('mad2_a2', 'Tolerância central?', 'Deleção clonal de linfócitos autoreativos no timo/medula.', '', 'definicao', 'material', ['central']),
    c('mad2_a2', 'Tolerância periférica?', 'Treg, anergia, deleção extratímica.', '', 'definicao', 'material', ['periferica']),
    c('mad2_a2', 'AIRE no timo?', 'Promove expressão de antígenos teciduais — deleção.', '', 'mecanismo', 'material', ['aire']),
    c('mad2_a2', 'CTLA-4 vs CD28?', 'CTLA-4 inibe coestimulação (Treg).', '', 'mecanismo', 'material', ['ctla4']),
    c('mad2_a2', 'PD-1/PD-L1: função?', 'Checkpoint inibitório — evita autoimunidade excessiva.', '', 'mecanismo', 'material', ['pd1']),
    c('mad2_a2', 'Perda de tolerância periférica leva a?', 'Autoimunidade.', '', 'mecanismo', 'material', ['autoimunidade']),
    c('mad2_a2', 'Deleção clonal vs anergia?', 'Morte celular vs inativação funcional.', '', 'diferenciacao', 'material', ['anergia']),
    c('mad2_a2', 'Microbiota e tolerância?', 'Treina imunidade no intestino.', '', 'mecanismo', 'material', ['microbiota']),
    c('mad2_a2', 'Molecular mimicry?', 'Patógeno similar a autoantígeno.', '', 'definicao', 'material', ['mimetismo']),
    c('mad2_a2', 'Epitope spreading?', 'Autoimunidade amplia alvos ao longo do tempo.', '', 'definicao', 'material', ['spreading']),
    c('mad2_a2', 'Inibidores de checkpoint em câncer: risco?', 'Reativação autoimune (colite, hipofisite).', '', 'extra_livro', 'extra', ['checkpoint']),
    c('mad2_a2', 'APECED: autoimune poliendocrinopatia?', 'Defeito AIRE — múltiplas autoimunidades.', '', 'extra', 'extra', ['apeced']),
  ],
  [ // mad2_a3
    c('mad2_a3', 'LES: autoanticorpos característicos?', 'ANA, anti-dsDNA, anti-Sm (entre outros).', '', 'clinica', 'material', ['les']),
    c('mad2_a3', 'Artrite reumatoide: marcador?', 'Fator reumatoide e anti-CCP.', '', 'clinica', 'material', ['ar']),
    c('mad2_a3', 'Doença de Graves: alvo?', 'Receptor de TSH — hipertireoidismo.', '', 'clinica', 'material', ['graves']),
    c('mad2_a3', 'Tireoidite de Hashimoto?', 'Anti-TPO/Tg — hipotireoidismo.', '', 'clinica', 'material', ['hashimoto']),
    c('mad2_a3', 'DM1: autoanticorpo?', 'Anti-GAD, anti-IA2, anti-ICA.', '', 'clinica', 'material', ['dm1']),
    c('mad2_a3', 'Esclerose múltipla: componente?', 'Dessmielinização autoimune mediada por linfócitos.', '', 'clinica', 'material', ['em']),
    c('mad2_a3', 'Miastenia gravis: alvo?', 'Receptor de acetilcolina (anticorpo).', '', 'clinica', 'material', ['miastenia']),
    c('mad2_a3', 'Púrpura trombocitopênica imune?', 'Anticorpo contra plaquetas.', '', 'clinica', 'material', ['pti']),
    c('mad2_a3', 'Células plasmáticas em autoimunidade produzem?', 'Autoanticorpos patogênicos.', '', 'mecanismo', 'material', ['plasmocito']),
    c('mad2_a3', 'Imunossupressores em AR: exemplos?', 'MTX, leflunomida, biológicos anti-TNF.', '', 'clinica', 'material', ['ar']),
    c('mad2_a3', 'Rituximabe: alvo?', 'CD20 em B — AR, LES, etc.', '', 'extra_livro', 'extra', ['rituximabe']),
    c('mad2_a3', 'Síndrome antifosfolípide: anticorpos?', 'aCL, anti-β2GPI, LAC — trombose.', '', 'extra', 'extra', ['saf']),
  ],
  [ // mad2_a4
    c('mad2_a4', 'Tipos de enxerto: autólogo?', 'Mesmo indivíduo.', '', 'definicao', 'material', ['enxerto']),
    c('mad2_a4', 'Alotransplante: rejeição hiperaguda?', 'Pré-formado anticorpo — minutos/horas.', '', 'clinica', 'material', ['hiperaguda']),
    c('mad2_a4', 'Rejeição aguda celular?', 'CD8+ ataca enxerto (dias-semanas).', '', 'mecanismo', 'material', ['aguda']),
    c('mad2_a4', 'Rejeição crônica?', 'Fibrose vascular — meses/anos.', '', 'clinica', 'material', ['cronica']),
    c('mad2_a4', 'Ciclosporina/tacrolimo: alvo?', 'Calcineurina — ↓ IL-2.', '', 'mecanismo', 'material', ['cnis']),
    c('mad2_a4', 'Micofenolato inibe?', 'Síntese de purinas em linfócitos.', '', 'mecanismo', 'material', ['mmf']),
    c('mad2_a4', 'Compatibilidade ABO/Rh transfusão?', 'Essencial — hemólise se incompatível.', '', 'prova', 'material', ['abo']),
    c('mad2_a4', 'Crossmatch transplante?', 'Soro receptor vs linfócitos doador — detecta DSA.', '', 'clinica', 'material', ['crossmatch']),
    c('mad2_a4', 'GvHD: direção?', 'Linfócitos do enxerto atacam receptor (medula).', '', 'clinica', 'material', ['gvhd']),
    c('mad2_a4', 'Reação transfusional febril não hemolítica?', 'Citocinas/HLA antigens — parar/observar.', '', 'clinica', 'material', ['transfusao']),
    c('mad2_a4', 'TRALI: mecanismo?', 'Anticorpos anti-HLA/HNA em plasma — edema pulmonar agudo.', '', 'extra_livro', 'extra', ['trali']),
    c('mad2_a4', 'Eritropoetina em insuficiência renal?', 'Reduz necessidade transfusional.', '', 'extra', 'extra', ['epo']),
  ],
  [ // mad2_a5
    c('mad2_a5', 'Treponema pallidum: diagnóstico sorológico?', 'VDRL/RPR + teste treponêmico específico.', '', 'clinica', 'material', ['sifilis']),
    c('mad2_a5', 'N. gonorrhoeae: cultura?', 'Meio Thayer-Martin (CO2).', '', 'prova', 'material', ['gonorreia']),
    c('mad2_a5', 'Chlamydia: intracelular obrigatória?', 'Sim — PCR preferido.', '', 'definicao', 'material', ['clamidia']),
    c('mad2_a5', 'Linfogranuloma venéreo: agente?', 'C. trachomatis L1–L3.', '', 'clinica', 'material', ['lgv']),
    c('mad2_a5', 'Sífilis latente: tratamento?', 'Penicilina benzatina (esquema por estágio).', '', 'clinica', 'material', ['penicilina']),
    c('mad2_a5', 'Resistência gonococo a ceftriaxona?', 'Emergência — vigilância antibiótica.', '', 'clinica', 'material', ['resistencia']),
    c('mad2_a5', 'Jarisch-Herxheimer?', 'Reação febril ao tratar sífilis (endotoxina).', '', 'clinica', 'material', ['jarisch']),
    c('mad2_a5', 'Sífilis congênita: transmissão?', 'Transplacentária.', '', 'clinica', 'material', ['congenita']),
    c('mad2_a5', 'Cancro duro: indolor?', 'Primário — úlcera única.', '', 'clinica', 'material', ['cancro']),
    c('mad2_a5', 'Neurossífilis: LCR?', 'Pleocitose, proteinorraquia — testes específicos.', '', 'clinica', 'material', ['neuro']),
    c('mad2_a5', 'Doxiclina em IST não grávida: cobre?', 'Clamídia (não penicilina para sífilis).', '', 'extra_livro', 'extra', ['doxiciclina']),
    c('mad2_a5', 'Profilaxia pós-exposição sexual?', 'Protocolos locais (tempo e esquema).', '', 'extra', 'extra', ['pep']),
  ],
  [ // mad2_a6
    c('mad2_a6', 'S. aureus: coagulase?', 'Positiva — patógeno comum de pele.', '', 'prova', 'material', ['aureus']),
    c('mad2_a6', 'S. pyogenes (GAS): exotoxina?', 'Eritrogênica — escarlatina.', '', 'clinica', 'material', ['piógenes']),
    c('mad2_a6', 'Celulite: agentes comuns?', 'GAS, S. aureus.', '', 'clinica', 'material', ['celulite']),
    c('mad2_a6', 'Impetigo: bactérias?', 'GAS e/ou S. aureus.', '', 'clinica', 'material', ['impetigo']),
    c('mad2_a6', 'Hanseníase multibacilar?', 'Índice bacilar alto — tratamento poliquímico prolongado.', '', 'clinica', 'material', ['hansen']),
    c('mad2_a6', 'M. leprae: transmissão?', 'Principalmente contato prolongado; não altamente contagiosa.', '', 'definicao', 'material', ['lepra']),
    c('mad2_a6', 'Necrotizing fasciitis: polimicrobiano vs monomicrobiano?', 'GAS vs mistura (inclui anaeróbios).', '', 'clinica', 'material', ['fasciite']),
    c('mad2_a6', 'Toxina Panton-Valentine em MRSA?', 'Associada a necrose pulmonar/pele.', '', 'clinica', 'material', ['pvl']),
    c('mad2_a6', 'Eritema crônico figurado na lepra?', 'Tipo lepromatoso.', '', 'clinica', 'material', ['lepra']),
    c('mad2_a6', 'Tratamento hanseníase PB vs MB?', 'Esquemas OMS (rifampicina + dapsona ± clofazimina).', '', 'clinica', 'material', ['pqt']),
    c('mad2_a6', 'Reação hansênica tipo 2?', 'Eritema nodoso — corticoide/ talidomida (contexto).', '', 'extra_livro', 'extra', ['reenacao']),
    c('mad2_a6', 'Descarte de instrumentos em possível CJD?', 'Protocolos específicos de esterilização.', '', 'extra', 'extra', ['cjd']),
  ],
  [ // mad2_a7
    c('mad2_a7', 'Sarampo: exantema típico?', 'Cefalocaudal, manchas que se unem.', '', 'clinica', 'material', ['sarampo']),
    c('mad2_a7', 'Sarampo: complicação?', 'Pneumonia, encefalite.', '', 'clinica', 'material', ['sarampo']),
    c('mad2_a7', 'Rubéola: risco gestacional?', 'Síndrome da rubéola congênita no 1º trimestre.', '', 'clinica', 'material', ['rubeola']),
    c('mad2_a7', 'Eritema infeccioso (parvovirus B19)?', 'Face esbofeteada, corpo em renda.', '', 'clinica', 'material', ['parvovirus']),
    c('mad2_a7', 'Varicela: lesão evolutiva?', 'Mácula → pápula → vesícula → crosta.', '', 'clinica', 'material', ['varicela']),
    c('mad2_a7', 'Herpangina (coxsackie)?', 'Vesículas em palato e faringe posterior.', '', 'clinica', 'material', ['herpangina']),
    c('mad2_a7', 'Mão-pé-boca?', 'Enterovírus — vesículas mãos/pés + oral.', '', 'clinica', 'material', ['enterovirus']),
    c('mad2_a7', 'Roséola infantum (HHV-6)?', 'Febre alta que cai e exantema surge.', '', 'clinica', 'material', ['roseola']),
    c('mad2_a7', 'Vacina tríplice viral previne?', 'Sarampo, caxumba, rubéola.', '', 'definicao', 'material', ['tríplice']),
    c('mad2_a7', 'Sarampo: notificação?', 'Compulsória — vigilância.', '', 'clinica', 'material', ['notificacao']),
    c('mad2_a7', 'Exantema medicamentoso?', 'Morfologia variada — história temporal com fármaco.', '', 'extra_livro', 'extra', ['drogas']),
    c('mad2_a7', 'Koplik spots?', 'Sarampo — mucosa oral antes do exantema.', '', 'extra', 'extra', ['koplik']),
  ],
  [ // mad2_a8
    c('mad2_a8', 'Hepatite A: transmissão?', 'Fecal-oral — vacina disponível.', '', 'definicao', 'material', ['hav']),
    c('mad2_a8', 'Hepatite B: cronicidade?', 'Risco maior se infecção neonatal/infantil.', '', 'clinica', 'material', ['hbv']),
    c('mad2_a8', 'HBsAg positivo significa?', 'Infecção aguda ou crônica (contexto).', '', 'prova', 'material', ['hbsag']),
    c('mad2_a8', 'Anti-HBs positivo?', 'Imunidade (vacina ou cura).', '', 'prova', 'material', ['antihbs']),
    c('mad2_a8', 'Hepatite C: tratamento atual?', 'Antivirais de ação direta (DAAs).', '', 'clinica', 'material', ['hcv']),
    c('mad2_a8', 'Hepatite D: requer?', 'Coinfecção/superinfecção com HBV.', '', 'definicao', 'material', ['hdv']),
    c('mad2_a8', 'Hepatite E: risco gestacional?', 'Gravidade em gravidez (alguns genótipos).', '', 'clinica', 'material', ['hev']),
    c('mad2_a8', 'Vacina HBV esquema?', '3 doses (0, 1, 6 meses comum).', '', 'definicao', 'material', ['vacina']),
    c('mad2_a8', 'HAV IgM positivo?', 'Infecção aguda recente.', '', 'prova', 'material', ['hav']),
    c('mad2_a8', 'Carga viral HCV monitora?', 'Resposta ao tratamento.', '', 'clinica', 'material', ['carga']),
    c('mad2_a8', 'Profilaxise pós-exposição HBV?', 'Imunoglobulina + vacina conforme status.', '', 'extra_livro', 'extra', ['pep']),
    c('mad2_a8', 'Cirrose por HBV/HCV: rastreio HCC?', 'USG + AFP/alfafetoproteína (protocolos).', '', 'extra', 'extra', ['hcc']),
  ],
  [ // mad2_a9
    c('mad2_a9', 'HIV liga-se a?', 'CD4 + correceptor CCR5/CXCR4.', '', 'definicao', 'material', ['hiv']),
    c('mad2_a9', 'CD4 <200: risco?', 'Infecções oportunistas (PJP, etc.).', '', 'clinica', 'material', ['aids']),
    c('mad2_a9', 'TARV: objetivo?', 'Suprimir carga viral indetectável.', '', 'clinica', 'material', ['tarv']),
    c('mad2_a9', 'Profilaxia pré-exposição (PrEP)?', 'Tenofovir + emtricitabina em risco.', '', 'clinica', 'material', ['prep']),
    c('mad2_a9', 'Profilaxia pós-exposição (PEP) HIV?', 'Início precoce (72h) — esquema 28 dias.', '', 'clinica', 'material', ['pep']),
    c('mad2_a9', 'Criptococo meningite em AIDS?', 'Amphotericina + flucitosina indução.', '', 'clinica', 'material', ['cripto']),
    c('mad2_a9', 'Pneumocystis jirovecii: profilaxia?', 'SMX/TMP quando CD4 baixo.', '', 'clinica', 'material', ['pjp']),
    c('mad2_a9', 'CMV retinite em AIDS?', 'Antivirais (ganciclovir).', '', 'clinica', 'material', ['cmv']),
    c('mad2_a9', 'Tuberculose associada HIV?', 'Tratamento TB + antirretroviral (timing de interação).', '', 'clinica', 'material', ['tb']),
    c('mad2_a9', 'Sífilis + HIV: critério de cura?', 'Titulação VDRL — possível resposta atípica.', '', 'clinica', 'material', ['sifilis']),
    c('mad2_a9', 'Undetectable = Untransmittable?', 'Carga viral suprimida reduz transmissão sexual drasticamente.', '', 'extra_livro', 'extra', ['u=u']),
    c('mad2_a9', 'Resistência a antirretrovirais?', 'Genotipagem quando falha virológica.', '', 'extra', 'extra', ['resistencia']),
  ],
  [ // mad2_a10
    c('mad2_a10', 'HSV-1 vs HSV-2 típico?', 'Oral vs genital (não exclusivo).', '', 'diferenciacao', 'material', ['hsv']),
    c('mad2_a10', 'VZV primário?', 'Varicela; reativação = herpes-zoster.', '', 'definicao', 'material', ['vzv']),
    c('mad2_a10', 'EBV: mononucleose?', 'Heterófilo positivo (monospot) — linfocitose atípica.', '', 'clinica', 'material', ['ebv']),
    c('mad2_a10', 'CMV em immunocomprometido?', 'Retinite, colite, esofagite.', '', 'clinica', 'material', ['cmv']),
    c('mad2_a10', 'Aciclovir: mecanismo?', 'Inibe DNA polimerase viral (precisa fosforilação viral).', '', 'mecanismo', 'material', ['aciclovir']),
    c('mad2_a10', 'Ganciclovir: CMV?', 'Similar, mas mais tóxico — monitorar neutrófilos.', '', 'clinica', 'material', ['ganciclovir']),
    c('mad2_a10', 'Latência HSV em?', 'Gânglios sensitivos.', '', 'definicao', 'material', ['latencia']),
    c('mad2_a10', 'Shingrix: vacina?', 'VZV recombinante — >50 anos.', '', 'clinica', 'material', ['shingrix']),
    c('mad2_a10', 'Encefalite herpética: tratamento?', 'Aciclovir IV empírico precoce.', '', 'clinica', 'material', ['encefalite']),
    c('mad2_a10', 'Roseola vs EBV em criança?', 'Idade e padrão febre/exantema diferem.', '', 'diferenciacao', 'material', ['roseola']),
    c('mad2_a10', 'Foscarnete: uso?', 'CMV resistente (segunda linha).', '', 'extra_livro', 'extra', ['foscarnete']),
    c('mad2_a10', 'Valaciclovir vs aciclovir?', 'Maior biodisponibilidade oral.', '', 'extra', 'extra', ['valaciclovir']),
  ],
];

const data = JSON.parse(fs.readFileSync(OUT, 'utf8'));
let id = 0;
for (const f of data.flashcards) if (f.id > id) id = f.id;
id++;
for (const lot of LOTS) for (const x of lot) data.flashcards.push({ ...x, id: id++ });
fs.writeFileSync(OUT, JSON.stringify(data, null, 2), 'utf8');
console.log('OK mad2 part1 total', data.flashcards.length, 'last id', id - 1);
