/** MAD2 mad2_a11–a20 × 12 — node scripts/append_flashcards_mad2_m3_part2.js */
const fs = require('fs');
const path = require('path');
const OUT = path.join(__dirname, '..', 'data', 'flashcards.json');
function c(t, f, v, e, cat, o, tags) {
  return { materia: 'mad2', tema: t, frente: f, verso: v, explicacao: e || '', dificuldade: 2, categoria: cat, origem: o, tags: tags || [] };
}
const LOTS = [
  [ // mad2_a11
    c('mad2_a11', 'Poliovírus: transmissão?', 'Fecal-oral.', '', 'definicao', 'material', ['polio']),
    c('mad2_a11', 'Vacina Sabin?', 'VOPV oral — vírus vivo atenuado.', '', 'definicao', 'material', ['vopv']),
    c('mad2_a11', 'Vacina Salk?', 'VIP inativada injetável.', '', 'definicao', 'material', ['vip']),
    c('mad2_a11', 'Paralisia flácida aguda: vigilância?', 'Investigar todas suspeitas (notificação).', '', 'clinica', 'material', ['pfa']),
    c('mad2_a11', 'Poliovírus replica onde?', 'Orofaringe e intestino — CNS em casos invasivos.', '', 'mecanismo', 'material', ['replicacao']),
    c('mad2_a11', 'Células motoras anteriores afetadas?', 'Paralisia inferior.', '', 'clinica', 'material', ['poliomielite']),
    c('mad2_a11', 'Pós-polic síndrome?', 'Fadiga muscular anos após infecção.', '', 'clinica', 'material', ['pos-polio']),
    c('mad2_a11', 'Erradicação global?', 'Vacinação + vigilância (poucos focos remanescentes).', '', 'definicao', 'material', ['erradicacao']),
    c('mad2_a11', 'VDPV?', 'Poliovírus derivado de vacina — surtos raros.', '', 'clinica', 'material', ['vdpv']),
    c('mad2_a11', 'Lavagem de mãos na prevenção polio?', 'Barreira fecal-oral.', '', 'mecanismo', 'material', ['higiene']),
    c('mad2_a11', 'Enterovírus não polio?', 'Coxsackie, echovirus — meningite aséptica.', '', 'extra_livro', 'extra', ['enterovirus']),
    c('mad2_a11', 'Suporte ventilatório histórico em polio?', 'Ferro de Dick (contexto epidemiológico).', '', 'extra', 'extra', ['historia']),
  ],
  [ // mad2_a12
    c('mad2_a12', 'Dengue: vetor?', 'Aedes aegypti.', '', 'definicao', 'material', ['dengue']),
    c('mad2_a12', 'Dengue grave: sinais de alarme?', 'Dor abdominal intensa, vômitos persistentes, sangramento.', '', 'clinica', 'material', ['dengue']),
    c('mad2_a12', 'Zika: complicação gestacional?', 'Microcefalia.', '', 'clinica', 'material', ['zika']),
    c('mad2_a12', 'Chikungunya: sintoma marcante?', 'Artralgia intensa prolongada.', '', 'clinica', 'material', ['chikungunya']),
    c('mad2_a12', 'Febre amarela: profilaxia?', 'Vacina atenuada (contraindicações imunossupressão).', '', 'clinica', 'material', ['febre-amarela']),
    c('mad2_a12', 'Diagnóstico molecular (PCR) em arbovírus?', 'Primeira semana — sorologia depois.', '', 'clinica', 'material', ['pcr']),
    c('mad2_a12', 'Hidratação oral na dengue sem alarme?', 'Pilar do manejo ambulatorial.', '', 'clinica', 'material', ['hidratacao']),
    c('mad2_a12', 'NSAIDs na dengue: evitar?', 'Risco hemorrágico (preferir dipirona/paracetamol conforme protocolo).', '', 'clinica', 'material', ['aine']),
    c('mad2_a12', 'Eliminação de criadouros: objetivo?', 'Controle vetorial.', '', 'mecanismo', 'material', ['aedes']),
    c('mad2_a12', 'Mayaro, Oropouche: grupo?', 'Togavirus/Bunyavirus — vigilância regional.', '', 'definicao', 'material', ['arbovirus']),
    c('mad2_a12', 'Síndrome de Guillain-Barré pós-Zika?', 'Associação descrita (imunológica).', '', 'extra_livro', 'extra', ['gbs']),
    c('mad2_a12', 'Teste rápido NS1 dengue?', 'Antígeno precoce — interpretar com data de início.', '', 'extra', 'extra', ['ns1']),
  ],
  [ // mad2_a13
    c('mad2_a13', 'Plasmodium falciparum: gravidade?', 'Parasitemia alta — formas múltiplas no eritrócito.', '', 'clinica', 'material', ['falciparum']),
    c('mad2_a13', 'Malária: diagnóstico microscópico?', 'Espessante de gota grossa + lâmina fina.', '', 'clinica', 'material', ['malária']),
    c('mad2_a13', 'T. cruzi: transmissão?', 'Triatomíneo, transfusão, vertical, oral.', '', 'definicao', 'material', ['chagas']),
    c('mad2_a13', 'Doença de Chagas crônica?', 'Cardiomiopatia, megacólon, megaesôfago.', '', 'clinica', 'material', ['chagas']),
    c('mad2_a13', 'Toxoplasma gondii: risco gestacional?', 'Infecção primária — transplacentária.', '', 'clinica', 'material', ['toxo']),
    c('mad2_a13', 'Trichomonas vaginalis: diagnóstico?', 'Wet mount móvel + PCR.', '', 'clinica', 'material', ['trichomonas']),
    c('mad2_a13', 'Leishmaniose visceral: agente?', 'L. donovani complex — esplenomegalia, febre.', '', 'clinica', 'material', ['leishmania']),
    c('mad2_a13', 'Giardia lamblia: tratamento?', 'Metronidazol / tinidazol.', '', 'clinica', 'material', ['giardia']),
    c('mad2_a13', 'Entamoeba histolytica: extra-intestinal?', 'Abscesso hepático.', '', 'clinica', 'material', ['ameba']),
    c('mad2_a13', 'Profilaxia malária viajante?', 'Quimioprofilaxia conforme resistência regional.', '', 'clinica', 'material', ['viagem']),
    c('mad2_a13', 'Benznidazol em Chagas indeterminado?', 'Indicação em protocolos selecionados.', '', 'extra_livro', 'extra', ['benznidazol']),
    c('mad2_a13', 'Atovaquona-proguanil para malária?', 'Profilaxia e tratamento (conforme esquema).', '', 'extra', 'extra', ['atovaquona']),
  ],
  [ // mad2_a14
    c('mad2_a14', 'Ascaris lumbricoides: complicação?', 'Obstrução intestinal, migração biliar.', '', 'clinica', 'material', ['ascaris']),
    c('mad2_a14', 'Ancylostoma/Necator: mecanismo?', 'Sangue intestinal — anemia ferropriva.', '', 'clinica', 'material', ['ancilostomíase']),
    c('mad2_a14', 'Strongyloides: auto-infecção?', 'Ciclo interno — hiperinfecção em imunossuprimidos.', '', 'clinica', 'material', ['strongyloides']),
    c('mad2_a14', 'Enterobius vermicularis: diagnóstico?', 'Fitas adesivas perianal (ovos).', '', 'clinica', 'material', ['oxiuro']),
    c('mad2_a14', 'Trichuris trichiura?', 'Diarreia crônica, retocolite (crianças).', '', 'clinica', 'material', ['tricuríase']),
    c('mad2_a14', 'Tratamento albendazol/mebendazol: cobre?', 'Muitos nematódeos intestinais.', '', 'clinica', 'material', ['albendazol']),
    c('mad2_a14', 'Larva migrans cutânea?', 'Ancilostomas de animais — ivermectina tópica/oral.', '', 'clinica', 'material', ['larva']),
    c('mad2_a14', 'Dracunculus medinensis?', 'Emergência da pele — erradicação em curso.', '', 'definicao', 'material', ['dracunculo']),
    c('mad2_a14', 'Wuchereria bancrofti?', 'Filariose linfática — elefantíase.', '', 'clinica', 'material', ['filariose']),
    c('mad2_a14', 'Diagnóstico de estrongiloidíase em imunossuprimido?', 'Múltiplas amostras de fezes; sorologia.', '', 'clinica', 'material', ['strongyloides']),
    c('mad2_a14', 'Ivermectina em strongyloides?', 'Tratamento de escolha em muitos casos.', '', 'extra_livro', 'extra', ['ivermectina']),
    c('mad2_a14', 'Síndrome de Loeffler (pulmão)?', 'Migrar larvas de Ascaris/Strongyloides — eosinofilia.', '', 'extra', 'extra', ['loeffler']),
  ],
  [ // mad2_a15
    c('mad2_a15', 'Taenia solium: ciclo?', 'Porco intermediário — humano com cisticercose se ingere ovos.', '', 'mecanismo', 'material', ['solium']),
    c('mad2_a15', 'Neurocisticercose: imagem?', 'Cistos com scolex no SNC.', '', 'clinica', 'material', ['neurocisticercose']),
    c('mad2_a15', 'Taenia saginata: intermediário?', 'Bovino — teníase intestinal.', '', 'definicao', 'material', ['saginata']),
    c('mad2_a15', 'Tratamento teníase?', 'Praziquantel / niclosamida.', '', 'clinica', 'material', ['teníase']),
    c('mad2_a15', 'Neurocisticercose: tratamento?', 'Anticonvulsivante + albendazol + corticoide (protocolo).', '', 'clinica', 'material', ['tratamento']),
    c('mad2_a15', 'Hymenolepis nana?', 'Autoinfecção — crianças.', '', 'clinica', 'material', ['hymenolepis']),
    c('mad2_a15', 'Diphyllobothrium latum?', 'Deficiência B12 por competição (raro).', '', 'clinica', 'material', ['diphyllobothrium']),
    c('mad2_a15', 'Echinococcus granulosus?', 'Cistos hidáticos — cirurgia + albendazol.', '', 'clinica', 'material', ['equinococo']),
    c('mad2_a15', 'Carne mal cozida e teníase?', 'T. solium/saginata cisticercos em músculo.', '', 'mecanismo', 'material', ['transmissao']),
    c('mad2_a15', 'Prevenção cisticercose?', 'Saneamento + cozinhar carne + higiene fecal.', '', 'clinica', 'material', ['prevencao']),
    c('mad2_a15', 'ELISA em neurocisticercose?', 'Sorologia auxiliar — imagem é central.', '', 'extra_livro', 'extra', ['elisa']),
    c('mad2_a15', 'E. multilocularis (alveolar)?', 'Comportamento tumoriforme — cirúrgico.', '', 'extra', 'extra', ['alveolar']),
  ],
  [ // mad2_a16
    c('mad2_a16', 'Penicilina G: espectro?', 'G+ cocos, alguns G−, não anaeróbios Bacteroides resistentes.', '', 'clinica', 'material', ['penicilina']),
    c('mad2_a16', 'Cefalosporinas 3ª geração: exemplo?', 'Ceftriaxona — G− ampliado, penetra SNC (parcial).', '', 'clinica', 'material', ['cefalosporina']),
    c('mad2_a16', 'Carbapenêmico: amplo espectro?', 'Meropenem — reservado para infecções graves.', '', 'clinica', 'material', ['carbapenem']),
    c('mad2_a16', 'Vancomicina: alvo?', 'Parede peptidoglicano G+ (inclui MRSA).', '', 'mecanismo', 'material', ['vancomicina']),
    c('mad2_a16', 'Inibidor de β-lactamase: exemplo?', 'Clavulanato com amoxicilina.', '', 'mecanismo', 'material', ['clavulanato']),
    c('mad2_a16', 'Betalactâmicos: alvo enzimático?', 'Transpeptidases PBP — síntese de parede.', '', 'mecanismo', 'material', ['pbp']),
    c('mad2_a16', 'MRSA: mecanismo?', 'PBP2a de baixa afinidade.', '', 'definicao', 'material', ['mrsa']),
    c('mad2_a16', 'VRE: resistência?', 'Alteração alvo vancomicina (D-Ala-D-Lac).', '', 'definicao', 'material', ['vre']),
    c('mad2_a16', 'Cefepima: geração?', '4ª — cobre Pseudomonas melhor que 3ª.', '', 'clinica', 'material', ['cefepima']),
    c('mad2_a16', 'Alergia penicilina: verificar?', 'Teste cutâneo em dúvida (não todos).', '', 'clinica', 'material', ['alergia']),
    c('mad2_a16', 'Red man syndrome?', 'Infusão rápida vancomicina — desacelerar infusão.', '', 'extra_livro', 'extra', ['vancomicina']),
    c('mad2_a16', 'Temocilina?', 'Glicilciclina — tetraciclina moderna (MRSA, etc.).', '', 'extra', 'extra', ['tigeciclina']),
  ],
  [ // mad2_a17
    c('mad2_a17', 'Aminoglicosídeo: alvo?', 'Subunidade 30S — iniciação/erro de leitura.', '', 'mecanismo', 'material', ['aminoglicosideo']),
    c('mad2_a17', 'Macrolídeo: alvo?', '50S — translocação.', '', 'mecanismo', 'material', ['macrolideo']),
    c('mad2_a17', 'Tetraciclinas: alvo?', '30S — bloqueio aminoacil-tRNA.', '', 'mecanismo', 'material', ['tetraciclina']),
    c('mad2_a17', 'Clindamicina: classe?', 'Lincosamina — 50S.', '', 'definicao', 'material', ['clindamicina']),
    c('mad2_a17', 'Linezolida: classe?', 'Oxazolidinona — 50S início.', '', 'definicao', 'material', ['linezolida']),
    c('mad2_a17', 'Cloranfenicol: toxicidade?', 'Supressão medular (dose/tempo).', '', 'clinica', 'material', ['cloranfenicol']),
    c('mad2_a17', 'Aminoglicosídeo: monitorar?', 'Níveis séricos e função renal (nefrotoxicidade).', '', 'clinica', 'material', ['monitorizacao']),
    c('mad2_a17', 'Macrolídeo e QT?', 'Prolongamento — cuidado com outros fármacos.', '', 'clinica', 'material', ['qt']),
    c('mad2_a17', 'Tetraciclina: contraindicação?', 'Gestação/crianças <8 anos (dentes).', '', 'clinica', 'material', ['tetraciclina']),
    c('mad2_a17', 'C. difficile pós-antibiótico?', 'Disbiose — metronidazol/vancomicina oral.', '', 'clinica', 'material', ['cdiff']),
    c('mad2_a17', 'Estreptograminas (quinupristina-dalfopristina)?', 'VRE — infusão venosa dolorosa.', '', 'extra_livro', 'extra', ['streptograma']),
    c('mad2_a17', 'Fusídico: uso?', 'Staphylococcus topico/sistêmico (limitado).', '', 'extra', 'extra', ['fusidico']),
  ],
  [ // mad2_a18
    c('mad2_a18', 'Fluoroquinolona: alvo?', 'DNA girase e topoisomerase IV (G− vs G+ diferen).', '', 'mecanismo', 'material', ['quinolona']),
    c('mad2_a18', 'Sulfonamida + trimetoprim:?', 'Inibição sequencial folato (bactéria).', '', 'mecanismo', 'material', ['sulfonamida']),
    c('mad2_a18', 'Resistência a quinolonas: mecanismos?', 'Mutações QRDR, bombas de efluxo.', '', 'definicao', 'material', ['resistencia']),
    c('mad2_a18', 'Rifampicina: uso isolado?', 'Não — resistência rápida (sempre combinação TB).', '', 'clinica', 'material', ['rifampicina']),
    c('mad2_a18', 'Metronidazol: espectro?', 'Anaeróbios e protozoários.', '', 'clinica', 'material', ['metronidazol']),
    c('mad2_a18', 'Nitrofurantoína: uso?', 'ITU baixa — não em IR com TFG muito baixa.', '', 'clinica', 'material', ['nitrofurantoina']),
    c('mad2_a18', 'Fosfomicina: uso?', 'ITU não complicada (dose única em alguns protocolos).', '', 'clinica', 'material', ['fosfomicina']),
    c('mad2_a18', 'Mutações espontâneas vs seleção?', 'Antibiótico seleciona mutantes resistentes.', '', 'mecanismo', 'material', ['mutacao']),
    c('mad2_a18', 'Plasmídeos de resistência?', 'Transmissão horizontal entre bactérias.', '', 'definicao', 'material', ['plasmideo']),
    c('mad2_a18', 'ESBL: o que é?', 'β-lactamases de espectro estendido — resistência a 3ª geração cefalosporinas.', '', 'definicao', 'material', ['esbl']),
    c('mad2_a18', 'Antibiótico stewardship?', 'Uso racional para reduzir resistência.', '', 'extra_livro', 'extra', ['stewardship']),
    c('mad2_a18', 'Colistina: reserva?', 'G− MDR — nefrotoxicidade.', '', 'extra', 'extra', ['colistina']),
  ],
  [ // mad2_a19
    c('mad2_a19', 'Aciclovir herpes: via?', 'Oral/IV conforme gravidade.', '', 'clinica', 'material', ['aciclovir']),
    c('mad2_a19', 'Ganciclovir CMV: monitorar?', 'Neutropenia, nefrotoxicidade.', '', 'clinica', 'material', ['ganciclovir']),
    c('mad2_a19', 'Oseltamivir: alvo?', 'Neuraminidase influenza — início precoce.', '', 'mecanismo', 'material', ['oseltamivir']),
    c('mad2_a19', 'Baloxavir marboxil?', 'Inibidor endonuclease cap dependente influenza.', '', 'definicao', 'material', ['baloxavir']),
    c('mad2_a19', 'TARV HIV: classes?', 'NRTI, NNRTI, PI, II, integrase.', '', 'definicao', 'material', ['tarv']),
    c('mad2_a19', 'Dolutegravir: classe?', 'Inibidor de integrase.', '', 'definicao', 'material', ['inst']),
    c('mad2_a19', 'Sofosbuvir + velpatasvir: indicação?', 'HCV com DAAs pangenotípico.', '', 'clinica', 'material', ['hcv']),
    c('mad2_a19', 'Ribavirina: uso?', 'HCV em combinações antigas; RSV em contextos específicos.', '', 'clinica', 'material', ['ribavirina']),
    c('mad2_a19', 'Foscarnete: mecanismo?', 'Inibe DNA polimerase (pirofosfato análogo).', '', 'mecanismo', 'material', ['foscarnete']),
    c('mad2_a19', 'Cidofovir: toxicidade?', 'Nefrotoxicidade — hidratação + probenecida.', '', 'clinica', 'material', ['cidofovir']),
    c('mad2_a19', 'Letermovir profilaxia CMV?', 'Pós-transplante (novo agente).', '', 'extra_livro', 'extra', ['letermovir']),
    c('mad2_a19', 'Paxlovid COVID-19?', 'Nirmatrelvir + ritonavir — interações CYP3A.', '', 'extra', 'extra', ['paxlovid']),
  ],
  [ // mad2_a20
    c('mad2_a20', 'Metronidazol: Giardia e anaeróbios?', 'Nitroredução intracelular — toxidade DNA.', '', 'mecanismo', 'material', ['metronidazol']),
    c('mad2_a20', 'Albendazol/ mebendazol: helmintos?', 'Inibem polimerização tubulina.', '', 'mecanismo', 'material', ['albendazol']),
    c('mad2_a20', 'Praziquantel: cestóides/trematódeos?', 'Aumenta permeabilidade Ca²⁺ membrana parasitária.', '', 'mecanismo', 'material', ['praziquantel']),
    c('mad2_a20', 'Ivermectina: nematódeos e ectoparasitas?', 'Canal glutamato-gated Cl−.', '', 'mecanismo', 'material', ['ivermectina']),
    c('mad2_a20', 'Anfotericina B: alvo?', 'Ergosterol membrana fúngica — tóxica.', '', 'mecanismo', 'material', ['anfotericina']),
    c('mad2_a20', 'Azoles: fluconazol?', 'Inibem 14α-desmetilase — síntese ergosterol.', '', 'mecanismo', 'material', ['azol']),
    c('mad2_a20', 'Echinocandinas: exemplo?', 'Caspofungina — inibe síntese parede (1,3 β-glucano).', '', 'mecanismo', 'material', ['echinocandina']),
    c('mad2_a20', 'Flucitosina: uso?', 'Combinada com anfotericina em criptococo (resistência se monoterapia).', '', 'clinica', 'material', ['flucitosina']),
    c('mad2_a20', 'Terbinafina: dermatofitos?', 'Inibe esqualeno epoxidase.', '', 'clinica', 'material', ['terbinafina']),
    c('mad2_a20', 'Nifurtimox em Chagas?', 'Tratamento em protocolos específicos.', '', 'clinica', 'material', ['nifurtimox']),
    c('mad2_a20', 'Melarsoprol: doença do sono?', 'Tóxico — arsenical (África).', '', 'extra_livro', 'extra', ['tripanosoma']),
    c('mad2_a20', 'Isavuconazole?', 'Azol ampliado — aspergilose/mucormicose (contexto).', '', 'extra', 'extra', ['isavuconazole']),
  ],
];

const data = JSON.parse(fs.readFileSync(OUT, 'utf8'));
let id = 0;
for (const f of data.flashcards) if (f.id > id) id = f.id;
id++;
for (const lot of LOTS) for (const x of lot) data.flashcards.push({ ...x, id: id++ });
fs.writeFileSync(OUT, JSON.stringify(data, null, 2), 'utf8');
console.log('OK mad2 part2 total', data.flashcards.length, 'last id', id - 1);
