/** IND ind_a1–a11 × 12 — node scripts/append_flashcards_ind_m2.js */
const fs = require('fs');
const path = require('path');
const OUT = path.join(__dirname, '..', 'data', 'flashcards.json');
function c(t, f, v, e, cat, o, tags) {
  return { materia: 'indicadores', tema: t, frente: f, verso: v, explicacao: e || '', dificuldade: 2, categoria: cat, origem: o, tags: tags || [] };
}
const LOTS = [
  [ // ind_a1
    c('ind_a1', 'Epidemiologia estuda?', 'Distribuição e determinantes de saúde/doença em populações.', '', 'definicao', 'material', ['epidemiologia']),
    c('ind_a1', 'John Snow: contribuição clássica?', 'Mapeou cólera e fechou poço de Broad Street (1854).', '', 'prova', 'material', ['snow']),
    c('ind_a1', 'Endemia vs epidemia?', 'Endemia: habitual na região; epidemia: excesso de casos esperados.', '', 'diferenciacao', 'material', ['endemia']),
    c('ind_a1', 'Pandemia?', 'Epidemia disseminada globalmente.', '', 'definicao', 'material', ['pandemia']),
    c('ind_a1', 'Vigilância epidemiológica: objetivo?', 'Detectar mudanças e orientar intervenções.', '', 'definicao', 'material', ['vigilancia']),
    c('ind_a1', 'População-alvo vs amostra?', 'Alvo: grupo estudo; amostra: parte representativa.', '', 'diferenciacao', 'material', ['amostra']),
    c('ind_a1', 'Sesgo de seleção?', 'Participantes não representam população (distorsão).', '', 'definicao', 'material', ['sesgo']),
    c('ind_a1', 'Coorte estuda?', 'Grupos expostos/não expostos ao longo do tempo.', '', 'definicao', 'material', ['coorte']),
    c('ind_a1', 'Casos e controles?', 'Retrospectivo — compara exposição entre doentes e não doentes.', '', 'definicao', 'material', ['caso-controle']),
    c('ind_a1', 'Ensaio clínico randomizado reduz?', 'Sesgos de confusão (randomização).', '', 'mecanismo', 'material', ['ecr']),
    c('ind_a1', 'Hans Rosling: foco?', 'Visualização de dados de saúde global (contexto educativo).', '', 'extra_livro', 'extra', ['dados']),
    c('ind_a1', 'Indicador de saúde: definição?', 'Medida quantitativa que resume evento de saúde em população.', '', 'extra', 'extra', ['indicador']),
  ],
  [ // ind_a2
    c('ind_a2', 'HND: fases típicas?', 'Exposição → período de latência → doença clínica → desfecho.', '', 'definicao', 'material', ['hnd']),
    c('ind_a2', 'Prevenção primária?', 'Evitar ocorrência (vacina, estilo de vida).', '', 'definicao', 'material', ['primaria']),
    c('ind_a2', 'Prevenção secundária?', 'Detecção precoce (rastreamento).', '', 'definicao', 'material', ['secundaria']),
    c('ind_a2', 'Prevenção terciária?', 'Limitar sequelas e reabilitar.', '', 'definicao', 'material', ['terciaria']),
    c('ind_a2', 'Prevenção quaternária?', 'Evitar intervenções desnecessárias/iatrogênicas.', '', 'definicao', 'material', ['quaternaria']),
    c('ind_a2', 'Rastreamento: requisito de Wilson?', 'Doença importante, tratamento disponível, teste aceitável, etc.', '', 'prova', 'material', ['rastreamento']),
    c('ind_a2', 'Período de latência longo implica?', 'Janela para prevenção primária antes de sintomas.', '', 'mecanismo', 'material', ['latencia']),
    c('ind_a2', 'Curva epidemiológica: eixo x comum?', 'Tempo (semanas) em surtos.', '', 'definicao', 'material', ['curva']),
    c('ind_a2', 'Caso índice?', 'Primeiro caso identificado em investigação.', '', 'definicao', 'material', ['indice']),
    c('ind_a2', 'Contato em vigilância?', 'Indivíduo exposto potencialmente infectado.', '', 'definicao', 'material', ['contato']),
    c('ind_a2', 'Imunidade de rebanho?', 'Proporção vacinada/imune necessária para interrupção transmissão.', '', 'extra_livro', 'extra', ['rebanho']),
    c('ind_a2', 'Janela imunológica HIV?', 'Período entre infecção e soroconversão (testes).', '', 'extra', 'extra', ['hiv']),
  ],
  [ // ind_a3
    c('ind_a3', 'Transição epidemiológica: mudança?', 'Doenças infecciosas para crônico-degenerativas.', '', 'definicao', 'material', ['transicao']),
    c('ind_a3', 'Transição demográfica: tendência?', 'Queda mortalidade e fecundidade → envelhecimento.', '', 'definicao', 'material', ['demografica']),
    c('ind_a3', 'Transição nutricional?', 'Desnutrição → excesso calórico/obesidade.', '', 'definicao', 'material', ['nutricional']),
    c('ind_a3', 'Brasil: perfil de mortalidade atual?', 'Predominância de DCNT (contexto geral).', '', 'clinica', 'material', ['brasil']),
    c('ind_a3', 'Dupla carga de doença?', 'Coexistência infecções e crônicos no mesmo país.', '', 'definicao', 'material', ['dupla']),
    c('ind_a3', 'Expectativa de vida: aumento?', 'Impacta prevalência de doenças crônicas.', '', 'mecanismo', 'material', ['expectativa']),
    c('ind_a3', 'Urbanização e saúde?', 'Exposição a poluição, sedentarismo, acidentes.', '', 'mecanismo', 'material', ['urbano']),
    c('ind_a3', 'Envelhecimento populacional: sistema de saúde?', 'Maior demanda por morbidades crônicas.', '', 'clinica', 'material', ['idoso']),
    c('ind_a3', 'Desigualdade social: efeito em saúde?', 'Gradiente de mortalidade/morbidade por classe.', '', 'mecanismo', 'material', ['desigualdade']),
    c('ind_a3', 'ODS 3: meta?', 'Saúde e bem-estar (ONU).', '', 'definicao', 'material', ['ods']),
    c('ind_a3', 'Mortalidade infantil no tempo no Brasil?', 'Tendência de queda (programas históricos).', '', 'extra_livro', 'extra', ['mi']),
    c('ind_a3', 'Carga global de doença (GBD): mede?', 'DALYs — anos de vida perdidos + vividos com incapacidade.', '', 'extra', 'extra', ['daly']),
  ],
  [ // ind_a4
    c('ind_a4', 'Taxa bruta de natalidade?', 'Nascidos vivos / população média (período).', '', 'definicao', 'material', ['natalidade']),
    c('ind_a4', 'Taxa de mortalidade geral?', 'Óbitos / população média (×1000 comum).', '', 'definicao', 'material', ['mortalidade']),
    c('ind_a4', 'Taxa de fecundidade vs fertilidade?', 'Fecundidade: filhos por mulher em idade fértil; fertilidade por idade.', '', 'diferenciacao', 'material', ['fecundidade']),
    c('ind_a4', 'Crescimento vegetativo?', 'Nascimentos − óbitos.', '', 'definicao', 'material', ['vegetativo']),
    c('ind_a4', 'Migração líquida afeta?', 'População regional além de nascimentos/óbitos.', '', 'mecanismo', 'material', ['migracao']),
    c('ind_a4', 'Razão de dependência?', '(Pop <15 + ≥65) / pop 15–64.', '', 'definicao', 'material', ['dependencia']),
    c('ind_a4', 'IBGE: fonte?', 'Censo e estimativas populacionais Brasil.', '', 'definicao', 'material', ['ibge']),
    c('ind_a4', 'Pirâmide etária larga na base?', 'População jovem (países em transição).', '', 'clinica', 'material', ['piramide']),
    c('ind_a4', 'Taxa específica por idade?', 'Eventos em faixa etária / população da faixa.', '', 'definicao', 'material', ['especifica']),
    c('ind_a4', 'Padronização direta: por quê?', 'Comparar populações com estruturas etárias diferentes.', '', 'mecanismo', 'material', ['padronizacao']),
    c('ind_a4', 'Taxa de mortalidade infantil é?', 'Óbitos <1 ano / 1000 nascidos vivos.', '', 'extra_livro', 'extra', ['mi']),
    c('ind_a4', 'Coeficiente de Gini: mede?', 'Desigualdade de renda (0–1).', '', 'extra', 'extra', ['gini']),
  ],
  [ // ind_a5
    c('ind_a5', 'Prevalência?', 'Casos existentes / população em momento ou período.', '', 'definicao', 'material', ['prevalencia']),
    c('ind_a5', 'Incidência?', 'Casos novos / população em risco no tempo.', '', 'definicao', 'material', ['incidencia']),
    c('ind_a5', 'Relação prevalência/incidência × duração?', 'Prevalência ≈ incidência × duração média (aprox.).', '', 'mecanismo', 'material', ['relacao']),
    c('ind_a5', 'Incidência cumulativa?', 'Proporção que adoece em período (risco).', '', 'definicao', 'material', ['cumulativa']),
    c('ind_a5', 'Densidade de incidência?', 'Casos / tempo-pessoa em risco.', '', 'definicao', 'material', ['densidade']),
    c('ind_a5', 'Taxa de ataque?', 'Incidência em surtos (ex.: por exposição comum).', '', 'definicao', 'material', ['ataque']),
    c('ind_a5', 'Odds ratio?', 'Razão de chances em estudos caso-controle.', '', 'definicao', 'material', ['odds']),
    c('ind_a5', 'Risco relativo?', 'Incidência expostos / não expostos (coorte).', '', 'definicao', 'material', ['rr']),
    c('ind_a5', 'Letalidade?', 'Óbitos / casos da doença (gravidade).', '', 'definicao', 'material', ['letalidade']),
    c('ind_a5', 'Mortalidade proporcional?', 'Óbitos por causa / total óbitos.', '', 'definicao', 'material', ['proporcional']),
    c('ind_a5', 'Número necessário para tratar (NNT)?', 'Pacientes a tratar para um benefício extra.', '', 'extra_livro', 'extra', ['nnt']),
    c('ind_a5', 'Viés de sobrevivência em prevalência?', 'Doenças mais longas aparecem mais na prevalência.', '', 'extra', 'extra', ['vies']),
  ],
  [ // ind_a6
    c('ind_a6', 'SIM: o que registra?', 'Óbitos no Brasil — causa básica.', '', 'definicao', 'material', ['sim']),
    c('ind_a6', 'Causa básica de morte?', 'Cadeia que iniciou o evento fatal (regra internacional).', '', 'definicao', 'material', ['causa-basica']),
    c('ind_a6', 'CID-10: uso?', 'Classificação de doenças e causas de óbito.', '', 'definicao', 'material', ['cid']),
    c('ind_a6', 'Mortalidade proporcional por causa?', 'Percentual de óbitos por causa específica.', '', 'definicao', 'material', ['proporcional']),
    c('ind_a6', 'Taxa de mortalidade específica por causa?', 'Óbitos por causa / população.', '', 'definicao', 'material', ['especifica']),
    c('ind_a6', 'Mortalidade por sexo?', 'Compara perfis (ex.: CV em homens mais cedo).', '', 'clinica', 'material', ['sexo']),
    c('ind_a6', 'Declaração de óbito: documento?', 'Base legal para registro civil e epidemiologia.', '', 'definicao', 'material', ['do']),
    c('ind_a6', 'PRO-AIM?', 'Sistema municipal de óbitos (qualidade local).', '', 'definicao', 'material', ['pro-aim']),
    c('ind_a6', 'Sub-registro de óbitos: efeito?', 'Subestima mortalidade (áreas remotas).', '', 'clinica', 'material', ['subregistro']),
    c('ind_a6', 'Óbito fetal vs neonatal em estatísticas?', 'Definições de limite de idade gestacional/peso (protocolos).', '', 'prova', 'material', ['fetal']),
    c('ind_a6', 'Mortalidade materna: numerador?', 'Óbitos maternos / nascidos vivos (OMS).', '', 'extra_livro', 'extra', ['mm']),
    c('ind_a6', 'Coeficiente geral de mortalidade?', 'Óbitos / população média (geralmente ×1000).', '', 'extra', 'extra', ['cgm']),
  ],
  [ // ind_a7
    c('ind_a7', 'Coeficiente de mortalidade infantil (Brasil)?', 'Óbitos <1 ano / 1000 NV.', '', 'definicao', 'material', ['mi']),
    c('ind_a7', 'Componentes da MI: neonatal precoce?', '0–6 dias (perinatal próximo ao parto).', '', 'definicao', 'material', ['neonatal']),
    c('ind_a7', 'Neonatal tardia?', '7–27 dias.', '', 'definicao', 'material', ['neonatal']),
    c('ind_a7', 'Pós-neonatal?', '28 dias a <1 ano.', '', 'definicao', 'material', ['pos-neonatal']),
    c('ind_a7', 'Mortalidade perinatal inclui?', 'Óbitos fetais + neonatal precoce (definições OMS).', '', 'definicao', 'material', ['perinatal']),
    c('ind_a7', 'Mortalidade materna: causas obstétricas?', 'Hemorragia, hipertensão, sepse, aborto inseguro.', '', 'clinica', 'material', ['materna']),
    c('ind_a7', 'Letalidade de caso em surt?', 'Óbitos / casos (ex.: febre amarela).', '', 'definicao', 'material', ['letalidade']),
    c('ind_a7', 'Óbito evitável?', 'Mortes que poderiam ser evitadas com intervenções (conceito).', '', 'definicao', 'material', ['evitavel']),
    c('ind_a7', 'Peso ao nascer baixo: risco?', 'Maior mortalidade neonatal.', '', 'clinica', 'material', ['pn']),
    c('ind_a7', 'Apgar baixo correlaciona?', 'Depressão neonatal — reanimação.', '', 'clinica', 'material', ['apgar']),
    c('ind_a7', 'Lactente: mortalidade por causas externas?', 'Importante após 1º ano (acidentes).', '', 'extra_livro', 'extra', ['externas']),
    c('ind_a7', 'Mortalidade proporcional infantil?', 'Participação dos óbitos infantis no total (interpretar com cautela).', '', 'extra', 'extra', ['proporcional']),
  ],
  [ // ind_a8
    c('ind_a8', 'DATASUS: portal?', 'Acesso a bases do SUS (TABNET, etc.).', '', 'definicao', 'material', ['datasus']),
    c('ind_a8', 'SINAN: notifica?', 'Doenças e agravos de notificação compulsória.', '', 'definicao', 'material', ['sinan']),
    c('ind_a8', 'SIM vs SINAN?', 'SIM óbitos; SINAN casos de doenças específicas.', '', 'diferenciacao', 'material', ['sim']),
    c('ind_a8', 'SIH/SUS: dados?', 'Internações hospitalares (AIH).', '', 'definicao', 'material', ['sih']),
    c('ind_a8', 'Cadastro Único: uso?', 'Programas sociais — perfil vulnerabilidade.', '', 'definicao', 'material', ['cadunico']),
    c('ind_a8', 'Notificação compulsória: base legal?', 'Portarias vigentes (lista atualizada).', '', 'definicao', 'material', ['notificacao']),
    c('ind_a8', 'Indicadores de morbidade hospitalar?', 'Internações por CID — vigilância.', '', 'clinica', 'material', ['morbidade']),
    c('ind_a8', 'Sistemas integrados: benefício?', 'Correlação vigilância–assistência.', '', 'mecanismo', 'material', ['integracao']),
    c('ind_a8', 'Limitação de dados administrativos?', 'Codificação incorreta, subnotificação.', '', 'clinica', 'material', ['qualidade']),
    c('ind_a8', 'RNDS: conceito?', 'Rede Nacional de Dados em Saúde (interoperabilidade).', '', 'definicao', 'material', ['rnds']),
    c('ind_a8', 'e-SUS APS: registra?', 'Atendimentos na atenção primária.', '', 'extra_livro', 'extra', ['esus']),
    c('ind_a8', 'Painel de monitoramento COVID-19 exemplo?', 'Transparência em tempo real (contexto pandemia).', '', 'extra', 'extra', ['covid']),
  ],
  [ // ind_a9
    c('ind_a9', 'Variável qualitativa nominal?', 'Categorias sem ordem (cor, sexo biológico em algumas análises).', '', 'definicao', 'material', ['nominal']),
    c('ind_a9', 'Variável ordinal?', 'Categorias ordenadas (estádios NYHA).', '', 'definicao', 'material', ['ordinal']),
    c('ind_a9', 'Variável quantitativa discreta?', 'Contagens inteiras (nº de filhos).', '', 'definicao', 'material', ['discreta']),
    c('ind_a9', 'Variável contínua?', 'Peso, pressão (em escala real).', '', 'definicao', 'material', ['continua']),
    c('ind_a9', 'Distribuição normal: simetria?', 'Média = mediana; forma de sino.', '', 'definicao', 'material', ['normal']),
    c('ind_a9', 'Histograma adequado para?', 'Variáveis contínuas agrupadas em classes.', '', 'definicao', 'material', ['histograma']),
    c('ind_a9', 'Gráfico de barras para?', 'Comparar categorias.', '', 'definicao', 'material', ['barras']),
    c('ind_a9', 'Boxplot mostra?', 'Mediana, quartis, outliers.', '', 'definicao', 'material', ['boxplot']),
    c('ind_a9', 'Variável de confusão?', 'Associada a exposição e desfecho — distorce associação.', '', 'definicao', 'material', ['confusao']),
    c('ind_a9', 'Razão de prevalência?', 'Prevalência expostos / não expostos (transversal).', '', 'definicao', 'material', ['rp']),
    c('ind_a9', 'Escala Likert?', 'Ordinal em questionários (concordo totalmente…).', '', 'extra_livro', 'extra', ['likert']),
    c('ind_a9', 'Dados linkage?', 'Associação de bases pelo mesmo indivíduo (CNPJ/CNS).', '', 'extra', 'extra', ['linkage']),
  ],
  [ // ind_a10
    c('ind_a10', 'Média aritmética: sensível a?', 'Valores extremos (outliers).', '', 'mecanismo', 'material', ['media']),
    c('ind_a10', 'Mediana: vantagem?', 'Robusta a outliers (distribuições assimétricas).', '', 'definicao', 'material', ['mediana']),
    c('ind_a10', 'Moda?', 'Valor mais frequente.', '', 'definicao', 'material', ['moda']),
    c('ind_a10', 'Desvio padrão: interpretação?', 'Dispersão em torno da média (mesma unidade da variável).', '', 'definicao', 'material', ['dp']),
    c('ind_a10', 'Variância = ?', 'Soma dos quadrados das diferenças à média / n (população) ou n-1 (amostra).', '', 'definicao', 'material', ['variancia']),
    c('ind_a10', 'Coeficiente de variação (CV)?', 'DP / média — compara dispersão entre variáveis diferentes.', '', 'definicao', 'material', ['cv']),
    c('ind_a10', 'Intervalo interquartil (IQR)?', 'Q3 − Q1 — amplitude central dos 50%.', '', 'definicao', 'material', ['iqr']),
    c('ind_a10', 'Distribuição assimétrica positiva?', 'Cauda à direita; média > mediana.', '', 'definicao', 'material', ['assimetria']),
    c('ind_a10', 'Erro padrão da média?', 'DP/√n — incerteza da estimativa da média.', '', 'definicao', 'material', ['epm']),
    c('ind_a10', 'Gráfico de dispersão: relação?', 'Duas variáveis quantitativas.', '', 'definicao', 'material', ['dispersao']),
    c('ind_a10', 'Log-transformação: quando?', 'Dados muito assimétricos positivos (contagens).', '', 'extra_livro', 'extra', ['log']),
    c('ind_a10', 'Percentil 95 de PA?', 'Valor abaixo do qual estão 95% dos indivíduos.', '', 'extra', 'extra', ['percentil']),
  ],
  [ // ind_a11
    c('ind_a11', 'Hipótese nula (H0)?', 'Ausência de diferença/associação (teste estatístico).', '', 'definicao', 'material', ['h0']),
    c('ind_a11', 'Hipótese alternativa (H1)?', 'Diferença ou associação existe.', '', 'definicao', 'material', ['h1']),
    c('ind_a11', 'Valor de p: interpretação?', 'Probabilidade dos dados (ou mais extremos) se H0 verdadeira.', '', 'definicao', 'material', ['p']),
    c('ind_a11', 'p < 0,05 tradicionalmente?', 'Rejeita H0 (significância estatística).', '', 'prova', 'material', ['significancia']),
    c('ind_a11', 'Erro tipo I?', 'Rejeitar H0 quando é verdadeira (falso positivo).', '', 'definicao', 'material', ['tipoI']),
    c('ind_a11', 'Erro tipo II?', 'Não rejeitar H0 falsa (falso negativo).', '', 'definicao', 'material', ['tipoII']),
    c('ind_a11', 'Poder do teste (1-β)?', 'Capacidade de detectar efeito real.', '', 'definicao', 'material', ['poder']),
    c('ind_a11', 'Intervalo de confiança 95%?', 'Faixa que contém parâmetro verdadeiro em ~95% repetições (frequencista).', '', 'definicao', 'material', ['ic']),
    c('ind_a11', 'Teste t compara?', 'Médias entre grupos (variável contínua aprox. normal).', '', 'definicao', 'material', ['teste-t']),
    c('ind_a11', 'Qui-quadrado: uso?', 'Associação entre variáveis categóricas.', '', 'definicao', 'material', ['qui-quadrado']),
    c('ind_a11', 'Correção de Bonferroni?', 'Reduz α quando múltiplos testes (menos falsos positivos).', '', 'extra_livro', 'extra', ['bonferroni']),
    c('ind_a11', 'Significância estatística ≠ clínica?', 'Efeito pode ser pequeno mas significativo com N grande.', '', 'extra', 'extra', ['clinica']),
  ],
];

const data = JSON.parse(fs.readFileSync(OUT, 'utf8'));
let id = 0;
for (const f of data.flashcards) if (f.id > id) id = f.id;
id++;
for (const lot of LOTS) for (const x of lot) data.flashcards.push({ ...x, id: id++ });
fs.writeFileSync(OUT, JSON.stringify(data, null, 2), 'utf8');
console.log('OK ind total', data.flashcards.length, 'last id', id - 1);
