/** BCM1 bcm1_a1–a11 × 12 — node scripts/append_flashcards_bcm1_m2_part1.js */
const fs = require('fs');
const path = require('path');
const OUT = path.join(__dirname, '..', 'data', 'flashcards.json');
function c(t, f, v, e, cat, o, tags) {
  return { materia: 'bcm1', tema: t, frente: f, verso: v, explicacao: e || '', dificuldade: 2, categoria: cat, origem: o, tags: tags || [] };
}
const LOTS = [
  [ // bcm1_a1
    c('bcm1_a1', 'Bicamada lipídica: orientação das caudas?', 'Caudas apolares voltadas para o interior (hidrofóbicas).', '', 'definicao', 'material', ['membrana']),
    c('bcm1_a1', 'Na⁺/K⁺-ATPase: troca iônica típica?', '3 Na⁺ saem, 2 K⁺ entram (consome ATP).', '', 'mecanismo', 'material', ['bomba']),
    c('bcm1_a1', 'RER vs REL: função principal do RER?', 'Ribossomos aderidos — síntese de proteínas de secreção, membrana e lisossomo.', '', 'diferenciacao', 'material', ['re']),
    c('bcm1_a1', 'Lisossomo: pH e papel das hidrolases?', 'pH ~4,5–5 — hidrolases ácidas degradam macromoléculas.', '', 'definicao', 'material', ['lisossomo']),
    c('bcm1_a1', 'Mitocôndria: onde ocorre fosforilação oxidativa?', 'Cristas da membrana interna (cadeia respiratória e ATP sintase).', '', 'definicao', 'material', ['mito']),
    c('bcm1_a1', 'DNA mitocondrial: herança?', 'Exclusivamente materna (na maioria dos casos).', '', 'prova', 'material', ['mtdna']),
    c('bcm1_a1', 'Ribossomo eucariótico vs procariótico/mitocondrial?', '80S (60S+40S) euca × 70S (50S+30S) proca/mito.', '', 'prova', 'material', ['ribossomo']),
    c('bcm1_a1', 'COPII transporta de onde para onde?', 'RE → Golgi (anterógrado).', '', 'definicao', 'material', ['vesiculas']),
    c('bcm1_a1', 'Mannose-6-fosfato endereça enzimas para?', 'Lisossomos (via Golgi).', '', 'mecanismo', 'material', ['m6p']),
    c('bcm1_a1', 'Microtúbulos: monômero e fármaco que estabiliza?', 'α/β-tubulina — paclitaxel estabiliza; vincristina despolimeriza.', '', 'clinica', 'material', ['tubulina']),
    c('bcm1_a1', 'Síndrome de Kartagener: defeito típico?', 'Dineína ciliar — cílios imóveis; pode haver situs inversus.', '', 'clinica', 'extra', ['kartagener']),
    c('bcm1_a1', 'Digitálica inibe Na⁺/K⁺-ATPase: efeito cardíaco indireto?', '↑Na⁺ intracelular → NCX → ↑Ca²⁺ → inotropismo positivo.', '', 'extra_livro', 'extra', ['digital']),
  ],
  [ // bcm1_a2
    c('bcm1_a2', 'pH arterial normal?', '7,35–7,45.', '', 'definicao', 'material', ['gasometria']),
    c('bcm1_a2', 'Principal tampão extracelular?', 'Sistema bicarbonato/CO₂.', '', 'definicao', 'material', ['tampao']),
    c('bcm1_a2', 'Acidose respiratória: alteração primária em PaCO₂?', 'PaCO₂ elevada.', '', 'prova', 'material', ['respiratoria']),
    c('bcm1_a2', 'Alcalose respiratória: alteração primária em PaCO₂?', 'PaCO₂ baixa (hiperventilação).', '', 'prova', 'material', ['respiratoria']),
    c('bcm1_a2', 'Acidose metabólica: HCO₃⁻ primário?', 'HCO₃⁻ baixo.', '', 'prova', 'material', ['metabolica']),
    c('bcm1_a2', 'Fórmula de Winter (compensação)?', 'PaCO₂ esperada ≈ 1,5 × HCO₃⁻ + 8 (±2).', '', 'prova', 'material', ['winter']),
    c('bcm1_a2', 'Ânion gap: fórmula clássica?', 'Na⁺ − (Cl⁻ + HCO₃⁻); normal ~8–12 mEq/L.', '', 'definicao', 'material', ['ag']),
    c('bcm1_a2', 'Hemoglobina como tampão: efeito Haldane?', 'Hb desoxigenada tampona mais H⁺.', '', 'mecanismo', 'material', ['hb']),
    c('bcm1_a2', 'NH₃ + H⁺ no rim forma?', 'NH₄⁺ — excreção de ácido.', '', 'mecanismo', 'material', ['amonia']),
    c('bcm1_a2', 'Distúrbio misto na gasometria: pista?', 'Compensação além do esperado para um distúrbio simples.', '', 'clinica', 'material', ['misto']),
    c('bcm1_a2', 'Acidose láctica: AG típico?', 'Elevado (lactato não medido no ânion).', '', 'clinica', 'extra', ['lactato']),
    c('bcm1_a2', 'MUDPILES lembra o quê?', 'Causas clássicas de AG elevado em acidose metabólica.', '', 'extra_livro', 'extra', ['mudpiles']),
  ],
  [ // bcm1_a3
    c('bcm1_a3', 'Genoma humano haploide: ordem de tamanho?', '~3,2 × 10⁹ pb.', '', 'definicao', 'material', ['genoma']),
    c('bcm1_a3', 'Exon vs íntron?', 'Exon permanece no mRNA maduro; íntron é removido no splicing.', '', 'diferenciacao', 'material', ['gene']),
    c('bcm1_a3', 'Regra GT–AG no splicing?', 'Íntron começa com GU e termina com AG no RNA.', '', 'prova', 'material', ['splicing']),
    c('bcm1_a3', 'Nucleossomo: o que envolve o DNA?', 'Octâmero de histonas (H2A, H2B, H3, H4).', '', 'definicao', 'material', ['cromatina']),
    c('bcm1_a3', 'Eucromatina vs heterocromatina?', 'Eucro: ativa/descondensada; hetero: mais condensada/inativa ou repetitiva.', '', 'diferenciacao', 'material', ['cromatina']),
    c('bcm1_a3', 'Corpúsculo de Barr relaciona-se a?', 'Inativação do X (lyonização) — XIST.', '', 'clinica', 'material', ['xist']),
    c('bcm1_a3', 'Telômero: sequência repetida humana?', 'TTAGGG (encurta a cada divisão; telomerase em germinativas/câncer).', '', 'definicao', 'material', ['telomero']),
    c('bcm1_a3', 'Sinal de poliadenilação DNA típico?', 'AATAAA → clivagem e cauda poly(A).', '', 'prova', 'material', ['polya']),
    c('bcm1_a3', 'Dogma central: fluxo clássico?', 'DNA → RNA → proteína (com replicação do DNA).', '', 'definicao', 'material', ['dogma']),
    c('bcm1_a3', 'DNA mitocondrial: formato e tamanho aproximado?', 'Circular ~16,5 kb; 37 genes.', '', 'prova', 'material', ['mtdna']),
    c('bcm1_a3', 'SNP significa?', 'Polimorfismo de nucleotídeo único.', '', 'definicao', 'extra', ['snp']),
    c('bcm1_a3', 'LINE vs SINE em termos de exemplo?', 'LINE-1 longo; Alu é SINE abundante no humano.', '', 'extra_livro', 'extra', ['repetitivo']),
  ],
  [ // bcm1_a4
    c('bcm1_a4', 'GPCR: quantos domínios transmembrana típicos?', 'Sete (receptores acoplados à proteína G).', '', 'definicao', 'material', ['gpcr']),
    c('bcm1_a4', 'Via Gs: segundo mensageiro principal?', '↑ cAMP → PKA.', '', 'mecanismo', 'material', ['camp']),
    c('bcm1_a4', 'Via Gq: produtos da PLC?', 'IP₃ (libera Ca²⁺ do RE) e DAG (ativa PKC).', '', 'mecanismo', 'material', ['ip3']),
    c('bcm1_a4', 'RTKs: ativação típica ao ligar?', 'Dimerização e autofosforilação em tirosinas.', '', 'mecanismo', 'material', ['rtk']),
    c('bcm1_a4', 'Via RAS clássica downstream?', 'RAF → MEK → ERK (MAPK).', '', 'mecanismo', 'material', ['mapk']),
    c('bcm1_a4', 'Insulina: via PI3K/Akt leva a?', 'Akt → mobilização de GLUT4 (músculo/adipócito).', '', 'clinica', 'material', ['insulina']),
    c('bcm1_a4', 'Hormônios esteroides: onde atuam?', 'Receptores nucleares/citosólicos — regulam transcrição.', '', 'diferenciacao', 'material', ['esteroides']),
    c('bcm1_a4', 'NO ativa qual segundo mensageiro?', 'cGMP (guanil ciclase solúvel).', '', 'mecanismo', 'material', ['no']),
    c('bcm1_a4', 'Toxina do cólera: alvo em Gs?', 'ADP-ribosilação de Gsα → cAMP alto no enterócito → diarreia.', '', 'clinica', 'material', ['colera']),
    c('bcm1_a4', 'Comunicação autócrina?', 'Célula responde ao próprio ligando (comum em tumor).', '', 'definicao', 'material', ['autocrina']),
    c('bcm1_a4', 'β-bloqueador bloqueia qual via em adrenoceptores?', 'GPCRs β — reduz cAMP dependente de agonista.', '', 'clinica', 'extra', ['beta-bloqueador']),
    c('bcm1_a4', 'Notch é exemplo de sinalização?', 'Juxtácrina (contato célula–célula).', '', 'extra_livro', 'extra', ['notch']),
  ],
  [ // bcm1_a5
    c('bcm1_a5', 'Replicação: modelo?', 'Semiconservativa.', '', 'definicao', 'material', ['replicacao']),
    c('bcm1_a5', 'DNA polimerase sintetiza em qual sentido?', '5′→3′; lê molde 3′→5′.', '', 'prova', 'material', ['pol']),
    c('bcm1_a5', 'Fita retardada: unidades?', 'Fragmentos de Okazaki.', '', 'definicao', 'material', ['okazaki']),
    c('bcm1_a5', 'Quem une fragmentos de Okazaki?', 'DNA ligase.', '', 'definicao', 'material', ['ligase']),
    c('bcm1_a5', 'Fluoroquinolonas: alvo bacteriano?', 'DNA girase e topoisomerase IV (procariotos).', '', 'clinica', 'material', ['fluoroquinolona']),
    c('bcm1_a5', 'Primase sintetiza?', 'RNA primer (DNA pol precisa de 3′-OH).', '', 'mecanismo', 'material', ['primase']),
    c('bcm1_a5', 'Telomerase compensa o quê?', 'Extremidade 5′ incompleta da fita tardia — repõe TTAGGG.', '', 'mecanismo', 'material', ['telomerase']),
    c('bcm1_a5', 'PCR: temperaturas típicas do ciclo?', '~95 °C desnaturação; ~50–65 °C anelamento; ~72 °C extensão.', '', 'prova', 'material', ['pcr']),
    c('bcm1_a5', 'Taq polimerase: origem?', 'Thermus aquaticus — termoestável.', '', 'definicao', 'material', ['taq']),
    c('bcm1_a5', 'RT-PCR: primeiro passo se o alvo é RNA?', 'Transcrição reversa para cDNA.', '', 'clinica', 'material', ['rt-pcr']),
    c('bcm1_a5', 'Limite de Hayflick relaciona-se a?', 'Senescência após divisões — telômeros encurtados em somáticas.', '', 'extra_livro', 'extra', ['hayflick']),
    c('bcm1_a5', 'qPCR mede o quê em tempo real?', 'Amplificação por fluorescência — quantificação.', '', 'extra', 'extra', ['qpcr']),
  ],
  [ // bcm1_a6
    c('bcm1_a6', 'RNA Pol II transcreve principalmente?', 'Pré-mRNAs (proteínas) e vários snRNAs.', '', 'definicao', 'material', ['pol2']),
    c('bcm1_a6', 'RNA Pol I local típico?', 'Nucléolo — rRNA 28S, 18S, 5,8S.', '', 'prova', 'material', ['pol1']),
    c('bcm1_a6', 'TATA box posição aproximada?', '~25–30 pb upstream do +1.', '', 'prova', 'material', ['tata']),
    c('bcm1_a6', 'Cap 5′ do mRNA: função?', 'Proteção contra exonucleases e reconhecimento para tradução (eIF4E).', '', 'mecanismo', 'material', ['cap']),
    c('bcm1_a6', 'Spliceossomo: componentes principais?', 'snRNPs U1, U2, U4, U5, U6.', '', 'definicao', 'material', ['spliceossomo']),
    c('bcm1_a6', 'Poliadenilação 3′: papel da cauda poly(A)?', 'Estabilidade e exportação nuclear; interação com PABP.', '', 'mecanismo', 'material', ['polya']),
    c('bcm1_a6', 'Rifampicina: alvo em micobacterias?', 'RNA polimerase bacteriana (β subunidade).', '', 'clinica', 'material', ['rifampicina']),
    c('bcm1_a6', 'Enhancer vs silencer?', 'Enhancer ativa à distância; silencer reprime transcrição.', '', 'diferenciacao', 'material', ['enhancer']),
    c('bcm1_a6', 'miRNA frequentemente liga onde?', '3′UTR — regula estabilidade/tradução.', '', 'mecanismo', 'material', ['mirna']),
    c('bcm1_a6', 'α-amanitina: sensibilidade das RNA pol?', 'Pol II muito sensível; Pol III moderada; Pol I resistente.', '', 'prova', 'material', ['amanitina']),
    c('bcm1_a6', 'HDAC inhibitors: efeito epigenético geral?', 'Aumentam acetilação de histonas → cromatina mais aberta.', '', 'clinica', 'extra', ['hdac']),
    c('bcm1_a6', 'Splicing alternativo gera?', 'Isoformas proteicas a partir do mesmo gene.', '', 'extra_livro', 'extra', ['isoforma']),
  ],
  [ // bcm1_a7
    c('bcm1_a7', 'Códon de início no mRNA?', 'AUG (metionina).', '', 'prova', 'material', ['codon']),
    c('bcm1_a7', 'Códons de parada (nonsense)?', 'UAA, UAG, UGA.', '', 'prova', 'material', ['stop']),
    c('bcm1_a7', 'Sítios A, P e E no ribossomo?', 'Aminoacil, peptidil, exit — elongation.', '', 'definicao', 'material', ['ribossomo']),
    c('bcm1_a7', 'Shine–Dalgarno: onde atua?', 'Alinha mRNA procariótico na subunidade 30S com rRNA 16S.', '', 'prova', 'material', ['sd']),
    c('bcm1_a7', 'Aminoglicosídeos: subunidade bacteriana?', '30S — erro de leitura / iniciação.', '', 'clinica', 'material', ['aminoglicosideo']),
    c('bcm1_a7', 'Macrolídeos e clindamicina: subunidade?', '50S — bloqueiam translocação/elongação.', '', 'clinica', 'material', ['macrolideo']),
    c('bcm1_a7', 'Tetraciclinas: mecanismo?', 'Ligação 30S — inibe entrada do aminoacil-tRNA.', '', 'clinica', 'material', ['tetraciclina']),
    c('bcm1_a7', 'Cloranfenicol: alvo?', 'Peptidil transferase 50S bacteriana.', '', 'clinica', 'material', ['cloranfenicol']),
    c('bcm1_a7', 'Linezolida: classe e alvo?', 'Oxazolidinona — 50S (início da formação do complexo).', '', 'clinica', 'material', ['linezolida']),
    c('bcm1_a7', 'Fusídico: inibe o quê na bactéria?', 'EF-G (translocação).', '', 'prova', 'material', ['fusidico']),
    c('bcm1_a7', 'Wobble: qual posição do códon?', 'Terceira base — degeneração do código.', '', 'extra_livro', 'extra', ['wobble']),
    c('bcm1_a7', 'IRES: utilidade viral?', 'Inicia tradução sem depender do cap 5′.', '', 'extra', 'extra', ['ires']),
  ],
  [ // bcm1_a8
    c('bcm1_a8', 'Proto-oncogene vira oncogene por?', 'Mutação, amplificação, translocação, inserção viral.', '', 'definicao', 'material', ['oncogene']),
    c('bcm1_a8', 't(9;22) gera?', 'BCR-ABL — LMC; tirosina cinase constitutiva.', '', 'clinica', 'material', ['ph']),
    c('bcm1_a8', 't(14;18) clássico?', 'IGH–BCL2 — linfoma folicular; antiapoptose.', '', 'clinica', 'material', ['bcl2']),
    c('bcm1_a8', 'Gene supressor tumoral: quantos alelos inativar (Knudson)?', 'Dois “golpes” (ambos alelos).', '', 'definicao', 'material', ['knudson']),
    c('bcm1_a8', 'Função de APC na via Wnt?', 'Destrói β-catenina — mutação → câncer colorretal (FAP).', '', 'mecanismo', 'material', ['apc']),
    c('bcm1_a8', 'BRCA1/2: tipo de reparo?', 'Recombinação homóloga (DSB).', '', 'definicao', 'material', ['brca']),
    c('bcm1_a8', 'VHL perde função: consequência?', 'HIF-1α acumula → VEGF ↑ (CCR claras).', '', 'clinica', 'material', ['vhl']),
    c('bcm1_a8', 'HER2/neu: mecanismo oncológico comum?', 'Amplificação — câncer de mama.', '', 'clinica', 'material', ['her2']),
    c('bcm1_a8', 'Imatinibe: alvo molecular?', 'BCR-ABL (e outros cinases conforme indicação).', '', 'clinica', 'material', ['imatinibe']),
    c('bcm1_a8', 'Metilação de promotor de gene supressor?', 'Epigenética — silenciamento sem mudar DNA.', '', 'mecanismo', 'material', ['metilacao']),
    c('bcm1_a8', 'Instabilidade de microssatélites (MSI) sugere defeito em?', 'MMR (genes MLH1, MSH2, etc.).', '', 'clinica', 'extra', ['msi']),
    c('bcm1_a8', 'KRAS mutado: estado de ligação preferido?', 'GTP-bound constitutivo (via MAPK ativa).', '', 'extra_livro', 'extra', ['kras']),
  ],
  [ // bcm1_a9
    c('bcm1_a9', 'Necrose: inflamação?', 'Sim — conteúdo celular liberado.', '', 'diferenciacao', 'material', ['necrose']),
    c('bcm1_a9', 'Apoptose: inflamação típica?', 'Não — corpos apoptóticos fagocitados.', '', 'diferenciacao', 'material', ['apoptose']),
    c('bcm1_a9', 'Necrose coagulativa: contexto clássico?', 'Isquemia de órgãos sólidos (exceto SNC).', '', 'clinica', 'material', ['coagulativa']),
    c('bcm1_a9', 'Necrose liquefativa no SNC?', 'Encefalo isquêmico — tecido liquefeito.', '', 'clinica', 'material', ['liquefativa']),
    c('bcm1_a9', 'Via extrínseca da apoptose: caspase iniciadora típica?', 'Caspase-8 (receptores de morte).', '', 'mecanismo', 'material', ['casp8']),
    c('bcm1_a9', 'Via intrínseca: molécula mitocondrial-chave liberada?', 'Citocromo c → apoptossomo.', '', 'mecanismo', 'material', ['cito-c']),
    c('bcm1_a9', 'Caspase efetora central?', 'Caspase-3.', '', 'definicao', 'material', ['casp3']),
    c('bcm1_a9', 'BCL-2 é pró ou antiapoptótico?', 'Antiapoptótico (bloqueia Bax/Bak).', '', 'prova', 'material', ['bcl2']),
    c('bcm1_a9', 'Fragmentação do DNA na apoptose: escala?', 'Múltiplos de ~200 pb (laddering).', '', 'prova', 'material', ['dna']),
    c('bcm1_a9', 'Necrose caseosa: associação clássica?', 'Tuberculose / granulomas.', '', 'clinica', 'material', ['caseosa']),
    c('bcm1_a9', 'p53 pode induzir apoptose por?', 'Ativar vias pró-apoptóticas (ex.: PUMA/Noxa) após dano ao DNA.', '', 'extra_livro', 'extra', ['p53']),
    c('bcm1_a9', 'Necrose gordurosa: órgão típico?', 'Pâncreas (pancreatite) — saponificação.', '', 'clinica', 'extra', ['gordurosa']),
  ],
  [ // bcm1_a10
    c('bcm1_a10', 'Fases da interfase?', 'G1, S, G2.', '', 'definicao', 'material', ['ciclo']),
    c('bcm1_a10', 'Fase S: evento principal?', 'Replicação do DNA (2N→4N conteúdo).', '', 'definicao', 'material', ['fase-s']),
    c('bcm1_a10', 'Ciclina D + CDK4/6 fosforila?', 'Rb — libera E2F.', '', 'mecanismo', 'material', ['rb']),
    c('bcm1_a10', 'Palbociclibe: alvo?', 'CDK4/6 — bloqueio em G1.', '', 'clinica', 'material', ['cdk46']),
    c('bcm1_a10', 'Checkpoint G1/S verifica principalmente?', 'Tamanho, nutrientes, integridade do DNA (Rb central).', '', 'definicao', 'material', ['g1s']),
    c('bcm1_a10', 'Checkpoint G2/M: sensores de DSB?', 'ATM/ATR → Chk1/Chk2.', '', 'mecanismo', 'material', ['atm']),
    c('bcm1_a10', 'MPF clássico?', 'Ciclina B + CDK1 — entrada em mitose.', '', 'definicao', 'material', ['mpf']),
    c('bcm1_a10', 'p21 induzido por p53 inibe?', 'CDKs — parada de ciclo.', '', 'mecanismo', 'material', ['p21']),
    c('bcm1_a10', 'SAC: o que verifica?', 'Ancoragem dos cromossomos ao fuso (cinetócoros).', '', 'definicao', 'material', ['sac']),
    c('bcm1_a10', 'Rb hipofosforilado: liga a?', 'E2F — reprime genes de S.', '', 'prova', 'material', ['e2f']),
    c('bcm1_a10', 'CIN significa?', 'Instabilidade cromossômica — aneuploidia frequente em tumores.', '', 'extra_livro', 'extra', ['cin']),
    c('bcm1_a10', 'G0: quando entra a célula?', 'Quiescência — ausência de progressão do ciclo.', '', 'extra', 'extra', ['g0']),
  ],
  [ // bcm1_a11
    c('bcm1_a11', 'Mutação missense?', 'Troca de aminoácido.', '', 'definicao', 'material', ['missense']),
    c('bcm1_a11', 'Mutação nonsense?', 'Códon de parada prematuro — proteína truncada.', '', 'definicao', 'material', ['nonsense']),
    c('bcm1_a11', 'Frameshift exige indel?', 'Não múltiplo de 3 bases.', '', 'prova', 'material', ['frameshift']),
    c('bcm1_a11', 'UV forma principalmente?', 'Dímeros de pirimidina (CPD).', '', 'mecanismo', 'material', ['uv']),
    c('bcm1_a11', 'NER remove?', 'Lesões em filamentos (inclui dímeros TT) — excisão de nucleotídeos.', '', 'definicao', 'material', ['ner']),
    c('bcm1_a11', 'DSB: vias principais?', 'HRR (homóloga) e NHEJ (não homóloga).', '', 'diferenciacao', 'material', ['dsb']),
    c('bcm1_a11', 'BRCA2 em reparo?', 'Recombinação homóloga (RAD51 filamentos).', '', 'clinica', 'material', ['brca2']),
    c('bcm1_a11', 'MMR corrige?', 'Erros de emparelhamento pós-replicação — MSI se defeituoso.', '', 'definicao', 'material', ['mmr']),
    c('bcm1_a11', 'Olaparibe: princípio em BRCA mutado?', 'Inibe PARP → letalidade sintética (defeito em HRR).', '', 'clinica', 'material', ['parp']),
    c('bcm1_a11', 'Anemia falciforme: tipo de mutação na β-globina?', 'Missense — Glu6→Val.', '', 'clinica', 'material', ['falciforme']),
    c('bcm1_a11', 'Transição vs transversão?', 'Transição: mesma família de bases; transversão: cruza purina/pirimidina.', '', 'extra_livro', 'extra', ['transicao']),
    c('bcm1_a11', 'XP: defeito em?', 'NER — xeroderma pigmentoso, risco de pele.', '', 'extra', 'extra', ['xp']),
  ],
];

const data = JSON.parse(fs.readFileSync(OUT, 'utf8'));
let id = 0;
for (const f of data.flashcards) if (f.id > id) id = f.id;
id++;
for (const lot of LOTS) for (const x of lot) data.flashcards.push({ ...x, id: id++ });
fs.writeFileSync(OUT, JSON.stringify(data, null, 2), 'utf8');
console.log('OK bcm1 part1 total', data.flashcards.length, 'last id', id - 1);
