/** BMF3 bmf3_a12–a22 × 12 — node scripts/append_flashcards_bmf3_m3_part2.js */
const fs = require('fs');
const path = require('path');
const OUT = path.join(__dirname, '..', 'data', 'flashcards.json');
function c(t, f, v, e, cat, o, tags) {
  return { materia: 'bmf3', tema: t, frente: f, verso: v, explicacao: e || '', dificuldade: 2, categoria: cat, origem: o, tags: tags || [] };
}
const LOTS = [
  [ // bmf3_a12
    c('bmf3_a12', 'TFG definida como?', 'Volume de plasma filtrado por unidade de tempo por ambos rins.', '', 'definicao', 'material', ['tfg']),
    c('bmf3_a12', 'Pressões de Starling no glomérulo: filtração favorável?', 'Pressão hidrostática capilar > pressões opostas (cápsula + oncótica).', '', 'mecanismo', 'material', ['starling']),
    c('bmf3_a12', 'Clearance de creatinina estima?', 'TFG (aproximação clínica).', '', 'definicao', 'material', ['creatinina']),
    c('bmf3_a12', 'RPF: significado?', 'Fluxo plasmático renal — nutre néfrons.', '', 'definicao', 'material', ['rpf']),
    c('bmf3_a12', 'Filtração fracionada?', 'TFG/RPF — proporção do plasma filtrado.', '', 'definicao', 'material', ['ff']),
    c('bmf3_a12', 'Constrição aferente diminui?', 'TFG (menos fluxo ao glomérulo).', '', 'mecanismo', 'material', ['aferente']),
    c('bmf3_a12', 'Angiotensina II: efeito em eferente?', 'Vasoconstrição eferente pode manter TFG em certos contextos.', '', 'mecanismo', 'material', ['angiotensina']),
    c('bmf3_a12', 'Autorregulação renal mantém?', 'Fluxo relativamente constante (miogênica, TGF).', '', 'definicao', 'material', ['autoregulacao']),
    c('bmf3_a12', 'Marcadores de lesão glomerular na urina?', 'Albuminúria micro/macro.', '', 'clinica', 'material', ['albuminuria']),
    c('bmf3_a12', 'MDRD/eGFR usa?', 'Creatinina, idade, sexo, raça (equações).', '', 'prova', 'material', ['egfr']),
    c('bmf3_a12', 'Contrastes iodados: risco?', 'Nefropatia induzida por contraste (especialmente IR prévia).', '', 'clinica', 'extra', ['contraste']),
    c('bmf3_a12', 'Inibidores da ECA podem alterar TFG inicialmente por?', 'Dilatar eferente menos — filtração pode cair levemente.', '', 'extra_livro', 'extra', ['eca']),
  ],
  [ // bmf3_a13
    c('bmf3_a13', 'Reabsorção de Na⁺ no TCP é?', 'Ativa (Na/K ATPase basolateral).', '', 'mecanismo', 'material', ['sodio']),
    c('bmf3_a13', 'Glicose aparece na urina quando?', 'Ultrapassa limiar tubular (~180 mg/dL sangue).', '', 'prova', 'material', ['limiar']),
    c('bmf3_a13', 'Alça de Henle ramo descendente permeável a?', 'Água (não sal).', '', 'definicao', 'material', ['descendente']),
    c('bmf3_a13', 'Ramo ascendente espesso impermeável a?', 'Água — reabsorve sal sem água (diluição medular).', '', 'mecanismo', 'material', ['ascendente']),
    c('bmf3_a13', 'Multiplicação contracorrente cria?', 'Gradiente osmótico medular para concentrar urina.', '', 'mecanismo', 'material', ['medula']),
    c('bmf3_a13', 'ADH age onde?', 'Ductos coletores — aquaporinas (água livre).', '', 'mecanismo', 'material', ['adh']),
    c('bmf3_a13', 'Aldosterona aumenta reabsorção de?', 'Na⁺ e secreção de K⁺/H⁺ (TCD/células principais).', '', 'mecanismo', 'material', ['aldosterona']),
    c('bmf3_a13', 'ANP aumenta?', 'Filtração e natriurese (menos reabsorção Na).', '', 'mecanismo', 'material', ['anp']),
    c('bmf3_a13', 'Diurético de alça inibe?', 'NKCC2 — perde gradiente medular (urina diluída).', '', 'clinica', 'material', ['furosemida']),
    c('bmf3_a13', 'Espironolactona: antagonista de?', 'Aldosterona (compete receptor).', '', 'clinica', 'material', ['espironolactona']),
    c('bmf3_a13', 'SIADH: urina?', 'Osmolaridade inapropriadamente alta, sódio plasmático baixo.', '', 'clinica', 'extra', ['siadh']),
    c('bmf3_a13', 'Hipercalemia com bloqueio da excreção renal: causa?', 'Insuficiência renal aguda, aldosterona baixa, fármacos.', '', 'extra_livro', 'extra', ['k']),
  ],
  [ // bmf3_a14
    c('bmf3_a14', 'Rim compensa acidose respiratória crônica?', 'Retém bicarbonato (compensação metabólica).', '', 'mecanismo', 'material', ['acidose']),
    c('bmf3_a14', 'Secreção tubular de H⁺ usa?', 'Bomba H⁺ ATPase e troca Na⁺/H⁺.', '', 'mecanismo', 'material', ['h']),
    c('bmf3_a14', 'Reabsorção de HCO3⁻ filtrado?', 'H⁺ secreto titula HCO3⁻ em CO₂ + H₂O intracelular → reabsorve HCO3⁻.', '', 'mecanismo', 'material', ['bicarbonato']),
    c('bmf3_a14', 'Acidose tubular renal proximal?', 'Perda de bicarbonato (Fanconi, etc.).', '', 'clinica', 'material', ['atr']),
    c('bmf3_a14', 'ATR distal tipo 1 (hipercalemia)?', 'Defeito secreção H⁺/K⁺ (aldosterona ou resposta).', '', 'clinica', 'material', ['atr']),
    c('bmf3_a14', 'dRTA tipo 1 (distal): defeito?', 'Não acidifica urina adequadamente (defeito bomba H⁺ ou canal).', '', 'clinica', 'material', ['atr']),
    c('bmf3_a14', 'Amoníagenese no rim?', 'NH₃ + H⁺ → NH₄⁺ excretável (acidose crônica aumenta).', '', 'mecanismo', 'material', ['nh4']),
    c('bmf3_a14', 'Urina net acid excretion inclui?', 'TA (titratable acidity) + NH₄⁺ − HCO3⁻ urinário.', '', 'definicao', 'material', ['nae']),
    c('bmf3_a14', 'Alcalose metabólica hipocloremica com volume?', 'Vômitos — perda HCl, aldosterona secundária retém HCO3.', '', 'clinica', 'material', ['alcalose']),
    c('bmf3_a14', 'Inibidor de anidrase carbônica na urina?', '↑ HCO3 urinário — acidose metabólica leve.', '', 'clinica', 'material', ['acetazolamida']),
    c('bmf3_a14', 'Δ anion gap na acidose metabólica?', 'AG elevado (lactato, cetoacidose) vs normal (perda HCO3 GI).', '', 'extra_livro', 'extra', ['ag']),
    c('bmf3_a14', 'pH urinário em avaliação de acidose?', 'Ajuda a distinguir compensação renal adequada.', '', 'extra', 'extra', ['ph-urina']),
  ],
  [ // bmf3_a15
    c('bmf3_a15', 'Suprarrenal: localização?', 'Topo dos rins — cápsula.', '', 'definicao', 'material', ['suprarrenal']),
    c('bmf3_a15', 'Zona glomerulosa secreta?', 'Aldosterona (mineralocorticoide).', '', 'definicao', 'material', ['glomerulosa']),
    c('bmf3_a15', 'Zona fasciculada?', 'Cortisol (glicocorticoide).', '', 'definicao', 'material', ['fasciculada']),
    c('bmf3_a15', 'Zona reticulada?', 'Androgênios adrenais (DHEA).', '', 'definicao', 'material', ['reticulada']),
    c('bmf3_a15', 'Medula suprarrenal deriva de?', 'Crista neural — cromafins (epinefrina).', '', 'definicao', 'material', ['medula']),
    c('bmf3_a15', 'Artérias suprarrenais ramos de?', 'Tronco celíaco, aorta, renal (variações).', '', 'definicao', 'material', ['vascular']),
    c('bmf3_a15', 'Síndrome de Conn: excesso?', 'Aldosterona — hipertensão + hipocalemia.', '', 'clinica', 'material', ['conn']),
    c('bmf3_a15', 'Doença de Addison: deficiência?', 'Cortisol + mineralocorticoide (autoimune comum).', '', 'clinica', 'material', ['addison']),
    c('bmf3_a15', 'Feocromocitoma: origem?', 'Medula — catecolaminas excessivas.', '', 'clinica', 'material', ['feocromocitoma']),
    c('bmf3_a15', 'Hiperplasia adrenal congênita clássica: deficiência?', '21-hidroxilase — cortisol baixo, androgênios altos.', '', 'clinica', 'material', ['hac']),
    c('bmf3_a15', 'Síndrome de Cushing iatrogênica?', 'Excesso glicocorticoide exógeno.', '', 'extra_livro', 'extra', ['cushing']),
    c('bmf3_a15', 'Tumor de adrenal incidentaloma: investigar?', 'Função hormonal (metanefrinas, cortisol noturno).', '', 'extra', 'extra', ['incidentaloma']),
  ],
  [ // bmf3_a16
    c('bmf3_a16', 'Aldosterona estimula canal ENaC em?', 'Néfron tardio — reabsorve Na.', '', 'mecanismo', 'material', ['aldosterona']),
    c('bmf3_a16', 'Cortisol liga receptor mineralocorticoide?', 'In vivo 11β-HSD2 protege (exceto se saturado).', '', 'mecanismo', 'material', ['cortisol']),
    c('bmf3_a16', 'Cortisol: efeito metabólico?', 'Gliconeogênese, lipólise, proteólise.', '', 'mecanismo', 'material', ['gliconeogenese']),
    c('bmf3_a16', 'Regulação do eixo HPA?', 'CRH → ACTH → cortisol (feedback negativo).', '', 'mecanismo', 'material', ['hpa']),
    c('bmf3_a16', 'Epinefrina sintetizada a partir de?', 'Tirosina → dopamina → norepinefrina → epinefrina (PNMT medular).', '', 'mecanismo', 'material', ['catecolamina']),
    c('bmf3_a16', 'Resposta ao estresse agudo: hormônio rápido?', 'Catecolaminas (segundos).', '', 'mecanismo', 'material', ['estresse']),
    c('bmf3_a16', 'Insuficiência adrenal aguda: emergência?', 'Hipotensão refratária, hiponatremia, hipercalemia.', '', 'clinica', 'material', ['crise']),
    c('bmf3_a16', 'Bloqueio β: cuidado em asmáticos?', 'Broncoespasmo (β2 bloqueio não seletivo).', '', 'clinica', 'material', ['beta']),
    c('bmf3_a16', 'Alfa-1 agonistas: uso?', 'Vasopressão (ex.: noradrenalina em choque).', '', 'clinica', 'material', ['alfa']),
    c('bmf3_a16', 'Fenocromocitoma: bloqueio primeiro?', 'α antes de β (evitar crise hipertensiva).', '', 'clinica', 'material', ['alfa-beta']),
    c('bmf3_a16', 'Metyrapona testa?', 'Eixo HPA (inibe 11β-hidroxilase).', '', 'extra_livro', 'extra', ['metyrapona']),
    c('bmf3_a16', 'Espironolactona em IC com FE reduzida?', 'Mortalidade em certos perfis (RALES trial contexto).', '', 'extra', 'extra', ['ic']),
  ],
  [ // bmf3_a17
    c('bmf3_a17', 'Túbulos seminíferos contêm?', 'Espermatogonias → espermátides (espermatogênese).', '', 'definicao', 'material', ['seminifero']),
    c('bmf3_a17', 'Células de Leydig produzem?', 'Testosterona (estimuladas por LH).', '', 'definicao', 'material', ['leydig']),
    c('bmf3_a17', 'Células de Sertoli?', 'Barreira hemato-testicular; nutrem espermatozoides; inibina B.', '', 'definicao', 'material', ['sertoli']),
    c('bmf3_a17', 'Epidídimo: função?', 'Maturação e armazenamento espermático.', '', 'definicao', 'material', ['epididimo']),
    c('bmf3_a17', 'Ducto deferente une a?', 'Epidídimo à uretra prostática (via ampola).', '', 'definicao', 'material', ['deferente']),
    c('bmf3_a17', 'Glândulas seminais contribuem com?', 'Frutose e prostaglandinas ao sêmen.', '', 'definicao', 'material', ['seminais']),
    c('bmf3_a17', 'Próstata: zona mais afetada por Hiperplasia?', 'Zona de transição (periuretral).', '', 'clinica', 'material', ['hpb']),
    c('bmf3_a17', 'Corpo esponjoso envolve?', 'Uretra peniana.', '', 'definicao', 'material', ['esponjoso']),
    c('bmf3_a17', 'Tunica albugínea testicular?', 'Envolve lóbulos e epidídimo.', '', 'definicao', 'material', ['albuginea']),
    c('bmf3_a17', 'Espermograma avalia?', 'Volume, concentração, motilidade, morfologia (WHO).', '', 'clinica', 'material', ['espermograma']),
    c('bmf3_a17', 'Torção testicular: urgência?', 'Isquemia — cirurgia em horas.', '', 'clinica', 'extra', ['torsao']),
    c('bmf3_a17', 'Varicocele: local?', 'Plexo pampiniforme — pode afetar fertilidade.', '', 'extra_livro', 'extra', ['varicocele']),
  ],
  [ // bmf3_a18
    c('bmf3_a18', 'Ovário: folículos primordiais contêm?', 'Oócito I arrestado na prófase I.', '', 'definicao', 'material', ['foliculo']),
    c('bmf3_a18', 'Endométrio proliferativo fase?', 'Estrogênio — reconstituição pós menstruação.', '', 'mecanismo', 'material', ['proliferativo']),
    c('bmf3_a18', 'Fase secretora endométrio?', 'Progesterona — glândulas tortuosas, espongiosidade.', '', 'mecanismo', 'material', ['secretora']),
    c('bmf3_a18', 'Colo uterino: muco na ovulação?', 'Fino e elástico (perianovulatório).', '', 'clinica', 'material', ['muco']),
    c('bmf3_a18', 'Trompa uterina: subdivisões?', 'Infundíbulo, ampola (fecundação), istmo.', '', 'definicao', 'material', ['trompa']),
    c('bmf3_a18', 'Útero: camadas?', 'Endométrio, miométrio, perimetrio.', '', 'definicao', 'material', ['utero']),
    c('bmf3_a18', 'Vagina histologia: epitélio?', 'Estratificado escamoso — hormônio-dependente.', '', 'definicao', 'material', ['vagina']),
    c('bmf3_a18', 'Ligamento largo contém?', 'Artérias uterinas, ureter medial (cuidado cirúrgico).', '', 'prova', 'material', ['largo']),
    c('bmf3_a18', 'Hímen: derivado embriológico?', 'Septo urogenital — variável.', '', 'definicao', 'material', ['himén']),
    c('bmf3_a18', 'Endometriose: definição?', 'Endométrio fora da cavidade uterina — dor/infertilidade.', '', 'clinica', 'material', ['endometriose']),
    c('bmf3_a18', 'Mioma: origem?', 'Miométrio — benigno mais comum.', '', 'clinica', 'extra', ['mioma']),
    c('bmf3_a18', 'Câncer de colo: rastreamento?', 'Papanicolau + HPV (protocolos).', '', 'extra_livro', 'extra', ['colo']),
  ],
  [ // bmf3_a19
    c('bmf3_a19', 'Espermatogênese local?', 'Túbulos seminíferos — mitose, meiose, espermiogênese.', '', 'definicao', 'material', ['espermatogenese']),
    c('bmf3_a19', 'Ovogênese: parada prolongada?', 'Prófase I desde vida fetal até ovulação.', '', 'mecanismo', 'material', ['ovogenese']),
    c('bmf3_a19', 'Ovulação libera?', 'Oócito II preso na metáfase II até fertilização.', '', 'definicao', 'material', ['ovulacao']),
    c('bmf3_a19', 'Atresia folicular?', 'Maioria dos folículos degenera (apoptose).', '', 'mecanismo', 'material', ['atresia']),
    c('bmf3_a19', 'Barreira hemato-testicular protege?', 'Antígenos espermáticos do sistema imune.', '', 'mecanismo', 'material', ['barreira']),
    c('bmf3_a19', 'Crossing-over ocorre em?', 'Prófase I da meiose — diversidade genética.', '', 'definicao', 'material', ['meiose']),
    c('bmf3_a19', 'Oócito I completa meiose I quando?', 'Pré-ovulação (LH surge).', '', 'mecanismo', 'material', ['lh']),
    c('bmf3_a19', 'Fertilidade masculina: espermatozoide maduro em?', '~72 dias (renovação contínua).', '', 'prova', 'material', ['esperma']),
    c('bmf3_a19', 'Menopausa: causa principal?', 'Esgotamento folicular — queda estrógeno.', '', 'clinica', 'material', ['menopausa']),
    c('bmf3_a19', 'Criptorquidia: risco?', 'Infertilidade e tumor testicular se não corrigida.', '', 'clinica', 'material', ['criptorquidia']),
    c('bmf3_a19', 'Síndrome de Klinefelter e fertilidade?', 'Azoospermia frequentemente — TESE possível.', '', 'extra_livro', 'extra', ['klinefelter']),
    c('bmf3_a19', 'Reserva ovariana avaliada por?', 'AMH, contagem antral folicular (USG).', '', 'extra', 'extra', ['amh']),
  ],
  [ // bmf3_a20
    c('bmf3_a20', 'GnRH pulsátil estimula?', 'FSH e LH da adenohipófise.', '', 'mecanismo', 'material', ['gnrh']),
    c('bmf3_a20', 'FSH no masculino age em?', 'Células de Sertoli — espermatogênese.', '', 'mecanismo', 'material', ['fsh']),
    c('bmf3_a20', 'LH no masculino?', 'Leydig — testosterona.', '', 'mecanismo', 'material', ['lh']),
    c('bmf3_a20', 'FSH no feminino?', 'Desenvolvimento folicular.', '', 'mecanismo', 'material', ['fsh']),
    c('bmf3_a20', 'LH pico mid-cycle?', 'Dispara ovulação e corpus luteum.', '', 'mecanismo', 'material', ['lh']),
    c('bmf3_a20', 'Estrogênio dominante fase folicular?', 'Estradiol — feedback negativo, depois positivo no pico.', '', 'mecanismo', 'material', ['estrogenio']),
    c('bmf3_a20', 'Progesterona na fase lútea?', 'Eleva temperatura basal; prepara endométrio.', '', 'mecanismo', 'material', ['progesterona']),
    c('bmf3_a20', 'Menstruação ocorre por?', 'Queda súbita de progesterona/estrogênio — descamação.', '', 'mecanismo', 'material', ['menstruacao']),
    c('bmf3_a20', 'Contraceptivo combinado inibe?', 'Ovulação (suprime LH/FSH via feedback).', '', 'clinica', 'material', ['aco']),
    c('bmf3_a20', 'Anovulação comum em?', 'SOP — irregularidade menstrual.', '', 'clinica', 'material', ['sop']),
    c('bmf3_a20', 'Progesterona só: método?', 'Minipílula — ovulação pode ocorrer.', '', 'extra_livro', 'extra', ['minipilula']),
    c('bmf3_a20', 'Terapia hormonal menopausa: risco discutido?', 'TEP/TVP e câncer mama conforme esquema.', '', 'extra', 'extra', ['thm']),
  ],
  [ // bmf3_a21
    c('bmf3_a21', 'Fertilização ocorre tipicamente em?', 'Ampola da tuba uterina.', '', 'definicao', 'material', ['fertilizacao']),
    c('bmf3_a21', 'Reação zona pellucida?', 'Bloqueia poliespermia após primeiro espermatozoide.', '', 'mecanismo', 'material', ['zona']),
    c('bmf3_a21', 'Segmentação: mórula vs blastocisto?', 'Mórula compacta; blastocisto com blastocele e ICM.', '', 'diferenciacao', 'material', ['blastocisto']),
    c('bmf3_a21', 'Implantação dia aproximado?', '~6–7 dias pós-fertilização.', '', 'prova', 'material', ['implantacao']),
    c('bmf3_a21', 'Trofoblasto forma?', 'Placenta e membranas fetais.', '', 'definicao', 'material', ['trofoblasto']),
    c('bmf3_a21', 'Disc embrionário bilaminar?', 'Hipoblasto e epiblasto.', '', 'definicao', 'material', ['bilaminar']),
    c('bmf3_a21', 'Gastrulação: forma?', 'Três folhetos germinativos.', '', 'definicao', 'material', ['gastrulacao']),
    c('bmf3_a21', 'Placenta: circulação materno-fetal?', 'Interviloso (sem mistura sanguínea direta).', '', 'mecanismo', 'material', ['placenta']),
    c('bmf3_a21', 'hcG produzido por?', 'Trofoblasto — mantém corpo lúteo inicialmente.', '', 'mecanismo', 'material', ['hcg']),
    c('bmf3_a21', 'Aborto espontâneo precoce: causa genética?', 'Aneuploidias frequentes.', '', 'clinica', 'material', ['aborto']),
    c('bmf3_a21', 'Gravidez ectópica: local mais comum?', 'Tuba ampular.', '', 'clinica', 'extra', ['ectopica']),
    c('bmf3_a21', 'Pré-eclâmpsia: marcador?', 'Hipertensão + proteinúria após 20s semanas.', '', 'extra_livro', 'extra', ['pre-eclampsia']),
  ],
  [ // bmf3_a22
    c('bmf3_a22', 'Parto: estímulo de contração uterina?', 'Ocitocina, prostaglandinas, estiramento.', '', 'mecanismo', 'material', ['parto']),
    c('bmf3_a22', 'Prostaglandinas cervicais no parto?', 'Amolecimento e dilatação do colo.', '', 'mecanismo', 'material', ['prostaglandina']),
    c('bmf3_a22', 'Reflexo de Ferguson?', 'Estiramento cervical estimula mais ocitocina (feedback).', '', 'mecanismo', 'material', ['ferguson']),
    c('bmf3_a22', 'Puerpério: definição?', 'Período após parto com involução uterina e adaptações.', '', 'definicao', 'material', ['puerperio']),
    c('bmf3_a22', 'Lactação: prolactina?', 'Síntese de leite (inibida por dopamina/dopamina alta sem sucção).', '', 'mecanismo', 'material', ['prolactina']),
    c('bmf3_a22', 'Reflexo da ejeção do leite?', 'Ocitocina — miocélulas alveolares contraem.', '', 'mecanismo', 'material', ['ocitocina']),
    c('bmf3_a22', 'Colostro vs leite maduro?', 'Colostro rico em IgA e fatores imunes; menos volume.', '', 'diferenciacao', 'material', ['colostro']),
    c('bmf3_a22', 'Amenorreia lactacional?', 'Prolactina inibe pulsos GnRH — contracepção imperfeita.', '', 'mecanismo', 'material', ['lactacao']),
    c('bmf3_a22', 'Involução uterina pós-parto: fator?', 'Queda estrogênio; ocitocina auxilia.', '', 'mecanismo', 'material', ['involucao']),
    c('bmf3_a22', 'Hemorragia pós-parto: causa mais comum?', 'Atonia uterina.', '', 'clinica', 'material', ['hpp']),
    c('bmf3_a22', 'Indução com ocitocina: risco?', 'Hipertonia uterina — monitorar.', '', 'clinica', 'extra', ['inducao']),
    c('bmf3_a22', 'Mastite lactacional: agente comum?', 'S. aureus — antibiótico compatível com amamentação.', '', 'extra_livro', 'extra', ['mastite']),
  ],
];

const data = JSON.parse(fs.readFileSync(OUT, 'utf8'));
let id = 0;
for (const f of data.flashcards) if (f.id > id) id = f.id;
id++;
for (const lot of LOTS) for (const x of lot) data.flashcards.push({ ...x, id: id++ });
fs.writeFileSync(OUT, JSON.stringify(data, null, 2), 'utf8');
console.log('OK bmf3 part2 total', data.flashcards.length, 'last id', id - 1);
