/** MAD1 mad1_a13–a24 × 12 cards — node scripts/append_flashcards_mad1_m2_part2.js */
const fs = require('fs');
const path = require('path');
const OUT = path.join(__dirname, '..', 'data', 'flashcards.json');
function c(t, f, v, e, cat, o, tags) {
  return { materia: 'mad1', tema: t, frente: f, verso: v, explicacao: e || '', dificuldade: 2, categoria: cat, origem: o, tags: tags || [] };
}
const LOTS = [
  [ // mad1_a13
    c('mad1_a13', 'Staphylococcus aureus: coagulase?', 'Coagulase + (patógeno comum de pele).', '', 'definicao', 'material', ['staph']),
    c('mad1_a13', 'S. pyogenes (GAS): teste rápido?', 'Bacitracina sensível; anti-estreptolisina O (ASLO).', '', 'prova', 'material', ['strepto']),
    c('mad1_a13', 'Impetigo: agentes comuns?', 'S. aureus e/ou S. pyogenes.', '', 'clinica', 'material', ['impetigo']),
    c('mad1_a13', 'Celulite: germes típicos?', 'Streptococos beta-hemolíticos e S. aureus.', '', 'clinica', 'material', ['celulite']),
    c('mad1_a13', 'Hanseníase: agente?', 'Mycobacterium leprae (obligado intracelular em macrófagos).', '', 'definicao', 'material', ['hanseniase']),
    c('mad1_a13', 'Formas clínicas da hanseníase (Ridley-Jopling simplificado)?', 'Tuberculoide ↔ lepromatosa (espectro imune).', '', 'clinica', 'material', ['lepra']),
    c('mad1_a13', 'Toxina Panton-Valentine: associação?', 'Abscessos de pele por MRSA.', '', 'clinica', 'material', ['pvl']),
    c('mad1_a13', 'Eritema marginado: associação?', 'Febre reumática (pós-estreptocócica).', '', 'clinica', 'material', ['fr']),
    c('mad1_a13', 'Necrotizing fasciitis: germes?', 'GAS polimicrobiano (inclui anaeróbios).', '', 'clinica', 'material', ['fasciite']),
    c('mad1_a13', 'Escarlatina: exotoxina?', 'Toxinas pirogênicas estreptocócicas.', '', 'mecanismo', 'material', ['escarlatina']),
    c('mad1_a13', 'Tinea corporis: agente?', 'Dermatófitos (Trichophyton, Microsporum).', '', 'extra_livro', 'extra', ['dermatofito']),
    c('mad1_a13', 'Botulismo: mecanismo?', 'Neurotoxina bloqueia liberação de ACh (descendente flácido).', '', 'extra_livro', 'extra', ['botulismo']),
  ],
  [ // mad1_a14
    c('mad1_a14', 'ITU mais comum por?', 'E. coli UPEC (fimbrias P).', '', 'prova', 'material', ['itu']),
    c('mad1_a14', 'Pielonefrite: sinais sistêmicos?', 'Febre, dor lombar, leucocitúria.', '', 'clinica', 'material', ['pielonefrite']),
    c('mad1_a14', 'Uretrite: N. gonorrhoeae vs C. trachomatis?', 'Gonococo purulento; clamídia pode ser mucoide/assintomática.', '', 'diferenciacao', 'material', ['uretrite']),
    c('mad1_a14', 'Nitrito na urina indica?', 'Gram-negativos que reduzem nitrato (não sensível a todos).', '', 'prova', 'material', ['nitrito']),
    c('mad1_a14', 'Leucocitúria: significado?', 'Inflamação/infeção urinária (não específica).', '', 'definicao', 'material', ['leucocituria']),
    c('mad1_a14', 'Bacteriúria assintomática tratar na gravidez?', 'Sim (risco de pielonefrite).', '', 'clinica', 'material', ['gestacao']),
    c('mad1_a14', 'Pielonefrite obstrutiva: complicação?', 'Abscesso perinefrítico — descompressão/cirurgia.', '', 'clinica', 'material', ['obstrucao']),
    c('mad1_a14', 'Prostatite aguda: quadro?', 'Febre, dor perineal, PSA pode subir.', '', 'clinica', 'material', ['prostatite']),
    c('mad1_a14', 'Klebsiella ITU: associação?', 'Pacientes institucionalizados, resistência a betalactâmicos.', '', 'clinica', 'material', ['klebsiella']),
    c('mad1_a14', 'Enterococcus faecalis na ITU: sensibilidade?', 'Variável — vancomicina em resistências específicas.', '', 'clinica', 'material', ['enterococo']),
    c('mad1_a14', 'Síndrome uretro-ocular de Reiter: gatilho?', 'Post-infecção (clamídia/Yersinia — reação).', '', 'extra_livro', 'extra', ['reiter']),
    c('mad1_a14', 'Pielonefrite enfimatosa: agente típico?', 'Gas por anaeróbios/Gram-negativos em diabéticos.', '', 'extra_livro', 'extra', ['enfisematosa']),
  ],
  [ // mad1_a15
    c('mad1_a15', 'Tuberculose: agente?', 'Mycobacterium tuberculosis (BAAR).', '', 'definicao', 'material', ['tb']),
    c('mad1_a15', 'Transmissão da TB pulmonar?', 'Gotículas (não fômites predominantes).', '', 'prova', 'material', ['transmissao']),
    c('mad1_a15', 'Latência TB: bacilo onde?', 'Granuloma (macrófagos epiteloides).', '', 'mecanismo', 'material', ['latencia']),
    c('mad1_a15', 'PPD positivo significa infecção ativa?', 'Não — apenas sensibilização (interpretar contexto).', '', 'prova', 'material', ['ppd']),
    c('mad1_a15', 'Pseudomonas aeruginosa: ambiente hospitalar?', 'Biofilme em cateteres e fibrose cística.', '', 'clinica', 'material', ['pseudomonas']),
    c('mad1_a15', 'Enterobacteriaceae: característica?', 'Gram-negativas bacilares, fermentam glicose.', '', 'definicao', 'material', ['enterobacter']),
    c('mad1_a15', 'ESBL: significa?', 'Betalactamase de espectro estendido — resistência a cefalosporinas de 3ª geração.', '', 'clinica', 'material', ['esbl']),
    c('mad1_a15', 'Carbapenemase KPC: impacto?', 'Resistência a carbapenens — isolamento rigoroso.', '', 'clinica', 'material', ['kpc']),
    c('mad1_a15', 'Leptospirose: transmissão?', 'Urina de roedores/contaminação hídrica.', '', 'clinica', 'material', ['leptospirose']),
    c('mad1_a15', 'Brucella: exposição ocupacional?', 'Veterinários/laticínios (zoonose).', '', 'clinica', 'material', ['brucella']),
    c('mad1_a15', 'GeneXpert MTB/RIF: detecta?', 'M. tuberculosis e resistência à rifampicina.', '', 'extra_livro', 'extra', ['genexpert']),
    c('mad1_a15', 'M. tuberculosis complex: espécies zoonóticas?', 'M. bovis (leite não pasteurizado).', '', 'extra_livro', 'extra', ['bovis']),
  ],
  [ // mad1_a16
    c('mad1_a16', 'Influenza A: antígenos de superfície?', 'Hemaglutinina (H) e neuraminidase (N).', '', 'prova', 'material', ['influenza']),
    c('mad1_a16', 'Pandemias de influenza: por quê?', 'Reassortimento antigênico (mudança de H/N).', '', 'mecanismo', 'material', ['pandemia']),
    c('mad1_a16', 'SARS-CoV-2: receptor de entrada?', 'ACE2 (via proteases TMPRSS2).', '', 'mecanismo', 'material', ['covid']),
    c('mad1_a16', 'VSR em lactentes: quadro?', 'Bronquiolite (sibilos, hipoxemia).', '', 'clinica', 'material', ['vsr']),
    c('mad1_a16', 'Adenovírus: manifestação?', 'Conjuntivite, gastroenterite, respiratório.', '', 'clinica', 'material', ['adenovirus']),
    c('mad1_a16', 'Parainfluenza: clínica típica?', 'Laringite/crupe em crianças.', '', 'clinica', 'material', ['parainfluenza']),
    c('mad1_a16', 'Oseltamivir: alvo?', 'Inibe neuraminidase (influenza).', '', 'mecanismo', 'material', ['oseltamivir']),
    c('mad1_a16', 'Vacina influenza anual: por quê?', 'Antigenic drift e cobertura sazonal.', '', 'prova', 'material', ['vacina-gripe']),
    c('mad1_a16', 'COVID-19: complicação trombótica?', 'Microtrombos e síndrome inflamatória multissistêmica.', '', 'clinica', 'material', ['covid']),
    c('mad1_a16', 'Metapneumovírus humano: população?', 'Infantil e idosos (sobreposição com VSR).', '', 'clinica', 'material', ['hmpv']),
    c('mad1_a16', 'Remdesivir: classe?', 'Análogo de nucleotídeo inibindo RNA polimerase viral.', '', 'extra_livro', 'extra', ['remdesivir']),
    c('mad1_a16', 'Influenza B: pandemias?', 'Menos reassortimento que A — epidemias sazonais.', '', 'diferenciacao', 'extra', ['influenza-b']),
  ],
  [ // mad1_a17
    c('mad1_a17', 'Dengue: vetor?', 'Aedes aegypti.', '', 'prova', 'material', ['dengue']),
    c('mad1_a17', 'Zika: complicação gestacional?', 'Microcefalia (in utero).', '', 'clinica', 'material', ['zika']),
    c('mad1_a17', 'Chikungunya: sintoma marcante?', 'Poliartralgia prolongada.', '', 'clinica', 'material', ['chikungunya']),
    c('mad1_a17', 'Dengue hemorrágico: mecanismo?', 'Imunopatologia em reinfecção (ADE — contexto).', '', 'mecanismo', 'material', ['dhh']),
    c('mad1_a17', 'Diagnóstico sorológico dengue: limitação?', 'Cruz-reação com outros flavivírus (interpretar vacinação).', '', 'clinica', 'material', ['sorologia']),
    c('mad1_a17', 'NS1 antígeno: janela?', 'Primeiros dias da dengue (antes de IgG).', '', 'prova', 'material', ['ns1']),
    c('mad1_a17', 'Hidratação na dengue: princípio?', 'Evitar choque no extravasamento (fase crítica).', '', 'clinica', 'material', ['hidratacao']),
    c('mad1_a17', 'Febre amarela: vetor e transmissão?', 'Haemagogus/Jungle vs Aedes urbano (sylvatic vs urbano).', '', 'clinica', 'material', ['febre-amarela']),
    c('mad1_a17', 'Mayaro e Oropouche: região?', 'Endemia amazônica (arbovírus emergentes).', '', 'definicao', 'material', ['arbovirus']),
    c('mad1_a17', 'Controle de vetores: medida fundamental?', 'Eliminação de criadouros e saneamento.', '', 'clinica', 'material', ['aedes']),
    c('mad1_a17', 'PCR para arbovírus: uso?', 'Confirmação precoce em surtos (painéis multiplex).', '', 'extra_livro', 'extra', ['pcr']),
    c('mad1_a17', 'Vacina dengue (tetravalente): indicação?', 'Conforme faixa etária e sorologia prévia (protocolo MS).', '', 'extra_livro', 'extra', ['vacina-dengue']),
  ],
  [ // mad1_a18
    c('mad1_a18', 'Hepatite A: transmissão?', 'Fecal-oral (água/alimentos).', '', 'prova', 'material', ['hav']),
    c('mad1_a18', 'Hepatite B: transmissão?', 'Sangue, sexual, vertical.', '', 'prova', 'material', ['hbv']),
    c('mad1_a18', 'Hepatite C: transmissão principal?', 'Sangue (atualmente compartilhamento de agulhas).', '', 'prova', 'material', ['hcv']),
    c('mad1_a18', 'HBV: marcador de infecção aguda?', 'IgM anti-HBc.', '', 'prova', 'material', ['hbc-igm']),
    c('mad1_a18', 'Portador crônico HBV: marcador?', 'HBsAg persistente >6 meses.', '', 'clinica', 'material', ['hbsag']),
    c('mad1_a18', 'HCV: cura com DAA?', 'Sim — terapias diretas antivirais em altas taxas.', '', 'clinica', 'material', ['daa']),
    c('mad1_a18', 'Hepatite D: requisito?', 'Coinfecção/superinfecção com HBV (defectivo).', '', 'definicao', 'material', ['hdv']),
    c('mad1_a18', 'HEV: risco em gravidez?', 'Maior gravidade (terceiro trimestre).', '', 'clinica', 'material', ['hev']),
    c('mad1_a18', 'Anti-HBs: significa imunidade?', 'Sim (vacina ou resolução com recuperação).', '', 'prova', 'material', ['anti-hbs']),
    c('mad1_a18', 'HAV: vacina?', 'Inativada — viajantes e endemia.', '', 'clinica', 'material', ['hav-vacina']),
    c('mad1_a18', 'HBV DNA: monitora o quê?', 'Replicação viral e tratamento.', '', 'extra_livro', 'extra', ['hbv-dna']),
    c('mad1_a18', 'HCV genótipo: importância?', 'Escolha de DAA e duração (menos hoje com pan-genotípicos).', '', 'extra_livro', 'extra', ['genotipo']),
  ],
  [ // mad1_a19
    c('mad1_a19', 'HIV: alvo celular principal?', 'CD4+ (gp120 liga CD4 e CCR5/CXCR4).', '', 'prova', 'material', ['hiv']),
    c('mad1_a19', 'Enzima retroviral para integração?', 'Integrase.', '', 'prova', 'material', ['integrase']),
    c('mad1_a19', 'Transcriptase reversa: função?', 'Síntese de DNA a partir do RNA viral.', '', 'mecanismo', 'material', ['tr']),
    c('mad1_a19', 'AIDS: critério imunológico clássico?', 'CD4 <200 ou doenças definidoras (CDC).', '', 'clinica', 'material', ['aids']),
    c('mad1_a19', 'Profilaxia pós-exposição: tempo?', 'Iniciar o quanto antes (72h ideal).', '', 'clinica', 'material', ['pep']),
    c('mad1_a19', 'PrEP: indicação?', 'Alto risco de exposição sexual a HIV.', '', 'clinica', 'material', ['prep']),
    c('mad1_a19', 'TARV: objetivo?', 'Supressão viral indetectável e preservação imune.', '', 'clinica', 'material', ['tarv']),
    c('mad1_a19', 'HIV e TB: relação?', 'Maior risco de TB reativação (imunodepressão).', '', 'clinica', 'material', ['hiv-tb']),
    c('mad1_a19', 'Criptococo meningite: contexto?', 'CD4 baixo (AIDS).', '', 'clinica', 'material', ['criptococo']),
    c('mad1_a19', 'Sarcoma de Kaposi: agente?', 'HHV-8 em imunossuprimidos.', '', 'clinica', 'material', ['kaposi']),
    c('mad1_a19', 'Resistência HIV: teste genotípico?', 'Orienta troca de esquema (mutações RT/protease).', '', 'extra_livro', 'extra', ['genotipo-hiv']),
    c('mad1_a19', 'U=U (undetectable = untransmittable)?', 'Carga viral indetectável não transmite sexualmente (evidência).', '', 'extra_livro', 'extra', ['uu']),
  ],
  [ // mad1_a20
    c('mad1_a20', 'HSV: latência onde?', 'Ganglios sensitivos (trigeminal/sacral).', '', 'prova', 'material', ['hsv']),
    c('mad1_a20', 'VZV: reativação?', 'Herpes-zóster (dermatomio).', '', 'clinica', 'material', ['vzv']),
    c('mad1_a20', 'CMV: risco fetal?', 'Infeção congênita — surdez, calcificações (PCR).', '', 'clinica', 'material', ['cmv']),
    c('mad1_a20', 'EBV: associação oncológica?', 'Linfoma de Burkitt, carcinoma nasofaríngeo.', '', 'clinica', 'material', ['ebv']),
    c('mad1_a20', 'Mononucleose: teste?', 'Heterófilo (Monospot) ou IgM anti-VCA.', '', 'prova', 'material', ['mono']),
    c('mad1_a20', 'Aciclovir: mecanismo?', 'Análogo de guanina inibindo DNA polimerase viral.', '', 'mecanismo', 'material', ['aciclovir']),
    c('mad1_a20', 'CMV em transplante: problema?', 'Doença por reativação — profilaxia com antivirais.', '', 'clinica', 'material', ['cmv-tx']),
    c('mad1_a20', 'Roseola infantum: agente?', 'HHV-6 (exantema súbito).', '', 'clinica', 'material', ['hhv6']),
    c('mad1_a20', 'Herpetic whitlow: local?', 'Dedo (profissionais de saúde).', '', 'clinica', 'material', ['whitlow']),
    c('mad1_a20', 'Neuralgia pós-herpética: prevenção?', 'Vacina VZV recombinante em idosos.', '', 'clinica', 'material', ['shingrix']),
    c('mad1_a20', 'Ganciclovir: uso principal?', 'CMV grave (inibidor de DNA pol CMV).', '', 'extra_livro', 'extra', ['ganciclovir']),
    c('mad1_a20', 'HHV-8: vírus de?', 'Sarcoma de Kaposi e linfoma primário efusão.', '', 'extra_livro', 'extra', ['hhv8']),
  ],
  [ // mad1_a21
    c('mad1_a21', 'Poliomielite: via de transmissão?', 'Fecal-oral (vírus enteroviral).', '', 'prova', 'material', ['polio']),
    c('mad1_a21', 'Vacina polio VOPV vs IPV?', 'VOPV oral (atenuada) vs IPV inativada (injetável).', '', 'diferenciacao', 'material', ['polio-vacina']),
    c('mad1_a21', 'Sarampo: complicação neurológica?', 'Encefalite (SSPE tardia — rara).', '', 'clinica', 'material', ['sarampo']),
    c('mad1_a21', 'Rubéola: risco gestacional?', 'Síndrome da rubéola congênita.', '', 'clinica', 'material', ['rubeola']),
    c('mad1_a21', 'Caxumba: complicação?', 'Orquite pós-pubere, pancreatite, meningoencefalite.', '', 'clinica', 'material', ['caxumba']),
    c('mad1_a21', 'Varicela: transmissão?', 'Aerossol e contato com lesões.', '', 'definicao', 'material', ['varicela']),
    c('mad1_a21', 'Raiva: profilaxia pós-mordida?', 'Vacina + imunoglobulina (limpeza local primeiro).', '', 'clinica', 'material', ['raiva']),
    c('mad1_a21', 'Enterovírus 71: surtos?', 'Mão-pé-boca grave (neuro).', '', 'clinica', 'material', ['ev71']),
    c('mad1_a21', 'Parotidite viral: agente comum?', 'Vírus da caxumba.', '', 'definicao', 'material', ['parotidite']),
    c('mad1_a21', 'Eritema infeccioso (quinta doença): agente?', 'Parvovírus B19.', '', 'clinica', 'material', ['parvovirose']),
    c('mad1_a21', 'Sarampo: Koplik spots?', 'Manchas bucais patognomônicas antes do exantema.', '', 'extra_livro', 'extra', ['koplik']),
    c('mad1_a21', 'Vírus JC: lesão em imunossuprimidos?', 'Leucoencefalopatia multifocal progressiva.', '', 'extra_livro', 'extra', ['pml']),
  ],
  [ // mad1_a22
    c('mad1_a22', 'Doença de Chagas: agente?', 'Trypanosoma cruzi.', '', 'definicao', 'material', ['chagas']),
    c('mad1_a22', 'Vetor Chagas?', 'Triatomíneos (barbeiro).', '', 'prova', 'material', ['triatomineo']),
    c('mad1_a22', 'Malária: agente?', 'Plasmodium spp. (falciparum grave).', '', 'definicao', 'material', ['malaria']),
    c('mad1_a22', 'Malária: vetor?', 'Anopheles.', '', 'prova', 'material', ['anopheles']),
    c('mad1_a22', 'Leishmaniose visceral: agente no Brasil?', 'Leishmania infantum (chagasi).', '', 'clinica', 'material', ['leishmania']),
    c('mad1_a22', 'Forma cutânea leishmaniose: lesão?', 'Úlcera indolor (L. braziliensis — mucosa).', '', 'clinica', 'material', ['leish-cutanea']),
    c('mad1_a22', 'Toxoplasmose: forma latente?', 'Cistos teciduais (bradyzoítos).', '', 'mecanismo', 'material', ['toxo']),
    c('mad1_a22', 'Giardíase: transmissão?', 'Fecal-oral (cistos).', '', 'clinica', 'material', ['giardia']),
    c('mad1_a22', 'Amebíase invasiva: lesão intestinal?', 'Flask-shaped ulcers (E. histolytica).', '', 'clinica', 'material', ['amebiase']),
    c('mad1_a22', 'Suramin e eflornitina: contexto?', 'HAT (doença do sono — Trypanosoma brucei).', '', 'clinica', 'material', ['hats']),
    c('mad1_a22', 'Teste rápido malária: detecta?', 'Antígeno parasitário (pHRP2 em P. falciparum).', '', 'extra_livro', 'extra', ['rdt-malaria']),
    c('mad1_a22', 'Benznidazol: uso?', 'Tratamento etiológico da doença de Chagas (fases indicadas).', '', 'extra_livro', 'extra', ['benznidazol']),
  ],
  [ // mad1_a23
    c('mad1_a23', 'Ascaris lumbricoides: transmissão?', 'Ingestão de ovos (solo/fecal).', '', 'definicao', 'material', ['ascaris']),
    c('mad1_a23', 'Ancilostomíase: mecanismo de anemia?', 'Sangue intestinal perda + sucção de vermes.', '', 'mecanismo', 'material', ['ancilostoma']),
    c('mad1_a23', 'Estrongiloidíase: particularidade?', 'Autoinfecção endógena (imunossuprimidos hiperinfecção).', '', 'clinica', 'material', ['strongyloides']),
    c('mad1_a23', 'Taenia solium: cisticercose?', 'Ovos ingeridos → cistos no SNC (mau higiene).', '', 'clinica', 'material', ['cisticercose']),
    c('mad1_a23', 'Teníase: transmissão?', 'Carne com cisticerco (solium/saginata).', '', 'definicao', 'material', ['teniase']),
    c('mad1_a23', 'Schistosoma mansoni: lesão hepática?', 'Granuloma perioval esquistossomose.', '', 'clinica', 'material', ['esquistossomose']),
    c('mad1_a23', 'Enterobius vermicularis: sintoma?', 'Prurido anal noturno (oxíuros).', '', 'clinica', 'material', ['oxiuro']),
    c('mad1_a23', 'Tricuríase: local?', 'Ceco (Trichuris trichiura).', '', 'definicao', 'material', ['tricuris']),
    c('mad1_a23', 'Filaríase linfática: agente?', 'Wuchereria bancrofti (vetor Culicidae).', '', 'clinica', 'material', ['filariose']),
    c('mad1_a23', 'Hidatidose: agente?', 'Echinococcus granulosus (cistos hepáticos).', '', 'clinica', 'material', ['equinococo']),
    c('mad1_a23', 'Albendazol mecanismo?', 'Inibe polimerização de tubulina helmíntica.', '', 'extra_livro', 'extra', ['albendazol']),
    c('mad1_a23', 'Ivermectina: uso em parasitas?', 'Nematódeos e escabiose (modula canais glutamato).', '', 'extra_livro', 'extra', ['ivermectina']),
  ],
  [ // mad1_a24
    c('mad1_a24', 'Histoplasma capsulatum: forma?', 'Levedura intracelular (fungos dimórficos).', '', 'definicao', 'material', ['histoplasma']),
    c('mad1_a24', 'Cryptococcus neoformans: capsula?', 'Polissacarídeo — tinta da índia no LCR.', '', 'prova', 'material', ['crypto']),
    c('mad1_a24', 'Candida albicans: forma invasiva?', 'Hifas e biofilme (cateteres).', '', 'clinica', 'material', ['candida']),
    c('mad1_a24', 'Aspergillus: risco?', 'Neutropenia prolongada — invasão pulmonar angioinvasiva.', '', 'clinica', 'material', ['aspergillus']),
    c('mad1_a24', 'Pneumocystis jirovecii: contexto?', 'CD4 baixo (AIDS) — pneumonia intersticial.', '', 'clinica', 'material', ['pcp']),
    c('mad1_a24', 'Dermatófitos: infecção?', 'Tinea (pele/cabelo/unha) — queratinófilos.', '', 'definicao', 'material', ['dermatofito']),
    c('mad1_a24', 'Malassezia: dermatite?', 'Pitiríase versicolor (leveduras lipofílicas).', '', 'clinica', 'material', ['malassezia']),
    c('mad1_a24', 'Micetoma: agentes?', 'Actinomicetos ou fúngicos (grãos coloridos).', '', 'clinica', 'material', ['micetoma']),
    c('mad1_a24', 'Paracoccidioides: forma no tecido?', 'Levedura com brotamento múltiplo (cogumelo mariner).', '', 'prova', 'material', ['paracoccidioides']),
    c('mad1_a24', 'Mucormicose: predisposição?', 'Cetoacidose diabética e desferroxamina (iron overload).', '', 'clinica', 'material', ['mucor']),
    c('mad1_a24', 'Anfotericina B: toxicidade?', 'Nefrotoxicidade — monitorar função renal.', '', 'extra_livro', 'extra', ['anfotericina']),
    c('mad1_a24', 'Echinocandinas: alvo?', 'Síntese de parede β-glucano (Candida/Aspergillus).', '', 'extra_livro', 'extra', ['echinocandina']),
  ],
];

const data = JSON.parse(fs.readFileSync(OUT, 'utf8'));
let id = 0;
for (const f of data.flashcards) if (f.id > id) id = f.id;
id++;
for (const lot of LOTS) {
  if (lot.length !== 12) throw new Error('lot size ' + lot[0].tema);
  for (const x of lot) data.flashcards.push({ ...x, id: id++ });
}
fs.writeFileSync(OUT, JSON.stringify(data, null, 2), 'utf8');
console.log('OK part2 total', data.flashcards.length, 'last id', id - 1);
