import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const AULA = 'cm5_a6';
const MARKER = 'cm5_quality_contract_2026_05_07_cm5_a6';

function p(rel) { return path.join(ROOT, rel); }
function readJson(rel) { return JSON.parse(fs.readFileSync(p(rel), 'utf8')); }
function writeJson(rel, data) {
  fs.mkdirSync(path.dirname(p(rel)), { recursive: true });
  fs.writeFileSync(p(rel), `${JSON.stringify(data, null, 2)}\n`, 'utf8');
}
function writeText(rel, text) {
  fs.mkdirSync(path.dirname(p(rel)), { recursive: true });
  fs.writeFileSync(p(rel), `${text.replace(/\r\n/g, '\n').replace(/\n*$/, '')}\n`, 'utf8');
}
function explanation(general, exp) {
  return [`Resumo: ${general}`, `A) ${exp.A}`, `B) ${exp.B}`, `C) ${exp.C}`, `D) ${exp.D}`].join('\n');
}
function q(dificuldade, caso_clinico, enunciado, opcoes, correta, general, exp) {
  return { materia: 'clinica_medica5', tema: AULA, aula_id: AULA, modulo: 5, dificuldade, caso_clinico, essencial: true, origem: MARKER, enunciado, opcoes, correta, explicacao_geral: general, explicacoes_opcoes: exp, explicacao: explanation(general, exp) };
}
function fc(dificuldade, frente, verso, explicacao, categoria, tags) {
  return { materia: 'clinica_medica5', tema: AULA, dificuldade, frente, verso, explicacao, origem: MARKER, categoria, tags };
}

function questions() {
  return [
    q(1, false, 'Qual conjunto de exames pode estabelecer diagnóstico de diabetes mellitus em contexto apropriado?', [
      'A) Glicemia de jejum, HbA1c, TTGO ou glicemia aleatória com sintomas clássicos.',
      'B) Colesterol total isolado.',
      'C) Insulina sérica isolada em jejum.',
      'D) Circunferência abdominal isolada.',
    ], 0, 'Diabetes é diagnosticado por hiperglicemia: jejum, HbA1c, TTGO ou glicemia aleatória com sintomas. Insulina e cintura não fecham DM isoladamente.', {
      A: 'CORRETA: reúne os critérios laboratoriais aceitos.',
      B: 'INCORRETA: colesterol avalia risco, não diagnostica DM.',
      C: 'INCORRETA: insulina sérica não é critério diagnóstico de rotina.',
      D: 'INCORRETA: cintura entra em síndrome metabólica, não fecha DM.',
    }),
    q(2, false, 'Quais valores clássicos fecham diabetes em exames laboratoriais confirmados?', [
      'A) Jejum >= 126 mg/dL, HbA1c >= 6,5% ou TTGO 2h >= 200 mg/dL.',
      'B) Jejum >= 90 mg/dL, HbA1c >= 5,0% ou HDL baixo.',
      'C) Triglicerídeos >= 150 mg/dL isoladamente.',
      'D) PA >= 130/85 mmHg isoladamente.',
    ], 0, 'Os cortes clássicos são jejum >= 126, HbA1c >= 6,5 e TTGO 2h >= 200. Em assintomático, confirmar em nova amostra.', {
      A: 'CORRETA: são os cortes usuais para DM.',
      B: 'INCORRETA: esses valores não fecham DM.',
      C: 'INCORRETA: triglicerídeo alto é critério metabólico, não diagnóstico de DM.',
      D: 'INCORRETA: pressão entra em risco cardiometabólico, não fecha DM.',
    }),
    q(2, true, 'Mulher de 54 anos, IMC 33, acantose, glicemia de jejum 118 mg/dL e HbA1c 6,0%. Qual interpretação é mais adequada?', [
      'A) Pré-diabetes/alto risco, com intervenção intensiva de estilo de vida e seguimento.',
      'B) Diabetes confirmado sem necessidade de repetir ou complementar.',
      'C) Hipoglicemia crônica.',
      'D) Síndrome metabólica impossível porque há obesidade.',
    ], 0, 'Jejum 100-125 e HbA1c 5,7-6,4 sugerem pré-diabetes. É janela para intervenção, não rótulo banal.', {
      A: 'CORRETA: há alto risco cardiometabólico e glicemia intermediária.',
      B: 'INCORRETA: não atingiu critério de DM.',
      C: 'INCORRETA: os valores estão elevados, não baixos.',
      D: 'INCORRETA: obesidade central favorece síndrome metabólica.',
    }),
    q(2, false, 'Qual combinação favorece síndrome metabólica pelo critério ATP III harmonizado?', [
      'A) Cintura aumentada, TG elevado, HDL baixo, PA elevada e glicemia alterada.',
      'B) Febre, tosse, leucocitose e PCR elevada.',
      'C) Anemia, plaquetopenia, esplenomegalia e blastos.',
      'D) Dor torácica, supra de ST, troponina e choque.',
    ], 0, 'Síndrome metabólica é agrupamento de obesidade central, dislipidemia aterogênica, pressão e glicemia alteradas.', {
      A: 'CORRETA: descreve os cinco componentes clássicos.',
      B: 'INCORRETA: isso sugere infecção/inflamação.',
      C: 'INCORRETA: quadro hematológico.',
      D: 'INCORRETA: síndrome coronariana aguda.',
    }),
    q(2, true, 'Homem com DM2, doença cardiovascular aterosclerótica estabelecida e HbA1c acima da meta usa metformina. Qual classe tem benefício cardiovascular preferencial se não houver contraindicação?', [
      'A) Agonista GLP-1 RA com benefício cardiovascular ou inibidor de SGLT2 conforme perfil.',
      'B) Sulfonilureia obrigatória como única opção cardioprotetora.',
      'C) Acarbose como primeira escolha universal para reduzir mortalidade cardiovascular.',
      'D) Suspender todo antidiabético porque há doença cardíaca.',
    ], 0, 'Em DM2 com ASCVD, HF ou DRC, a escolha não é só HbA1c: GLP-1 RA e SGLT2i entram por desfecho cardiovascular/renal conforme perfil.', {
      A: 'CORRETA: é a lógica moderna de tratamento orientado por comorbidade.',
      B: 'INCORRETA: sulfonilureia reduz glicemia, mas não é a classe cardioprotetora preferencial.',
      C: 'INCORRETA: não é primeira escolha universal de prognóstico.',
      D: 'INCORRETA: cardiopatia exige tratamento mais cuidadoso, não abandono.',
    }),
    q(2, true, 'Paciente com DM2, albuminúria persistente e TFG 48 mL/min/1,73 m2. Qual escolha tem racional renal e cardiovascular se tolerada?', [
      'A) Inibidor de SGLT2.',
      'B) Glibenclamida em dose alta como proteção renal.',
      'C) Pioglitazona obrigatória em insuficiência cardíaca.',
      'D) Suspender IECA/BRA sempre que houver albuminúria.',
    ], 0, 'SGLT2i tem benefício renal e cardiovascular em DM2 com DRC/albuminúria. IECA/BRA também é pilar se hipertensão/albuminúria e tolerância.', {
      A: 'CORRETA: classe central em DRC diabética moderna.',
      B: 'INCORRETA: sulfonilureia aumenta risco de hipoglicemia e não protege rim.',
      C: 'INCORRETA: tiazolidinediona pode piorar retenção hídrica/IC.',
      D: 'INCORRETA: bloqueio do SRAA é protetor em albuminúria, com monitorização.',
    }),
    q(3, true, 'Paciente com glicemia 420 mg/dL, poliúria, perda ponderal, cetonemia positiva, pH 7,21 e bicarbonato baixo. Qual diagnóstico e prioridade são mais prováveis?', [
      'A) Cetoacidose diabética; volume, insulina IV e correção de potássio conforme protocolo.',
      'B) Síndrome metabólica simples; alta com dieta.',
      'C) Hipoglicemia por jejum prolongado.',
      'D) Estado hiperosmolar sem necessidade de hidratação.',
    ], 0, 'Cetoacidose diabética combina hiperglicemia, cetose e acidose. Potássio define segurança da insulina.', {
      A: 'CORRETA: é emergência metabólica.',
      B: 'INCORRETA: acidose e cetose não são simples ambulatório.',
      C: 'INCORRETA: há hiperglicemia importante.',
      D: 'INCORRETA: hidratação é base tanto em CAD quanto em EHH.',
    }),
    q(3, true, 'Idoso com DM2 chega sonolento, glicemia 780 mg/dL, osmolaridade alta, desidratação grave, cetose discreta e pH quase normal. Qual quadro é mais provável?', [
      'A) Estado hiperosmolar hiperglicêmico.',
      'B) Hipoglicemia grave.',
      'C) Síndrome metabólica isolada.',
      'D) Hipotireoidismo subclínico.',
    ], 0, 'EHH tem hiperglicemia e osmolaridade muito altas, desidratação intensa e pouca cetose/acidose em relação à CAD.', {
      A: 'CORRETA: padrão clássico de EHH em DM2 idoso.',
      B: 'INCORRETA: glicemia está extremamente alta.',
      C: 'INCORRETA: é emergência aguda.',
      D: 'INCORRETA: não explica hiperosmolaridade.',
    }),
    q(2, false, 'Qual rastreio anual é essencial em paciente com diabetes para complicação microvascular?', [
      'A) Albuminúria/TFG, exame de fundo de olho e avaliação de pés/neuropatia.',
      'B) Colonoscopia mensal.',
      'C) Troponina seriada em todo assintomático.',
      'D) Tomografia de crânio anual universal.',
    ], 0, 'Rim, retina e pés/neuropatia são eixos de rastreio de complicações microvasculares e amputação evitável.', {
      A: 'CORRETA: cobre nefropatia, retinopatia e neuropatia/pé diabético.',
      B: 'INCORRETA: não é rastreio específico de DM.',
      C: 'INCORRETA: troponina é para suspeita aguda.',
      D: 'INCORRETA: TC anual não rastreia complicação diabética comum.',
    }),
    q(2, true, 'Paciente diabético com ferida plantar, perda de sensibilidade ao monofilamento e pulsos diminuídos. Qual erro deve ser evitado?', [
      'A) Tratar como lesão simples sem avaliar infecção, isquemia, neuropatia e necessidade de desbridamento.',
      'B) Examinar pulsos e sensibilidade.',
      'C) Solicitar avaliação vascular se houver isquemia.',
      'D) Orientar descarga de pressão quando indicado.',
    ], 0, 'Pé diabético mistura neuropatia, infecção e isquemia. Chamar de calo ou ferida simples atrasa cuidado e aumenta amputação.', {
      A: 'CORRETA: é o erro grave.',
      B: 'INCORRETA: é conduta adequada.',
      C: 'INCORRETA: isquemia precisa ser reconhecida.',
      D: 'INCORRETA: offloading é parte do cuidado.',
    }),
    q(2, false, 'Qual meta glicêmica ambulatorial deve ser individualizada em vez de aplicada cegamente?', [
      'A) HbA1c.',
      'B) Sódio sérico.',
      'C) Hemoglobina total.',
      'D) Leucócitos.',
    ], 0, 'HbA1c geral frequentemente mira perto de 7%, mas idade, comorbidades, hipoglicemia, expectativa de vida e gestação mudam a meta.', {
      A: 'CORRETA: meta de HbA1c é individualizada.',
      B: 'INCORRETA: sódio não é meta glicêmica.',
      C: 'INCORRETA: hemoglobina avalia anemia.',
      D: 'INCORRETA: leucócitos avaliam inflamação/infeção.',
    }),
    q(2, false, 'Qual frase resume melhor o tratamento moderno do DM2?', [
      'A) Controlar glicose, peso e risco cardio-renal de forma integrada.',
      'B) Escolher remédio apenas pelo menor preço sem olhar comorbidade.',
      'C) Mirar HbA1c e ignorar coração, rim e obesidade.',
      'D) Usar insulina para todos no diagnóstico, sem exceção.',
    ], 0, 'O tratamento moderno é centrado em desfecho: glicemia importa, mas coração, rim, peso e hipoglicemia também.', {
      A: 'CORRETA: resume a lógica atual.',
      B: 'INCORRETA: custo importa, mas não pode apagar comorbidades.',
      C: 'INCORRETA: essa é a visão antiga e incompleta.',
      D: 'INCORRETA: insulina é essencial em muitos casos, mas não universal no DM2 inicial.',
    }),
  ];
}

function cards() {
  return [
    fc(1, 'DM pode ser diagnosticado por jejum, HbA1c, TTGO ou glicemia aleatória com {{c1::sintomas clássicos}}.', 'Sintomas clássicos', 'Poliúria, polidipsia, perda ponderal e glicemia aleatória >= 200 sustentam diagnóstico.', 'diagnostico', ['cm5', 'diabetes', 'diagnostico']),
    fc(1, 'Corte clássico de DM: glicemia de jejum {{c1::>= 126 mg/dL}}.', '>= 126 mg/dL', 'Em assintomático, confirmar em nova amostra ou outro teste alterado.', 'diagnostico', ['cm5', 'diabetes', 'jejum']),
    fc(1, 'HbA1c diagnóstica para DM é {{c1::>= 6,5%}}.', '>= 6,5%', 'Pode falhar em anemia, hemoglobinopatia, DRC e situações de troca eritrocitária.', 'diagnostico', ['cm5', 'diabetes', 'hba1c']),
    fc(2, 'Pré-diabetes inclui HbA1c {{c1::5,7-6,4%}}.', '5,7-6,4%', 'É janela para intervenção intensiva, não rótulo inofensivo.', 'diagnostico', ['cm5', 'prediabetes']),
    fc(2, 'Síndrome metabólica reúne cintura aumentada, TG alto, HDL baixo, PA elevada e {{c1::glicemia alterada}}.', 'Glicemia alterada', 'É marcador de resistência insulínica e risco cardiovascular.', 'sindrome_metabolica', ['cm5', 'metabolica']),
    fc(2, 'DM2 com DRC/albuminúria favorece {{c1::SGLT2i}} se tolerado.', 'SGLT2i', 'Benefício renal e cardiovascular vai além da queda de HbA1c.', 'tratamento', ['cm5', 'diabetes', 'sglt2']),
    fc(2, 'DM2 com ASCVD favorece GLP-1 RA de benefício CV ou {{c1::SGLT2i}} conforme perfil.', 'SGLT2i', 'A escolha moderna é guiada por comorbidades.', 'tratamento', ['cm5', 'diabetes', 'cv']),
    fc(3, 'Cetoacidose diabética = hiperglicemia + cetose + {{c1::acidose metabólica}}.', 'Acidose metabólica', 'Potássio precisa ser checado antes/durante insulina.', 'emergencia', ['cm5', 'cad']),
    fc(3, 'Estado hiperosmolar tem hiperglicemia extrema, osmolaridade alta e {{c1::pouca cetose/acidose}}.', 'Pouca cetose/acidose', 'Desidratação é muito marcada, comum em idosos com DM2.', 'emergencia', ['cm5', 'ehh']),
    fc(2, 'Rastreio microvascular no DM inclui rim, retina e {{c1::pés/neuropatia}}.', 'Pés/neuropatia', 'Monofilamento, pulsos e inspeção previnem amputação.', 'complicacoes', ['cm5', 'diabetes', 'rastreio']),
    fc(2, 'Meta de HbA1c deve ser {{c1::individualizada}}.', 'Individualizada', 'Hipoglicemia, idade, comorbidades e expectativa de vida mudam a meta.', 'metas', ['cm5', 'diabetes', 'hba1c']),
    fc(2, 'Tratamento moderno do DM2 integra glicose, peso e risco {{c1::cardio-renal}}.', 'Cardio-renal', 'Não basta baixar açúcar se o paciente infarta, dialisa ou faz hipoglicemia.', 'raciocinio', ['cm5', 'diabetes', 'cardiorenal']),
  ];
}

function material() {
  return [
    '---',
    'aula_id: cm5_a6',
    'materia: clinica_medica5',
    'modulo: 5',
    'tema: Síndrome Metabólica e Diabetes Mellitus',
    'versao_v3: 3.0.0',
    'status: published_local',
    'revisado_em: 2026-05-07',
    'checksum_lint: pass_pending',
    '---',
    '',
    '# Síndrome Metabólica e Diabetes Mellitus',
    '',
    '**Disciplina:** Clínica Médica 5',
    '**Módulo:** 5 | **Referência principal:** ADA Standards of Care 2026 + Diretriz SBD 2024/2025 + IDF Metabolic Syndrome',
    '**Tempo de estudo sugerido:** 25-35 min',
    '',
    '---',
    '',
    '## Relevância Clínica e Acadêmica',
    '',
    'Diabetes e síndrome metabólica são o centro do risco cardiometabólico. A aula não é só decorar corte de glicemia. Você precisa reconhecer **pré-diabetes**, fechar **diagnóstico**, tratar DM2 pensando em **coração e rim**, e não perder emergência metabólica.',
    '',
    'A prova costuma misturar obesidade, HAS, dislipidemia, esteatose, DRC, infarto prévio e sintomas clássicos. Se você responde só "metformina para todos" ou só "HbA1c abaixo de 7", fica atrasado. O tratamento moderno é por fenótipo e risco.',
    '',
    '> **Pegadinha de prova:** glicose é importante, mas não é o único alvo. Em DM2 com DRC, IC ou ASCVD, a escolha da droga muda por benefício renal e cardiovascular, não apenas pela HbA1c.',
    '',
    '---',
    '',
    '## Caso da Semana',
    '',
    '**Ato 1 - Entrada:** homem de 58 anos, IMC 34, cintura aumentada, HAS em uso irregular, TG 240 mg/dL, HDL 34 mg/dL e glicemia de jejum 122 mg/dL. Ele diz que "não tem diabetes", então acha que está tudo bem.',
    '',
    '**Ato 2 - Virada:** seis meses depois, retorna com HbA1c 7,8%, albuminúria e histórico recente de angioplastia. Agora a pergunta não é só se ele precisa baixar glicose, mas qual droga também reduz risco cardiovascular e renal.',
    '',
    '**Ato 3 - Decisão:** o raciocínio correto separa três camadas: síndrome metabólica como alerta, diabetes como diagnóstico e comorbidades como guia de tratamento. A escolha terapêutica muda quando há ASCVD, DRC, IC, obesidade ou risco de hipoglicemia.',
    '',
    '> **Moral da vinheta:** não espere o infarto para chamar síndrome metabólica de problema. Ela é o trailer do filme cardiometabólico.',
    '',
    '---',
    '',
    '## Diagnóstico de Diabetes',
    '',
    '| Critério | Corte clássico | Observação |',
    '|---|---|---|',
    '| **Glicemia de jejum** | >= 126 mg/dL | jejum de pelo menos 8h |',
    '| **HbA1c** | >= 6,5% | cuidado com anemia, hemoglobinopatia e DRC |',
    '| **TTGO 2h** | >= 200 mg/dL | após 75 g de glicose |',
    '| **Glicemia aleatória** | >= 200 mg/dL | com sintomas clássicos |',
    '',
    'Em assintomáticos, confirme com repetição ou outro teste alterado. Em sintomático clássico com glicemia aleatória muito alta, o diagnóstico é mais direto.',
    '',
    'Sintomas clássicos:',
    '',
    '- Poliúria.',
    '- Polidipsia.',
    '- Perda ponderal.',
    '- Visão turva.',
    '- Infecções recorrentes.',
    '',
    '**Macete MedGradPlus - açúcar alto precisa de contexto:** jejum e HbA1c fecham o ambulatório; glicemia aleatória com sintomas fecha a emergência diagnóstica.',
    '',
    '---',
    '',
    '## Pré-diabetes',
    '',
    '| Exame | Faixa de pré-diabetes |',
    '|---|---|',
    '| **Glicemia de jejum** | 100-125 mg/dL |',
    '| **HbA1c** | 5,7-6,4% |',
    '| **TTGO 2h** | 140-199 mg/dL |',
    '',
    'Pré-diabetes não é "quase nada". É risco aumentado de DM2, esteatose, síndrome metabólica e evento cardiovascular. A intervenção mais importante é perda de peso, alimentação, atividade física, sono e tratamento de fatores de risco.',
    '',
    'Metformina pode ser considerada em alto risco, especialmente IMC elevado, idade mais jovem, histórico de diabetes gestacional ou progressão glicêmica, mas estilo de vida continua sendo a base.',
    '',
    '---',
    '',
    '## Síndrome Metabólica',
    '',
    'Síndrome metabólica é um cluster de resistência insulínica e risco cardiovascular. O critério harmonizado usa componentes como cintura aumentada, triglicerídeos, HDL, pressão e glicemia.',
    '',
    '| Componente | Pista prática |',
    '|---|---|',
    '| **Cintura aumentada** | obesidade central |',
    '| **Triglicerídeos altos** | >= 150 mg/dL ou tratamento |',
    '| **HDL baixo** | < 40 homem, < 50 mulher |',
    '| **Pressão elevada** | >= 130/85 ou tratamento |',
    '| **Glicemia alterada** | >= 100 mg/dL ou DM |',
    '',
    'Ela não é diagnóstico "decorativo". É uma forma rápida de dizer: este paciente tem alto risco de DM2, DAC, AVC, DRC e esteatose metabólica.',
    '',
    '> **Armadilha de prova:** síndrome metabólica não exige diabetes. Glicemia alterada já entra no critério, e obesidade central puxa o risco antes do DM aparecer.',
    '',
    '---',
    '',
    '## Classificação do Diabetes',
    '',
    '| Tipo | Pista | Erro comum |',
    '|---|---|---|',
    '| **DM1** | jovem, magro, autoimune, cetose | achar que adulto nunca tem DM1 |',
    '| **DM2** | resistência insulínica, obesidade, familiar | ignorar cetose em DM2 grave |',
    '| **LADA** | adulto com autoimunidade lenta | tratar como DM2 comum por anos |',
    '| **MODY** | jovem, forte herança familiar, não obeso | chamar tudo de DM1/DM2 |',
    '| **Gestacional** | hiperglicemia detectada na gestação | esquecer reclassificação pós-parto |',
    '',
    'A maior parte da prática é DM2, mas a prova gosta de exceções: adulto magro com autoimunidade, jovem com herança dominante e gestante com rastreio alterado.',
    '',
    '---',
    '',
    '## Metas de HbA1c',
    '',
    'Meta comum para muitos adultos: perto de **7%**. Mas meta não é tatuagem.',
    '',
    '| Perfil | Meta tende a ser | Racional |',
    '|---|---|---|',
    '| **Jovem, saudável, sem hipoglicemia** | mais estrita | longa expectativa de vida |',
    '| **Idoso frágil, comorbidades, hipoglicemia** | menos estrita | segurança primeiro |',
    '| **Gestação** | específica | risco fetal e materno |',
    '| **Doença avançada** | individualizada | evitar dano por excesso de tratamento |',
    '',
    'HbA1c pode enganar em anemia, hemoglobinopatias, DRC avançada, transfusão recente e situações com mudança na vida média da hemácia.',
    '',
    '> **Armadilha de banca:** HbA1c bonita não absolve hipoglicemia. Se o idoso caiu duas vezes por hipoglicemia para manter 6,4%, a meta está errada para ele.',
    '',
    '---',
    '',
    '## Tratamento do DM2',
    '',
    'O tratamento começa por estilo de vida, mas não termina nele. A escolha farmacológica depende de glicemia, peso, risco de hipoglicemia, custo, rim, coração e preferências.',
    '',
    '| Cenário | Classe com papel forte | Por quê |',
    '|---|---|---|',
    '| **ASCVD estabelecida** | GLP-1 RA com benefício CV ou SGLT2i | reduz eventos em selecionados |',
    '| **Insuficiência cardíaca** | SGLT2i | reduz hospitalização por IC |',
    '| **DRC/albuminúria** | SGLT2i, SRAA se indicado | proteção renal/cardíaca |',
    '| **Obesidade importante** | GLP-1 RA/GIP-GLP-1 conforme acesso | peso e glicose |',
    '| **Custo muito restritivo** | metformina, sulfonilureia, insulina humana | cuidado com hipoglicemia |',
    '',
    '**Macete MedGradPlus - DM2 virou cardio-renal:** se tem coração ou rim, escolha droga perguntando "qual desfecho eu quero evitar?", não só "quanto cai a HbA1c?".',
    '',
    '---',
    '',
    '## Metformina, GLP-1 e SGLT2',
    '',
    '| Classe | Vantagem | Cuidado |',
    '|---|---|---|',
    '| **Metformina** | barata, eficaz, neutra/leve perda de peso | TFG, GI, B12 |',
    '| **SGLT2i** | rim, IC, peso discreto | infecção genital, euglycemic DKA rara, TFG |',
    '| **GLP-1 RA** | peso, ASCVD em selecionados | GI, custo, contraindicações específicas |',
    '| **Sulfonilureia** | custo baixo, potente | hipoglicemia, ganho de peso |',
    '| **Insulina** | potência ilimitada | hipoglicemia, técnica, ganho de peso |',
    '',
    'Insulina entra cedo se há catabolismo, sintomas importantes, glicemia muito alta, HbA1c muito elevada, suspeita de DM1, gestação em muitos cenários ou falha terapêutica.',
    '',
    '---',
    '',
    '## Emergências Hiperglicêmicas',
    '',
    '| Quadro | Pista | Conduta base |',
    '|---|---|---|',
    '| **Cetoacidose diabética** | hiperglicemia + cetose + acidose | volume, K, insulina IV |',
    '| **Estado hiperosmolar** | glicose muito alta + osmolaridade + desidratação | volume agressivo, K, insulina |',
    '',
    'Na CAD, não comece insulina sem olhar potássio. Se K estiver muito baixo, a insulina pode precipitar arritmia fatal. Primeiro repõe potássio conforme protocolo.',
    '',
    'Gatilhos comuns:',
    '',
    '- Infecção.',
    '- Omissão de insulina.',
    '- IAM/AVC.',
    '- Corticoide.',
    '- SGLT2i em situação de risco, especialmente jejum/doença aguda.',
    '',
    '> **Pérola Clínica:** CAD é acidose; EHH é osmolaridade. Os dois desidratam, os dois matam, mas a pista dominante muda.',
    '',
    '---',
    '',
    '## Complicações Crônicas',
    '',
    '| Eixo | Como rastrear | Frequência típica |',
    '|---|---|---|',
    '| **Retina** | fundo de olho | periódico conforme tipo/controle |',
    '| **Rim** | TFG + albuminúria | pelo menos anual em muitos pacientes |',
    '| **Neuropatia/pés** | monofilamento, pulsos, inspeção | pelo menos anual e a cada consulta se alto risco |',
    '| **Cardiovascular** | risco global, PA, lipídios, sintomas | contínuo |',
    '',
    'Pé diabético é onde a medicina simples salva membro: tirar sapato, olhar pele, testar sensibilidade, palpar pulso e tratar calçado/pressão.',
    '',
    '---',
    '',
    '## Conduta Ambulatorial Organizada',
    '',
    'Checklist prático:',
    '',
    '- Confirmar tipo de diabetes e tempo de doença.',
    '- Registrar HbA1c, glicemias, hipoglicemias e adesão.',
    '- Medir PA, peso, IMC e cintura quando útil.',
    '- Checar TFG, albuminúria, perfil lipídico e função hepática conforme contexto.',
    '- Atualizar retina, pés e vacinas.',
    '- Revisar risco cardiovascular e renal.',
    '- Escolher tratamento por comorbidade, não só HbA1c.',
    '- Combinar meta realista e segura.',
    '',
    '---',
    '',
    '## Pontos-Chave',
    '',
    '- DM é diagnóstico de hiperglicemia, não de insulina sérica.',
    '- Jejum >= 126, HbA1c >= 6,5 ou TTGO 2h >= 200 fecham DM se confirmados.',
    '- Pré-diabetes é oportunidade de prevenção.',
    '- Síndrome metabólica é cluster de risco cardiometabólico.',
    '- HbA1c deve ser individualizada.',
    '- DM2 com ASCVD, IC ou DRC muda escolha de droga.',
    '- SGLT2i é central em DRC/IC quando tolerado.',
    '- GLP-1 RA ajuda peso e risco CV em perfis selecionados.',
    '- CAD = hiperglicemia, cetose e acidose.',
    '- EHH = hiperosmolaridade e desidratação extrema.',
    '- Rastreie rim, retina e pés.',
    '- Pé diabético não é ferida simples.',
    '',
    '---',
    '',
    '## Mini Quiz',
    '',
    '**1. Qual valor de HbA1c fecha diabetes em critério clássico?**',
    '',
    '- [x] >= 6,5%',
    '- [ ] >= 5,0%',
    '- [ ] >= 5,4%',
    '- [ ] >= 6,0% sempre',
    '',
    '> **Explicação:** HbA1c >= 6,5% é critério diagnóstico, salvo limitações do método/contexto.',
    '',
    '**2. Qual combinação representa síndrome metabólica?**',
    '',
    '- [x] Cintura aumentada, TG alto, HDL baixo, PA elevada e glicemia alterada',
    '- [ ] Febre, tosse e PCR elevada',
    '- [ ] Anemia e plaquetopenia',
    '- [ ] Dor pleurítica e D-dímero',
    '',
    '> **Explicação:** síndrome metabólica é cluster cardiometabólico de resistência insulínica.',
    '',
    '**3. DM2 com DRC albuminúrica favorece qual classe?**',
    '',
    '- [x] SGLT2i',
    '- [ ] Antibiótico crônico',
    '- [ ] AINE contínuo',
    '- [ ] Corticoide diário',
    '',
    '> **Explicação:** SGLT2i reduz progressão renal e eventos em pacientes selecionados.',
    '',
    '**4. Qual frase sobre HbA1c é correta?**',
    '',
    '- [x] A meta deve ser individualizada',
    '- [ ] Todo paciente deve ficar abaixo de 5%',
    '- [ ] Nunca sofre interferência',
    '- [ ] Substitui avaliação de hipoglicemia',
    '',
    '> **Explicação:** idade, hipoglicemia, comorbidades e método alteram alvo e interpretação.',
    '',
    '**5. CAD é definida por qual tríade?**',
    '',
    '- [x] Hiperglicemia, cetose e acidose',
    '- [ ] Hipoglicemia, alcalose e hipocalcemia',
    '- [ ] Cintura, HDL e PA',
    '- [ ] Troponina, ST e GRACE',
    '',
    '> **Explicação:** cetoacidose diabética é emergência metabólica com cetose e acidose.',
    '',
    '**6. Em pé diabético, qual erro é grave?**',
    '',
    '- [x] Ignorar isquemia, neuropatia e infecção',
    '- [ ] Palpar pulsos',
    '- [ ] Testar monofilamento',
    '- [ ] Inspecionar calçados',
    '',
    '> **Explicação:** pé diabético exige avaliação vascular, neurológica e infecciosa.',
    '',
    '---',
    '',
    '## Pré-Prova',
    '',
    '### Síntese para a prova',
    '',
    'Diabetes não é só HbA1c. Feche diagnóstico com critérios de hiperglicemia, identifique pré-diabetes e síndrome metabólica como risco, e trate DM2 olhando coração, rim, peso e hipoglicemia. Em emergência, separe CAD de EHH: a primeira tem cetose e acidose; a segunda tem hiperosmolaridade e desidratação extrema.',
    '',
    '### Macete-âncora',
    '',
    '**Diagnóstico é açúcar; tratamento é risco.**',
    '',
    '- Jejum >= 126, HbA1c >= 6,5, TTGO 2h >= 200.',
    '- Pré-diabetes: intervir antes do dano.',
    '- Síndrome metabólica: cintura + TG/HDL/PA/glicose.',
    '- ASCVD/DRC/IC: pensar GLP-1 RA ou SGLT2i conforme perfil.',
    '- CAD: cetose + acidose.',
    '- EHH: osmolaridade + desidratação.',
    '',
    '### Erros que derrubam nota',
    '',
    '- Diagnosticar DM por insulina sérica.',
    '- Ignorar confirmação em assintomático.',
    '- Tratar DM2 só pela HbA1c e esquecer rim/coração.',
    '- Começar insulina na CAD sem olhar potássio.',
    '- Chamar pé diabético de ferida simples.',
    '- Aplicar meta rígida de HbA1c em idoso frágil com hipoglicemia.',
    '',
    '---',
    '',
    '## Fontes',
    '',
    '- American Diabetes Association. **Standards of Care in Diabetes - 2026**.',
    '- Sociedade Brasileira de Diabetes. **Diretriz SBD 2024/2025 - diagnóstico de diabetes mellitus**.',
    '- International Diabetes Federation. **Worldwide definition of the metabolic syndrome**.',
    '- Harrison Medicina Interna, 21ª edição, capítulos de diabetes e síndrome metabólica.',
  ].join('\n');
}

function updateFiles() {
  const md = material();
  writeText('data/materiais/clinica_medica5/cm5_a6.md', md);
  writeText('materiais/modulo5/clinica_medica5/cm5_a6.md', md);
}
function updateData() {
  const qData = readJson('data/questoes.json');
  let questoes = (qData.questoes || []).filter((item) => item.origem !== MARKER);
  const novos = questions();
  let maxQ = Math.max(0, ...questoes.map((item) => Number(item.id) || 0));
  for (const item of novos) item.id = ++maxQ;
  questoes.push(...novos);
  writeJson('data/questoes.json', { ...qData, questoes });

  const fcData = readJson('data/flashcards.json');
  let flashcards = (fcData.flashcards || []).filter((item) => item.origem !== MARKER);
  const novosCards = cards();
  let maxFc = Math.max(0, ...flashcards.map((item) => Number(item.id) || 0));
  for (const item of novosCards) item.id = ++maxFc;
  flashcards.push(...novosCards);
  writeJson('data/flashcards.json', { ...fcData, flashcards });
}
function updateRefs() {
  writeJson('data/refs/cm5_a6.refs.json', {
    aula_id: AULA,
    materia: 'clinica_medica5',
    tema: 'Síndrome Metabólica e Diabetes Mellitus',
    generatedAt: '2026-05-07T19:40:00.000Z',
    marker: MARKER,
    image_decision: {
      usar_imagem: false,
      motivo: 'Tema centrado em critérios, conduta e estratificação cardio-renal; imagem Wikimedia disponível tenderia a ser decorativa, não essencial.',
    },
    fontes_base: [
      {
        tipo: 'diretriz',
        titulo: 'American Diabetes Association - Standards of Care in Diabetes 2026',
        url: 'https://professional.diabetes.org/standards-of-care/practice-guidelines-resources',
        uso: 'diagnóstico, metas, tratamento por comorbidades, risco cardiovascular e renal.',
      },
      {
        tipo: 'diretriz',
        titulo: 'Sociedade Brasileira de Diabetes - Diagnóstico de diabetes mellitus, Diretriz 2024/2025',
        url: 'https://diretriz.diabetes.org.br/diagnostico-de-diabetes-mellitus/',
        uso: 'critérios diagnósticos no Brasil e rastreio.',
      },
      {
        tipo: 'consenso',
        titulo: 'International Diabetes Federation - Worldwide definition of the metabolic syndrome',
        url: 'https://idf.org/about-diabetes/resources/idf-consensus-worldwide-definition-of-the-metabolic-syndrome/',
        uso: 'componentes de síndrome metabólica e risco cardiometabólico.',
      },
    ],
  });
}

updateFiles();
updateData();
updateRefs();

console.log('CM5 a6 atualizada com material, essenciais e flashcards.');
