import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const AULA = 'cm5_a4';
const MARKER = 'cm5_quality_contract_2026_05_07_cm5_a4';

function p(rel) { return path.join(ROOT, rel); }
function readJson(rel) { return JSON.parse(fs.readFileSync(p(rel), 'utf8')); }
function writeJson(rel, data) {
  fs.mkdirSync(path.dirname(p(rel)), { recursive: true });
  fs.writeFileSync(p(rel), `${JSON.stringify(data, null, 2)}\n`, 'utf8');
}
function writeText(rel, text) {
  fs.mkdirSync(path.dirname(p(rel)), { recursive: true });
  fs.writeFileSync(p(rel), `${text.replace(/\r\n/g, '\n').replace(/\n*$/, '')}\n`, 'utf8');
}

function explanation(general, exp) {
  return [`Resumo: ${general}`, `A) ${exp.A}`, `B) ${exp.B}`, `C) ${exp.C}`, `D) ${exp.D}`].join('\n');
}

function q(dificuldade, caso_clinico, enunciado, opcoes, correta, general, exp) {
  return {
    materia: 'clinica_medica5',
    tema: AULA,
    aula_id: AULA,
    modulo: 5,
    dificuldade,
    caso_clinico,
    essencial: true,
    origem: MARKER,
    enunciado,
    opcoes,
    correta,
    explicacao_geral: general,
    explicacoes_opcoes: exp,
    explicacao: explanation(general, exp),
  };
}

function fc(dificuldade, frente, verso, explicacao, categoria, tags) {
  return {
    materia: 'clinica_medica5',
    tema: AULA,
    dificuldade,
    frente,
    verso,
    explicacao,
    origem: MARKER,
    categoria,
    tags,
  };
}

function questions() {
  return [
    q(1, false, 'Qual é a primeira pergunta prática diante de uma taquiarritmia no pronto atendimento?', [
      'A) O paciente está instável ou estável hemodinamicamente.',
      'B) Qual é a marca do aparelho de ECG.',
      'C) Se o paciente sabe nomear a arritmia.',
      'D) Se há apenas alteração discreta de potássio, antes de avaliar perfusão.',
    ], 0, 'Em arritmia aguda, estabilidade vem antes do nome fino do ritmo. Hipotensão, choque, dor isquêmica, edema agudo de pulmão ou rebaixamento mudam a conduta para cardioversão/choque conforme o cenário.', {
      A: 'CORRETA: instabilidade define urgência e pode indicar cardioversão sincronizada.',
      B: 'INCORRETA: detalhe técnico não vem antes de perfusão.',
      C: 'INCORRETA: paciente raramente sabe o diagnóstico eletrocardiográfico.',
      D: 'INCORRETA: eletrólitos importam, mas não atrasam manejo do instável.',
    }),
    q(2, true, 'Paciente com palpitações, PA 78x44, confusão e taquicardia regular de QRS estreito a 180 bpm. Qual conduta é mais apropriada?', [
      'A) Cardioversão elétrica sincronizada.',
      'B) Alta com retorno ambulatorial.',
      'C) Apenas hidratação oral e observar em casa.',
      'D) Esperar troponina seriada antes de tratar a instabilidade.',
    ], 0, 'Taquiarritmia com pulso e instabilidade clínica pede cardioversão elétrica sincronizada. Não se espera exame para corrigir hipoperfusão.', {
      A: 'CORRETA: instabilidade + taquiarritmia com pulso = cardioversão sincronizada.',
      B: 'INCORRETA: hipotensão e confusão são sinais de gravidade.',
      C: 'INCORRETA: hidratação oral não trata choque arrítmico.',
      D: 'INCORRETA: troponina pode ser útil depois, mas não antes da estabilização.',
    }),
    q(2, false, 'Qual achado de ECG é mais típico de fibrilação atrial?', [
      'A) Ritmo irregularmente irregular sem ondas P sinusais organizadas.',
      'B) Onda P antes de todo QRS com intervalo PR fixo.',
      'C) Supra de ST em derivações contíguas como critério obrigatório.',
      'D) QRS sempre estreito e frequência sempre menor que 60 bpm.',
    ], 0, 'Fibrilação atrial é ritmo irregularmente irregular, sem onda P sinusal organizada. O QRS costuma ser estreito se a condução é pelo sistema normal, mas pode ser largo em bloqueio ou pré-excitação.', {
      A: 'CORRETA: é a descrição clássica da FA no ECG.',
      B: 'INCORRETA: isso descreve ritmo sinusal ou arritmia atrial organizada.',
      C: 'INCORRETA: supra de ST não define FA.',
      D: 'INCORRETA: a frequência pode ser baixa, normal ou alta; QRS pode alargar por outras razões.',
    }),
    q(3, true, 'Homem com estenose mitral moderada e episódios de fibrilação atrial no Holter precisa de prevenção de embolização sistêmica. Qual opção é mais adequada?', [
      'A) Antagonista da vitamina K, como varfarina, com alvo de INR apropriado.',
      'B) Aspirina isolada como equivalente à anticoagulação.',
      'C) Rivaroxabana como primeira escolha em toda FA valvar.',
      'D) Nenhuma terapia, porque FA paroxística não emboliza.',
    ], 0, 'FA associada a estenose mitral moderada a importante é cenário em que anticoagulação com antagonista da vitamina K permanece indicada; DOAC não é escolha padrão.', {
      A: 'CORRETA: estenose mitral moderada/importante desloca a conduta para VKA.',
      B: 'INCORRETA: antiagregante não substitui anticoagulação na prevenção embólica da FA.',
      C: 'INCORRETA: DOACs são preferidos em muitos casos de FA, mas não nessa exceção clássica.',
      D: 'INCORRETA: FA paroxística também carrega risco tromboembólico.',
    }),
    q(2, false, 'Em fibrilação atrial sem valvopatia mitral moderada/importante nem válvula mecânica, qual princípio moderno é correto?', [
      'A) DOACs são preferidos à varfarina na maioria dos pacientes elegíveis.',
      'B) AAS é equivalente a DOAC para prevenir AVC.',
      'C) Anticoagulação depende só da frequência cardíaca no ECG.',
      'D) Todo paciente com FA deve receber anticoagulação sem avaliar risco de sangramento.',
    ], 0, 'Diretrizes modernas preferem DOAC em grande parte da FA não valvar elegível, guiando indicação por risco tromboembólico e segurança.', {
      A: 'CORRETA: é o padrão atual fora das exceções clássicas.',
      B: 'INCORRETA: AAS não oferece proteção equivalente.',
      C: 'INCORRETA: risco embólico não depende apenas da frequência.',
      D: 'INCORRETA: risco de sangramento e decisão compartilhada importam.',
    }),
    q(3, true, 'Paciente com fibrilação atrial, QRS largo irregular e suspeita de pré-excitação. Qual erro terapêutico deve ser evitado?', [
      'A) Bloquear o nó AV com verapamil, diltiazem, betabloqueador, digoxina ou adenosina.',
      'B) Chamar ajuda especializada e monitorizar.',
      'C) Cardioversão elétrica se houver instabilidade.',
      'D) Considerar antiarrítmico apropriado em cenário estável e monitorizado.',
    ], 0, 'FA pré-excitada é armadilha de prova. Bloquear o nó AV pode favorecer condução pela via acessória e precipitar fibrilação ventricular.', {
      A: 'CORRETA: esse é o erro que derruba nota e pode matar.',
      B: 'INCORRETA: ajuda especializada é adequada.',
      C: 'INCORRETA: instabilidade indica cardioversão.',
      D: 'INCORRETA: pode haver opção antiarrítmica, mas com critério e monitorização.',
    }),
    q(2, false, 'Taquicardia supraventricular paroxística regular de QRS estreito, paciente estável. Qual sequência inicial é coerente?', [
      'A) Manobra vagal e, se necessário, adenosina em bolus rápido.',
      'B) Varfarina imediata antes de qualquer tentativa de reversão.',
      'C) Desfibrilação não sincronizada em todo paciente consciente.',
      'D) Digoxina como droga obrigatória de primeira linha.',
    ], 0, 'TSV regular estreita em paciente estável costuma responder a manobras vagais e adenosina. Instabilidade muda para cardioversão sincronizada.', {
      A: 'CORRETA: é a lógica prática para TSV regular estreita estável.',
      B: 'INCORRETA: anticoagulação não é o tratamento agudo da TSV típica.',
      C: 'INCORRETA: choque não sincronizado é para ritmos sem pulso/indicações específicas.',
      D: 'INCORRETA: digoxina não é primeira linha para reversão rápida de TSV típica.',
    }),
    q(2, false, 'Qual descrição favorece taquicardia ventricular monomórfica sustentada?', [
      'A) Taquicardia regular de QRS largo, especialmente em paciente com cardiopatia estrutural.',
      'B) Ritmo sinusal a 72 bpm com PR fixo.',
      'C) Ritmo irregularmente irregular sempre benigno.',
      'D) Bradicardia sinusal durante sono sem sintomas.',
    ], 0, 'Taquicardia regular de QRS largo deve ser tratada como ventricular até prova em contrário, principalmente se há cardiopatia estrutural.', {
      A: 'CORRETA: a regra segura é presumir TV no QRS largo regular.',
      B: 'INCORRETA: isso descreve ritmo sinusal.',
      C: 'INCORRETA: irregularidade não torna ritmo benigno.',
      D: 'INCORRETA: bradicardia assintomática do sono não descreve TV.',
    }),
    q(3, true, 'Paciente usa macrolídeo e antiemético, chega com síncope, QT prolongado e taquicardia ventricular polimórfica em torção das pontas. Qual conduta tem racional imediato?', [
      'A) Sulfato de magnésio, correção de potássio/magnésio e suspensão de drogas que prolongam QT.',
      'B) Verapamil em dose alta como primeira medida universal.',
      'C) Dobrar dose das drogas que prolongam QT para estabilizar membrana.',
      'D) Alta com orientação dietética apenas.',
    ], 0, 'Torsades de pointes é TV polimórfica associada a QT longo. Magnésio e correção de fatores precipitantes são centrais; se instável/sem pulso, segue choque conforme ACLS.', {
      A: 'CORRETA: magnésio e retirada de gatilhos são medidas-chave.',
      B: 'INCORRETA: verapamil não é tratamento padrão de torsades.',
      C: 'INCORRETA: isso piora o gatilho.',
      D: 'INCORRETA: síncope e TV polimórfica exigem cuidado agudo.',
    }),
    q(2, true, 'Idoso com FC 34 bpm, hipotensão, tontura e bloqueio AV avançado no ECG. Atropina foi ineficaz. Qual próxima medida é coerente?', [
      'A) Marcapasso transcutâneo e preparo para estimulação transvenosa se necessário.',
      'B) Alta porque bradicardia em idoso é sempre fisiológica.',
      'C) Adenosina em bolus rápido.',
      'D) Manobra vagal repetida até a frequência subir.',
    ], 0, 'Bradicardia sintomática com repercussão pede atropina se apropriado; se ineficaz, pacing transcutâneo e/ou drogas vasoativas enquanto se prepara solução definitiva.', {
      A: 'CORRETA: bloqueio avançado sintomático pode precisar de pacing.',
      B: 'INCORRETA: hipotensão e tontura indicam instabilidade.',
      C: 'INCORRETA: adenosina pode piorar bloqueio e não trata bradicardia.',
      D: 'INCORRETA: manobra vagal reduz condução AV.',
    }),
    q(2, false, 'Qual dose de atropina aparece no algoritmo atual de bradicardia sintomática em adultos?', [
      'A) 1 mg IV a cada 3-5 minutos, máximo de 3 mg.',
      'B) 0,05 mg IV uma vez ao dia.',
      'C) 10 mg IV em bolus único para todos.',
      'D) Atropina é proibida em qualquer bradicardia.',
    ], 0, 'O algoritmo adulto moderno usa atropina 1 mg IV repetível a cada 3-5 minutos até dose máxima de 3 mg, quando apropriado.', {
      A: 'CORRETA: é a dose prática atual.',
      B: 'INCORRETA: dose muito baixa e sem papel no algoritmo.',
      C: 'INCORRETA: dose excessiva.',
      D: 'INCORRETA: atropina ainda é opção em bradicardia sintomática apropriada.',
    }),
    q(2, false, 'Qual é o erro mais comum ao interpretar taquicardia sinusal?', [
      'A) Tratar como diagnóstico final e esquecer causa como febre, dor, hipovolemia, anemia, sepse ou tireotoxicose.',
      'B) Procurar gatilhos clínicos antes de prescrever antiarrítmico.',
      'C) Reavaliar sinais vitais e perfusão.',
      'D) Pensar em causa sistêmica quando a frequência acompanha o contexto.',
    ], 0, 'Taquicardia sinusal geralmente é resposta a um problema. A prova pune quem tenta "converter" a consequência sem tratar a causa.', {
      A: 'CORRETA: taquicardia sinusal é sinal, não diagnóstico final confortável.',
      B: 'INCORRETA: isso é conduta adequada.',
      C: 'INCORRETA: reavaliação clínica é obrigatória.',
      D: 'INCORRETA: esse raciocínio evita erro.',
    }),
  ];
}

function cards() {
  return [
    fc(1, 'Na arritmia aguda, a primeira pergunta é se o paciente está {{c1::instável}}.', 'Instável', 'Hipotensão, choque, dor isquêmica, edema pulmonar e rebaixamento mudam a conduta.', 'abordagem', ['cm5', 'arritmia', 'emergencia']),
    fc(2, 'Taquiarritmia com pulso e instabilidade pede {{c1::cardioversão sincronizada}}.', 'Cardioversão sincronizada', 'O sincronismo evita choque no período vulnerável da repolarização.', 'acls', ['cm5', 'taquicardia', 'cardioversao']),
    fc(1, 'Fibrilação atrial no ECG é ritmo {{c1::irregularmente irregular}} sem onda P sinusal organizada.', 'Irregularmente irregular', 'É o padrão clássico que a banca cobra antes de anticoagulação.', 'ecg', ['cm5', 'fa', 'ecg']),
    fc(2, 'FA com estenose mitral moderada/importante ou válvula mecânica usa {{c1::varfarina/VKA}}, não DOAC como rotina.', 'Varfarina/VKA', 'É exceção central das diretrizes modernas e caiu em prova pública.', 'anticoagulacao', ['cm5', 'fa', 'vka']),
    fc(2, 'Na maioria da FA não valvar elegível, anticoagulação prefere {{c1::DOAC}} em vez de varfarina.', 'DOAC', 'Sempre ponderar risco tromboembólico, sangramento, rim e interações.', 'anticoagulacao', ['cm5', 'fa', 'doac']),
    fc(3, 'FA pré-excitada com QRS largo irregular: evitar bloqueadores do {{c1::nó AV}}.', 'Nó AV', 'Adenosina, betabloqueador, diltiazem/verapamil e digoxina podem favorecer via acessória.', 'armadilha', ['cm5', 'wpw', 'fa']),
    fc(2, 'TSV regular estreita estável começa com manobra vagal e {{c1::adenosina}}.', 'Adenosina', 'Bolus rápido e monitorização; instabilidade muda para cardioversão.', 'tsv', ['cm5', 'tsv', 'adenosina']),
    fc(2, 'Taquicardia regular de QRS largo deve ser tratada como {{c1::taquicardia ventricular}} até prova em contrário.', 'Taquicardia ventricular', 'Essa regra é especialmente importante em cardiopata estrutural.', 'ecg', ['cm5', 'tv', 'qrs_largo']),
    fc(3, 'Torsades de pointes é TV polimórfica com QT longo e pede {{c1::magnésio}}.', 'Magnésio', 'Também corrigir K/Mg e retirar drogas que prolongam QT.', 'emergencia', ['cm5', 'torsades', 'qt']),
    fc(2, 'Bradicardia sintomática usa atropina {{c1::1 mg IV a cada 3-5 min, máximo 3 mg}} quando apropriado.', '1 mg IV a cada 3-5 min, máximo 3 mg', 'Se ineficaz, pacing e/ou drogas vasoativas entram no fluxo.', 'acls', ['cm5', 'bradicardia', 'atropina']),
    fc(2, 'Bloqueio AV avançado com hipotensão após atropina ineficaz indica {{c1::marcapasso transcutâneo}} enquanto prepara solução definitiva.', 'Marcapasso transcutâneo', 'Pode ser ponte para marcapasso transvenoso ou definitivo conforme causa.', 'bradiarritmia', ['cm5', 'bloqueio_av', 'pacing']),
    fc(1, 'Taquicardia sinusal é geralmente {{c1::sinal de causa sistêmica}}, não diagnóstico final.', 'Sinal de causa sistêmica', 'Procure dor, febre, hipovolemia, anemia, sepse, hipóxia e tireotoxicose.', 'raciocinio', ['cm5', 'taquicardia_sinusal', 'causa']),
  ];
}

function material() {
  return [
    '---',
    'aula_id: cm5_a4',
    'materia: clinica_medica5',
    'modulo: 5',
    'tema: Arritmias Cardíacas',
    'versao_v3: 3.0.0',
    'status: published_local',
    'revisado_em: 2026-05-07',
    'checksum_lint: pass_pending',
    '---',
    '',
    '# Arritmias Cardíacas',
    '',
    '**Disciplina:** Clínica Médica 5',
    '**Módulo:** 5 | **Referência principal:** ACC/AHA/HRS FA 2023 + ESC FA 2024 + AHA ACLS 2025',
    '**Tempo de estudo sugerido:** 25-35 min',
    '',
    '---',
    '',
    '## Relevância Clínica e Acadêmica',
    '',
    'Arritmia é uma aula em que o aluno erra por tentar decorar nomes antes de responder o básico: **o paciente está instável? o QRS é estreito ou largo? o ritmo é regular ou irregular?**',
    '',
    'Na prova, a banca costuma esconder a resposta em três linhas: pressão baixa, confusão, dor torácica, edema pulmonar ou síncope. Se você ignora isso e fica procurando detalhe bonito no ECG, escolhe droga quando precisava de choque sincronizado.',
    '',
    '> **Pegadinha de prova:** arritmia instável não espera você terminar a classificação completa. Primeiro estabiliza. Depois você faz o diagnóstico fino.',
    '',
    'Esta aula conversa diretamente com `cm5_a2`: lá você aprendeu a ler o ECG; aqui você transforma leitura em decisão. Também conversa com `cm5_a3`, porque IC, FA e bloqueios se alimentam em círculo.',
    '',
    '---',
    '',
    '## Caso da Semana',
    '',
    '**Ato 1 - Entrada:** homem de 74 anos, hipertenso e com dispneia aos pequenos esforços, chega com palpitações há 6 horas. Está sudoreico, PA 84x50 mmHg, confuso, saturando 91% e com estertores bibasais.',
    '',
    '**Ato 2 - Virada:** o ECG mostra ritmo irregularmente irregular, QRS estreito e frequência ventricular perto de 160 bpm. A família conta que ele já teve episódio parecido, mas nunca usou anticoagulante.',
    '',
    '**Ato 3 - Decisão:** antes de discutir DOAC, escore de risco ou cardioversão eletiva, a prioridade é reconhecer **FA instável** com congestão e hipoperfusão. Aqui a conduta inicial é cardioversão elétrica sincronizada, com monitorização e manejo da IC aguda.',
    '',
    '> **Moral da vinheta:** se a perfusão caiu, o tratamento agudo é guiado pela instabilidade. Anticoagulação e estratégia crônica vêm depois que o paciente volta a existir como paciente estável.',
    '',
    '---',
    '',
    '## Abordagem Inicial',
    '',
    'A sequência mental deve ser curta:',
    '',
    '1. **Tem pulso?**',
    '2. **Está instável?**',
    '3. **Frequência alta ou baixa?**',
    '4. **QRS estreito ou largo?**',
    '5. **Ritmo regular ou irregular?**',
    '',
    'Sinais de instabilidade relevantes:',
    '',
    '- Hipotensão ou choque.',
    '- Rebaixamento do nível de consciência.',
    '- Dor torácica isquêmica persistente.',
    '- Edema agudo de pulmão.',
    '- Sinais de má perfusão: pele fria, oligúria, lactato alto.',
    '',
    '**Macete MedGradPlus - pulso, pressão, QRS:** se tem pulso, você decide entre cardioversão sincronizada, droga ou observação. Se não tem pulso, é parada. Se a pressão caiu, o ECG deixa de ser curiosidade e vira emergência.',
    '',
    '---',
    '',
    '## Taquiarritmia com Pulso',
    '',
    '| Situação | Conduta central | Observação de prova |',
    '|---|---|---|',
    '| **Instável** | cardioversão elétrica sincronizada | sedar se possível, mas não atrasar se choque |',
    '| **Regular estreita estável** | manobra vagal, adenosina | típico de TSV paroxística |',
    '| **Regular larga estável** | tratar como TV até prova em contrário | antiarrítmico e especialista |',
    '| **Irregular larga** | cuidado com FA pré-excitada | evitar bloqueio isolado do nó AV |',
    '',
    'A frequência por si só não basta. Um paciente com 160 bpm conversando bem é diferente de outro com 150 bpm, confuso e hipotenso.',
    '',
    '> **Pérola Clínica:** QRS largo regular em adulto cardiopata é TV até prova em contrário. Não chame de "supraventricular com aberrância" para se sentir tranquilo sem base.',
    '',
    '---',
    '',
    '## Cardioversão, Desfibrilação e Adenosina',
    '',
    '| Intervenção | Quando pensar | Erro comum |',
    '|---|---|---|',
    '| **Cardioversão sincronizada** | taquiarritmia com pulso e instabilidade | atrasar por exame desnecessário |',
    '| **Desfibrilação** | ritmo chocável sem pulso ou FV/TV sem pulso | usar sincronismo em parada |',
    '| **Adenosina** | TSV regular estreita estável; às vezes regular larga monomórfica sob protocolo | usar em FA pré-excitada ou ritmo irregular largo |',
    '',
    'Adenosina bloqueia transitoriamente o nó AV. Isso ajuda na TSV dependente do nó AV, mas pode ser perigoso quando há via acessória ou ritmo irregular largo.',
    '',
    '**Macete MedGradPlus - sincroniza se tem pulso:** choque em taquiarritmia com pulso geralmente é sincronizado. Choque em parada não fica esperando onda R.',
    '',
    '---',
    '',
    '## Fibrilação Atrial',
    '',
    'Fibrilação atrial é a arritmia sustentada mais cobrada. O ECG clássico mostra **ritmo irregularmente irregular**, ausência de onda P sinusal organizada e resposta ventricular variável.',
    '',
    'Três decisões importam:',
    '',
    '1. **Instável ou estável?**',
    '2. **Controle de frequência ou ritmo?**',
    '3. **Precisa anticoagular? Com o quê?**',
    '',
    '| Cenário | Conduta que a banca quer |',
    '|---|---|',
    '| **FA instável** | cardioversão elétrica sincronizada |',
    '| **FA estável com resposta alta** | controle de frequência ou ritmo conforme contexto |',
    '| **FA com alto risco embólico** | anticoagulação se benefício superar risco |',
    '| **FA com estenose mitral moderada/importante ou válvula mecânica** | antagonista da vitamina K |',
    '| **FA sem essas exceções, elegível** | DOAC costuma ser preferido |',
    '',
    'Controle de frequência costuma usar betabloqueador ou bloqueador de canal de cálcio não diidropiridínico em paciente adequado. Mas cuidado: **diltiazem e verapamil podem piorar HFrEF/descompensação**.',
    '',
    '> **Armadilha de banca:** "FA paroxística" não significa "sem risco de AVC". O risco embólico vem do perfil do paciente, não só da duração percebida do episódio.',
    '',
    '---',
    '',
    '## Anticoagulação na FA',
    '',
    'A regra moderna é separar FA com exceções clássicas das demais:',
    '',
    '- **Válvula mecânica:** varfarina/VKA.',
    '- **Estenose mitral moderada ou importante:** varfarina/VKA.',
    '- **Demais pacientes elegíveis:** DOAC frequentemente preferido.',
    '',
    'AAS isolado não substitui anticoagulação para prevenção de AVC na FA. Ele pode aparecer na alternativa para seduzir, mas não entrega proteção equivalente.',
    '',
    'A decisão também exige rim, idade, sangramento prévio, interações e adesão. Só que em prova a exceção mais importante é simples: **estenose mitral significativa e válvula mecânica não são território de DOAC de rotina**.',
    '',
    '---',
    '',
    '## FA Pré-excitada e WPW',
    '',
    'FA pré-excitada aparece como ritmo irregular, frequentemente com QRS largo e muito rápido. O perigo é bloquear o nó AV e deixar a via acessória conduzir ainda mais.',
    '',
    'Evite bloqueadores isolados do nó AV:',
    '',
    '- Adenosina.',
    '- Betabloqueadores.',
    '- Diltiazem/verapamil.',
    '- Digoxina.',
    '',
    'Se instável: cardioversão elétrica. Se estável: manejo monitorizado, especialista e antiarrítmico apropriado conforme protocolo local.',
    '',
    '> **Pegadinha de prova:** irregular + largo + muito rápido não é "FA comum". Pense em pré-excitação antes de apertar o freio do nó AV.',
    '',
    '---',
    '',
    '## Taquicardia Supraventricular Paroxística',
    '',
    'A TSV paroxística típica é regular, estreita e abrupta. O paciente relata palpitação súbita, às vezes com desconforto, tontura ou ansiedade secundária.',
    '',
    'Paciente estável:',
    '',
    '1. Manobra vagal bem feita.',
    '2. Adenosina em bolus rápido se não reverter e não houver contraindicação.',
    '3. Monitorização e registro do ECG antes/depois.',
    '',
    'Paciente instável:',
    '',
    '- Cardioversão sincronizada.',
    '',
    'Não confunda TSV com taquicardia sinusal. Na sinusal, há causa sistêmica: dor, febre, sepse, anemia, hipóxia, tireotoxicose, hipovolemia ou abstinência.',
    '',
    '---',
    '',
    '## Taquicardias Ventriculares',
    '',
    'Taquicardia ventricular sustentada costuma ser **QRS largo** e pode ser monomórfica ou polimórfica.',
    '',
    '| Tipo | Pista | Conduta geral |',
    '|---|---|---|',
    '| **TV monomórfica estável** | QRS largo regular | antiarrítmico e especialista; tratar como TV |',
    '| **TV com instabilidade e pulso** | hipotensão, choque, dor, edema pulmonar | cardioversão sincronizada |',
    '| **TV sem pulso/FV** | parada cardiorrespiratória | desfibrilação + RCP |',
    '| **Torsades de pointes** | TV polimórfica + QT longo | magnésio, corrigir K/Mg, retirar gatilhos |',
    '',
    'Torsades aparece com hipocalemia, hipomagnesemia, bradicardia e drogas que prolongam QT: macrolídeos, fluoroquinolonas, antieméticos, antipsicóticos e alguns antiarrítmicos.',
    '',
    '**Macete MedGradPlus - QT longo pede magnésio:** se a vinheta tem síncope, QT longo e droga nova, não procure verapamil. Procure torsades.',
    '',
    '---',
    '',
    '## Bradiarritmias e Bloqueios',
    '',
    'Bradicardia importante é geralmente FC menor que 50 bpm com sintomas ou sinais de má perfusão. O número isolado não basta: atleta dormindo com FC 45 não é o mesmo que idoso com FC 34, hipotenso e confuso.',
    '',
    'Fluxo prático:',
    '',
    '1. Avaliar via aérea, oxigenação, monitor, acesso venoso e ECG.',
    '2. Procurar causa reversível: isquemia, droga, hipercalemia, hipotermia, intoxicação.',
    '3. Se sintomática e apropriada: atropina 1 mg IV a cada 3-5 min, máximo 3 mg.',
    '4. Se atropina falhar ou bloqueio avançado: marcapasso transcutâneo e/ou epinefrina/dopamina conforme protocolo.',
    '5. Preparar marcapasso transvenoso/definitivo quando indicado.',
    '',
    '| Bloqueio | ECG | Gravidade prática |',
    '|---|---|---|',
    '| **1º grau** | PR prolongado, todo P conduz | geralmente benigno se isolado |',
    '| **Mobitz I** | PR aumenta até bloquear | muitas vezes nodal |',
    '| **Mobitz II** | P bloqueia sem alongamento progressivo | maior risco; pensar em pacing |',
    '| **3º grau** | dissociação AV | alto risco se sintomático |',
    '',
    '> **Pérola Clínica:** bloqueio AV avançado sintomático não é lugar para repetir manobra vagal. O problema já é condução lenta demais.',
    '',
    '---',
    '',
    '## Causas Reversíveis que a Prova Cobra',
    '',
    '| Causa | Arritmia típica | Conduta-chave |',
    '|---|---|---|',
    '| **Hipercalemia** | QRS largo, ondas T apiculadas, bloqueios | cálcio IV se alteração grave + reduzir K |',
    '| **Tireotoxicose** | FA, taquicardia sinusal | tratar tireoide e controlar frequência |',
    '| **Isquemia** | TV, bloqueio, FA | protocolo coronariano quando indicado |',
    '| **Hipóxia/sepse** | taquicardia sinusal, FA | tratar causa sistêmica |',
    '| **Drogas** | QT longo, bloqueios | suspender gatilho e antagonizar quando possível |',
    '',
    'A banca gosta de taquicardia sinusal como distração. Febre, dor e sepse aceleram o nó sinusal. Antiarrítmico sem tratar causa é cosmético perigoso.',
    '',
    '---',
    '',
    '## Conduta por Vinheta',
    '',
    '| Vinheta | Tradução | Conduta inicial |',
    '|---|---|---|',
    '| **Palpitação súbita, QRS estreito regular, PA normal** | TSV provável | vagal/adenosina |',
    '| **FA, dispneia, PA 80x50, confusão** | FA instável | cardioversão sincronizada |',
    '| **QRS largo regular em cardiopata** | TV até prova contrária | tratar como TV |',
    '| **QT longo + síncope + droga nova** | torsades | magnésio e retirar gatilho |',
    '| **FC 34 + hipotensão + BAV avançado** | bradiarritmia grave | atropina/pacing |',
    '| **Estenose mitral + FA** | alto risco embólico valvar | varfarina/VKA |',
    '',
    '---',
    '',
    '## Ponte com próximas aulas',
    '',
    '- `cm5_a1`: HAS aumenta FA, HVE e doença estrutural.',
    '- `cm5_a2`: ECG é a linguagem básica desta aula.',
    '- `cm5_a3`: IC muda escolha de fármacos e piora prognóstico da FA.',
    '- `cm5_a5`: isquemia pode causar TV, FA e bloqueios.',
    '- `farm_a10`: antiarrítmicos explicam mecanismo, toxicidade e interações.',
    '',
    '---',
    '',
    '## Pontos-Chave',
    '',
    '- Instabilidade manda mais que o nome exato da arritmia.',
    '- Taquiarritmia instável com pulso pede cardioversão sincronizada.',
    '- Ritmo irregularmente irregular sem P organizada sugere FA.',
    '- FA não valvar elegível geralmente prefere DOAC.',
    '- FA com estenose mitral moderada/importante ou válvula mecânica usa VKA.',
    '- FA pré-excitada: não bloqueie isoladamente o nó AV.',
    '- TSV regular estreita estável: manobra vagal e adenosina.',
    '- QRS largo regular em cardiopata: trate como TV até prova contrária.',
    '- Torsades: QT longo, TV polimórfica, magnésio e corrigir eletrólitos.',
    '- Bradicardia sintomática: atropina 1 mg IV e pacing se falha/alto grau.',
    '- Taquicardia sinusal pede causa, não vaidade antiarrítmica.',
    '',
    '---',
    '',
    '## Mini Quiz',
    '',
    '**1. Paciente com taquicardia e hipotensão deve ser avaliado primeiro por qual critério?**',
    '',
    '- [x] Instabilidade hemodinâmica',
    '- [ ] Nome comercial do monitor',
    '- [ ] Preferência do paciente por comprimido',
    '- [ ] Troponina antes de qualquer conduta',
    '',
    '> **Explicação:** instabilidade define prioridade. Em taquiarritmia com pulso, pode indicar cardioversão sincronizada.',
    '',
    '**2. Qual ECG sugere fibrilação atrial?**',
    '',
    '- [x] Ritmo irregularmente irregular sem P sinusal organizada',
    '- [ ] PR fixo com P antes de todo QRS',
    '- [ ] Bradicardia sinusal regular',
    '- [ ] Bloqueio AV de primeiro grau isolado',
    '',
    '> **Explicação:** a assinatura da FA é irregularidade irregular e ausência de onda P organizada.',
    '',
    '**3. FA com estenose mitral moderada deve receber qual estratégia anticoagulante típica?**',
    '',
    '- [x] Varfarina/antagonista da vitamina K',
    '- [ ] Aspirina isolada',
    '- [ ] Nenhuma terapia porque FA paroxística não emboliza',
    '- [ ] DOAC obrigatório em qualquer valvopatia',
    '',
    '> **Explicação:** estenose mitral moderada/importante é exceção clássica ao uso rotineiro de DOAC.',
    '',
    '**4. Qual erro é grave na FA pré-excitada?**',
    '',
    '- [x] Bloquear isoladamente o nó AV',
    '- [ ] Monitorizar',
    '- [ ] Chamar especialista',
    '- [ ] Cardioverter se instável',
    '',
    '> **Explicação:** bloquear o nó AV pode favorecer condução pela via acessória e degenerar para FV.',
    '',
    '**5. QRS largo regular em paciente com cardiopatia estrutural deve ser tratado inicialmente como o quê?**',
    '',
    '- [x] Taquicardia ventricular',
    '- [ ] Taquicardia sinusal benigna',
    '- [ ] Ansiedade sem risco',
    '- [ ] Ritmo normal com artefato sempre',
    '',
    '> **Explicação:** a regra segura é TV até prova em contrário.',
    '',
    '**6. Bradicardia sintomática com bloqueio AV avançado e falha da atropina pede qual ponte terapêutica?**',
    '',
    '- [x] Marcapasso transcutâneo',
    '- [ ] Adenosina',
    '- [ ] Manobra vagal',
    '- [ ] Alta ambulatorial',
    '',
    '> **Explicação:** se há hipoperfusão e atropina falha, pacing vira medida de ponte para solução definitiva.',
    '',
    '---',
    '',
    '## Pré-Prova',
    '',
    '### Síntese para a prova',
    '',
    'Arritmia em prova é menos "decore todos os ritmos" e mais **classifique para agir**. Primeiro estabilidade. Depois QRS estreito/largo. Depois regular/irregular. Com isso você evita os erros fatais: atrasar cardioversão no instável, chamar QRS largo regular de benigno, anticoagular FA valvar com remédio errado e bloquear nó AV na FA pré-excitada.',
    '',
    '### Macete-âncora',
    '',
    '**Instável choca; largo é TV até provar; irregular largo não bloqueia nó AV.**',
    '',
    '- Instável com pulso: cardioversão sincronizada.',
    '- Sem pulso: algoritmo de parada.',
    '- QRS largo regular: TV até prova contrária.',
    '- Irregular largo: pense em FA pré-excitada.',
    '- Bradicardia sintomática: atropina 1 mg e pacing se necessário.',
    '',
    '### Erros que derrubam nota',
    '',
    '- Usar AAS como substituto de anticoagulação na FA.',
    '- Dar DOAC de rotina para FA com estenose mitral moderada/importante.',
    '- Usar verapamil/diltiazem em HFrEF descompensada sem cuidado.',
    '- Dar adenosina em ritmo irregular largo suspeito de pré-excitação.',
    '- Tratar taquicardia sinusal sem procurar causa.',
    '- Repetir manobra vagal em bloqueio AV avançado sintomático.',
    '',
    '---',
    '',
    '## Fontes',
    '',
    '- ACC/AHA/ACCP/HRS. **2023 Guideline for the Diagnosis and Management of Atrial Fibrillation**.',
    '- European Society of Cardiology. **2024 ESC Guidelines for the management of atrial fibrillation**.',
    '- American Heart Association. **2025 Guidelines for CPR and Emergency Cardiovascular Care - Adult Bradycardia and Tachycardia With a Pulse**.',
    '- Harrison Medicina Interna, 21ª edição, capítulos de arritmias e eletrofisiologia clínica.',
    '- Cecil-Goldman Medicine, 26ª edição, capítulos de arritmias cardíacas.',
    '',
    '---',
    '',
    '## Questões mapeadas',
    '',
    '- **ENARE 2024, Acesso Direto Tipo 1** - questão pública com estenose mitral moderada e fibrilação atrial no Holter, útil para anticoagulação com VKA.',
    '- **ENAMED 2025, Caderno preliminar** - questão pública com fibrilação atrial em paciente com AVC agudo, útil para risco tromboembólico.',
    '- **ENAMED 2025, Caderno preliminar** - questão pública com síncope, ECG e alterações de ST/T em paciente com perda ponderal, útil para raciocínio de arritmia/risco elétrico sem copiar enunciado.',
  ].join('\n');
}

function updateFiles() {
  const md = material();
  writeText('data/materiais/clinica_medica5/cm5_a4.md', md);
  writeText('materiais/modulo5/clinica_medica5/cm5_a4.md', md);
}

function updateData() {
  const qData = readJson('data/questoes.json');
  let questoes = (qData.questoes || []).filter((item) => item.origem !== MARKER);
  const novos = questions();
  let maxQ = Math.max(0, ...questoes.map((item) => Number(item.id) || 0));
  for (const item of novos) item.id = ++maxQ;
  questoes.push(...novos);
  writeJson('data/questoes.json', { ...qData, questoes });

  const fcData = readJson('data/flashcards.json');
  let flashcards = (fcData.flashcards || []).filter((item) => item.origem !== MARKER);
  const novosCards = cards();
  let maxFc = Math.max(0, ...flashcards.map((item) => Number(item.id) || 0));
  for (const item of novosCards) item.id = ++maxFc;
  flashcards.push(...novosCards);
  writeJson('data/flashcards.json', { ...fcData, flashcards });
}

function updateRefs() {
  writeJson('data/refs/cm5_a4.refs.json', {
    aula_id: AULA,
    materia: 'clinica_medica5',
    tema: 'Arritmias Cardíacas',
    generatedAt: '2026-05-07T18:00:00.000Z',
    marker: MARKER,
    fontes_base: [
      {
        tipo: 'diretriz',
        titulo: '2023 ACC/AHA/ACCP/HRS Guideline for the Diagnosis and Management of Atrial Fibrillation',
        url: 'https://www.ahajournals.org/doi/10.1161/CIR.0000000000001193',
        uso: 'diagnóstico de FA, anticoagulação, exceções para válvula mecânica/estenose mitral e estratégia de controle.',
      },
      {
        tipo: 'diretriz',
        titulo: '2024 ESC Guidelines for the management of atrial fibrillation',
        url: 'https://academic.oup.com/eurheartj/article/45/36/3314/7738779',
        uso: 'modelo AF-CARE, risco tromboembólico e manejo integrado.',
      },
      {
        tipo: 'algoritmo',
        titulo: 'AHA 2025 Guidelines for CPR and ECC - Adult Bradycardia and Tachycardia With a Pulse',
        url: 'https://cpr.heart.org/en/resuscitation-science/cpr-and-ecc-guidelines',
        uso: 'taquicardia com pulso, bradicardia sintomática, atropina, pacing e cardioversão.',
      },
    ],
    questoes_publicas: [
      {
        origem: 'ENARE 2024',
        url: 'https://mapa-vagas-enare-ebserh.conhecimento.fgv.br/provas-gabaritos-medica.html',
        descricao: 'Questão pública de acesso direto com estenose mitral moderada e fibrilação atrial no Holter; usada apenas como mapeamento temático para anticoagulação com VKA.',
        copiar_enunciado: false,
      },
      {
        origem: 'ENAMED 2025',
        url: 'https://download.inep.gov.br/enamed/provas_e_gabaritos/2025_caderno_superampliado_preliminar.pdf',
        descricao: 'Questão pública com fibrilação atrial no contexto de AVC agudo; usada como mapeamento de risco tromboembólico, sem transcrição.',
        copiar_enunciado: false,
      },
      {
        origem: 'ENAMED 2025',
        url: 'https://download.inep.gov.br/enamed/provas_e_gabaritos/2025_caderno_superampliado_preliminar.pdf',
        descricao: 'Questão pública com síncope e ECG em paciente com perda ponderal; usada como mapeamento para risco elétrico/ECG, sem transcrição.',
        copiar_enunciado: false,
      },
    ],
  });
}

updateFiles();
updateData();
updateRefs();

console.log('CM5 a4 atualizada com material, essenciais e flashcards.');
