import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const AULA = 'cm5_a7';
const MARKER = 'cm5_quality_contract_2026_05_07_cm5_a7';
const FIG_ID = 'CM5-A7-F01';

function p(rel) { return path.join(ROOT, rel); }
function readJson(rel) { return JSON.parse(fs.readFileSync(p(rel), 'utf8')); }
function writeJson(rel, data) {
  fs.mkdirSync(path.dirname(p(rel)), { recursive: true });
  fs.writeFileSync(p(rel), `${JSON.stringify(data, null, 2)}\n`, 'utf8');
}
function writeText(rel, text) {
  fs.mkdirSync(path.dirname(p(rel)), { recursive: true });
  fs.writeFileSync(p(rel), `${text.replace(/\r\n/g, '\n').replace(/\n*$/, '')}\n`, 'utf8');
}
function explanation(general, exp) {
  return [`Resumo: ${general}`, `A) ${exp.A}`, `B) ${exp.B}`, `C) ${exp.C}`, `D) ${exp.D}`].join('\n');
}
function q(dificuldade, caso_clinico, enunciado, opcoes, correta, general, exp) {
  return { materia: 'clinica_medica5', tema: AULA, aula_id: AULA, modulo: 5, dificuldade, caso_clinico, essencial: true, origem: MARKER, enunciado, opcoes, correta, explicacao_geral: general, explicacoes_opcoes: exp, explicacao: explanation(general, exp) };
}
function fc(dificuldade, frente, verso, explicacao, categoria, tags) {
  return { materia: 'clinica_medica5', tema: AULA, dificuldade, frente, verso, explicacao, origem: MARKER, categoria, tags };
}

function questions() {
  return [
    q(1, false, 'Qual eixo hormonal explica a relação entre hipotálamo, hipófise anterior e córtex adrenal?', ['A) CRH estimula ACTH, que estimula cortisol.', 'B) TSH estimula ACTH, que inibe cortisol.', 'C) Insulina estimula GH, que reduz cortisol.', 'D) Aldosterona estimula prolactina, que reduz ACTH.'], 0, 'O eixo HPA é CRH, ACTH e cortisol, com feedback negativo do cortisol sobre hipotálamo e hipófise.', { A: 'CORRETA: é a sequência central do eixo HPA.', B: 'INCORRETA: TSH pertence ao eixo tireoidiano.', C: 'INCORRETA: mistura eixo pancreático e GH.', D: 'INCORRETA: aldosterona não regula prolactina desse modo.' }),
    q(2, true, 'Paciente com fadiga, perda ponderal, hiperpigmentação, hipotensão, hiponatremia e hipercalemia. Qual diagnóstico é mais provável?', ['A) Insuficiência adrenal primária.', 'B) Hipertireoidismo subclínico.', 'C) Prolactinoma.', 'D) Acromegalia.'], 0, 'Insuficiência adrenal primária cursa com deficiência de cortisol e aldosterona, gerando hiperpigmentação por ACTH alto e hipercalemia.', { A: 'CORRETA: hiperpigmentação e hipercalemia apontam para forma primária.', B: 'INCORRETA: não explica hipercalemia e hiperpigmentação.', C: 'INCORRETA: prolactinoma dá hipogonadismo/galactorreia e efeito de massa.', D: 'INCORRETA: acromegalia tem crescimento acral e IGF-1 alto.' }),
    q(3, true, 'Mulher com insuficiência adrenal conhecida chega com vômitos, febre, confusão, PA 78x42 e hipoglicemia. Qual conduta imediata é mais adequada?', ['A) Hidrocortisona IV e reposição volêmica, sem esperar confirmação laboratorial se crise adrenal é provável.', 'B) Alta com prednisona oral para iniciar na próxima semana.', 'C) Furosemida para tratar hiponatremia.', 'D) Teste de supressão com dexametasona antes de qualquer tratamento.'], 0, 'Crise adrenal é emergência. Se suspeita é alta, colhe exames se possível, mas não atrasa hidrocortisona e volume.', { A: 'CORRETA: tratar rápido salva vida.', B: 'INCORRETA: instabilidade exige tratamento imediato.', C: 'INCORRETA: volume e cortisol são prioridades; furosemida pode piorar choque.', D: 'INCORRETA: teste de Cushing não tem papel na crise adrenal.' }),
    q(2, false, 'Qual rastreio inicial é mais apropriado diante de suspeita clínica de síndrome de Cushing endógena?', ['A) Cortisol salivar noturno, cortisol urinário livre de 24h ou teste de supressão com 1 mg de dexametasona.', 'B) Cortisol aleatório às 15h isolado.', 'C) TSH isolado.', 'D) Radiografia simples de sela túrcica.'], 0, 'Cushing deve ser rastreado com testes validados de hipercortisolismo, não com cortisol aleatório isolado.', { A: 'CORRETA: são testes de rastreio aceitos.', B: 'INCORRETA: cortisol aleatório tem muita sobreposição.', C: 'INCORRETA: TSH não rastreia Cushing.', D: 'INCORRETA: imagem não vem antes de evidência hormonal.' }),
    q(2, true, 'Paciente com hipertensão resistente e hipocalemia espontânea. Qual investigação inicial é mais coerente?', ['A) Relação aldosterona/renina.', 'B) Prolactina apenas.', 'C) IGF-1 apenas.', 'D) Cortisol salivar como primeiro exame obrigatório.'], 0, 'Hipertensão resistente com hipocalemia sugere hiperaldosteronismo primário; triagem é aldosterona/renina, com preparo adequado.', { A: 'CORRETA: é o rastreio central.', B: 'INCORRETA: prolactina não explica hipocalemia.', C: 'INCORRETA: IGF-1 rastreia acromegalia.', D: 'INCORRETA: Cushing pode causar HAS, mas hipocalemia/resistência aponta primeiro para aldosterona.' }),
    q(2, false, 'Qual achado favorece prolactinoma clinicamente relevante?', ['A) Galactorreia, amenorreia/hipogonadismo e prolactina elevada persistente.', 'B) Hipercalemia e hiperpigmentação.', 'C) Pés e mãos aumentados com IGF-1 alto.', 'D) PA resistente com renina suprimida e aldosterona alta.'], 0, 'Prolactinoma causa hiperprolactinemia e hipogonadismo; macroadenoma pode causar cefaleia e defeito visual.', { A: 'CORRETA: é apresentação típica.', B: 'INCORRETA: sugere insuficiência adrenal primária.', C: 'INCORRETA: sugere acromegalia.', D: 'INCORRETA: sugere hiperaldosteronismo.' }),
    q(2, true, 'Homem com aumento de número do calçado, mãos alargadas, sudorese, apneia do sono e hipertensão. Qual exame rastreia melhor acromegalia?', ['A) IGF-1.', 'B) Cortisol aleatório.', 'C) Prolactina isolada como único teste.', 'D) Aldosterona urinária isolada.'], 0, 'IGF-1 é rastreio inicial de acromegalia. Confirmação costuma envolver teste oral de glicose com GH, conforme endocrinologia.', { A: 'CORRETA: IGF-1 integra secreção de GH e é rastreio prático.', B: 'INCORRETA: cortisol não rastreia GH.', C: 'INCORRETA: prolactina pode coelevar, mas não rastreia acromegalia.', D: 'INCORRETA: aldosterona não tem papel.' }),
    q(3, true, 'Paciente com cefaleia súbita intensa, vômitos, queda visual e oftalmoplegia; RM sugere sangramento em macroadenoma hipofisário. Qual hipótese e conduta são prioritárias?', ['A) Apoplexia hipofisária; corticoide de estresse, avaliação visual e neurocirurgia/endocrinologia urgente.', 'B) Enxaqueca simples; alta após analgésico.', 'C) Hipoglicemia funcional; dieta fracionada.', 'D) Tireoidite subaguda; AINE e retorno.'], 0, 'Apoplexia hipofisária é emergência neuroendócrina, com risco de insuficiência adrenal aguda e perda visual.', { A: 'CORRETA: não pode atrasar corticoide se instável/suspeita forte.', B: 'INCORRETA: déficit visual/oftalmoplegia não é enxaqueca simples.', C: 'INCORRETA: não explica massa selar hemorrágica.', D: 'INCORRETA: tireoidite não causa esse quadro selar.' }),
    q(2, false, 'Qual princípio evita erro ao encontrar incidentaloma adrenal?', ['A) Avaliar secreção hormonal e risco radiológico antes de chamar de benigno.', 'B) Ignorar todo nódulo menor que 10 cm.', 'C) Fazer adrenalectomia em todos sem exames.', 'D) Tratar todos com corticoide crônico.'], 0, 'Incidentaloma adrenal exige avaliar autonomia de cortisol, feocromocitoma quando apropriado, aldosterona se HAS/hipocalemia, e características de imagem.', { A: 'CORRETA: função e imagem guiam conduta.', B: 'INCORRETA: tamanho não é o único critério.', C: 'INCORRETA: cirurgia universal é excesso.', D: 'INCORRETA: corticoide crônico pode causar dano.' }),
    q(2, true, 'Paciente com crises de cefaleia, sudorese, palpitações e hipertensão paroxística. Qual tumor funcional deve ser lembrado?', ['A) Feocromocitoma/paraganglioma.', 'B) Prolactinoma sempre.', 'C) Craniofaringioma sempre.', 'D) Adenoma tireotrófico sempre.'], 0, 'Tríade paroxística com HAS sugere feocromocitoma/paraganglioma; confirmar bioquimicamente antes de cirurgia.', { A: 'CORRETA: quadro clássico catecolaminérgico.', B: 'INCORRETA: prolactinoma não dá crises adrenérgicas típicas.', C: 'INCORRETA: craniofaringioma é massa selar, não catecolamina.', D: 'INCORRETA: TSHoma é raro e dá hipertireoidismo central.' }),
    q(2, false, 'Qual erro é comum na investigação de doença hipofisária?', ['A) Pedir RM antes de interpretar o eixo hormonal e depois tratar incidentaloma como causa de tudo.', 'B) Avaliar campo visual em macroadenoma próximo ao quiasma.', 'C) Dosar prolactina em suspeita de galactorreia/amenorreia.', 'D) Pensar em hipopituitarismo quando há macroadenoma.'], 0, 'Imagem sem hipótese hormonal gera incidentalomas e falsas atribuições. Macroadenoma, porém, exige avaliação hormonal e visual.', { A: 'CORRETA: esse é o erro de sequência.', B: 'INCORRETA: é conduta adequada.', C: 'INCORRETA: é conduta adequada.', D: 'INCORRETA: é raciocínio adequado.' }),
    q(2, false, 'Qual frase diferencia insuficiência adrenal primária da central?', ['A) Na primária, aldosterona tende a cair e ACTH sobe; na central, aldosterona costuma ser preservada e ACTH baixo/inadequado.', 'B) Na primária, ACTH sempre cai a zero.', 'C) Na central, hiperpigmentação e hipercalemia são obrigatórias.', 'D) Não há diferença laboratorial útil.'], 0, 'A forma primária lesa adrenal, perdendo cortisol e mineralocorticoide. A central perde ACTH, mas o eixo renina-angiotensina preserva mais aldosterona.', { A: 'CORRETA: é a diferença essencial.', B: 'INCORRETA: ACTH sobe na primária.', C: 'INCORRETA: hiperpigmentação/hipercalemia favorecem primária.', D: 'INCORRETA: ACTH, renina/aldosterona e eletrólitos ajudam muito.' }),
  ];
}

function cards() {
  return [
    fc(1, 'Eixo HPA: CRH estimula ACTH, que estimula {{c1::cortisol}}.', 'Cortisol', 'Cortisol faz feedback negativo em hipotálamo e hipófise.', 'eixo', ['cm5', 'hipofise', 'adrenal']),
    fc(2, 'Insuficiência adrenal primária sugere ACTH alto, hiperpigmentação e {{c1::hipercalemia}}.', 'Hipercalemia', 'Aldosterona baixa explica hipercalemia e hipotensão.', 'adrenal', ['cm5', 'addison']),
    fc(3, 'Crise adrenal exige hidrocortisona IV e {{c1::reposição volêmica}} sem atrasar por exame.', 'Reposição volêmica', 'Colha cortisol/ACTH se possível, mas trate primeiro se grave.', 'emergencia', ['cm5', 'crise_adrenal']),
    fc(2, 'Cushing é rastreado com cortisol salivar noturno, cortisol urinário 24h ou {{c1::dexametasona 1 mg}}.', 'Dexametasona 1 mg', 'Cortisol aleatório isolado é armadilha.', 'cushing', ['cm5', 'cushing']),
    fc(2, 'HAS resistente + hipocalemia sugere hiperaldosteronismo; rastreio é relação {{c1::aldosterona/renina}}.', 'Aldosterona/renina', 'Preparação medicamentosa e potássio interferem no resultado.', 'adrenal', ['cm5', 'aldosterona']),
    fc(2, 'Prolactinoma causa galactorreia, hipogonadismo e {{c1::prolactina elevada}}.', 'Prolactina elevada', 'Macroadenoma pode causar cefaleia e defeito campimétrico.', 'hipofise', ['cm5', 'prolactinoma']),
    fc(2, 'Acromegalia deve ser rastreada com {{c1::IGF-1}}.', 'IGF-1', 'GH pulsa; IGF-1 é mais estável para rastreio.', 'hipofise', ['cm5', 'acromegalia']),
    fc(3, 'Apoplexia hipofisária = cefaleia súbita, alteração visual e risco de {{c1::insuficiência adrenal aguda}}.', 'Insuficiência adrenal aguda', 'Corticoide de estresse pode ser necessário antes da confirmação completa.', 'emergencia', ['cm5', 'apoplexia']),
    fc(2, 'Incidentaloma adrenal exige avaliar função hormonal e {{c1::risco radiológico}}.', 'Risco radiológico', 'Não basta medir tamanho; densidade, washout e secreção importam.', 'incidentaloma', ['cm5', 'adrenal']),
    fc(2, 'Feocromocitoma lembra crises de cefaleia, sudorese, palpitações e {{c1::hipertensão paroxística}}.', 'Hipertensão paroxística', 'Confirmar bioquimicamente antes de operar.', 'adrenal', ['cm5', 'feocromocitoma']),
    fc(2, 'Macroadenoma hipofisário próximo ao quiasma exige avaliação de {{c1::campo visual}}.', 'Campo visual', 'Defeito bitemporal é pista clássica de compressão quiasmática.', 'hipofise', ['cm5', 'macroadenoma']),
    fc(2, 'Na insuficiência adrenal central, ACTH é baixo/inadequado e aldosterona costuma estar {{c1::preservada}}.', 'Preservada', 'Por isso hipercalemia é menos típica que na forma primária.', 'adrenal', ['cm5', 'adrenal_central']),
  ];
}

function material() {
  return [
    '---',
    'aula_id: cm5_a7',
    'materia: clinica_medica5',
    'modulo: 5',
    'tema: Doenças da Hipófise e das Adrenais',
    'versao_v3: 3.0.0',
    'status: published_local',
    'revisado_em: 2026-05-07',
    'checksum_lint: pass_pending',
    '---',
    '',
    '# Doenças da Hipófise e das Adrenais',
    '',
    '**Disciplina:** Clínica Médica 5',
    '**Módulo:** 5 | **Referência principal:** Harrison 21ª ed. + Endocrine Society + ESE/ENSAT 2023',
    '**Tempo de estudo sugerido:** 30-40 min',
    '',
    '---',
    '',
    '## Relevância Clínica e Acadêmica',
    '',
    'Hipófise e adrenal são temas pequenos no cronograma, mas grandes em armadilhas. O erro clássico é pedir imagem antes de saber qual eixo está doente, encontrar um incidentaloma e culpar o nódulo por tudo.',
    '',
    'Aqui o raciocínio precisa ser hormonal: **qual eixo? excesso ou deficiência? emergência ou ambulatório? massa funcionante ou não funcionante?** Essa ordem evita tanto atraso em crise adrenal quanto cirurgia desnecessária em incidentaloma.',
    '',
    '> **Pegadinha de prova:** cortisol aleatório quase nunca resolve Cushing nem insuficiência adrenal. A pergunta certa é contexto + teste certo + horário certo.',
    '',
    '---',
    '',
    '### Figura sugerida',
    '',
    '**Figura-ID:** `CM5-A7-F01`',
    '',
    '**Quando usar:** após a introdução, antes dos eixos hormonais.',
    '',
    '**Por que importa:** o eixo HPA organiza CRH, ACTH, cortisol e feedback, que são a base para diferenciar insuficiência adrenal primária, central e Cushing.',
    '',
    '---',
    '',
    '## Caso da Semana',
    '',
    '**Ato 1 - Entrada:** mulher de 38 anos chega com fadiga progressiva, perda de peso, tontura ao levantar e escurecimento de pregas palmares. PA 86x54, sódio baixo e potássio alto.',
    '',
    '**Ato 2 - Virada:** a família relata vômitos e febre desde ontem. Ela está sonolenta e hipoglicêmica. O laboratório de cortisol não ficará pronto rapidamente.',
    '',
    '**Ato 3 - Decisão:** o quadro é crise adrenal provável. A prioridade é hidrocortisona IV e volume. Se der para colher cortisol e ACTH antes, ótimo; se não der, não se atrasa tratamento em paciente instável.',
    '',
    '> **Moral da vinheta:** adrenal é eixo em que esperar resultado pode ser dano. Crise adrenal se trata quando é provável.',
    '',
    '---',
    '',
    '## Eixo HPA',
    '',
    'O eixo hipotálamo-hipófise-adrenal funciona assim:',
    '',
    '- Hipotálamo libera **CRH**.',
    '- Hipófise anterior libera **ACTH**.',
    '- Córtex adrenal libera **cortisol**.',
    '- Cortisol faz feedback negativo no hipotálamo e na hipófise.',
    '',
    '**Macete MedGradPlus - ACTH conta a origem:** cortisol baixo com ACTH alto aponta adrenal primária; cortisol baixo com ACTH baixo ou inadequado aponta causa central.',
    '',
    '| Situação | ACTH | Aldosterona | Pista |',
    '|---|---|---|---|',
    '| **Primária** | alto | baixa | hiperpigmentação, hipercalemia |',
    '| **Central** | baixo/inadequado | geralmente preservada | sem hiperpigmentação típica |',
    '| **Cushing ACTH-dependente** | alto/inadequado | variável | doença hipofisária ou ectópica |',
    '| **Cushing adrenal** | baixo | variável | lesão adrenal autônoma |',
    '',
    '---',
    '',
    '## Insuficiência Adrenal',
    '',
    'Pense em insuficiência adrenal quando houver fadiga, perda ponderal, hipotensão, náuseas, dor abdominal, hiponatremia, hipoglicemia e piora em estresse.',
    '',
    '| Forma | Achados | Mecanismo |',
    '|---|---|---|',
    '| **Primária** | hiperpigmentação, hipercalemia, renina alta | adrenal falha |',
    '| **Central** | pouca hiperpigmentação, K normal | ACTH baixo |',
    '| **Induzida por corticoide** | retirada ou estresse após uso crônico | eixo suprimido |',
    '',
    'Diagnóstico ambulatorial usa cortisol matinal e ACTH, com teste de estímulo com cosintropina quando necessário. Mas paciente em choque não é ambulatório.',
    '',
    '> **Armadilha de banca:** hipercalemia é pista forte de insuficiência adrenal primária. Na central, a aldosterona costuma ser preservada pelo sistema renina-angiotensina.',
    '',
    '---',
    '',
    '## Crise Adrenal',
    '',
    'Crise adrenal é emergência:',
    '',
    '- Hipotensão ou choque.',
    '- Vômitos, dor abdominal, febre.',
    '- Hipoglicemia.',
    '- Hiponatremia.',
    '- História de Addison, corticoide crônico ou doença hipofisária.',
    '',
    'Conduta prática:',
    '',
    '1. Acesso venoso, monitorização e glicemia.',
    '2. Coletar cortisol/ACTH se não atrasar.',
    '3. Hidrocortisona IV em dose de estresse.',
    '4. Soro fisiológico e glicose se hipoglicemia.',
    '5. Tratar gatilho: infecção, vômitos, cirurgia, omissão de corticoide.',
    '',
    '---',
    '',
    '## Cushing',
    '',
    'Cushing é excesso crônico de cortisol. Suspeite se há obesidade centrípeta, face arredondada, estrias violáceas largas, fraqueza proximal, equimoses, osteoporose, diabetes, HAS e infecções.',
    '',
    'Primeiro exclua uso exógeno de corticoide. Depois rastreie hipercortisolismo com teste validado.',
    '',
    '| Teste | O que avalia | Erro comum |',
    '|---|---|---|',
    '| **Cortisol salivar noturno** | perda do ritmo circadiano | coletar errado |',
    '| **Cortisol urinário livre 24h** | produção integrada | coleta incompleta |',
    '| **Dexametasona 1 mg** | supressão por feedback | interação medicamentosa |',
    '',
    '**Macete MedGradPlus - Cushing não se caça com cortisol solto:** se o enunciado traz "cortisol aleatório normal", isso não exclui Cushing. Use teste de rastreio correto.',
    '',
    '---',
    '',
    '## Hiperaldosteronismo Primário',
    '',
    'É causa importante e tratável de hipertensão secundária. Suspeite em:',
    '',
    '- Hipertensão resistente.',
    '- Hipocalemia espontânea ou induzida por diurético.',
    '- HAS + incidentaloma adrenal.',
    '- HAS grave ou início jovem.',
    '- História familiar de AVC precoce/HAS precoce.',
    '',
    '| Etapa | Exame | Observação |',
    '|---|---|---|',
    '| **Triagem** | relação aldosterona/renina | corrigir K e revisar drogas |',
    '| **Confirmação** | testes confirmatórios selecionados | com endocrinologia |',
    '| **Lateralização** | imagem e, muitas vezes, cateterismo venoso adrenal | antes de cirurgia |',
    '| **Tratamento** | adrenalectomia unilateral ou antagonista mineralocorticoide | depende da causa |',
    '',
    '> **Pérola Clínica:** hipocalemia não é obrigatória. Muitos pacientes com hiperaldosteronismo têm potássio normal.',
    '',
    '---',
    '',
    '## Feocromocitoma e Paraganglioma',
    '',
    'A tríade clássica é cefaleia, sudorese e palpitações, com hipertensão paroxística ou sustentada.',
    '',
    'O erro perigoso é operar ou biopsiar sem preparo. Primeiro confirme bioquimicamente, depois faça imagem e preparo alfa-bloqueador quando indicado.',
    '',
    '| Pista | Significado |',
    '|---|---|',
    '| **Crises adrenérgicas** | catecolaminas em excesso |',
    '| **HAS paroxística** | flutuação pressórica |',
    '| **Incidentaloma adrenal + sintomas** | investigar funcionalidade |',
    '| **História familiar** | pensar síndromes genéticas |',
    '',
    '---',
    '',
    '## Prolactinoma',
    '',
    'Hiperprolactinemia causa hipogonadismo:',
    '',
    '- Mulher: amenorreia, oligomenorreia, infertilidade, galactorreia.',
    '- Homem: queda de libido, disfunção erétil, infertilidade.',
    '- Macroadenoma: cefaleia, alteração visual, hipopituitarismo.',
    '',
    'Antes de chamar de prolactinoma, exclua gravidez, hipotireoidismo primário, doença renal, medicações antidopaminérgicas e efeito haste.',
    '',
    '| Situação | Pista | Conduta geral |',
    '|---|---|---|',
    '| **Microprolactinoma** | prolactina alta, sem massa grande | agonista dopaminérgico se indicado |',
    '| **Macroprolactinoma** | massa e prolactina alta | agonista dopaminérgico e seguimento visual |',
    '| **Efeito haste** | prolactina moderada com massa | tratar causa da compressão |',
    '',
    '---',
    '',
    '## Acromegalia',
    '',
    'Acromegalia é excesso de GH, geralmente por adenoma hipofisário. O início é lento: muda anel, sapato, face, mandíbula, língua, sudorese e ronco.',
    '',
    'Comorbidades importantes:',
    '',
    '- Hipertensão.',
    '- Diabetes.',
    '- Apneia do sono.',
    '- Cardiomiopatia.',
    '- Artropatia.',
    '- Neoplasia colorretal, conforme rastreio indicado.',
    '',
    'Rastreio inicial: **IGF-1**. Confirmação e seguimento são especializados, com teste de supressão de GH por glicose e RM de hipófise quando indicado.',
    '',
    '> **Armadilha de banca:** GH pulsa. IGF-1 é o rastreio que segura melhor a suspeita.',
    '',
    '---',
    '',
    '## Incidentaloma Hipofisário',
    '',
    'Incidentaloma hipofisário exige responder:',
    '',
    '1. Produz hormônio?',
    '2. Comprime quiasma?',
    '3. Causa hipopituitarismo?',
    '4. Está crescendo?',
    '',
    '| Avaliação | Por quê |',
    '|---|---|',
    '| **Prolactina** | hiperprolactinemia é comum e tratável |',
    '| **IGF-1** | rastreia acromegalia silenciosa |',
    '| **Eixo adrenal/tireoidiano/gonadal** | hipopituitarismo |',
    '| **Campo visual** | se toca/comprime quiasma |',
    '| **RM dedicada** | caracteriza lesão e seguimento |',
    '',
    '---',
    '',
    '## Incidentaloma Adrenal',
    '',
    'Incidentaloma adrenal não é "achado inocente" até provar duas coisas: baixa suspeita radiológica e ausência de secreção hormonal clinicamente relevante.',
    '',
    '| Pergunta | Como investigar |',
    '|---|---|',
    '| **Parece maligno?** | tamanho, densidade, heterogeneidade, crescimento |',
    '| **Secreta cortisol?** | supressão com dexametasona 1 mg |',
    '| **Secreta catecolamina?** | metanefrinas quando apropriado |',
    '| **Secreta aldosterona?** | aldosterona/renina se HAS ou hipocalemia |',
    '',
    '---',
    '',
    '## Apoplexia Hipofisária',
    '',
    'Apoplexia é infarto ou hemorragia em adenoma hipofisário. Suspeite em cefaleia súbita intensa, vômitos, alteração visual, oftalmoplegia, rebaixamento e sinais de insuficiência adrenal.',
    '',
    'Conduta:',
    '',
    '- Corticoide de estresse se instável ou suspeita forte de deficiência adrenal.',
    '- Avaliação neuro-oftalmológica.',
    '- RM de sela.',
    '- Neurocirurgia/endocrinologia urgente.',
    '',
    '---',
    '',
    '## Pontos-Chave',
    '',
    '- CRH, ACTH e cortisol formam o eixo HPA.',
    '- ACTH ajuda a separar adrenal primária de central.',
    '- Hiperpigmentação e hipercalemia favorecem insuficiência adrenal primária.',
    '- Crise adrenal é tratamento antes de burocracia diagnóstica.',
    '- Cushing não se exclui com cortisol aleatório.',
    '- Hiperaldosteronismo é HAS secundária tratável e pode ter K normal.',
    '- Feocromocitoma exige confirmação e preparo antes de cirurgia.',
    '- Prolactinoma causa hipogonadismo e galactorreia.',
    '- Acromegalia rastreia com IGF-1.',
    '- Macroadenoma perto do quiasma pede campo visual.',
    '- Incidentaloma adrenal exige função e imagem.',
    '- Apoplexia hipofisária é emergência.',
    '',
    '---',
    '',
    '## Mini Quiz',
    '',
    '**1. Qual sequência define o eixo HPA?**',
    '',
    '- [x] CRH, ACTH e cortisol',
    '- [ ] TRH, TSH e aldosterona',
    '- [ ] GnRH, GH e cortisol',
    '- [ ] Insulina, renina e prolactina',
    '',
    '> **Explicação:** CRH estimula ACTH, que estimula cortisol.',
    '',
    '**2. Hiperpigmentação e hipercalemia sugerem qual forma de insuficiência adrenal?**',
    '',
    '- [x] Primária',
    '- [ ] Central pura',
    '- [ ] Subclínica tireoidiana',
    '- [ ] Prolactinoma',
    '',
    '> **Explicação:** ACTH alto e aldosterona baixa favorecem forma primária.',
    '',
    '**3. Qual teste não é bom rastreio isolado para Cushing?**',
    '',
    '- [x] Cortisol aleatório',
    '- [ ] Cortisol salivar noturno',
    '- [ ] Cortisol urinário livre 24h',
    '- [ ] Dexametasona 1 mg',
    '',
    '> **Explicação:** cortisol aleatório tem muita sobreposição e não resolve a suspeita.',
    '',
    '**4. HAS resistente com hipocalemia sugere rastrear o quê?**',
    '',
    '- [x] Hiperaldosteronismo primário',
    '- [ ] Prolactinoma',
    '- [ ] Diabetes insipidus',
    '- [ ] Hipotireoidismo central',
    '',
    '> **Explicação:** aldosterona autônoma causa retenção de sódio, perda de potássio e HAS.',
    '',
    '**5. Qual exame rastreia acromegalia?**',
    '',
    '- [x] IGF-1',
    '- [ ] Troponina',
    '- [ ] TSH isolado',
    '- [ ] Cortisol urinário para todos',
    '',
    '> **Explicação:** IGF-1 é mais estável que GH basal.',
    '',
    '**6. Cefaleia súbita, alteração visual e macroadenoma hemorrágico sugerem:**',
    '',
    '- [x] Apoplexia hipofisária',
    '- [ ] Cistite simples',
    '- [ ] Síndrome metabólica',
    '- [ ] Osteoporose primária',
    '',
    '> **Explicação:** é emergência neuroendócrina, com risco visual e adrenal.',
    '',
    '---',
    '',
    '## Pré-Prova',
    '',
    '### Síntese para a prova',
    '',
    'Hipófise e adrenal exigem ordem. Primeiro eixo e hormônio; depois imagem. Cortisol baixo com ACTH alto é adrenal primária; cortisol baixo com ACTH baixo é central. Cushing se rastreia com testes próprios. HAS resistente com hipocalemia pede aldosterona/renina. Prolactinoma dá hipogonadismo; acromegalia rastreia com IGF-1; apoplexia e crise adrenal são emergências.',
    '',
    '### Macete-âncora',
    '',
    '**Hormônio antes da imagem; emergência antes da confirmação perfeita.**',
    '',
    '- ACTH alto: adrenal primária.',
    '- ACTH baixo: central.',
    '- Cortisol demais: rastreie Cushing direito.',
    '- Aldosterona demais: HAS resistente e K baixo.',
    '- Prolactina demais: hipogonadismo e galactorreia.',
    '- GH demais: IGF-1 alto e crescimento acral.',
    '',
    '### Erros que derrubam nota',
    '',
    '- Usar cortisol aleatório para excluir Cushing.',
    '- Atrasar hidrocortisona em crise adrenal.',
    '- Pedir imagem antes de confirmar eixo hormonal.',
    '- Esquecer campo visual no macroadenoma.',
    '- Não pensar em apoplexia hipofisária na cefaleia súbita com déficit visual.',
    '- Chamar todo incidentaloma adrenal de benigno sem avaliar secreção.',
    '',
    '---',
    '',
    '## Fontes',
    '',
    '- Pituitary Society. **Pituitary incidentaloma consensus guideline statement**, 2025.',
    '- Pituitary Society. **Diagnosis and management of prolactin-secreting pituitary adenomas**, 2023.',
    '- Endocrine Society. **Primary Adrenal Insufficiency** guideline.',
    '- Endocrine Society. **Primary Aldosteronism** guideline.',
    '- ESE/ENSAT. **Adrenal incidentaloma guideline**, 2023.',
    '- Endocrine Society. **Diagnosis of Cushing syndrome** guideline.',
    '- Harrison Medicina Interna, 21ª edição, capítulos de hipófise, adrenal e endocrinologia clínica.',
  ].join('\n');
}

function updateFiles() {
  const md = material();
  writeText('data/materiais/clinica_medica5/cm5_a7.md', md);
  writeText('materiais/modulo5/clinica_medica5/cm5_a7.md', md);
}

function updateData() {
  const qData = readJson('data/questoes.json');
  let questoes = (qData.questoes || []).filter((item) => item.origem !== MARKER);
  const novos = questions();
  let maxQ = Math.max(0, ...questoes.map((item) => Number(item.id) || 0));
  for (const item of novos) item.id = ++maxQ;
  questoes.push(...novos);
  writeJson('data/questoes.json', { ...qData, questoes });

  const fcData = readJson('data/flashcards.json');
  let flashcards = (fcData.flashcards || []).filter((item) => item.origem !== MARKER);
  const novosCards = cards();
  let maxFc = Math.max(0, ...flashcards.map((item) => Number(item.id) || 0));
  for (const item of novosCards) item.id = ++maxFc;
  flashcards.push(...novosCards);
  writeJson('data/flashcards.json', { ...fcData, flashcards });
}

function updateFigures() {
  const rel = 'data/materiais_figuras.json';
  const data = readJson(rel);
  const entries = (data.entries || []).filter((fig) => fig.id !== FIG_ID);
  entries.push({
    id: FIG_ID,
    modulo: 5,
    disciplina: 'clinica_medica5',
    aula: AULA,
    caminhoMaterial: 'materiais/modulo5/clinica_medica5/cm5_a7.md',
    momento: 'Após introdução, antes de Eixo HPA',
    descricaoVisual: 'Esquema do eixo hipotálamo-hipófise-adrenal com CRH, ACTH, cortisol e feedback negativo.',
    tipoSugerido: 'Esquema didático em SVG.',
    buscaCommonsEn: 'HPA axis hypothalamus pituitary adrenal cortex axis svg',
    buscaCommonsPt: 'eixo hipotálamo hipófise adrenal CRH ACTH cortisol',
    status: 'encontrada',
    urlImagem: 'https://upload.wikimedia.org/wikipedia/commons/a/ad/HPA-axis_-_Hypothalamus%2C_Pituitary_and_Adrenal_cortex_Axis.svg',
    urlThumbnail: '',
    urlPaginaCommons: 'https://commons.wikimedia.org/wiki/File:HPA-axis_-_Hypothalamus,_Pituitary_and_Adrenal_cortex_Axis.svg',
    licenca: 'CC BY-SA 4.0',
    credito: 'Biolinkage Project / Biomedo, via Wikimedia Commons',
    legenda: 'Eixo HPA: CRH estimula ACTH, ACTH estimula cortisol, e cortisol faz feedback negativo.',
    notas: 'Imagem essencial para diferenciar insuficiência adrenal primária, central e hipercortisolismo.',
  });
  writeJson(rel, { ...data, updatedAt: new Date().toISOString(), entries });
}

function updateRefs() {
  writeJson('data/refs/cm5_a7.refs.json', {
    aula_id: AULA,
    materia: 'clinica_medica5',
    tema: 'Doenças da Hipófise e das Adrenais',
    generatedAt: '2026-05-07T19:55:00.000Z',
    marker: MARKER,
    fontes_base: [
      { tipo: 'consenso', titulo: 'Pituitary Society - Pituitary incidentaloma consensus guideline statement, 2025', url: 'https://www.nature.com/articles/s41574-025-01134-8', uso: 'incidentaloma hipofisário, avaliação hormonal, visual e seguimento.' },
      { tipo: 'diretriz', titulo: 'Endocrine Society - Primary Adrenal Insufficiency', url: 'https://www.endocrine.org/clinical-practice-guidelines/primary-adrenal-insufficiency', uso: 'insuficiência adrenal e crise adrenal.' },
      { tipo: 'diretriz', titulo: 'Endocrine Society - Primary Aldosteronism', url: 'https://www.endocrine.org/clinical-practice-guidelines/primary-aldosteronism-2', uso: 'rastreio e manejo de hiperaldosteronismo primário.' },
      { tipo: 'diretriz', titulo: 'ESE/ENSAT - Adrenal incidentaloma guideline, 2023', url: 'https://academic.oup.com/ejendo/article/189/1/G1/7198474', uso: 'incidentaloma adrenal e secreção hormonal.' },
    ],
    imagem: FIG_ID,
  });
}

updateFiles();
updateData();
updateFigures();
updateRefs();

console.log('CM5 a7 atualizada com material, essenciais, flashcards e figura.');
