import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const MARKER = 'cm5_quality_contract_2026_05_07_cm5_a18_a21';

function p(rel) { return path.join(ROOT, rel); }
function readJson(rel) { return JSON.parse(fs.readFileSync(p(rel), 'utf8')); }
function writeJson(rel, data) { fs.mkdirSync(path.dirname(p(rel)), { recursive: true }); fs.writeFileSync(p(rel), `${JSON.stringify(data, null, 2)}\n`, 'utf8'); }
function writeText(rel, text) { fs.mkdirSync(path.dirname(p(rel)), { recursive: true }); fs.writeFileSync(p(rel), `${text.replace(/\r\n/g, '\n').replace(/\n*$/, '')}\n`, 'utf8'); }
function table(headers, rows) { return [`| ${headers.join(' | ')} |`, `| ${headers.map(() => '---').join(' | ')} |`, ...rows.map((r) => `| ${r.join(' | ')} |`)]; }
function q(aula, [dif, caso, enunciado, correta, b, c, d, general]) {
  return {
    materia: 'clinica_medica5',
    tema: aula,
    aula_id: aula,
    modulo: 5,
    dificuldade: dif,
    caso_clinico: caso,
    essencial: true,
    origem: `${MARKER}_${aula}`,
    enunciado,
    opcoes: [`A) ${correta}`, `B) ${b}`, `C) ${c}`, `D) ${d}`],
    correta: 0,
    explicacao_geral: general,
    explicacoes_opcoes: { A: `CORRETA: ${general}`, B: 'INCORRETA: não corresponde ao padrão da vinheta.', C: 'INCORRETA: distrator comum.', D: 'INCORRETA: não é a prioridade.' },
    explicacao: [`Resumo: ${general}`, `A) CORRETA: ${general}`, 'B) INCORRETA: não corresponde.', 'C) INCORRETA: distrator.', 'D) INCORRETA: não é prioridade.'].join('\n'),
  };
}
function fc(aula, [dif, frente, verso, explicacao, categoria, tags]) { return { materia: 'clinica_medica5', tema: aula, dificuldade: dif, frente, verso, explicacao, origem: `${MARKER}_${aula}`, categoria, tags }; }

const lessons = [
  {
    aula: 'cm5_a18',
    title: 'Dermatoses Virais e Micoses',
    ref: 'CDC zoster/molusco/HPV/tinea + Ministério da Saúde micoses endêmicas + Harrison 21ª ed. + Cecil-Goldman 26ª ed.',
    image: {
      id: 'CM5-A18-F01',
      urlImagem: 'https://upload.wikimedia.org/wikipedia/commons/7/78/%E0%B0%AE%E0%B1%87%E0%B0%96%E0%B0%B2_%E0%B0%B5%E0%B0%BF%E0%B0%B8%E0%B0%B0%E0%B1%8D%E0%B0%AA%E0%B0%BF%E0%B0%A3%E0%B0%BF_%28Herpes_Zoster%29.jpeg',
      urlThumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/%E0%B0%AE%E0%B1%87%E0%B0%96%E0%B0%B2_%E0%B0%B5%E0%B0%BF%E0%B0%B8%E0%B0%B0%E0%B1%8D%E0%B0%AA%E0%B0%BF%E0%B0%A3%E0%B0%BF_%28Herpes_Zoster%29.jpeg/960px-%E0%B0%AE%E0%B1%87%E0%B0%96%E0%B0%B2_%E0%B0%B5%E0%B0%BF%E0%B0%B8%E0%B0%B0%E0%B1%8D%E0%B0%AA%E0%B0%BF%E0%B0%A3%E0%B0%BF_%28Herpes_Zoster%29.jpeg',
      urlPaginaCommons: 'https://commons.wikimedia.org/wiki/File:%E0%B0%AE%E0%B1%87%E0%B0%96%E0%B0%B2_%E0%B0%B5%E0%B0%BF%E0%B0%B8%E0%B0%B0%E0%B1%8D%E0%B0%AA%E0%B0%BF%E0%B0%A3%E0%B0%BF_(Herpes_Zoster).jpeg',
      licenca: 'CC0',
      credito: 'డా. గన్నవరపు నరసింహమూర్తి',
      legenda: 'Herpes-zóster em padrão dermatomal. Dor neuropática e vesículas agrupadas ajudam a separar de micoses e dermatites.',
      descricaoVisual: 'Lesões vesiculares de herpes-zóster em faixa dermatomal.',
      momento: 'Após diferenciar HSV, varicela e zóster.',
      buscaEn: 'shingles rash dermatome',
      buscaPt: 'herpes zóster dermátomo vesículas',
    },
    imageDecision: { usar_imagem: true, figura_id: 'CM5-A18-F01', motivo: 'Dermatologia depende de morfologia; zóster dermatomal é sinal visual que muda diagnóstico e urgência ocular.' },
    relevance: ['Dermatologia em clínica médica é reconhecimento de padrão. A banca não quer álbum de lesões; quer que você diferencie **vesícula viral**, **pápula umbilicada**, **placa anular com borda ativa** e **micose que piorou com corticoide**.', '', 'O foco de prova é zóster, HSV, varicela, molusco, verrugas, dermatofitoses, candidíase e pitiríase versicolor.', '', '> **Pegadinha de prova:** corticoide em tinea deixa a lesão menos típica e mais extensa. Tinea incognito é erro criado pelo tratamento errado.'],
    case: ['**Ato 1 - Entrada:** idoso com dor em queimação e vesículas agrupadas em faixa torácica unilateral.', '', '**Ato 2 - Virada:** jovem usa corticoide em placa anular pruriginosa e a lesão se espalha, com borda menos nítida.', '', '**Ato 3 - Decisão:** o primeiro é zóster e pede antiviral precoce se indicado; o segundo é tinea incognito e pede parar corticoide e confirmar micose.', '', '> **Moral da vinheta:** pele tem gramática. Distribuição, borda e sintoma contam mais que adjetivo solto.'],
    sections: [
      ['Figura sugerida', ['**Figura-ID:** `CM5-A18-F01`', '- **Momento:** após o bloco HSV/varicela/zóster.', '- **Descrição técnica:** vesículas em faixa dermatomal.', '- **Legenda:** zóster dermatomal com vesículas agrupadas e dor neuropática.']],
      ['HSV, Varicela e Zóster', ['HSV faz vesículas agrupadas recorrentes em base eritematosa, geralmente oral ou genital. Varicela é disseminada, com lesões em diferentes estágios. Zóster é unilateral, dermatomal e doloroso.', '', ...table(['Vírus', 'Padrão', 'Armadilha'], [['**HSV**', 'recorrente, oral/genital', 'pode disseminar em imunossuprimido'], ['**Varicela**', 'difusa, polimórfica', 'adulto pode ser grave'], ['**Zóster**', 'dermatomal doloroso', 'olho e face são urgência']]), '', '**Macete MedGradPlus - zóster respeita faixa:** se cruza linha média e não dói, pense duas vezes.']],
      ['Zóster Oftálmico e Ramsay Hunt', ['Sinal de Hutchinson, lesão em ponta do nariz ou acometimento ocular exigem avaliação urgente. Ramsay Hunt associa zóster ótico, paralisia facial e dor.', '', '> **Armadilha de banca:** zóster no território V1 não é dermatite simples. Olho em risco muda conduta.']],
      ['Molusco, Verrugas e HPV', ['Molusco contagioso tem pápulas umbilicadas. Em adulto com lesão disseminada, pense imunossupressão/HIV. Verrugas anogenitais são diagnóstico clínico; teste de HPV não é forma de fechar a lesão visível.', '', 'Vacina previne doença por tipos cobertos, mas não trata verruga já presente.', '', '**Macete MedGradPlus - umbilicado é molusco:** pápula lisa com umbigo no centro é pista visual forte.']],
      ['Dermatofitoses', ['Tinea corporis/cruris tem placa anular, borda ativa, descamação periférica e clareamento central. KOH deve colher da borda ativa.', '', ...table(['Tinea', 'Pista', 'Tratamento'], [['**Corporis/cruris**', 'anel pruriginoso', 'tópico se limitada'], ['**Capitis**', 'couro cabeludo', 'oral'], ['**Unguium**', 'unha', 'confirmar e considerar oral'], ['**Incognito**', 'após corticoide', 'parar corticoide e antifúngico']])]],
      ['Malassezia, Candida e Micoses Profundas', ['Pitiríase versicolor por Malassezia causa máculas hipo ou hipercromias finamente descamativas, mais em tronco. Candidíase/intertrigo tem eritema em dobra com lesões satélites.', '', 'Esporotricose pode formar lesão nodular com trajeto linfangítico. Micoses profundas e endêmicas pedem contexto epidemiológico e imunidade.', '', '> **Pérola Clínica:** micose que não parece micose depois de corticoide pode ser exatamente micose mascarada.']],
    ],
    key: ['Zóster é unilateral, dermatomal e doloroso.', 'V1/Hutchinson muda urgência.', 'Ramsay Hunt associa ouvido e paralisia facial.', 'Molusco é pápula umbilicada.', 'Molusco disseminado em adulto sugere imunossupressão.', 'Tinea tem borda ativa.', 'KOH colhe da borda.', 'Tinea capitis exige tratamento oral.', 'Corticoide pode causar tinea incognito.', 'Pitiríase versicolor é Malassezia.', 'Candidíase tem satélites em dobras.', 'Verruga por HPV é diagnóstico clínico.'],
    quiz: [['Zóster típico é:', 'Dermatomal, unilateral e doloroso', 'Anular com clareamento central', 'Pápula umbilicada', 'Escama gordurosa em face', 'Dor e faixa dermatomal são pistas.'], ['Sinal de Hutchinson sugere risco de:', 'Zóster oftálmico', 'Tinea pedis', 'Molusco simples', 'Psoríase', 'Nariz/V1 ameaça olho.'], ['Tinea corporis deve ter amostra de KOH coletada na:', 'Borda ativa', 'Pele normal distante', 'Unha contralateral', 'Mucosa oral sempre', 'Borda concentra fungo.'], ['Tinea capitis trata com:', 'Antifúngico sistêmico', 'Creme isolado sempre', 'Antibiótico', 'Triptano', 'Couro cabeludo exige via oral.'], ['Pápula umbilicada sugere:', 'Molusco contagioso', 'CRAO', 'Ménière', 'Rinite', 'Morfologia é clássica.'], ['Candidíase em dobra costuma ter:', 'Lesões satélites', 'Cilindros hemáticos', 'Cherry-red spot', 'Trismo', 'Satélites ajudam diagnóstico.']],
    questions: [[2, true, 'Idoso com dor em queimação e vesículas em faixa torácica unilateral. Diagnóstico?', 'Herpes-zóster.', 'Tinea corporis.', 'Molusco.', 'Psoríase.', 'Faixa dermatomal dolorosa é zóster.'], [3, true, 'Zóster em V1 com lesão na ponta do nariz. Conduta?', 'Avaliação oftalmológica urgente.', 'Aguardar 6 meses.', 'Corticoide tópico isolado.', 'Epley.', 'Hutchinson sugere risco ocular.'], [2, false, 'Placa anular pruriginosa com borda ativa. Exame simples?', 'KOH da borda ativa.', 'TC de crânio.', 'Eletrocardiograma.', 'Punção lombar.', 'KOH confirma dermatófito.'], [2, false, 'Tinea capitis deve receber:', 'Antifúngico sistêmico.', 'Creme isolado.', 'Antibiótico para GAS.', 'Oxigênio alto fluxo.', 'Folículo/couro cabeludo exige tratamento oral.'], [2, true, 'Lesão piorou e ficou atípica após corticoide tópico em placa anular. Hipótese?', 'Tinea incognito.', 'CRAO.', 'HPN.', 'Rinite alérgica.', 'Corticoide mascara dermatófito.'], [2, false, 'Molusco contagioso tem:', 'Pápulas umbilicadas.', 'Pápulas purpúricas sempre.', 'Cortina visual.', 'Otorreia.', 'Umbilicação é pista.'], [2, true, 'Adulto com molusco disseminado. O que investigar?', 'Imunossupressão/HIV conforme contexto.', 'Apenas presbiopia.', 'VPPB.', 'OME.', 'Disseminação em adulto é alerta.'], [2, false, 'Pitiríase versicolor é causada por:', 'Malassezia.', 'Streptococcus pyogenes.', 'Neisseria meningitidis.', 'Candida auris sempre.', 'Malassezia é levedura lipofílica.'], [2, false, 'Candidíase em dobra sugere:', 'Eritema com lesões satélites.', 'Placa prateada em extensor.', 'Cherry-red spot.', 'Trismo.', 'Satélites são típicos.'], [2, false, 'Verruga anogenital por HPV é geralmente diagnóstico:', 'Clínico.', 'Por TC.', 'Por fundo de olho.', 'Por audiometria.', 'Lesão visível orienta diagnóstico.'], [2, false, 'Varicela clássica tem lesões:', 'Em diferentes estágios.', 'Só em um dermátomo sempre.', 'Apenas nas unhas.', 'Só em retina.', 'Polimorfismo lesional é pista.'], [2, true, 'Nódulos em trajeto linfangítico após trauma com planta/gato lembram:', 'Esporotricose.', 'Cefaleia em salvas.', 'CRVO.', 'Otite externa.', 'Trajeto linfangítico é pista.']],
    cards: [[2, 'Zóster é vesicular, doloroso e {{c1::dermatomal}}.', 'dermatomal', 'Geralmente unilateral.', 'viral', ['cm5', 'zoster']], [3, 'Sinal de Hutchinson sugere zóster {{c1::oftálmico}}.', 'oftálmico', 'Risco ocular.', 'viral', ['cm5', 'zoster']], [2, 'Molusco tem pápula {{c1::umbilicada}}.', 'umbilicada', 'Centro deprimido.', 'viral', ['cm5', 'molusco']], [2, 'Tinea corporis tem borda {{c1::ativa}}.', 'ativa', 'KOH vem da borda.', 'micose', ['cm5', 'tinea']], [2, 'Tinea capitis exige antifúngico {{c1::sistêmico}}.', 'sistêmico', 'Creme não alcança folículo.', 'micose', ['cm5', 'capitis']], [2, 'Corticoide pode mascarar tinea: tinea {{c1::incognito}}.', 'incognito', 'Lesão fica atípica.', 'micose', ['cm5', 'incognito']], [2, 'Pitiríase versicolor é causada por {{c1::Malassezia}}.', 'Malassezia', 'Máculas descamativas no tronco.', 'micose', ['cm5', 'malassezia']], [2, 'Candidíase em dobra tem lesões {{c1::satélites}}.', 'satélites', 'Intertrigo candidiásico.', 'micose', ['cm5', 'candida']], [2, 'Verruga anogenital por HPV é diagnóstico {{c1::clínico}}.', 'clínico', 'HPV teste não fecha lesão visível.', 'hpv', ['cm5', 'hpv']], [2, 'Varicela tem lesões em diferentes {{c1::estágios}}.', 'estágios', 'Polimorfismo lesional.', 'viral', ['cm5', 'varicela']], [2, 'Ramsay Hunt associa zóster ótico e paralisia {{c1::facial}}.', 'facial', 'Pode ter hipoacusia/vertigem.', 'viral', ['cm5', 'ramsay']], [2, 'Esporotricose pode seguir trajeto {{c1::linfangítico}}.', 'linfangítico', 'Pista após trauma/inoculação.', 'micose', ['cm5', 'esporotricose']]],
    fontes: ['CDC. **Clinical Overview of Shingles**.', 'CDC. **Molluscum Contagiosum Clinical Overview**.', 'CDC. **Ringworm Clinical Overview**.', 'Ministério da Saúde. **Micoses endêmicas**.', 'Harrison Medicina Interna, 21ª edição, capítulos de dermatologia infecciosa.'],
  },
  {
    aula: 'cm5_a19',
    title: 'Lesões Eritematodescamativas',
    ref: 'AAD-NPF psoriasis guidelines + NICE psoriasis CG153 + SBD psoríase + Harrison 21ª ed. + Cecil-Goldman 26ª ed.',
    image: { id: 'CM5-A19-F01', urlImagem: 'https://upload.wikimedia.org/wikipedia/commons/3/38/Psoriasis_on_Human_shins.jpg', urlThumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Psoriasis_on_Human_shins.jpg/960px-Psoriasis_on_Human_shins.jpg', urlPaginaCommons: 'https://commons.wikimedia.org/wiki/File:Psoriasis_on_Human_shins.jpg', licenca: 'CC BY 4.0', credito: 'Drb206', legenda: 'Psoríase em placas em membros inferiores. Placas eritematoescamosas bem delimitadas em extensores orientam o diagnóstico.', descricaoVisual: 'Placas eritematoescamosas compatíveis com psoríase.', momento: 'Após o bloco de psoríase em placas.', buscaEn: 'psoriasis plaque clinical photograph', buscaPt: 'psoríase em placas escamas' },
    imageDecision: { usar_imagem: true, figura_id: 'CM5-A19-F01', motivo: 'Morfologia de placa eritematoescamosa é central para diferenciar psoríase, tinea, eczema e sífilis secundária.' },
    relevance: ['Lesão eritematodescamativa é dermatologia de prova pura: distribuição, borda, escama, palma/planta, unha e sintomas sistêmicos.', '', 'O aluno erra quando chama tudo de eczema ou passa corticoide sem excluir tinea. Aqui a prioridade é separar psoríase, dermatite seborreica, pitiríase rósea, tinea, eczema, líquen plano, sífilis secundária e lúpus cutâneo.', '', '> **Pegadinha de prova:** antes de chamar placa anular de eczema, pense em tinea e faça KOH se a morfologia pedir.'],
    case: ['**Ato 1 - Entrada:** homem com placas bem delimitadas, descamativas, em cotovelos e joelhos, além de pitting ungueal.', '', '**Ato 2 - Virada:** outro paciente tem exantema descamativo em palmas e plantas com adenomegalia e história sexual de risco.', '', '**Ato 3 - Decisão:** o primeiro é psoríase; o segundo é sífilis secundária até prova em contrário.', '', '> **Moral da vinheta:** escama não é diagnóstico. Distribuição e contexto dão o nome.'],
    sections: [
      ['Figura sugerida', ['**Figura-ID:** `CM5-A19-F01`', '- **Momento:** após introdução de psoríase.', '- **Descrição técnica:** placas eritematoescamosas bem delimitadas.', '- **Legenda:** psoríase em placas, padrão extensor e bem delimitado.']],
      ['Psoríase', ['Psoríase em placas dá placas eritematoescamosas bem delimitadas, em extensores, couro cabeludo e região sacral. Unhas podem ter pitting, onicólise e manchas em óleo.', '', ...table(['Variante', 'Pista', 'Gravidade'], [['**Placas**', 'extensores, escama prateada', 'comum'], ['**Gutata**', 'pós-estreptococo', 'jovens'], ['**Inversa**', 'dobras, pouca escama', 'mimetiza candidíase'], ['**Pustulosa/eritrodérmica**', 'sistêmica/extensa', 'grave']]), '', '**Macete MedGradPlus - extensor, unha, articulação:** esse trio puxa psoríase.']],
      ['Artrite e Gravidade', ['Dor articular, dactilite, rigidez matinal e entesite mudam manejo. Psoríase não é só pele.', '', 'Eritrodermia, pustulose generalizada, acometimento extenso, face/mãos/genitais e impacto funcional elevam gravidade.', '', '> **Armadilha de banca:** corticoide sistêmico pode rebater psoríase e precipitar formas graves.']],
      ['Dermatite Seborreica e Pitiríase Rósea', ['Seborreica tem escama gordurosa em couro cabeludo, sobrancelhas, sulco nasolabial e esterno. Piora em HIV e Parkinson.', '', 'Pitiríase rósea começa com placa-mãe e depois lesões em árvore de Natal no tronco, geralmente autolimitada.', '', '**Macete MedGradPlus - gordurosa no centro da face:** seborreica ama área sebácea.']],
      ['Mimetizadores que Derrubam', ['Tinea corporis faz anel com borda ativa. Eczema numular faz placas arredondadas, mas sem clareamento central típico. Líquen plano tem pápulas violáceas pruriginosas. Sífilis secundária pode acometer palmas e plantas.', '', ...table(['Mimetizador', 'Pista', 'Exame'], [['**Tinea**', 'borda ativa', 'KOH'], ['**Sífilis**', 'palma/planta, sistêmico', 'sorologia'], ['**Lúpus**', 'fotoexposição', 'ANA/contexto'], ['**Eczema**', 'prurido e história atópica', 'clínico']])]],
      ['Conduta Inicial', ['Hidratante, corticoide tópico, análogos de vitamina D e tratamento de couro cabeludo entram conforme gravidade. Fototerapia e sistêmicos são para doença moderada/grave ou refratária.', '', '> **Pérola Clínica:** se tem articulação, unha importante ou doença extensa, a pergunta deixou de ser pomada.']],
    ],
    key: ['Psoríase em placas pega extensores.', 'Pitting ungueal reforça psoríase.', 'Auspitz e Koebner são pistas clássicas.', 'Gutata pode seguir estreptococo.', 'Inversa tem pouca escama.', 'Pustulosa/eritrodérmica é grave.', 'Seborreica tem escama gordurosa.', 'Pitiríase rósea tem placa-mãe.', 'Tinea tem borda ativa.', 'Sífilis secundária acomete palma/planta.', 'Artrite psoriásica muda gravidade.', 'Corticoide sistêmico em psoríase pode rebater.'],
    quiz: [['Psoríase em placas típica acomete:', 'Extensores e couro cabeludo', 'Apenas mucosa oral', 'Somente planta dos pés', 'Retina', 'Distribuição extensor é clássica.'], ['Placa-mãe e árvore de Natal sugerem:', 'Pitiríase rósea', 'CRAO', 'VPPB', 'OME', 'Padrão autolimitado no tronco.'], ['Escama gordurosa no sulco nasolabial sugere:', 'Dermatite seborreica', 'Sífilis secundária sempre', 'Zóster', 'Meningite', 'Área sebácea é pista.'], ['Palmas e plantas em lesão descamativa sistêmica lembram:', 'Sífilis secundária', 'Rinite', 'Cefaleia', 'Otite', 'Sífilis não poupa palma/planta.'], ['Placa anular com borda ativa pede pensar em:', 'Tinea', 'CRVO', 'Surdez súbita', 'HPN', 'Borda ativa é dermatófito.'], ['Psoríase com dactilite sugere:', 'Artrite psoriásica', 'Conjuntivite viral', 'OME', 'Cistite', 'Articulação muda manejo.']],
    questions: [[2, true, 'Placas eritematoescamosas em cotovelos/joelhos com pitting ungueal. Diagnóstico?', 'Psoríase.', 'Tinea incognito obrigatória.', 'Molusco.', 'CRAO.', 'Distribuição e unha são típicas.'], [2, false, 'Psoríase gutata costuma ocorrer após:', 'Infecção estreptocócica.', 'CRAO.', 'VPPB.', 'Cerume.', 'Estreptococo é gatilho clássico.'], [2, false, 'Dermatite seborreica acomete preferencialmente:', 'Couro cabeludo, sulco nasolabial e esterno.', 'Retina.', 'Cápsula de Bowman.', 'Cóclea.', 'Áreas sebáceas são típicas.'], [2, true, 'Placa-mãe seguida de lesões em árvore de Natal. Diagnóstico?', 'Pitiríase rósea.', 'Psoríase pustulosa.', 'CRVO.', 'Meningite.', 'Padrão clássico e autolimitado.'], [2, false, 'Lesão anular com borda ativa deve levantar:', 'Tinea corporis.', 'Alzheimer.', 'CRAO.', 'Meningite.', 'Dermatófito é mimetizador.'], [2, true, 'Lesões descamativas em palmas/plantas com sintomas sistêmicos. Exame?', 'Sorologia para sífilis.', 'Dix-Hallpike.', 'Audiometria apenas.', 'Tonometria.', 'Sífilis secundária entra forte.'], [3, false, 'Psoríase eritrodérmica deve ser vista como:', 'Grave e potencialmente sistêmica.', 'Sempre leve.', 'Rinite.', 'OME.', 'Eritrodermia pode descompensar.'], [2, false, 'Dactilite em paciente com psoríase sugere:', 'Artrite psoriásica.', 'Faringite viral.', 'Tinea pedis simples.', 'Cefaleia tensional.', 'Sinal articular.'], [2, false, 'Corticoide sistêmico em psoríase pode causar:', 'Rebote/piora grave.', 'Cura definitiva sempre.', 'CRAO.', 'Surdez súbita.', 'Risco de rebote é clássico.'], [2, false, 'Psoríase inversa ocorre em:', 'Dobras, com pouca escama.', 'Fundo de olho.', 'Ouvido médio.', 'Meninge.', 'Dobras mudam morfologia.'], [2, false, 'Fenômeno de Koebner é:', 'Lesão em área de trauma.', 'Surdez súbita.', 'Vertigem posicional.', 'Bacteriúria.', 'Trauma induz placa.'], [2, false, 'Auspitz é:', 'Sangramento puntiforme ao remover escama.', 'Nistagmo vertical.', 'Cherry-red spot.', 'Sinal de Giordano.', 'Pista clássica de psoríase.']],
    cards: [[2, 'Psoríase típica acomete superfícies {{c1::extensoras}}.', 'extensoras', 'Cotovelos e joelhos.', 'psoriase', ['cm5', 'dermato']], [2, 'Pitting ungueal reforça {{c1::psoríase}}.', 'psoríase', 'Unha muda gravidade.', 'psoriase', ['cm5', 'unha']], [2, 'Psoríase gutata pode seguir faringite {{c1::estreptocócica}}.', 'estreptocócica', 'Jovens e lesões em gotas.', 'psoriase', ['cm5', 'gutata']], [2, 'Dermatite seborreica tem escama {{c1::gordurosa}}.', 'gordurosa', 'Áreas sebáceas.', 'seborreica', ['cm5', 'dermato']], [2, 'Pitiríase rósea começa com placa {{c1::mãe}}.', 'mãe', 'Depois árvore de Natal.', 'pitiriase', ['cm5', 'dermato']], [2, 'Sífilis secundária pode acometer palmas e {{c1::plantas}}.', 'plantas', 'Não esquecer sorologia.', 'sifilis', ['cm5', 'dermato']], [2, 'Tinea tem borda {{c1::ativa}}.', 'ativa', 'Mimetiza eczema/psoríase.', 'tinea', ['cm5', 'dermato']], [3, 'Psoríase eritrodérmica é forma {{c1::grave}}.', 'grave', 'Risco sistêmico.', 'psoriase', ['cm5', 'grave']], [2, 'Dactilite sugere artrite {{c1::psoriásica}}.', 'psoriásica', 'Não é só pele.', 'artrite', ['cm5', 'psoriase']], [2, 'Koebner é lesão em área de {{c1::trauma}}.', 'trauma', 'Fenômeno isomórfico.', 'psoriase', ['cm5', 'koebner']], [2, 'Auspitz é sangramento {{c1::puntiforme}}.', 'puntiforme', 'Após remover escama.', 'psoriase', ['cm5', 'auspitz']], [2, 'Psoríase inversa ocorre em {{c1::dobras}}.', 'dobras', 'Pouca descamação.', 'psoriase', ['cm5', 'inversa']]],
    fontes: ['AAD-NPF. **Psoriasis clinical guidelines**.', 'NICE. **Psoriasis: assessment and management CG153**.', 'Sociedade Brasileira de Dermatologia. **Consenso Brasileiro de Psoríase**.', 'Harrison Medicina Interna, 21ª edição, capítulos de dermatologia inflamatória.', 'Cecil-Goldman Medicine, 26ª edição, capítulos de dermatologia.'],
  },
  {
    aula: 'cm5_a20',
    title: 'Hepatoesplenomegalia, Icterícia Febril e Adenomegalias',
    ref: 'Ministério da Saúde dengue/leptospirose/leishmaniose/malária + Tokyo Guidelines colangite + Harrison 21ª ed. + Cecil-Goldman 26ª ed.',
    image: null,
    imageDecision: { usar_imagem: false, motivo: 'Tema é sindrômico e ganha mais com algoritmo/tabela diferencial do que com imagem isolada.' },
    relevance: ['Esta é uma aula de raciocínio sindrômico. A prova joga febre, icterícia, baço, fígado e linfonodo para ver se você separa colangite, leptospirose, malária, leishmaniose visceral, hepatites, dengue grave e linfoma.', '', 'A pergunta raramente pede uma lista completa. Ela pede reconhecer o padrão que mata ou que exige investigação rápida.', '', '> **Pegadinha de prova:** icterícia febril com hipotensão e confusão não é hepatite para observar. Pense colangite grave ou sepse.'],
    case: ['**Ato 1 - Entrada:** homem com febre, icterícia, dor em hipocôndrio direito e hipotensão.', '', '**Ato 2 - Virada:** outro paciente tem febre prolongada, esplenomegalia volumosa e pancitopenia após viver em área endêmica.', '', '**Ato 3 - Decisão:** o primeiro é colangite grave até prova em contrário; o segundo lembra leishmaniose visceral. A mesma febre com icterícia não tem sempre a mesma origem.', '', '> **Moral da vinheta:** primeiro identifique a síndrome dominante; depois escolha exame e urgência.'],
    sections: [
      ['Icterícia Febril', ['Diferencie colestase, hepatocelular, hemólise e sepse. Febre muda prioridade.', '', ...table(['Padrão', 'Pistas', 'Diagnóstico'], [['**Colangite**', 'Charcot/Reynolds', 'imagem biliar e drenagem'], ['**Leptospirose**', 'enchente, panturrilha, sufusão', 'função renal e sorologia/PCR'], ['**Malária**', 'área endêmica, calafrios', 'gota espessa/TDR'], ['**Dengue grave**', 'extravasamento/choque', 'hematócrito e plaquetas']]), '', '**Macete MedGradPlus - icterícia febril instável drena ou interna:** não transforme sepse biliar em hepatite ambulatorial.']],
      ['Colangite', ['Tríade de Charcot: febre, icterícia e dor em hipocôndrio direito. Pentade de Reynolds adiciona hipotensão e alteração mental.', '', 'Conduta: antibiótico, suporte e drenagem biliar quando indicada. Choque e confusão elevam gravidade.', '', '> **Armadilha de banca:** antibiótico sem drenagem em obstrução infectada pode ser insuficiente.']],
      ['Leptospirose, Dengue, Febre Amarela e Hepatites', ['Leptospirose: exposição a enchente/roedores, mialgia de panturrilha, sufusão conjuntival, IRA, icterícia e hemorragia em formas graves.', '', 'Dengue grave: extravasamento plasmático, choque, sangramento importante ou disfunção orgânica. Hepatites virais entram com pródromo, transaminases altas e epidemiologia.', '', '**Macete MedGradPlus - panturrilha e enchente:** se vierem juntas com icterícia e rim, lepto sobe no ranking.']],
      ['Hepatoesplenomegalia', ['Baço grande com febre prolongada sugere leishmaniose visceral, malária, EBV/CMV, HIV, esquistossomose, cirrose/hipertensão portal ou doença hematológica.', '', ...table(['Causa', 'Pista', 'Exame'], [['**Leishmaniose visceral**', 'febre, baço, pancitopenia', 'teste rápido/sorologia/aspirado'], ['**Malária**', 'área de transmissão', 'gota espessa'], ['**EBV/CMV**', 'linfócitos atípicos', 'sorologia'], ['**Linfoma/leucemia**', 'B symptoms, citopenias', 'hemograma/biópsia']])]],
      ['Adenomegalias', ['Classifique localizada versus generalizada, dolorosa versus endurecida, móvel versus fixa, tamanho, duração e sintomas B.', '', 'Red flags: supraclavicular, dura/fixa, crescimento progressivo, >40 anos, febre prolongada, sudorese noturna, perda de peso, hepatoesplenomegalia e citopenias.', '', '> **Pérola Clínica:** não dê corticoide antes de investigar linfoma se o paciente está estável. Você pode apagar a biópsia.']],
      ['Exames Iniciais', ['Hemograma com diferencial, plaquetas, bilirrubinas, transaminases, FA/GGT, INR, função renal, urina, PCR, hemoculturas se sepse, ultrassom abdominal, sorologias conforme contexto, gota espessa em área de malária e testes de HIV/EBV/CMV quando indicados.', '', 'A escolha é guiada por epidemiologia. Pergunte viagem, enchente, exposição rural, contato com cães, drogas, sexo, transfusão, vacinação e área endêmica.']],
    ],
    key: ['Charcot é febre, icterícia e dor em HCD.', 'Reynolds adiciona hipotensão e confusão.', 'Colangite grave precisa suporte e drenagem.', 'Leptospirose lembra enchente e panturrilha.', 'Dengue grave é extravasamento, choque, sangramento ou órgão.', 'LV lembra febre prolongada, baço e pancitopenia.', 'Malária exige gota espessa/TDR.', 'EBV pode dar esplenomegalia.', 'Adenopatia supraclavicular é red flag.', 'Sintomas B sugerem linfoma/TB/HIV.', 'Não dar corticoide antes de biópsia se suspeita de linfoma.', 'Epidemiologia guia o painel.'],
    quiz: [['Charcot é:', 'Febre, icterícia e dor em HCD', 'Marcha, urina e cognição', 'Disúria, urgência e polaciúria', 'Dor orbitária e rinorreia', 'Tríade de colangite.'], ['Reynolds adiciona:', 'Hipotensão e alteração mental', 'Prurido e espirros', 'Pitting ungueal', 'Fotofobia', 'Gravidade na colangite.'], ['Leishmaniose visceral clássica tem:', 'Febre prolongada, esplenomegalia e pancitopenia', 'Vertigem posicional', 'Olho vermelho', 'Otalgia', 'Síndrome febril com baço.'], ['Leptospirose grave lembra:', 'Enchente, panturrilha, rim e icterícia', 'Placa-mãe', 'Aura visual', 'OME', 'Epidemiologia e mialgia são pistas.'], ['Adenopatia supraclavicular sugere:', 'Alto risco de malignidade', 'Rinite alérgica', 'VPPB', 'Conjuntivite', 'Localização é red flag.'], ['Malária deve ser investigada com:', 'Gota espessa ou teste rápido', 'Dix-Hallpike', 'Tonometria', 'Rinne', 'Diagnóstico parasitológico/rápido.']],
    questions: [[3, true, 'Febre, icterícia, dor em HCD, hipotensão e confusão. Diagnóstico/conduta?', 'Colangite grave com antibiótico, suporte e avaliação de drenagem.', 'Hepatite leve para casa.', 'Rinite.', 'VPPB.', 'Reynolds indica gravidade.'], [2, false, 'Tríade de Charcot inclui:', 'Febre, icterícia e dor em HCD.', 'Marcha, urina e cognição.', 'Disúria, urgência e polaciúria.', 'Dor orbitária e lacrimejamento.', 'Charcot é colangite.'], [2, true, 'Febre prolongada, esplenomegalia volumosa e pancitopenia em área endêmica. Hipótese?', 'Leishmaniose visceral.', 'OMA.', 'CRAO.', 'Tinea pedis.', 'LV causa baço e citopenias.'], [2, true, 'Enchente, mialgia de panturrilha, sufusão conjuntival, IRA e icterícia. Hipótese?', 'Leptospirose.', 'Psoríase.', 'VPPB.', 'Rinite.', 'Padrão clássico de lepto grave.'], [2, false, 'Malária em área de transmissão deve ser investigada com:', 'Gota espessa/teste rápido.', 'KOH.', 'Rinne.', 'Epley.', 'Confirma parasitemia.'], [2, false, 'Dengue grave é definida por:', 'Choque/extravasamento, sangramento grave ou órgão.', 'Coriza clara.', 'Pitting ungueal.', 'Cefaleia tensional.', 'Critérios de gravidade mudam manejo.'], [3, false, 'Adenopatia supraclavicular endurecida em adulto é:', 'Red flag para malignidade.', 'Sempre benigna.', 'Rinite.', 'VPPB.', 'Supraclavicular é alto risco.'], [2, false, 'Sintomas B incluem:', 'Febre, sudorese noturna e perda de peso.', 'Disúria.', 'Espirros.', 'Otalgia.', 'Pistas de linfoma/TB/HIV.'], [3, true, 'Suspeita de linfoma, paciente estável. O que evitar antes de biópsia?', 'Corticoide empírico.', 'Hemograma.', 'Exame físico.', 'Biópsia.', 'Corticoide pode mascarar histologia.'], [2, false, 'EBV pode causar esplenomegalia e exige cuidado com:', 'Trauma/esporte por risco de ruptura esplênica.', 'Tonometria.', 'Epley.', 'Insulina.', 'Baço aumentado muda orientação.'], [2, false, 'Bilirrubina direta alta com FA/GGT sugere padrão:', 'Colestático.', 'Nefrótico.', 'Vestibular.', 'Auditivo.', 'Colestase orienta via biliar.'], [2, true, 'Febre, icterícia e viagem a área de febre amarela sem vacina. Raciocínio?', 'Arbovirose/hepatite grave conforme contexto e notificação.', 'Cefaleia tensional.', 'OME.', 'Dermatite seborreica.', 'Epidemiologia guia suspeita.']],
    cards: [[2, 'Charcot = febre, icterícia e dor em {{c1::HCD}}.', 'HCD', 'Tríade de colangite.', 'colangite', ['cm5', 'ictericia']], [3, 'Reynolds adiciona hipotensão e {{c1::confusão}}.', 'confusão', 'Gravidade na colangite.', 'colangite', ['cm5', 'sepsis']], [2, 'Leptospirose lembra enchente e dor de {{c1::panturrilha}}.', 'panturrilha', 'Sufusão conjuntival e IRA reforçam.', 'lepto', ['cm5', 'infecto']], [2, 'LV = febre prolongada, esplenomegalia e {{c1::pancitopenia}}.', 'pancitopenia', 'Área endêmica importa.', 'lv', ['cm5', 'baço']], [2, 'Malária confirma com gota {{c1::espessa}}.', 'espessa', 'Ou teste rápido conforme cenário.', 'malaria', ['cm5', 'febre']], [2, 'Dengue grave envolve choque, sangramento ou {{c1::órgão}}.', 'órgão', 'Disfunção orgânica muda gravidade.', 'dengue', ['cm5', 'arbovirose']], [2, 'Adenopatia supraclavicular é red flag de {{c1::malignidade}}.', 'malignidade', 'Especialmente dura/fixa.', 'linfonodo', ['cm5', 'adenomegalia']], [2, 'Sintomas B = febre, sudorese noturna e {{c1::perda de peso}}.', 'perda de peso', 'Pista de linfoma/TB/HIV.', 'linfoma', ['cm5', 'b_symptoms']], [3, 'Evite {{c1::corticoide}} antes de biópsia em suspeita de linfoma estável.', 'corticoide', 'Pode apagar diagnóstico.', 'linfoma', ['cm5', 'biopsia']], [2, 'EBV pode causar esplenomegalia e risco de ruptura {{c1::esplênica}}.', 'esplênica', 'Evitar esporte de contato.', 'ebv', ['cm5', 'baço']], [2, 'FA/GGT e bilirrubina direta sugerem padrão {{c1::colestático}}.', 'colestático', 'Pensa via biliar.', 'ictericia', ['cm5', 'colestase']], [2, 'Epidemiologia é central em icterícia {{c1::febril}}.', 'febril', 'Viagem, enchente e área endêmica mudam tudo.', 'abordagem', ['cm5', 'febre']]],
    fontes: ['Ministério da Saúde. **Dengue: diagnóstico e manejo clínico**.', 'Ministério da Saúde. **Leptospirose - recomendações de conduta clínica**.', 'Ministério da Saúde. **Leishmaniose visceral grave**.', 'Tokyo Guidelines. **Acute cholangitis and cholecystitis**.', 'Harrison Medicina Interna, 21ª edição, capítulos de hepatologia e infectologia.'],
  },
  {
    aula: 'cm5_a21',
    title: 'Perda de Peso Não Intencional',
    ref: 'AAFP involuntary weight loss + NICE suspected cancer + Harrison 21ª ed. + Cecil-Goldman 26ª ed.',
    image: null,
    imageDecision: { usar_imagem: false, motivo: 'Perda de peso é algoritmo diagnóstico e red flags; imagem não acrescenta informação acionável.' },
    relevance: ['Perda de peso não intencional é aula de medicina interna completa. A prova quer que você confirme que a perda é real, meça gravidade e organize causas por mecanismo, sem pedir TC de corpo inteiro como reflexo.', '', 'O raciocínio precisa separar **baixa ingesta**, **aumento de gasto**, **má absorção**, **perdas**, **câncer**, **infecção crônica**, **endócrino**, **psiquiátrico**, **social** e **medicação**.', '', '> **Pegadinha de prova:** emagrecimento importante com exame inicial normal não autoriza abandono; mas também não obriga painel infinito sem pista. Seguimento é parte da investigação.'],
    case: ['**Ato 1 - Entrada:** idoso perdeu 8% do peso em 6 meses. A filha relata menos apetite, prótese dentária ruim e início de donepezila recente.', '', '**Ato 2 - Virada:** outro paciente perdeu peso com febre vespertina, sudorese noturna e linfonodo endurecido.', '', '**Ato 3 - Decisão:** o primeiro pede avaliação global e causas geriátricas/medicamentosas. O segundo tem red flags sistêmicas e precisa investigação dirigida.', '', '> **Moral da vinheta:** perda de peso é sinal, não diagnóstico. O contexto escolhe o caminho.'],
    sections: [
      ['Definição e Confirmação', ['Use definição prática: perda >5% em 6-12 meses ou >5 kg em 6 meses, principalmente se não intencional.', '', 'Confirme peso anterior, balança, edema, dieta, atividade física, medicamentos e intenção real. GLP-1, estimulantes, digoxina, metformina e polifarmácia podem contribuir.', '', '**Macete MedGradPlus - pese antes de caçar:** confirme o número antes de pedir uma bateria infinita.']],
      ['Mecanismos', [...table(['Mecanismo', 'Exemplos', 'Pista'], [['**Baixa ingesta**', 'depressão, demência, dentição', 'apetite baixo'], ['**Gasto aumentado**', 'câncer, hipertireoidismo, infecção', 'febre, taquicardia'], ['**Má absorção**', 'celíaca, DII, pancreática', 'diarreia/esteatorreia'], ['**Perdas**', 'DM, proteinúria, vômitos', 'poliúria, edema']]), '', 'Pensar por mecanismo evita lista caótica.']],
      ['Red Flags', ['Red flags: febre, sudorese noturna, linfonodo duro/fixo, anemia, sangramento, disfagia, alteração de hábito intestinal, dor persistente, tabagismo, HIV/TB, massa abdominal, hepatosplenomegalia e perda rápida.', '', '> **Armadilha de banca:** perda de peso com disfagia progressiva não é ansiedade até prova em contrário.']],
      ['Avaliação Inicial', ['História alimentar, medicações, álcool/drogas, humor, cognição, dentição, sintomas GI/respiratórios/endócrinos, exame de pele, cavidade oral, tireoide, linfonodos, mama, abdome, toque quando indicado.', '', 'Exames-base: hemograma, eletrólitos, renal/hepático, glicemia/HbA1c, TSH, PCR/VHS, urina, RX tórax, HIV/TB conforme contexto e rastreios oncológicos por idade/risco.', '', '**Macete MedGradPlus - básico bem feito vence painel aleatório:** hemograma, TSH, glicemia, inflamação e RX tórax encontram muita pista.']],
      ['Câncer, Infecção e Endócrino', ['Câncer GI, pulmão e hematológico são lembrados por anemia, sangramento, disfagia, alteração intestinal, tabagismo, linfonodos e sintomas B.', '', 'TB, HIV, endocardite e abscessos crônicos entram com febre, sudorese, exposição e inflamação. Hipertireoidismo e diabetes entram com polifagia, tremor, taquicardia, poliúria ou HbA1c alterada.', '', '> **Pérola Clínica:** perda com polifagia não tranquiliza. Pode ser diabetes ou hipertireoidismo.']],
      ['Idoso e Seguimento', ['No idoso, dentição, disfagia, depressão, demência, isolamento, insegurança alimentar e polifarmácia são causas reais, não diagnósticos de exclusão preguiçosos.', '', 'Se investigação inicial é negativa e paciente está estável, programe reavaliação em 3-6 meses, reponha nutrição, revise medicações e siga pistas novas. Se continua perdendo, suba investigação.', '', 'Não confunda seguimento estruturado com abandono. A diferença é data, peso, plano e retorno.']],
    ],
    key: ['Perda relevante é >5% em 6-12 meses.', 'Confirme peso real.', 'Separe por baixa ingesta, gasto, má absorção e perdas.', 'Medicamentos podem causar emagrecimento.', 'Disfagia progressiva é red flag.', 'Anemia e alteração intestinal sugerem GI.', 'Febre/sudorese sugerem infecção ou linfoma.', 'Polifagia com perda sugere DM/hipertireoidismo.', 'Idoso pede dentição, depressão, demência e social.', 'Exames iniciais devem ser dirigidos e básicos.', 'TC de corpo inteiro não é primeiro reflexo em todos.', 'Reavaliação documentada é conduta.'],
    quiz: [['Perda de peso relevante costuma ser:', '>5% em 6-12 meses', '1 kg em 5 anos sempre grave', 'Apenas IMC baixo', 'Somente relato sem confirmar', 'Percentual e tempo importam.'], ['Perda com polifagia sugere:', 'Diabetes ou hipertireoidismo', 'OME', 'VPPB', 'Psoríase apenas', 'Gasto/perda metabólica.'], ['Perda com disfagia progressiva sugere investigar:', 'Câncer de esôfago/obstrução', 'Rinite', 'Cefaleia', 'Tinea', 'Disfagia é red flag.'], ['Idoso com perda de peso exige avaliar:', 'Dentição, depressão, demência e remédios', 'Apenas TC de crânio', 'Só KOH', 'Dix-Hallpike', 'Causas geriátricas são comuns.'], ['Exame-base razoável inclui:', 'Hemograma, função renal/hepática, TSH, glicemia e RX tórax', 'Apenas audiometria', 'Somente fundo de olho', 'Nenhum exame', 'Básico guia próximos passos.'], ['Se inicial negativa e estável:', 'Seguimento com reavaliação de peso e pistas', 'Abandono', 'Corticoide empírico', 'Antibiótico mensal', 'Seguimento é conduta ativa.']],
    questions: [[1, false, 'Qual definição prática de perda de peso não intencional relevante?', 'Mais de 5% em 6-12 meses.', 'Qualquer 500 g em 10 anos.', 'Somente IMC < 18.', 'Apenas relato sem confirmar.', 'Percentual e tempo definem relevância.'], [2, true, 'Paciente perdeu peso com polifagia, tremor e taquicardia. Hipótese?', 'Hipertireoidismo.', 'OME.', 'VPPB.', 'Ceratite.', 'Gasto aumentado com sintomas tireoidianos.'], [2, true, 'Perda de peso com poliúria, polidipsia e HbA1c alta. Causa?', 'Diabetes mellitus.', 'Rinite alérgica.', 'CRVO.', 'Otite externa.', 'Glicosúria e catabolismo.'], [3, true, 'Perda de peso, disfagia progressiva e tabagismo. Próximo passo?', 'Investigar neoplasia esofágica/obstrução.', 'Aguardar 1 ano.', 'Tratar como ansiedade apenas.', 'Epley.', 'Disfagia progressiva é red flag.'], [2, true, 'Perda de peso, febre vespertina, sudorese noturna e tosse crônica. Investigar:', 'Tuberculose/HIV conforme contexto.', 'VPPB.', 'Psoríase inversa.', 'OME.', 'Sintomas constitucionais e tosse.'], [2, false, 'No idoso, causa comum e negligenciada de perda de peso:', 'Dentição ruim, depressão, demência e polifarmácia.', 'CRAO obrigatório.', 'Epley.', 'Rinite.', 'Geriatria muda investigação.'], [2, false, 'Exames iniciais razoáveis incluem:', 'Hemograma, função renal/hepática, glicemia/HbA1c, TSH e RX tórax.', 'Apenas TC de corpo inteiro.', 'Somente audiometria.', 'Dix-Hallpike.', 'Painel básico guia.'], [2, true, 'Perda de peso com anemia ferropriva e alteração de hábito intestinal. Investigar:', 'Câncer colorretal/doença GI.', 'Otite externa.', 'VPPB.', 'Rinite.', 'Anemia e intestino são red flags GI.'], [2, false, 'Albumina baixa, PCR alta e anemia sugerem:', 'Doença inflamatória/neoplásica ou infecção crônica.', 'Rinite simples.', 'OME.', 'Cefaleia tensional.', 'Marcadores sistêmicos preocupam.'], [2, false, 'TC de corpo inteiro na perda de peso deve ser:', 'Dirigida por pistas, não reflexo inicial universal.', 'Primeiro exame em todos sempre.', 'Proibida sempre.', 'Substitui história.', 'Investigação deve ser racional.'], [2, true, 'Paciente estável, investigação inicial negativa e peso parou de cair. Conduta?', 'Reavaliar em 3-6 meses com peso e novas pistas.', 'Abandonar sem plano.', 'Corticoide empírico.', 'Quimioterapia.', 'Seguimento estruturado é adequado.'], [2, false, 'Medicação que pode contribuir para perda de peso:', 'GLP-1 ou estimulantes, conforme contexto.', 'Qualquer antibiótico por 1 dia sempre.', 'Colírio lubrificante sempre.', 'Curativo.', 'Revisão medicamentosa é obrigatória.']],
    cards: [[1, 'Perda relevante é >{{c1::5%}} em 6-12 meses.', '5%', 'Definição prática.', 'definicao', ['cm5', 'peso']], [2, 'Confirme peso real antes de {{c1::investigar}} em excesso.', 'investigar', 'Balança e edema importam.', 'abordagem', ['cm5', 'peso']], [2, 'Perda com polifagia sugere DM ou {{c1::hipertireoidismo}}.', 'hipertireoidismo', 'Gasto/perda metabólica.', 'endocrino', ['cm5', 'peso']], [2, 'Disfagia progressiva com perda sugere câncer de {{c1::esôfago}}.', 'esôfago', 'Red flag GI.', 'cancer', ['cm5', 'disfagia']], [2, 'Febre e sudorese noturna são sintomas {{c1::B}}.', 'B', 'Linfoma/TB/HIV entram.', 'red_flag', ['cm5', 'peso']], [2, 'Idoso com perda pede avaliar dentição e {{c1::depressão}}.', 'depressão', 'Também demência e social.', 'geriatria', ['cm5', 'idoso']], [2, 'Exame inicial inclui hemograma, TSH e {{c1::glicemia}}.', 'glicemia', 'Baseia próximas etapas.', 'exames', ['cm5', 'peso']], [2, 'Perda + anemia ferropriva sugere trato {{c1::GI}}.', 'GI', 'Câncer colorretal é preocupação.', 'gi', ['cm5', 'anemia']], [2, 'GLP-1 pode causar perda de {{c1::peso}}.', 'peso', 'Revisar medicações.', 'medicacao', ['cm5', 'peso']], [2, 'Investigação negativa e estável pede {{c1::seguimento}} estruturado.', 'seguimento', 'Peso, retorno e novas pistas.', 'seguimento', ['cm5', 'peso']], [2, 'Cachexia não é só magreza; envolve inflamação e perda {{c1::muscular}}.', 'muscular', 'Prognóstico pior.', 'cachexia', ['cm5', 'peso']], [2, 'TC de corpo inteiro não substitui {{c1::história}} clínica.', 'história', 'Evita caça aleatória.', 'abordagem', ['cm5', 'peso']]],
    fontes: ['AAFP. **Unintentional Weight Loss in Older Adults**.', 'NICE. **Suspected cancer: recognition and referral NG12**.', 'Merck Manual Professional. **Involuntary Weight Loss**.', 'Harrison Medicina Interna, 21ª edição, capítulos de sintomas sistêmicos e oncologia.', 'Cecil-Goldman Medicine, 26ª edição, capítulos de abordagem clínica.'],
  },
];

function buildMaterial(lesson) {
  const lines = ['---', `aula_id: ${lesson.aula}`, 'materia: clinica_medica5', 'modulo: 5', `tema: ${lesson.title}`, 'versao_v3: 3.0.0', 'status: published_local', 'revisado_em: 2026-05-07', 'checksum_lint: pass_pending', '---', '', `# ${lesson.title}`, '', '**Disciplina:** Clínica Médica 5', `**Módulo:** 5 | **Referência principal:** ${lesson.ref}`, '**Tempo de estudo sugerido:** 30-40 min', '', '---', '', '## Relevância Clínica e Acadêmica', '', ...lesson.relevance, '', '---', '', '## Caso da Semana', '', ...lesson.case, '', '---', ''];
  for (const [title, body] of lesson.sections) lines.push(`## ${title}`, '', ...body, '', '---', '');
  lines.push('## Pontos-Chave', '');
  for (const k of lesson.key) lines.push(`- ${k}`);
  lines.push('', '---', '', '## Mini Quiz', '');
  lesson.quiz.forEach(([stem, correct, b, c, d, why], i) => lines.push(`**${i + 1}. ${stem}**`, '', `- [x] ${correct}`, `- [ ] ${b}`, `- [ ] ${c}`, `- [ ] ${d}`, '', `> **Explicação:** ${why}`, ''));
  lines.push('---', '', '## Pré-Prova', '', '### Síntese para a prova', '', `${lesson.title} é aula de reconhecimento de padrão e decisão inicial. A prova cobra a pista que muda diagnóstico, gravidade e encaminhamento, não uma lista infinita.`, '', '### Macete-âncora', '', '**Padrão primeiro, lista depois.**', '', '- Identifique morfologia ou síndrome.', '- Procure red flags.', '- Escolha exame simples que confirma.', '- Evite tratamento reflexo sem hipótese.', '- Reavalie se o curso não bate com a hipótese.', '', '### Erros que derrubam nota', '', '- Tratar todo quadro parecido do mesmo jeito.', '- Ignorar epidemiologia e distribuição.', '- Usar corticoide antes de excluir infecção/micose/linfoma quando isso importa.', '- Pedir exame caro sem pergunta clínica.', '- Não reconhecer sinal de urgência.', '', '---', '', '## Fontes', '');
  for (const fonte of lesson.fontes) lines.push(`- ${fonte}`);
  return lines.join('\n');
}
function updateMaterials() { for (const l of lessons) { const md = buildMaterial(l); writeText(`data/materiais/clinica_medica5/${l.aula}.md`, md); writeText(`materiais/modulo5/clinica_medica5/${l.aula}.md`, md); } }
function updateData() {
  const qData = readJson('data/questoes.json');
  let questoes = (qData.questoes || []).filter((x) => !String(x.origem || '').startsWith(MARKER));
  let maxQ = Math.max(0, ...questoes.map((x) => Number(x.id) || 0));
  const newQ = lessons.flatMap((l) => l.questions.map((item) => q(l.aula, item)));
  for (const item of newQ) item.id = ++maxQ;
  questoes.push(...newQ);
  writeJson('data/questoes.json', { ...qData, questoes });
  const fcData = readJson('data/flashcards.json');
  let flashcards = (fcData.flashcards || []).filter((x) => !String(x.origem || '').startsWith(MARKER));
  let maxFc = Math.max(0, ...flashcards.map((x) => Number(x.id) || 0));
  const newFc = lessons.flatMap((l) => l.cards.map((item) => fc(l.aula, item)));
  for (const item of newFc) item.id = ++maxFc;
  flashcards.push(...newFc);
  writeJson('data/flashcards.json', { ...fcData, flashcards });
}
function updateFigures() {
  const data = readJson('data/materiais_figuras.json');
  const ids = new Set(lessons.filter((l) => l.image).map((l) => l.image.id));
  const entries = (data.entries || []).filter((fig) => !ids.has(fig.id));
  for (const l of lessons) if (l.image) entries.push({ id: l.image.id, modulo: 5, disciplina: 'clinica_medica5', aula: l.aula, caminhoMaterial: `materiais/modulo5/clinica_medica5/${l.aula}.md`, momento: l.image.momento, descricaoVisual: l.image.descricaoVisual, tipoSugerido: 'Imagem Wikimedia Commons aprovada.', buscaCommonsEn: l.image.buscaEn, buscaCommonsPt: l.image.buscaPt, status: 'aprovada', urlImagem: l.image.urlImagem, urlThumbnail: l.image.urlThumbnail, urlPaginaCommons: l.image.urlPaginaCommons, licenca: l.image.licenca, credito: l.image.credito, legenda: l.image.legenda, notas: 'Figura incluída por relevância diagnóstica real, não por decoração.' });
  entries.sort((a, b) => String(a.id).localeCompare(String(b.id)));
  writeJson('data/materiais_figuras.json', { ...data, updatedAt: new Date().toISOString(), entries });
}
function updateRefs() {
  for (const l of lessons) writeJson(`data/refs/${l.aula}.refs.json`, { aula_id: l.aula, materia: 'clinica_medica5', tema: l.title, generatedAt: '2026-05-08T00:20:00.000Z', marker: `${MARKER}_${l.aula}`, image_decision: l.imageDecision, fontes_base: l.fontes.map((fonte) => ({ tipo: 'fonte', titulo: fonte.replace(/\*\*/g, ''), uso: 'base clínica e padrão de prova para material, questões e flashcards.' })) });
}

updateMaterials();
updateData();
updateFigures();
updateRefs();

console.log('CM5 a18-a21 atualizadas com materiais, essenciais, flashcards e imagens quando relevantes.');
