import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const AULA = 'cm5_a9';
const MARKER = 'cm5_quality_contract_2026_05_07_cm5_a9';

function p(rel) { return path.join(ROOT, rel); }
function readJson(rel) { return JSON.parse(fs.readFileSync(p(rel), 'utf8')); }
function writeJson(rel, data) { fs.mkdirSync(path.dirname(p(rel)), { recursive: true }); fs.writeFileSync(p(rel), `${JSON.stringify(data, null, 2)}\n`, 'utf8'); }
function writeText(rel, text) { fs.mkdirSync(path.dirname(p(rel)), { recursive: true }); fs.writeFileSync(p(rel), `${text.replace(/\r\n/g, '\n').replace(/\n*$/, '')}\n`, 'utf8'); }
function explanation(general, exp) { return [`Resumo: ${general}`, `A) ${exp.A}`, `B) ${exp.B}`, `C) ${exp.C}`, `D) ${exp.D}`].join('\n'); }
function q(dificuldade, caso_clinico, enunciado, opcoes, correta, general, exp) {
  return { materia: 'clinica_medica5', tema: AULA, aula_id: AULA, modulo: 5, dificuldade, caso_clinico, essencial: true, origem: MARKER, enunciado, opcoes, correta, explicacao_geral: general, explicacoes_opcoes: exp, explicacao: explanation(general, exp) };
}
function fc(dificuldade, frente, verso, explicacao, categoria, tags) {
  return { materia: 'clinica_medica5', tema: AULA, dificuldade, frente, verso, explicacao, origem: MARKER, categoria, tags };
}

function questions() {
  return [
    q(1, false, 'Qual definição é mais adequada para doença renal crônica?', ['A) Anormalidade de estrutura ou função renal por pelo menos 3 meses, com implicação para saúde.', 'B) Creatinina elevada em uma única coleta durante desidratação.', 'C) Qualquer edema de membros inferiores.', 'D) Urina escura por 24 horas após exercício.'], 0, 'DRC exige persistência por 3 meses e pode ser definida por eTFG baixa ou marcadores de lesão renal.', { A: 'CORRETA: é a definição KDIGO.', B: 'INCORRETA: pode ser injúria aguda/reversível.', C: 'INCORRETA: edema é inespecífico.', D: 'INCORRETA: achado transitório não fecha DRC.' }),
    q(2, false, 'Quais dois eixos são centrais para estadiar risco na DRC?', ['A) eTFG e albuminúria.', 'B) Hemoglobina e leucócitos.', 'C) IMC e temperatura.', 'D) Sódio e cloro isolados.'], 0, 'KDIGO usa causa, GFR e albuminúria. eTFG e albuminúria definem prognóstico e seguimento.', { A: 'CORRETA: são os eixos práticos.', B: 'INCORRETA: anemia importa, mas não estadia risco renal isoladamente.', C: 'INCORRETA: não são eixos KDIGO.', D: 'INCORRETA: eletrólitos isolados não classificam DRC.' }),
    q(2, true, 'Paciente com eTFG 48 mL/min/1,73 m2 e albuminúria 420 mg/g persistentes. Qual classificação é mais coerente?', ['A) DRC G3a A3.', 'B) DRC G1 A1 normal, sem risco.', 'C) Lesão renal aguda obrigatória.', 'D) Síndrome nefrótica sempre.'], 0, 'eTFG 45-59 é G3a; albuminúria >= 300 mg/g é A3. Persistência define DRC.', { A: 'CORRETA: classifica corretamente.', B: 'INCORRETA: eTFG e albuminúria alteradas.', C: 'INCORRETA: persistência por 3 meses fala DRC.', D: 'INCORRETA: síndrome nefrótica depende proteinúria maciça e outros achados.' }),
    q(2, false, 'Qual marcador deve ser pesquisado mesmo quando a creatinina parece pouco alterada?', ['A) Albuminúria.', 'B) Troponina em todo assintomático.', 'C) Amilase salivar.', 'D) TSH como marcador renal.'], 0, 'Albuminúria é marcador precoce e prognóstico de lesão renal e risco cardiovascular.', { A: 'CORRETA: muda risco e tratamento.', B: 'INCORRETA: troponina é contexto agudo.', C: 'INCORRETA: sem papel.', D: 'INCORRETA: TSH não substitui rim.' }),
    q(2, true, 'Paciente com DRC, DM2 e albuminúria persistente. Qual classe tem benefício cardiorrenal se eTFG permitir?', ['A) Inibidor de SGLT2.', 'B) AINE crônico.', 'C) Aminoglicosídeo profilático.', 'D) Corticoide para todos.'], 0, 'SGLT2i reduz progressão renal e eventos cardiovasculares em pacientes apropriados com DRC, inclusive por mecanismos além da glicemia.', { A: 'CORRETA: pilar moderno.', B: 'INCORRETA: AINE pode piorar rim.', C: 'INCORRETA: nefrotóxico.', D: 'INCORRETA: não é universal e pode fazer dano.' }),
    q(2, true, 'Após iniciar IECA em paciente com DRC albuminúrica, creatinina sobe discretamente e potássio fica normal. Qual conduta é mais adequada?', ['A) Reavaliar magnitude e manter se aumento aceitável, com monitorização.', 'B) Suspender sempre qualquer IECA na primeira elevação.', 'C) Dobrar AINE para proteger rim.', 'D) Ignorar potássio para sempre.'], 0, 'Bloqueio do SRAA pode causar queda inicial esperada da eTFG. Suspensão depende de magnitude, hipercalemia, hipotensão e contexto.', { A: 'CORRETA: é o raciocínio seguro.', B: 'INCORRETA: suspender automaticamente remove benefício.', C: 'INCORRETA: AINE piora hemodinâmica renal.', D: 'INCORRETA: potássio deve ser monitorado.' }),
    q(2, false, 'Qual meta terapêutica é central para retardar progressão da DRC?', ['A) Controle de PA, albuminúria, diabetes quando presente e evitar nefrotóxicos.', 'B) Hidratação excessiva universal sem limites.', 'C) Repouso absoluto permanente.', 'D) Antibiótico mensal preventivo.'], 0, 'Progressão da DRC reduz com controle pressórico, bloqueio SRAA quando indicado, SGLT2i em perfis adequados, controle metabólico e evitar dano adicional.', { A: 'CORRETA: combina pilares reais.', B: 'INCORRETA: pode causar congestão.', C: 'INCORRETA: exercício seguro é benéfico.', D: 'INCORRETA: não é prevenção de DRC.' }),
    q(3, true, 'Paciente com DRC G4, dispneia, edema, K+ 6,6, acidose e ECG com alterações. Qual prioridade é correta?', ['A) Tratar hipercalemia grave imediatamente e avaliar necessidade de diálise.', 'B) Aguardar consulta anual sem intervenção.', 'C) Dar suplemento de potássio.', 'D) Iniciar AINE para dor lombar.'], 0, 'Hipercalemia com alteração de ECG é emergência. DRC avançada com distúrbios refratários pode exigir terapia renal substitutiva.', { A: 'CORRETA: estabilizar membrana e reduzir potássio é prioridade.', B: 'INCORRETA: há risco de arritmia/morte.', C: 'INCORRETA: piora hipercalemia.', D: 'INCORRETA: AINE piora rim e potássio.' }),
    q(2, false, 'Qual complicação metabólica é comum na DRC avançada?', ['A) Acidose metabólica.', 'B) Hipercalcemia obrigatória em todos.', 'C) Alcalose respiratória isolada permanente.', 'D) Hipoglicemia como critério diagnóstico universal.'], 0, 'DRC reduz excreção ácida, favorecendo acidose metabólica, além de distúrbios de K, fósforo, PTH e anemia.', { A: 'CORRETA: é comum em DRC avançada.', B: 'INCORRETA: distúrbios de cálcio variam.', C: 'INCORRETA: não é padrão universal.', D: 'INCORRETA: pode ocorrer, mas não define DRC.' }),
    q(2, false, 'Qual mecanismo explica anemia da DRC?', ['A) Deficiência relativa de eritropoetina e inflamação/ferro funcional.', 'B) Excesso de eritropoetina.', 'C) Hemorragia obrigatória em todo paciente.', 'D) Aumento de T3 por tireotoxicose.'], 0, 'O rim produz eritropoetina; DRC reduz estímulo eritropoiético e inflamação altera ferro.', { A: 'CORRETA: é o mecanismo central.', B: 'INCORRETA: é deficiência, não excesso.', C: 'INCORRETA: sangramento pode coexistir, mas não é obrigatório.', D: 'INCORRETA: tireoide não é mecanismo principal.' }),
    q(2, true, 'Paciente com eTFG em queda rápida, albuminúria A3, hematúria dismórfica e hipertensão resistente. Qual decisão é mais adequada?', ['A) Encaminhar precocemente à nefrologia.', 'B) Tratar como envelhecimento normal.', 'C) Aguardar 5 anos para repetir exames.', 'D) Suspender todos os anti-hipertensivos.'], 0, 'Red flags como queda rápida de eTFG, A3, hematúria glomerular e HAS resistente indicam avaliação especializada.', { A: 'CORRETA: risco alto e possível glomerulopatia.', B: 'INCORRETA: não é envelhecimento normal.', C: 'INCORRETA: atraso pode perder janela terapêutica.', D: 'INCORRETA: PA deve ser controlada.' }),
    q(2, false, 'Qual frase sobre creatinina é correta?', ['A) Creatinina isolada pode parecer normal em baixa massa muscular; eTFG e contexto são necessários.', 'B) Creatinina normal sempre exclui DRC.', 'C) Creatinina não sofre influência de músculo.', 'D) eTFG nunca deve ser calculada.'], 0, 'Creatinina depende de massa muscular, dieta e secreção tubular; eTFG melhora a interpretação, e cistatina C pode ajudar em situações selecionadas.', { A: 'CORRETA: evita falso conforto.', B: 'INCORRETA: albuminúria ou baixa massa muscular podem mascarar.', C: 'INCORRETA: massa muscular influencia muito.', D: 'INCORRETA: eTFG é central.' }),
  ];
}

function cards() {
  return [
    fc(1, 'DRC exige alteração renal por pelo menos {{c1::3 meses}}.', '3 meses', 'Sem persistência, pense em injúria aguda ou alteração transitória.', 'conceito', ['cm5', 'drc']),
    fc(1, 'Classificação de risco na DRC combina eTFG e {{c1::albuminúria}}.', 'Albuminúria', 'Albuminúria muda prognóstico mesmo com creatinina pouco alterada.', 'classificacao', ['cm5', 'drc', 'albuminuria']),
    fc(2, 'eTFG 45-59 mL/min/1,73 m2 corresponde a G{{c1::3a}}.', '3a', 'G3a é perda moderada leve/moderada, depende também de albuminúria.', 'classificacao', ['cm5', 'drc', 'gfr']),
    fc(2, 'Albuminúria >= 300 mg/g corresponde a A{{c1::3}}.', '3', 'A3 indica alto risco renal e cardiovascular.', 'classificacao', ['cm5', 'drc', 'a3']),
    fc(2, 'DRC diabética albuminúrica favorece {{c1::SGLT2i}} se eTFG permitir.', 'SGLT2i', 'Benefício cardiorrenal além da HbA1c.', 'tratamento', ['cm5', 'drc', 'sglt2']),
    fc(2, 'IECA/BRA pode causar queda inicial esperada de {{c1::eTFG}}.', 'eTFG', 'Monitorar creatinina e potássio; não suspender automaticamente.', 'tratamento', ['cm5', 'drc', 'sraa']),
    fc(2, 'Evitar {{c1::AINE}} é medida prática para proteger rim em DRC.', 'AINE', 'AINE reduz prostaglandina renal, piora perfusão e pode subir K.', 'nefrotoxico', ['cm5', 'drc', 'aine']),
    fc(3, 'Hipercalemia com alteração de ECG exige {{c1::tratamento imediato}}.', 'Tratamento imediato', 'Cálcio IV estabiliza membrana quando indicado; depois deslocar/remover K.', 'emergencia', ['cm5', 'hipercalemia']),
    fc(2, 'Anemia da DRC ocorre por deficiência relativa de {{c1::eritropoetina}}.', 'Eritropoetina', 'Também há inflamação e distúrbio de ferro funcional.', 'complicacoes', ['cm5', 'drc', 'anemia']),
    fc(2, 'DRC avançada favorece acidose {{c1::metabólica}}.', 'Metabólica', 'Rim perde capacidade de excretar carga ácida.', 'complicacoes', ['cm5', 'drc', 'acidose']),
    fc(2, 'Hematúria glomerular, A3 e queda rápida de eTFG são red flags para {{c1::nefrologia}}.', 'Nefrologia', 'Pode haver glomerulopatia tratável.', 'encaminhamento', ['cm5', 'drc', 'nefrologia']),
    fc(2, 'Creatinina isolada pode enganar em paciente com baixa {{c1::massa muscular}}.', 'Massa muscular', 'Use eTFG, albuminúria e contexto; cistatina C pode ajudar.', 'diagnostico', ['cm5', 'drc', 'creatinina']),
  ];
}

function material() {
  return [
    '---',
    'aula_id: cm5_a9',
    'materia: clinica_medica5',
    'modulo: 5',
    'tema: Doença Renal Crônica',
    'versao_v3: 3.0.0',
    'status: published_local',
    'revisado_em: 2026-05-07',
    'checksum_lint: pass_pending',
    '---',
    '',
    '# Doença Renal Crônica',
    '',
    '**Disciplina:** Clínica Médica 5',
    '**Módulo:** 5 | **Referência principal:** KDIGO 2024 + KDIGO Diabetes CKD + Harrison 21ª ed. + Cecil-Goldman 26ª ed.',
    '**Tempo de estudo sugerido:** 25-35 min',
    '',
    '---',
    '',
    '## Relevância Clínica e Acadêmica',
    '',
    'Doença renal crônica é onde o aluno costuma errar por olhar só creatinina. A prova quer que você use **tempo**, **eTFG**, **albuminúria**, **risco de progressão** e **complicações**.',
    '',
    'DRC também é cardiologia disfarçada: albuminúria prediz evento cardiovascular, SGLT2i e IECA/BRA protegem rim e coração, e hipercalemia pode matar antes da próxima consulta.',
    '',
    '> **Pegadinha de prova:** creatinina normal não exclui DRC. Um idoso sarcopênico pode ter creatinina aparentemente tranquila com eTFG ruim, e um paciente com albuminúria A3 já tem risco mesmo com eTFG preservada.',
    '',
    '---',
    '',
    '## Caso da Semana',
    '',
    '**Ato 1 - Entrada:** homem de 61 anos, DM2 e HAS, chega com creatinina 1,4 mg/dL. O aluno diz que "não parece tão alto". A eTFG calculada é 48 e a relação albumina/creatinina urinária é 520 mg/g.',
    '',
    '**Ato 2 - Virada:** três meses depois, os achados persistem. Ele usa ibuprofeno quase diariamente para dor lombar e nunca teve albuminúria discutida no consultório.',
    '',
    '**Ato 3 - Decisão:** agora não é "creatinina levemente alta". É DRC G3a A3, com alto risco renal e cardiovascular. A conduta é bloquear progressão, retirar nefrotóxico, controlar PA/DM e considerar SGLT2i se elegível.',
    '',
    '> **Moral da vinheta:** DRC se enxerga com lente de risco, não com olhômetro de creatinina.',
    '',
    '---',
    '',
    '## Definição',
    '',
    'DRC é anormalidade de estrutura ou função renal por **pelo menos 3 meses**, com implicação para saúde.',
    '',
    'Pode ser definida por:',
    '',
    '- eTFG < 60 mL/min/1,73 m2 persistente.',
    '- Albuminúria persistente.',
    '- Alterações urinárias persistentes, como hematúria glomerular.',
    '- Alteração estrutural em imagem.',
    '- História de transplante renal.',
    '',
    '**Macete MedGradPlus - três meses ou três perguntas:** é rim crônico? tem eTFG? tem albuminúria? Se você não respondeu isso, ainda não classificou DRC.',
    '',
    '---',
    '',
    '## Classificação KDIGO',
    '',
    'A lógica é CGA: causa, GFR e albuminúria.',
    '',
    '| Categoria G | eTFG | Tradução |',
    '|---|---|---|',
    '| **G1** | >= 90 | normal/alta com marcador de lesão |',
    '| **G2** | 60-89 | leve redução com marcador de lesão |',
    '| **G3a** | 45-59 | redução leve a moderada |',
    '| **G3b** | 30-44 | redução moderada a grave |',
    '| **G4** | 15-29 | grave |',
    '| **G5** | < 15 | falência renal |',
    '',
    '| Categoria A | Albumina/creatinina | Risco |',
    '|---|---|---|',
    '| **A1** | < 30 mg/g | normal a levemente aumentada |',
    '| **A2** | 30-300 mg/g | moderadamente aumentada |',
    '| **A3** | > 300 mg/g | gravemente aumentada |',
    '',
    'Quanto pior G e pior A, maior risco de progressão, evento cardiovascular e necessidade de seguimento estreito.',
    '',
    '---',
    '',
    '## Albuminúria',
    '',
    'Albuminúria é mais que "proteína na urina". Ela indica dano glomerular/endotelial e risco cardiovascular.',
    '',
    'Como usar:',
    '',
    '- Preferir relação albumina/creatinina urinária em amostra isolada.',
    '- Confirmar persistência.',
    '- Interpretar com febre, exercício, infecção urinária e menstruação.',
    '- Usar para guiar bloqueio SRAA, SGLT2i e intensidade de seguimento.',
    '',
    '> **Armadilha de banca:** EAS sem proteína não substitui albuminúria quantitativa em paciente diabético ou hipertenso de risco.',
    '',
    '---',
    '',
    '## Causas Comuns',
    '',
    '| Causa | Pista |',
    '|---|---|',
    '| **Diabetes** | albuminúria, retinopatia, longa duração |',
    '| **Hipertensão** | HAS longa, HVE, albuminúria menor |',
    '| **Glomerulopatias** | hematúria dismórfica, cilindros, proteinúria |',
    '| **Rim policístico** | rins aumentados, história familiar |',
    '| **Nefropatia por droga** | AINE, lítio, contraste, aminoglicosídeo |',
    '| **Uropatia obstrutiva** | jato fraco, hidronefrose, próstata |',
    '',
    'Nem toda DRC em diabético é "do diabetes". Hematúria glomerular, queda rápida de eTFG, ausência de retinopatia ou proteinúria abrupta pedem olhar alternativo.',
    '',
    '---',
    '',
    '## Tratamento para Retardar Progressão',
    '',
    'Pilares:',
    '',
    '- Controle pressórico.',
    '- IECA/BRA quando albuminúria e perfil indicam.',
    '- SGLT2i em pacientes elegíveis.',
    '- Controle glicêmico individualizado no diabetes.',
    '- Reduzir sal.',
    '- Evitar AINE e nefrotóxicos.',
    '- Tratar obesidade, tabagismo e risco cardiovascular.',
    '- Ajustar dose de fármacos pela eTFG.',
    '',
    '**Macete MedGradPlus - DRC não é só rim:** quem tem albuminúria também tem artéria doente. O tratamento mira rim e coração ao mesmo tempo.',
    '',
    '---',
    '',
    '## IECA/BRA e SGLT2i',
    '',
    '| Classe | Benefício | Cuidado |',
    '|---|---|---|',
    '| **IECA/BRA** | reduz pressão intraglomerular e albuminúria | creatinina e potássio |',
    '| **SGLT2i** | reduz progressão renal e IC | eTFG, volume, infecção genital, pausa em doença aguda |',
    '| **Finerenona** | selecionados com DM2/albuminúria | potássio e acesso |',
    '| **GLP-1 RA** | risco CV e peso em DM2 | GI, custo, perfil |',
    '',
    'Queda inicial de eTFG após IECA/BRA ou SGLT2i pode ser hemodinâmica e esperada. O erro é suspender automaticamente sem avaliar magnitude, potássio, hipotensão, desidratação ou estenose renal.',
    '',
    '---',
    '',
    '## Complicações da DRC',
    '',
    '| Complicação | Mecanismo | Conduta geral |',
    '|---|---|---|',
    '| **Anemia** | EPO baixa, inflamação, ferro funcional | investigar ferro e causas associadas |',
    '| **Acidose metabólica** | menor excreção ácida | bicarbonato em selecionados |',
    '| **Hipercalemia** | menor excreção, SRAA, dieta/drogas | dieta, drogas, resinas, emergência se ECG |',
    '| **DRC-MBD** | fósforo, cálcio, PTH, vitamina D | monitorar e tratar conforme estágio |',
    '| **Sobrecarga volêmica** | sódio/água | diurético, sal, diálise se refratário |',
    '',
    '> **Pérola Clínica:** hipercalemia com ECG alterado é emergência elétrica, não "resultado para repetir amanhã".',
    '',
    '---',
    '',
    '## Quando Encaminhar à Nefrologia',
    '',
    'Red flags:',
    '',
    '- eTFG < 30.',
    '- Queda rápida de eTFG.',
    '- Albuminúria A3 persistente.',
    '- Hematúria glomerular ou cilindros.',
    '- Hipertensão resistente.',
    '- Hipercalemia recorrente.',
    '- Suspeita de glomerulonefrite.',
    '- DRC hereditária ou rins policísticos.',
    '- Necessidade de preparar terapia renal substitutiva.',
    '',
    'Encaminhar não é desistir do paciente. É preservar janela de diagnóstico, proteção renal e preparação para diálise/transplante quando necessário.',
    '',
    '---',
    '',
    '## Preparo para Terapia Renal Substitutiva',
    '',
    'Quando DRC avança, o cuidado passa a incluir educação e planejamento:',
    '',
    '- Hemodiálise.',
    '- Diálise peritoneal.',
    '- Transplante renal.',
    '- Tratamento conservador em pacientes selecionados.',
    '',
    'O pior cenário é começar hemodiálise por cateter em urgência sem conversa prévia. Planejamento reduz complicação e sofrimento.',
    '',
    '---',
    '',
    '## Pontos-Chave',
    '',
    '- DRC exige persistência por 3 meses.',
    '- Classifique por causa, eTFG e albuminúria.',
    '- Albuminúria muda risco e tratamento.',
    '- Creatinina isolada engana em baixa massa muscular.',
    '- DM e HAS são causas comuns, mas não explicam tudo.',
    '- IECA/BRA protege em albuminúria, com monitorização.',
    '- SGLT2i é pilar moderno em DRC elegível.',
    '- AINE é inimigo frequente do rim crônico.',
    '- Hipercalemia com ECG é emergência.',
    '- Anemia, acidose e DRC-MBD são complicações esperadas.',
    '- A3, queda rápida e hematúria glomerular pedem nefrologia.',
    '- DRC é risco cardiovascular alto.',
    '',
    '---',
    '',
    '## Mini Quiz',
    '',
    '**1. DRC exige alteração renal por quanto tempo?**',
    '',
    '- [x] Pelo menos 3 meses',
    '- [ ] 24 horas',
    '- [ ] 48 horas',
    '- [ ] Apenas uma coleta',
    '',
    '> **Explicação:** persistência separa DRC de alteração aguda/transitória.',
    '',
    '**2. Quais eixos classificam risco na DRC?**',
    '',
    '- [x] eTFG e albuminúria',
    '- [ ] Temperatura e IMC',
    '- [ ] Leucócitos e plaquetas',
    '- [ ] TSH e T4',
    '',
    '> **Explicação:** KDIGO usa causa, GFR e albuminúria.',
    '',
    '**3. Albuminúria >= 300 mg/g corresponde a qual categoria?**',
    '',
    '- [x] A3',
    '- [ ] A1',
    '- [ ] G1',
    '- [ ] G5',
    '',
    '> **Explicação:** A3 é albuminúria gravemente aumentada.',
    '',
    '**4. Qual droga deve ser evitada como rotina em DRC por nefrotoxicidade?**',
    '',
    '- [x] AINE',
    '- [ ] IECA sempre',
    '- [ ] SGLT2i sempre',
    '- [ ] Estatina sempre',
    '',
    '> **Explicação:** AINE reduz perfusão renal e pode precipitar piora e hipercalemia.',
    '',
    '**5. Hipercalemia com alteração de ECG exige:**',
    '',
    '- [x] Tratamento imediato',
    '- [ ] Repetir em um ano',
    '- [ ] Suplementar potássio',
    '- [ ] Ignorar se assintomático',
    '',
    '> **Explicação:** risco é arritmia fatal.',
    '',
    '**6. Creatinina isolada pode enganar principalmente em quem?**',
    '',
    '- [x] Paciente com baixa massa muscular',
    '- [ ] Atleta com muita massa sempre sem risco',
    '- [ ] Pessoa febril apenas',
    '- [ ] Todo paciente com TSH alto',
    '',
    '> **Explicação:** menos músculo pode produzir menos creatinina, mascarando eTFG ruim.',
    '',
    '---',
    '',
    '## Pré-Prova',
    '',
    '### Síntese para a prova',
    '',
    'DRC é alteração renal por pelo menos 3 meses. Não classifique por creatinina solta: use eTFG e albuminúria. A3 e queda rápida mudam risco. Tratamento mira pressão, albuminúria, diabetes, SGLT2i/IECA/BRA quando indicados, evitar AINE e tratar complicações. Hipercalemia com ECG é emergência.',
    '',
    '### Macete-âncora',
    '',
    '**DRC = tempo + filtro + vazamento.**',
    '',
    '- Tempo: 3 meses.',
    '- Filtro: eTFG.',
    '- Vazamento: albuminúria.',
    '- Proteção: PA, SRAA, SGLT2i, sem AINE.',
    '- Perigo: hipercalemia, acidose, volume, queda rápida.',
    '',
    '### Erros que derrubam nota',
    '',
    '- Diagnosticar DRC por uma creatinina isolada.',
    '- Esquecer albuminúria em diabético/hipertenso.',
    '- Suspender IECA/BRA/SGLT2i por qualquer queda inicial de eTFG.',
    '- Prescrever AINE crônico.',
    '- Não encaminhar A3 com hematúria glomerular.',
    '- Subestimar hipercalemia com ECG.',
    '',
    '---',
    '',
    '## Fontes',
    '',
    '- KDIGO. **2024 Clinical Practice Guideline for the Evaluation and Management of Chronic Kidney Disease**.',
    '- KDIGO. **Diabetes Management in Chronic Kidney Disease**.',
    '- KDIGO. **Blood Pressure in CKD** guideline.',
    '- Harrison Medicina Interna, 21ª edição, capítulos de doença renal crônica.',
    '- Cecil-Goldman Medicine, 26ª edição, capítulos de nefrologia clínica.',
  ].join('\n');
}

function updateFiles() { const md = material(); writeText('data/materiais/clinica_medica5/cm5_a9.md', md); writeText('materiais/modulo5/clinica_medica5/cm5_a9.md', md); }
function updateData() {
  const qData = readJson('data/questoes.json');
  let questoes = (qData.questoes || []).filter((item) => item.origem !== MARKER);
  const novos = questions();
  let maxQ = Math.max(0, ...questoes.map((item) => Number(item.id) || 0));
  for (const item of novos) item.id = ++maxQ;
  questoes.push(...novos);
  writeJson('data/questoes.json', { ...qData, questoes });

  const fcData = readJson('data/flashcards.json');
  let flashcards = (fcData.flashcards || []).filter((item) => item.origem !== MARKER);
  const novosCards = cards();
  let maxFc = Math.max(0, ...flashcards.map((item) => Number(item.id) || 0));
  for (const item of novosCards) item.id = ++maxFc;
  flashcards.push(...novosCards);
  writeJson('data/flashcards.json', { ...fcData, flashcards });
}
function updateRefs() {
  writeJson('data/refs/cm5_a9.refs.json', {
    aula_id: AULA,
    materia: 'clinica_medica5',
    tema: 'Doença Renal Crônica',
    generatedAt: '2026-05-07T20:25:00.000Z',
    marker: MARKER,
    image_decision: { usar_imagem: false, motivo: 'Mapa GFR/albuminúria é melhor como tabela própria; imagem Wikimedia não agregaria precisão didática.' },
    fontes_base: [
      { tipo: 'diretriz', titulo: 'KDIGO 2024 CKD Evaluation and Management', url: 'https://kdigo.org/guidelines/ckd-evaluation-and-management/kdigo-2024-ckd-guideline-executive-summary/', uso: 'definição, classificação CGA, risco e encaminhamento.' },
      { tipo: 'diretriz', titulo: 'KDIGO Diabetes in CKD', url: 'https://kdigo.org/guidelines/diabetes-ckd/', uso: 'SGLT2i e manejo cardiorrenal.' },
      { tipo: 'diretriz', titulo: 'KDIGO Blood Pressure in CKD', url: 'https://kdigo.org/guidelines/blood-pressure-in-ckd/', uso: 'PA, albuminúria e bloqueio SRAA.' },
    ],
  });
}

updateFiles();
updateData();
updateRefs();

console.log('CM5 a9 atualizada com material, essenciais e flashcards.');
