import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const MARKER = 'cm5_quality_contract_2026_05_07_cm5_a3';

function p(rel) { return path.join(ROOT, rel); }
function readJson(rel) { return JSON.parse(fs.readFileSync(p(rel), 'utf8')); }
function writeJson(rel, data) { fs.writeFileSync(p(rel), `${JSON.stringify(data, null, 2)}\n`, 'utf8'); }
function writeText(rel, text) {
  fs.mkdirSync(path.dirname(p(rel)), { recursive: true });
  fs.writeFileSync(p(rel), `${text.replace(/\r\n/g, '\n').replace(/\n*$/, '')}\n`, 'utf8');
}

function explanation(general, exp) {
  return [`Resumo: ${general}`, `A) ${exp.A}`, `B) ${exp.B}`, `C) ${exp.C}`, `D) ${exp.D}`].join('\n');
}

function q(dificuldade, caso, enunciado, opcoes, correta, general, exp) {
  return {
    materia: 'clinica_medica5',
    tema: 'cm5_a3',
    aula_id: 'cm5_a3',
    modulo: 5,
    dificuldade,
    caso_clinico: caso,
    essencial: true,
    origem: MARKER,
    enunciado,
    opcoes,
    correta,
    explicacao_geral: general,
    explicacoes_opcoes: exp,
    explicacao: explanation(general, exp),
  };
}

function fc(dificuldade, frente, verso, explicacao, categoria, tags) {
  return { materia: 'clinica_medica5', tema: 'cm5_a3', dificuldade, frente, verso, explicacao, origem: MARKER, categoria, tags };
}

function questions() {
  return [
    q(1, false, 'Qual definição descreve melhor insuficiência cardíaca?', ['A) Síndrome clínica por incapacidade cardíaca de suprir demanda ou fazê-lo apenas com pressões de enchimento elevadas.', 'B) Doença exclusiva de fração de ejeção reduzida.', 'C) Diagnóstico feito apenas por edema de membros inferiores.', 'D) Sinônimo obrigatório de infarto agudo do miocárdio.'], 0, 'Insuficiência cardíaca é síndrome clínica, não apenas número de ecocardiograma. Pode ocorrer com fração reduzida, levemente reduzida ou preservada.', { A: 'CORRETA: resume a fisiopatologia central de baixo débito e/ou congestão por pressão de enchimento elevada.', B: 'INCORRETA: IC também ocorre com fração preservada.', C: 'INCORRETA: edema é inespecífico e isolado não fecha IC.', D: 'INCORRETA: IAM é causa possível, não sinônimo.' }),
    q(2, false, 'Paciente com FEVE de 32% e sintomas aos esforços habituais tem qual fenótipo principal?', ['A) IC com fração de ejeção reduzida.', 'B) IC com fração de ejeção preservada.', 'C) IC de alto débito por definição.', 'D) Apenas dispneia funcional sem doença cardíaca.'], 0, 'FEVE menor ou igual a 40% caracteriza HFrEF/ICFER na classificação moderna.', { A: 'CORRETA: FEVE de 32% define fenótipo de fração reduzida.', B: 'INCORRETA: preservada exige FEVE alta, usualmente >= 50%, com evidência de IC.', C: 'INCORRETA: alto débito é etiologia específica, não definida pela FEVE baixa.', D: 'INCORRETA: FEVE reduzida com sintomas aponta doença estrutural.' }),
    q(2, false, 'Qual quarteto farmacológico é base modificadora de prognóstico na IC com fração de ejeção reduzida, se tolerado?', ['A) ARNI ou IECA/BRA, betabloqueador validado, antagonista mineralocorticoide e inibidor de SGLT2.', 'B) Diurético de alça, digoxina, nitrato sublingual e clonidina.', 'C) AAS, estatina, antibiótico e broncodilatador.', 'D) Bloqueador de canal de cálcio não diidropiridínico, alfa-bloqueador, AINE e corticoide.'], 0, 'Diretrizes AHA/ACC/HFSA e ESC consolidam quatro pilares para HFrEF: bloqueio neuro-hormonal e SGLT2, além de diurético para sintomas congestivos.', { A: 'CORRETA: é o núcleo de terapia modificadora de desfecho em HFrEF.', B: 'INCORRETA: diurético melhora congestão, mas não substitui os quatro pilares.', C: 'INCORRETA: pode tratar comorbidades, não HFrEF como base.', D: 'INCORRETA: alguns desses podem piorar IC ou não são base terapêutica.' }),
    q(3, true, 'Homem de 68 anos com IC conhecida chega dispneico, ortopneico, estertores, turgência jugular e extremidades quentes. PA 148x86. Qual perfil hemodinâmico e primeira prioridade terapêutica são mais coerentes?', ['A) Quente e úmido; diurético de alça intravenoso e ajuste de congestão.', 'B) Frio e seco; volume agressivo com soro fisiológico.', 'C) Quente e seco; suspender todos os diuréticos por 30 dias.', 'D) Frio e úmido; iniciar betabloqueador em dose alta imediatamente.'], 0, 'Congestão com perfusão preservada é perfil quente e úmido. O manejo inicial mira descongestão.', { A: 'CORRETA: quente = perfundido; úmido = congesto.', B: 'INCORRETA: não há sinais de hipovolemia.', C: 'INCORRETA: o problema é congestão ativa.', D: 'INCORRETA: betabloqueador em dose alta no descompensado pode piorar perfusão.' }),
    q(2, true, 'Mulher com dispneia progressiva, BNP elevado e ecocardiograma com FEVE 58%, hipertrofia ventricular esquerda e aumento de átrio esquerdo. Qual interpretação evita erro comum?', ['A) IC com fração preservada é possível se houver sintomas, peptídeo natriurético e evidência estrutural/diastólica.', 'B) IC é impossível se a FEVE for maior que 50%.', 'C) BNP elevado exclui doença cardíaca.', 'D) Aumento de átrio esquerdo confirma embolia pulmonar como única hipótese.'], 0, 'HFpEF exige integração clínica, biomarcador e evidência estrutural/funcional. FEVE preservada não exclui IC.', { A: 'CORRETA: é a lógica diagnóstica correta para HFpEF.', B: 'INCORRETA: essa é a armadilha clássica.', C: 'INCORRETA: BNP elevado apoia estresse cardíaco, embora não seja exclusivo.', D: 'INCORRETA: átrio esquerdo aumentado sugere pressão de enchimento crônica.' }),
    q(2, false, 'Qual marcador laboratorial é mais útil para apoiar ou afastar IC em paciente com dispneia inespecífica, respeitando contexto clínico?', ['A) BNP ou NT-proBNP.', 'B) TSH isolado como exame confirmatório universal.', 'C) D-dímero como marcador específico de IC.', 'D) Hemoglobina glicada como substituto do ecocardiograma.'], 0, 'Peptídeos natriuréticos ajudam muito no diagnóstico diferencial de dispneia; valores baixos têm bom valor para afastar IC em muitos contextos.', { A: 'CORRETA: BNP/NT-proBNP refletem estresse de parede ventricular.', B: 'INCORRETA: TSH avalia causa/contribuinte, não confirma IC universalmente.', C: 'INCORRETA: D-dímero é inespecífico e mais usado para TEP em contexto apropriado.', D: 'INCORRETA: HbA1c avalia diabetes, não estrutura cardíaca.' }),
    q(2, true, 'Paciente com HFrEF está euvolêmico, PA 118x72, K+ 4,4 e TFG 52. Usa IECA e betabloqueador. Qual acréscimo tem racional prognóstico se não houver contraindicação?', ['A) Espironolactona ou eplerenona.', 'B) AINE crônico para reduzir ativação inflamatória.', 'C) Verapamil para aumentar força de contração.', 'D) Suspender betabloqueador estável por ser sempre proibido em IC.'], 0, 'Antagonista mineralocorticoide reduz morbimortalidade em HFrEF sintomática, com monitorização de potássio e função renal.', { A: 'CORRETA: MRA é um dos pilares quando TFG e potássio permitem.', B: 'INCORRETA: AINE pode reter sódio, piorar rim e descompensar IC.', C: 'INCORRETA: verapamil/diltiazem podem piorar HFrEF.', D: 'INCORRETA: betabloqueadores validados reduzem mortalidade quando paciente está estável.' }),
    q(3, true, 'Homem com HFrEF usa carvedilol e sacubitril/valsartana. Chega em choque, pele fria, confuso, PAS 78 mmHg e lactato elevado. Qual atitude é mais segura?', ['A) Manter todas as medicações em dose plena sem avaliar perfusão.', 'B) Reconhecer perfil frio com hipoperfusão e tratar como descompensação grave, ajustando temporariamente drogas que pioram choque.', 'C) Dobrar betabloqueador para controlar frequência antes de estabilizar.', 'D) Dar alta porque IC crônica sempre dispensa internação.'], 1, 'Hipoperfusão muda prioridade. Em choque, estabilização hemodinâmica vem antes de otimização ambulatorial de neuro-hormonal.', { A: 'INCORRETA: dose plena pode ser insegura no choque.', B: 'CORRETA: frio = hipoperfundido; precisa manejo monitorizado.', C: 'INCORRETA: betabloqueio pode piorar choque.', D: 'INCORRETA: sinais de choque indicam gravidade.' }),
    q(2, false, 'Qual betabloqueador tem evidência clássica em HFrEF?', ['A) Carvedilol.', 'B) Atenolol como escolha preferencial universal.', 'C) Propranolol em qualquer dose e cenário.', 'D) Sotalol para todos os pacientes com FEVE reduzida.'], 0, 'Carvedilol, metoprolol succinato e bisoprolol são betabloqueadores consagrados em HFrEF.', { A: 'CORRETA: carvedilol é uma das opções validadas.', B: 'INCORRETA: atenolol não é pilar clássico de HFrEF.', C: 'INCORRETA: propranolol não é base padrão para HFrEF.', D: 'INCORRETA: sotalol é antiarrítmico e pode ser problemático.' }),
    q(2, false, 'Em paciente com IC e congestão, qual papel principal do diurético de alça?', ['A) Aliviar congestão e sintomas, sem substituir terapia modificadora de prognóstico.', 'B) Curar remodelamento ventricular sozinho.', 'C) Substituir SGLT2, betabloqueador, MRA e ARNI em HFrEF.', 'D) Ser evitado em todo paciente com edema pulmonar.'], 0, 'Diurético é central para descongestão, mas não é o mesmo que terapia modificadora de mortalidade.', { A: 'CORRETA: melhora dispneia, edema e pressão de enchimento.', B: 'INCORRETA: não reverte remodelamento como monoterapia prognóstica.', C: 'INCORRETA: pilares prognósticos continuam necessários se tolerados.', D: 'INCORRETA: edema pulmonar congestivo frequentemente exige diurético.' }),
    q(3, true, 'Paciente com HFrEF, QRS 165 ms com padrão de bloqueio de ramo esquerdo, sintomas persistentes apesar de terapia otimizada. Qual intervenção não farmacológica pode entrar na discussão especializada?', ['A) Terapia de ressincronização cardíaca.', 'B) Marcapasso temporário em todos os casos assintomáticos.', 'C) Cardioversão elétrica semanal programada.', 'D) Angioplastia obrigatória sem avaliar coronárias.'], 0, 'CRT pode beneficiar pacientes selecionados com HFrEF, QRS largo, especialmente BRE, e sintomas apesar de terapia otimizada.', { A: 'CORRETA: QRS largo/BRE é pista para ressincronização em critérios apropriados.', B: 'INCORRETA: marcapasso temporário não trata dessincronia crônica.', C: 'INCORRETA: cardioversão não é terapia de base da dessincronia.', D: 'INCORRETA: revascularização depende de anatomia/isquemia, não é automática.' }),
    q(2, false, 'Qual orientação reduz reinternação em IC e deve aparecer na alta de paciente compensado?', ['A) Plano de peso diário, sinais de alarme, adesão medicamentosa e retorno precoce.', 'B) Suspender todo tratamento assim que a dispneia melhorar.', 'C) Aumentar sal livremente para evitar hiponatremia.', 'D) Evitar vacinas porque todo imunizante descompensa IC.'], 0, 'Autocuidado estruturado e transição de cuidado reduzem descompensações evitáveis.', { A: 'CORRETA: educação e seguimento são parte do tratamento, não detalhe administrativo.', B: 'INCORRETA: suspensão precipita nova descompensação.', C: 'INCORRETA: excesso de sódio favorece retenção hídrica.', D: 'INCORRETA: vacinação é geralmente protetora em cardiopatas.' }),
  ];
}

function cards() {
  return [
    fc(1, 'IC é incapacidade de suprir demanda ou fazê-lo com {{c1::pressões de enchimento elevadas}}.', 'Pressões de enchimento elevadas', 'Congestão vem de pressão de enchimento alta; baixo débito é outra face da síndrome.', 'conceito', ['cm5', 'ic', 'conceito']),
    fc(1, 'FEVE <= 40% define IC com fração de ejeção {{c1::reduzida}}.', 'Reduzida', 'Esse fenótipo concentra as melhores evidências dos quatro pilares farmacológicos.', 'classificacao', ['cm5', 'ic', 'hfrEF']),
    fc(2, 'Os quatro pilares da HFrEF incluem ARNI/IECA/BRA, beta bloqueador, MRA e {{c1::SGLT2i}}.', 'SGLT2i', 'SGLT2 reduz hospitalização por IC e desfechos cardiovasculares, inclusive sem diabetes.', 'tratamento', ['cm5', 'ic', 'sglt2']),
    fc(2, 'Diurético de alça na IC serve principalmente para {{c1::descongestão}}.', 'Descongestão', 'Ele melhora sintomas e volume, mas não substitui terapia que muda prognóstico.', 'tratamento', ['cm5', 'ic', 'diuretico']),
    fc(2, 'BNP/NT-proBNP ajudam no diferencial de dispneia porque refletem {{c1::estresse de parede cardíaca}}.', 'Estresse de parede cardíaca', 'Valores baixos ajudam a afastar IC em muitos cenários, mas sempre com contexto.', 'diagnostico', ['cm5', 'ic', 'bnp']),
    fc(2, 'IC com FEVE preservada exige sintomas + evidência objetiva; FEVE normal {{c1::não exclui IC}}.', 'Não exclui IC', 'HFpEF é comum em idosos, hipertensos, obesos e diabéticos.', 'classificacao', ['cm5', 'ic', 'hfpef']),
    fc(2, 'Perfil quente e úmido na IC significa perfusão preservada com {{c1::congestão}}.', 'Congestão', 'É o perfil clássico para diurese e vasodilatação conforme PA/contexto.', 'aguda', ['cm5', 'ic', 'congestao']),
    fc(3, 'Perfil frio na IC indica {{c1::hipoperfusão}}.', 'Hipoperfusão', 'Pele fria, confusão, oligúria, lactato alto e hipotensão mudam prioridade para suporte hemodinâmico.', 'aguda', ['cm5', 'ic', 'choque']),
    fc(2, 'Betabloqueadores clássicos em HFrEF: carvedilol, metoprolol succinato e {{c1::bisoprolol}}.', 'Bisoprolol', 'Atenolol não é o pilar clássico de IC com fração reduzida.', 'tratamento', ['cm5', 'ic', 'betabloqueador']),
    fc(2, 'MRA na HFrEF exige monitorar {{c1::potássio e função renal}}.', 'Potássio e função renal', 'Espironolactona/eplerenona reduzem eventos, mas podem causar hipercalemia.', 'tratamento', ['cm5', 'ic', 'mra']),
    fc(3, 'QRS largo com BRE em HFrEF sintomática pode indicar {{c1::ressincronização cardíaca}}.', 'Ressincronização cardíaca', 'CRT é para pacientes selecionados, após terapia otimizada e critérios eletrocardiográficos.', 'dispositivos', ['cm5', 'ic', 'crt']),
    fc(2, 'Alta de IC precisa incluir peso diário, sinais de alarme e {{c1::retorno precoce}}.', 'Retorno precoce', 'A transição de cuidado evita reinternação por ajuste tardio de volume e medicação.', 'seguimento', ['cm5', 'ic', 'alta']),
  ];
}

function material() {
  return [
    '---',
    'aula_id: cm5_a3',
    'materia: clinica_medica5',
    'modulo: 5',
    'tema: Insuficiência Cardíaca',
    'versao_v3: 3.0.0',
    'status: published_local',
    'revisado_em: 2026-05-07',
    'checksum_lint: pass_pending',
    '---',
    '',
    '# Insuficiência Cardíaca',
    '',
    '**Disciplina:** Clínica Médica 5',
    '**Módulo:** 5 | **Referência principal:** AHA/ACC/HFSA 2022 + ESC Focused Update 2023 + Cecil-Goldman 26ª ed.',
    '**Tempo de estudo sugerido:** 20-30 min',
    '',
    '---',
    '',
    '## Relevância Clínica e Acadêmica',
    '',
    'Aqui no MedGradPlus a gente trata insuficiência cardíaca como a ponte entre semiologia, fisiologia, farmacologia e emergência. A banca não quer só que você reconheça edema. Ela quer saber se você separa **congestão** de **hipoperfusão**, se entende **fração de ejeção**, se sabe o que realmente muda prognóstico na HFrEF e se não inicia medicamento errado no paciente em choque.',
    '',
    'IC aparece em ambulatório, enfermaria e pronto atendimento. O mesmo paciente pode estar compensado hoje e voltar amanhã com ortopneia, edema agudo de pulmão ou hipoperfusão. O raciocínio precisa ser organizado em duas perguntas: **qual fenótipo crônico?** e **qual perfil hemodinâmico agora?**',
    '',
    '> **Pegadinha de prova:** fração de ejeção normal não exclui insuficiência cardíaca. IC com fração preservada existe e é comum em idosos, hipertensos, obesos e diabéticos.',
    '',
    '---',
    '',
    '## Conceito e fisiopatologia',
    '',
    'Insuficiência cardíaca é uma **síndrome clínica** em que o coração não consegue suprir a demanda metabólica ou só consegue fazê-lo com **pressões de enchimento elevadas**.',
    '',
    'Isso gera duas faces:',
    '',
    '- **Congestão:** dispneia, ortopneia, estertores, turgência jugular, edema, hepatomegalia.',
    '- **Baixo débito/hipoperfusão:** fadiga extrema, pele fria, confusão, oligúria, lactato elevado.',
    '',
    'A ativação neuro-hormonal tenta compensar, mas cobra preço:',
    '',
    '- Sistema renina-angiotensina-aldosterona aumenta vasoconstrição e retenção de sódio.',
    '- Sistema simpático aumenta frequência e contratilidade no curto prazo.',
    '- Com o tempo, ocorre remodelamento ventricular, fibrose e piora progressiva.',
    '',
    '**Macete MedGradPlus - congestão é pressão, choque é perfusão:** ortopneia e edema falam de pressão de enchimento; pele fria e confusão falam de perfusão. Misturar os dois leva a conduta errada.',
    '',
    '---',
    '',
    '## Classificação por fração de ejeção',
    '',
    '| Fenótipo | FEVE | Ponto central |',
    '|---|---|---|',
    '| **HFrEF / ICFER** | <= 40% | melhor evidência dos quatro pilares |',
    '| **HFmrEF / ICFE levemente reduzida** | 41-49% | área intermediária, SGLT2 ganha espaço |',
    '| **HFpEF / ICFE preservada** | >= 50% | sintomas + evidência objetiva de IC |',
    '| **IC recuperada** | antes reduzida, agora melhor | não suspender terapia sem motivo forte |',
    '',
    'A FEVE é importante, mas não é tudo. Ela orienta terapia, prognóstico e necessidade de dispositivos, mas o diagnóstico final exige clínica e evidência objetiva.',
    '',
    '> **Armadilha de banca:** "FEVE 60%" não é carta de inocência. Se há dispneia, BNP alto, átrio esquerdo aumentado, hipertrofia ventricular e disfunção diastólica, pense em HFpEF.',
    '',
    '---',
    '',
    '## Estadiamento e classe funcional',
    '',
    'Duas linguagens aparecem em prova:',
    '',
    '| Sistema | O que mede | Exemplo |',
    '|---|---|---|',
    '| **ACC/AHA A-D** | progressão estrutural/risco | A = risco, C = IC sintomática |',
    '| **NYHA I-IV** | limitação funcional | III = sintomas com pequenos esforços |',
    '',
    'ACC/AHA:',
    '',
    '- **A:** risco de IC, sem doença estrutural.',
    '- **B:** doença estrutural, sem sintomas.',
    '- **C:** doença estrutural com sintomas atuais ou prévios.',
    '- **D:** IC avançada/refratária.',
    '',
    'NYHA:',
    '',
    '- **I:** sem limitação.',
    '- **II:** sintomas aos esforços habituais maiores.',
    '- **III:** sintomas com pequenos esforços.',
    '- **IV:** sintomas em repouso.',
    '',
    '---',
    '',
    '## Diagnóstico: clínica, BNP e ecocardiograma',
    '',
    'Nenhum dado isolado fecha tudo. O tripé prático é:',
    '',
    '1. **Clínica compatível**.',
    '2. **Peptídeo natriurético** quando a dispneia é duvidosa.',
    '3. **Ecocardiograma** para estrutura, FEVE, valvas e pressão pulmonar.',
    '',
    '| Achado | Ajuda em | Limite |',
    '|---|---|---|',
    '| **BNP/NT-proBNP** | afastar IC se baixo | sobe em DRC, idade, FA |',
    '| **Eco** | FEVE, diástole, valvas | depende de janela e interpretação |',
    '| **RX tórax** | congestão, derrame, cardiomegalia | pode ser normal no início |',
    '| **ECG** | isquemia, HVE, ritmo | ECG normal reduz probabilidade, não zera |',
    '',
    '> **Pérola Clínica:** BNP baixo pesa contra IC. BNP alto ajuda, mas não é exclusivo: idade, DRC, sepse, TEP e fibrilação atrial também elevam.',
    '',
    '---',
    '',
    '## Perfil hemodinâmico na descompensação',
    '',
    'Na IC aguda, classifique antes de tratar:',
    '',
    '| Perfil | Perfusão | Congestão | Tradução |',
    '|---|---|---|---|',
    '| **Quente e seco** | preservada | ausente | compensado |',
    '| **Quente e úmido** | preservada | presente | congesto comum |',
    '| **Frio e seco** | baixa | ausente | baixo débito sem congestão |',
    '| **Frio e úmido** | baixa | presente | pior perfil |',
    '',
    'Sinais de congestão:',
    '',
    '- Ortopneia.',
    '- Dispneia paroxística noturna.',
    '- Estertores.',
    '- Turgência jugular.',
    '- Edema periférico.',
    '- Hepatomegalia dolorosa.',
    '',
    'Sinais de hipoperfusão:',
    '',
    '- Extremidades frias.',
    '- Confusão.',
    '- Oligúria.',
    '- Hipotensão.',
    '- Lactato elevado.',
    '- Pulso fino.',
    '',
    '**Macete MedGradPlus - quente/frio, seco/úmido:** quente/frio é perfusão; seco/úmido é volume. Não confunda. O paciente quente e úmido precisa descongestionar; o frio e úmido precisa de UTI mentalmente antes de qualquer receita bonita.',
    '',
    '---',
    '',
    '## Tratamento crônico da HFrEF: quatro pilares',
    '',
    'Na IC com fração reduzida, a base modificadora de prognóstico é:',
    '',
    '1. **ARNI** preferencial quando possível, ou IECA/BRA.',
    '2. **Betabloqueador validado:** carvedilol, metoprolol succinato ou bisoprolol.',
    '3. **Antagonista mineralocorticoide:** espironolactona ou eplerenona.',
    '4. **Inibidor de SGLT2:** dapagliflozina ou empagliflozina.',
    '',
    '| Classe | Benefício | Cuidado |',
    '|---|---|---|',
    '| **ARNI/IECA/BRA** | remodelamento e mortalidade | rim, K+, hipotensão |',
    '| **Betabloqueador** | mortalidade e arritmia | iniciar estável, titular lento |',
    '| **MRA** | mortalidade e internação | K+ e TFG |',
    '| **SGLT2i** | internação e desfecho CV | infecção genital, volume, euglicêmica rara |',
    '',
    'Diurético de alça entra para **congestão**. Ele é indispensável no paciente úmido, mas não substitui os quatro pilares.',
    '',
    '---',
    '',
    '## O que não fazer',
    '',
    '- Não iniciar betabloqueador em dose alta no paciente em choque.',
    '- Não manter AINE crônico em paciente congestionando.',
    '- Não suspender terapia só porque a FEVE melhorou.',
    '- Não chamar edema de IC sem avaliar rim, fígado, veias e medicamentos.',
    '- Não tratar BNP isolado; trate paciente com síndrome clínica.',
    '',
    '> **Pegadinha:** paciente com HFrEF estável deve usar betabloqueador validado. Paciente em choque por IC não é hora de dobrar betabloqueador. A mesma classe pode ser salvadora ou perigosa conforme o momento.',
    '',
    '---',
    '',
    '## HFpEF: fração preservada não é normalidade',
    '',
    'IC com fração preservada costuma envolver:',
    '',
    '- Idade avançada.',
    '- Hipertensão.',
    '- Obesidade.',
    '- Diabetes.',
    '- Fibrilação atrial.',
    '- Hipertrofia ventricular.',
    '- Aumento de átrio esquerdo.',
    '',
    'O manejo foca em:',
    '',
    '- Controle de congestão com diurético.',
    '- Controle de pressão arterial.',
    '- Tratamento de FA e isquemia quando presentes.',
    '- Reabilitação e manejo de obesidade/comorbidades.',
    '- SGLT2i como classe com benefício em HFpEF/HFmrEF nas atualizações recentes.',
    '',
    '---',
    '',
    '## Dispositivos e encaminhamento',
    '',
    'Alguns pacientes precisam de terapia além de remédio:',
    '',
    '- **CDI:** prevenção de morte súbita em HFrEF selecionada, após tempo adequado de terapia otimizada.',
    '- **CRT:** ressincronização em HFrEF com QRS largo, especialmente BRE, sintomas persistentes e critérios formais.',
    '- **Transplante/dispositivo de assistência:** IC avançada, refratária, em centro especializado.',
    '',
    'Não decore dispositivo como receita universal. A banca costuma cobrar **quem é candidato provável**, não todos os critérios finos.',
    '',
    '---',
    '',
    '## Caso da Semana',
    '',
    '> **Caso da Semana - Ortopneia na madrugada.**',
    '>',
    '> **Ato 1 (persona):** Homem, 72 anos, hipertenso e diabético, acorda sentado na cama por falta de ar. Relata ganho de 3 kg em 1 semana e edema em pernas.',
    '>',
    '> **Ato 2 (dados):** PA 154x88, FC 104, SatO2 91%, estertores bibasais, turgência jugular e extremidades quentes. BNP elevado. Eco prévio: FEVE 34%.',
    '>',
    '> **Ato 3 (comando):**',
    '> 1. Qual fenótipo crônico pela FEVE?',
    '> 2. Qual perfil hemodinâmico atual?',
    '> 3. Qual prioridade imediata: pilar prognóstico ou descongestão?',
    '>',
    '> No MedGradPlus, a resposta completa separa crônico de agudo: HFrEF no papel, quente e úmido no leito.',
    '',
    '---',
    '',
    '## Diagnóstico Diferencial da Dispneia',
    '',
    '| Diagnóstico | A favor | Contra IC isolada |',
    '|---|---|---|',
    '| **DPOC/asma** | sibilos, história pulmonar | BNP baixo, RX sem congestão |',
    '| **TEP** | dor pleurítica, taquicardia, risco trombótico | eco/BNP podem confundir |',
    '| **Pneumonia** | febre, escarro, consolidação | BNP pode subir por estresse |',
    '| **Anemia** | palidez, Hb baixa | eco pode ser normal |',
    '| **DRC/nefrose** | edema, proteinúria | congestão pulmonar nem sempre presente |',
    '',
    '---',
    '',
    '## Ponte com próximas aulas',
    '',
    '- `cm5_a1`: HAS é causa e fator de descompensação da IC.',
    '- `cm5_a2`: ECG mostra isquemia, ritmo, bloqueio e HVE.',
    '- `cm5_a4`: FA e bloqueios agravam IC e mudam conduta.',
    '- `cm5_a5`: doença coronariana é etiologia central de HFrEF.',
    '- `cm5_a6`: diabetes e SGLT2 conectam metabolismo e IC.',
    '- `cm5_a9`: DRC limita MRA/IECA/ARNI e aumenta hipercalemia.',
    '',
    '---',
    '',
    '## Pontos-Chave',
    '',
    '- IC é síndrome clínica de **baixo débito e/ou congestão**.',
    '- FEVE <= 40% define **HFrEF**.',
    '- FEVE preservada **não exclui IC**.',
    '- BNP/NT-proBNP ajuda no diferencial de dispneia.',
    '- Ecocardiograma define FEVE, valvas, estrutura e função diastólica.',
    '- Perfil quente/frio mede **perfusão**.',
    '- Perfil seco/úmido mede **congestão**.',
    '- HFrEF tem quatro pilares: **ARNI/IECA/BRA, beta bloqueador, MRA, SGLT2i**.',
    '- Diurético trata **congestão**, não substitui terapia prognóstica.',
    '- Betabloqueador é pilar no estável, mas perigoso se iniciado/agudizado no choque.',
    '- MRA exige potássio e função renal adequados.',
    '- CRT entra em HFrEF selecionada com QRS largo/BRE.',
    '',
    '---',
    '',
    '## Mini Quiz',
    '',
    '**1. Qual frase define insuficiência cardíaca de forma mais correta?**',
    '',
    '- [x] Síndrome em que o coração não supre demanda ou só o faz com pressões de enchimento elevadas',
    '- [ ] Toda dispneia com ausculta normal',
    '- [ ] Qualquer FEVE abaixo de 70%',
    '- [ ] Sinônimo obrigatório de infarto agudo',
    '',
    '> **Explicação:** IC é **síndrome clínica** com baixo débito e/ou congestão por pressões elevadas, não apenas um número isolado.',
    '',
    '**2. FEVE de 35% em paciente sintomático classifica qual fenótipo?**',
    '',
    '- [x] HFrEF / ICFER',
    '- [ ] HFpEF obrigatória',
    '- [ ] IC de alto débito',
    '- [ ] Coração estruturalmente normal',
    '',
    '> **Explicação:** FEVE <= 40% define **IC com fração de ejeção reduzida**.',
    '',
    '**3. Qual conjunto representa os quatro pilares da HFrEF?**',
    '',
    '- [ ] Diurético, digoxina, clonidina e AAS',
    '- [x] ARNI/IECA/BRA, betabloqueador validado, MRA e SGLT2i',
    '- [ ] Antibiótico, broncodilatador, AINE e corticoide',
    '- [ ] Verapamil, diltiazem, alfa-bloqueador e nitrato sublingual',
    '',
    '> **Explicação:** Os quatro pilares modificam desfechos em HFrEF. Diurético é essencial para **congestão**, mas não substitui os pilares.',
    '',
    '**4. Paciente com estertores, TJP e extremidades quentes é qual perfil?**',
    '',
    '- [ ] Frio e seco',
    '- [x] Quente e úmido',
    '- [ ] Frio e úmido',
    '- [ ] Quente e seco',
    '',
    '> **Explicação:** Quente = perfusão preservada. Úmido = congestão. Esse é o perfil congestionado mais comum.',
    '',
    '**5. Mulher com dispneia, BNP alto, FEVE 58%, átrio esquerdo aumentado e HVE pode ter qual diagnóstico?**',
    '',
    '- [ ] IC impossível',
    '- [x] IC com fração de ejeção preservada',
    '- [ ] IAM com supra obrigatório',
    '- [ ] Choque cardiogênico por definição',
    '',
    '> **Explicação:** HFpEF exige sintomas e evidência objetiva. **FEVE preservada não exclui IC**.',
    '',
    '**6. Paciente com HFrEF chega hipotenso, confuso, frio e com lactato alto. Qual erro deve ser evitado?**',
    '',
    '- [ ] Reconhecer hipoperfusão',
    '- [ ] Monitorizar em cenário de gravidade',
    '- [x] Dobrar betabloqueador imediatamente',
    '- [ ] Reavaliar drogas conforme perfusão',
    '',
    '> **Explicação:** Betabloqueador é pilar no estável, mas aumentar dose no choque pode piorar hipoperfusão.',
    '',
    '---',
    '',
    '## Pré-Prova',
    '',
    '### Síntese para a prova',
    '',
    'Insuficiência cardíaca cai como **fenótipo + perfil + tratamento**. Primeiro identifique se é HFrEF, HFmrEF ou HFpEF. Depois, se descompensou, classifique quente/frio e seco/úmido. Só então escolha conduta: descongestão, suporte hemodinâmico ou otimização dos quatro pilares.',
    '',
    '### Macete-âncora',
    '',
    '**FEVE diz o remédio; quente/frio e seco/úmido dizem a urgência.**',
    '',
    '- FEVE reduzida: quatro pilares.',
    '- Úmido: diurese/descongestão.',
    '- Frio: hipoperfusão e gravidade.',
    '- Preservada: não descarte IC; procure evidência objetiva.',
    '',
    '### Erros que derrubam nota',
    '',
    '- Dizer que FEVE normal exclui IC.',
    '- Trocar diurético por terapia modificadora de prognóstico.',
    '- Dobrar betabloqueador em paciente frio/choque.',
    '- Esquecer SGLT2i nos pilares de HFrEF.',
    '- Não monitorar potássio e rim com MRA.',
    '- Ignorar perfil hemodinâmico na descompensação.',
    '',
    '---',
    '',
    '## Fontes',
    '',
    '- AHA/ACC/HFSA. **2022 Guideline for the Management of Heart Failure**.',
    '- European Society of Cardiology. **2023 Focused Update of the 2021 ESC Guidelines for Heart Failure**.',
    '- Cecil-Goldman Medicine, 26ª edição, capítulo de insuficiência cardíaca.',
    '- Harrison\'s Principles of Internal Medicine, 21ª edição, capítulo de insuficiência cardíaca.',
    '',
    '---',
    '',
    '## Questões de Residência (mapeadas)',
    '',
    '> Esta seção registra temas de provas públicas. Não transcrever enunciados no app; usar apenas para calibrar estilo e recorrência.',
    '',
    '- **ENAMED 2025, Caderno 01, Q1** - HAS, dispneia progressiva, quarta bulha e ecocardiograma em contexto de IC.',
    '- **ENARE 2024, Acesso Direto Tipo 1** - insuficiência cardíaca congestiva em paciente clínico complexo.',
    '- **ENAMED 2025, Caderno 01, Q67** - dor torácica, achado de ST e integração com síndrome coronariana como causa/agravante cardiovascular.',
  ].join('\n');
}

function updateData() {
  const qData = readJson('data/questoes.json');
  let questoes = (qData.questoes || []).filter((item) => item.origem !== MARKER);
  const novos = questions();
  let maxQ = Math.max(0, ...questoes.map((item) => Number(item.id) || 0));
  for (const item of novos) item.id = ++maxQ;
  questoes.push(...novos);
  writeJson('data/questoes.json', { ...qData, questoes });

  const fcData = readJson('data/flashcards.json');
  let flashcards = (fcData.flashcards || []).filter((item) => item.origem !== MARKER);
  const novosCards = cards();
  let maxFc = Math.max(0, ...flashcards.map((item) => Number(item.id) || 0));
  for (const item of novosCards) item.id = ++maxFc;
  flashcards.push(...novosCards);
  writeJson('data/flashcards.json', { ...fcData, flashcards });
}

function updateRefs() {
  writeJson('data/refs/cm5_a3.refs.json', {
    aula_id: 'cm5_a3',
    materia: 'clinica_medica5',
    modulo: 5,
    tema: 'Insuficiência Cardíaca',
    gerado_em: '2026-05-07',
    revisado: false,
    livros: [
      { titulo: 'Cecil-Goldman Medicine', edicao: '26ª edição', capitulo: 'Insuficiência cardíaca', relevancia: 'principal' },
      { titulo: "Harrison's Principles of Internal Medicine", edicao: '21ª edição', capitulo: 'Heart Failure', relevancia: 'complementar' },
    ],
    diretrizes: [
      { titulo: '2022 AHA/ACC/HFSA Guideline for the Management of Heart Failure', instituicao: 'AHA/ACC/HFSA', url: 'https://www.acc.org/Guidelines/Guidelines/2022/03/30/16/38/2022-Heart-Failure', uso: 'fenótipos, estágios e terapia modificadora de prognóstico' },
      { titulo: '2023 Focused Update of the 2021 ESC Guidelines for Heart Failure', instituicao: 'European Society of Cardiology', url: 'https://www.escardio.org/guidelines/clinical-practice-guidelines/all-esc-practice-guidelines/focused-update-on-heart-failure-guidelines/', uso: 'atualização em SGLT2i para HFmrEF/HFpEF e manejo contemporâneo' },
    ],
    questoes_publicas: [
      { fonte: 'INEP ENAMED', ano: 2025, questao: '1', url: 'https://download.inep.gov.br/enamed/provas_e_gabaritos/2025_caderno_superampliado_preliminar.pdf', topico_mapeado: 'dispneia, HAS, quarta bulha e ecocardiograma em contexto de IC', status: 'mapeada_sem_transcricao', observacao: 'Usar como calibrador de estilo, sem copiar enunciado.' },
      { fonte: 'FGV/Ebserh ENARE', ano: 2024, questao: 'Acesso Direto - caderno tipo 1', url: 'https://mapa-vagas-enare-ebserh.conhecimento.fgv.br/provas-gabaritos-medica.html', topico_mapeado: 'insuficiência cardíaca congestiva em cenário clínico', status: 'mapeada_sem_transcricao', observacao: 'Triagem local por PDF identificou recorrência cardiovascular.' },
    ],
    pontos_de_prova: [
      'Definição sindrômica de IC.',
      'Classificação por FEVE.',
      'BNP/NT-proBNP e ecocardiograma.',
      'Perfis quente/frio e seco/úmido.',
      'Quatro pilares da HFrEF.',
      'Papel do diurético de alça.',
      'HFpEF e SGLT2i.',
      'CRT/CDI em pacientes selecionados.',
    ],
    observacoes: 'Sem imagem nesta aula por decisão operacional: apenas cm5_a1 e cm5_a2 receberam Wikimedia nesta rodada.',
  });
}

function main() {
  const md = material();
  writeText('data/materiais/clinica_medica5/cm5_a3.md', md);
  writeText('materiais/modulo5/clinica_medica5/cm5_a3.md', md);
  updateData();
  updateRefs();
  console.log('CM5 a3 atualizada com material, essenciais e flashcards.');
}

main();
