import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const AULA = 'cm5_a5';
const MARKER = 'cm5_quality_contract_2026_05_07_cm5_a5';

function p(rel) { return path.join(ROOT, rel); }
function readJson(rel) { return JSON.parse(fs.readFileSync(p(rel), 'utf8')); }
function writeJson(rel, data) {
  fs.mkdirSync(path.dirname(p(rel)), { recursive: true });
  fs.writeFileSync(p(rel), `${JSON.stringify(data, null, 2)}\n`, 'utf8');
}
function writeText(rel, text) {
  fs.mkdirSync(path.dirname(p(rel)), { recursive: true });
  fs.writeFileSync(p(rel), `${text.replace(/\r\n/g, '\n').replace(/\n*$/, '')}\n`, 'utf8');
}
function explanation(general, exp) {
  return [`Resumo: ${general}`, `A) ${exp.A}`, `B) ${exp.B}`, `C) ${exp.C}`, `D) ${exp.D}`].join('\n');
}
function q(dificuldade, caso_clinico, enunciado, opcoes, correta, general, exp) {
  return {
    materia: 'clinica_medica5',
    tema: AULA,
    aula_id: AULA,
    modulo: 5,
    dificuldade,
    caso_clinico,
    essencial: true,
    origem: MARKER,
    enunciado,
    opcoes,
    correta,
    explicacao_geral: general,
    explicacoes_opcoes: exp,
    explicacao: explanation(general, exp),
  };
}
function fc(dificuldade, frente, verso, explicacao, categoria, tags) {
  return { materia: 'clinica_medica5', tema: AULA, dificuldade, frente, verso, explicacao, origem: MARKER, categoria, tags };
}

function questions() {
  return [
    q(1, false, 'Qual tríade define angina típica?', [
      'A) Desconforto retroesternal, precipitado por esforço ou estresse, aliviado por repouso ou nitrato.',
      'B) Dor pleurítica que piora à inspiração e melhora ao deitar.',
      'C) Dor epigástrica de segundos, sempre pós-prandial e sem relação com esforço.',
      'D) Dor reprodutível à palpação costal como critério obrigatório de DAC.',
    ], 0, 'Angina típica combina localização/qualidade sugestiva, gatilho por esforço ou estresse e alívio com repouso ou nitrato.', {
      A: 'CORRETA: reúne os três critérios clássicos.',
      B: 'INCORRETA: pleurítica sugere mais causa pulmonar/pericárdica.',
      C: 'INCORRETA: segundos e pós-prandial isolado não é padrão típico.',
      D: 'INCORRETA: dor reprodutível favorece parede torácica, não DAC típica.',
    }),
    q(2, true, 'Homem de 62 anos tem aperto retroesternal ao subir ladeiras há 6 meses, melhora em 5 minutos ao parar. Sem dor em repouso, ECG basal sem supra e troponina normal. Qual síndrome é mais provável?', [
      'A) Doença coronariana crônica com angina estável.',
      'B) Infarto com supra de ST obrigatório.',
      'C) Dissecção aguda de aorta até prova em contrário.',
      'D) Pericardite aguda viral típica.',
    ], 0, 'Dor previsível ao esforço, curta, aliviada por repouso e sem biomarcador de necrose sugere doença coronariana crônica/angina estável.', {
      A: 'CORRETA: a previsibilidade por esforço é a pista.',
      B: 'INCORRETA: não há dor prolongada, supra ou troponina positiva.',
      C: 'INCORRETA: faltam dor súbita lancinante, assimetria de pulsos ou sinais de aorta.',
      D: 'INCORRETA: pericardite costuma ter dor posicional e atrito, não padrão de esforço previsível.',
    }),
    q(2, false, 'Qual achado transforma o raciocínio de coronariopatia crônica em suspeita de síndrome coronariana aguda?', [
      'A) Dor em repouso/progressiva, alteração dinâmica de ST ou troponina em elevação.',
      'B) Dor estável há anos, sempre igual, com troponina normal.',
      'C) Dislipidemia isolada sem sintomas.',
      'D) Teste ergométrico antigo normal em paciente assintomático.',
    ], 0, 'Dor nova, crescente, em repouso ou associada a ST/troponina muda o cenário para SCA, que exige fluxo agudo.', {
      A: 'CORRETA: são sinais de instabilidade clínica e miocárdica.',
      B: 'INCORRETA: isso é mais compatível com quadro crônico estável.',
      C: 'INCORRETA: fator de risco isolado não define SCA.',
      D: 'INCORRETA: exame antigo não define evento agudo.',
    }),
    q(2, false, 'Na investigação de dor torácica estável, qual princípio evita excesso de exame?', [
      'A) Estimar probabilidade pré-teste e escolher teste conforme risco, ECG, capacidade de exercício e disponibilidade.',
      'B) Fazer cateterismo invasivo em todo paciente com qualquer desconforto torácico.',
      'C) Ignorar idade, sexo, sintomas e fatores de risco.',
      'D) Usar troponina seriada como único exame para todo quadro crônico estável.',
    ], 0, 'Diretrizes de doença coronariana crônica valorizam probabilidade pré-teste e seleção racional de teste anatômico ou funcional.', {
      A: 'CORRETA: evita tanto subdiagnóstico quanto cascata desnecessária.',
      B: 'INCORRETA: cateterismo não é triagem universal de dor estável.',
      C: 'INCORRETA: esses elementos definem probabilidade.',
      D: 'INCORRETA: troponina é central em suspeita aguda, não como único teste crônico.',
    }),
    q(2, false, 'Qual exame anatômico não invasivo pode ser útil em paciente selecionado com suspeita de DAC crônica?', [
      'A) Angiotomografia de coronárias.',
      'B) Hemograma como teste confirmatório de estenose coronária.',
      'C) Radiografia simples de tórax para medir placa aterosclerótica.',
      'D) Urina tipo 1 como teste de isquemia miocárdica.',
    ], 0, 'Angiotomografia coronária pode avaliar anatomia coronária em cenários selecionados; testes funcionais avaliam isquemia.', {
      A: 'CORRETA: é ferramenta anatômica não invasiva reconhecida.',
      B: 'INCORRETA: hemograma não mostra estenose coronária.',
      C: 'INCORRETA: RX tórax não quantifica placa coronária.',
      D: 'INCORRETA: urina tipo 1 não diagnostica isquemia miocárdica.',
    }),
    q(2, true, 'Paciente com angina estável usa sildenafila para disfunção erétil. Qual antianginoso exige alerta forte por risco de hipotensão grave?', [
      'A) Nitrato.',
      'B) Estatina.',
      'C) AAS em baixa dose.',
      'D) Inibidor de SGLT2.',
    ], 0, 'Nitratos não devem ser combinados com inibidores de PDE5, como sildenafila, pelo risco de hipotensão importante.', {
      A: 'CORRETA: combinação nitrato + PDE5 é contraindicação clássica.',
      B: 'INCORRETA: estatina não tem essa interação hemodinâmica.',
      C: 'INCORRETA: AAS não causa essa vasodilatação sinérgica.',
      D: 'INCORRETA: SGLT2 pode ter efeitos hemodinâmicos leves, mas não é a interação clássica.',
    }),
    q(2, false, 'Qual é o papel das estatinas na doença coronariana crônica?', [
      'A) Reduzir risco cardiovascular por controle agressivo de LDL, geralmente com alta intensidade se tolerada.',
      'B) Aliviar dor anginosa em minutos como nitrato sublingual.',
      'C) Substituir antiagregante em todo paciente.',
      'D) Ser suspensa assim que o LDL melhora.',
    ], 0, 'Estatina é terapia de prevenção secundária na DAC; reduz eventos e deve ser mantida com metas/intensidade apropriadas.', {
      A: 'CORRETA: LDL é alvo central de prevenção.',
      B: 'INCORRETA: estatina não é antianginoso de alívio imediato.',
      C: 'INCORRETA: não substitui antiagregação quando indicada.',
      D: 'INCORRETA: melhora do LDL é efeito desejado, não motivo automático para suspender.',
    }),
    q(2, false, 'Qual opção costuma ser parte da prevenção secundária em DAC crônica estabelecida, se não houver contraindicação?', [
      'A) AAS em baixa dose ou alternativa como clopidogrel se intolerância.',
      'B) Antibiótico profilático crônico para placa aterosclerótica.',
      'C) Corticoide sistêmico contínuo para reduzir inflamação coronária.',
      'D) Suspender atividade física em todo paciente para sempre.',
    ], 0, 'Antiagregação, estatina, cessação de tabagismo, controle pressórico, diabetes e reabilitação são pilares de prevenção secundária.', {
      A: 'CORRETA: antiagregante é pilar em muitos pacientes com DAC estabelecida.',
      B: 'INCORRETA: aterosclerose não é tratada com antibiótico crônico.',
      C: 'INCORRETA: corticoide crônico aumenta risco e não é prevenção padrão.',
      D: 'INCORRETA: exercício supervisionado/reabilitação é benéfico em estáveis.',
    }),
    q(3, true, 'Paciente com angina estável segue sintomático apesar de tratamento clínico otimizado e tem anatomia coronária de alto risco. Qual conceito é correto?', [
      'A) Revascularização pode ser indicada para sintomas refratários ou prognóstico em anatomias selecionadas.',
      'B) Stent cura aterosclerose sistêmica e dispensa estatina.',
      'C) Cateterismo é proibido em qualquer DAC crônica.',
      'D) Tratamento clínico nunca é necessário após revascularização.',
    ], 0, 'Revascularização na DAC crônica é selecionada: alívio de sintomas refratários e benefício prognóstico em anatomias específicas. Ela não substitui prevenção secundária.', {
      A: 'CORRETA: esse é o raciocínio equilibrado.',
      B: 'INCORRETA: aterosclerose é sistêmica e exige terapia contínua.',
      C: 'INCORRETA: cateterismo tem papel em alto risco ou planejamento terapêutico.',
      D: 'INCORRETA: prevenção secundária continua após stent ou cirurgia.',
    }),
    q(2, false, 'Qual medida não farmacológica tem benefício real na DAC crônica?', [
      'A) Cessação de tabagismo e reabilitação/exercício supervisionado.',
      'B) Repouso absoluto permanente.',
      'C) Dieta sem medicação em todos os pacientes com infarto prévio.',
      'D) Evitar vacina e acompanhamento por medo de descompensar.',
    ], 0, 'Mudança de estilo de vida é tratamento, não enfeite: parar tabaco, exercício, dieta, peso, sono e adesão reduzem risco.', {
      A: 'CORRETA: são medidas com impacto clínico.',
      B: 'INCORRETA: sedentarismo piora risco.',
      C: 'INCORRETA: dieta ajuda, mas não substitui prevenção secundária indicada.',
      D: 'INCORRETA: seguimento e prevenção são parte do cuidado.',
    }),
    q(3, true, 'Homem com dor torácica prolongada, infra de ST novo, inversão de T, troponina em curva e GRACE alto. Qual erro seria grave?', [
      'A) Tratar como DAC crônica estável e marcar consulta para meses depois.',
      'B) Reconhecer síndrome coronariana aguda sem supra de alto risco.',
      'C) Monitorizar em unidade apropriada.',
      'D) Considerar estratégia invasiva precoce conforme risco.',
    ], 0, 'Dor prolongada com alteração dinâmica e troponina positiva é SCA, não angina estável. GRACE alto reforça estratégia agressiva.', {
      A: 'CORRETA: esse é o erro que a questão quer evitar.',
      B: 'INCORRETA: essa é a leitura adequada.',
      C: 'INCORRETA: monitorização é correta.',
      D: 'INCORRETA: alto risco pode indicar estratégia invasiva precoce.',
    }),
    q(2, false, 'Qual frase resume melhor o tratamento da DAC crônica?', [
      'A) Aliviar angina, reduzir eventos e tratar fatores de risco de forma contínua.',
      'B) Usar nitrato e ignorar LDL, tabaco e diabetes.',
      'C) Fazer stent em todo paciente assintomático.',
      'D) Suspender estatina e AAS quando a dor melhora.',
    ], 0, 'DAC crônica exige dupla meta: qualidade de vida por controle de sintomas e prevenção de infarto/morte por terapia de risco.', {
      A: 'CORRETA: une sintoma e prognóstico.',
      B: 'INCORRETA: nitrato alivia sintoma, não resolve risco global.',
      C: 'INCORRETA: revascularização não é universal.',
      D: 'INCORRETA: melhora da dor não elimina prevenção secundária.',
    }),
  ];
}

function cards() {
  return [
    fc(1, 'Angina típica = desconforto retroesternal + esforço/estresse + alívio com {{c1::repouso ou nitrato}}.', 'Repouso ou nitrato', 'Três critérios tornam a dor muito mais sugestiva de isquemia miocárdica.', 'diagnostico', ['cm5', 'dac', 'angina']),
    fc(2, 'Dor em repouso/progressiva, ST dinâmico ou troponina subindo sugere {{c1::síndrome coronariana aguda}}.', 'Síndrome coronariana aguda', 'Essa é a fronteira entre DAC crônica e fluxo de emergência.', 'diferencial', ['cm5', 'sca', 'dac']),
    fc(2, 'Na dor torácica estável, o exame depende da {{c1::probabilidade pré-teste}} e do perfil do paciente.', 'Probabilidade pré-teste', 'Evita pedir cateterismo para todo mundo ou ignorar risco alto.', 'diagnostico', ['cm5', 'dac', 'teste']),
    fc(2, 'Angiotomografia coronária é teste {{c1::anatômico}} não invasivo para DAC em paciente selecionado.', 'Anatômico', 'Testes funcionais respondem se há isquemia; CCTA mostra anatomia.', 'diagnostico', ['cm5', 'dac', 'ccta']),
    fc(2, 'Nitrato não deve ser associado a inibidor de PDE5 como {{c1::sildenafila}}.', 'Sildenafila', 'A combinação pode causar hipotensão grave.', 'tratamento', ['cm5', 'angina', 'nitrato']),
    fc(2, 'Estatina na DAC crônica serve para reduzir {{c1::LDL e risco cardiovascular}}.', 'LDL e risco cardiovascular', 'Não é remédio de alívio imediato de dor.', 'prevencao', ['cm5', 'dac', 'estatina']),
    fc(2, 'AAS em baixa dose é prevenção secundária comum na DAC, salvo {{c1::contraindicação ou estratégia antitrombótica alternativa}}.', 'Contraindicação ou estratégia alternativa', 'Clopidogrel pode ser alternativa em intolerância, e cenários com anticoagulação exigem ajuste.', 'prevencao', ['cm5', 'dac', 'aas']),
    fc(2, 'Betabloqueador reduz demanda miocárdica ao diminuir frequência e {{c1::contratilidade}}.', 'Contratilidade', 'Ajuda sintomas anginosos, especialmente pós-IAM ou com disfunção ventricular quando indicado.', 'antianginoso', ['cm5', 'angina', 'betabloqueador']),
    fc(2, 'Revascularização na DAC crônica é para sintomas refratários ou {{c1::anatomia de alto risco}} em casos selecionados.', 'Anatomia de alto risco', 'Stent ou cirurgia não substituem tratamento clínico e prevenção secundária.', 'revascularizacao', ['cm5', 'dac', 'pci']),
    fc(1, 'Cessar tabagismo é uma das intervenções mais fortes para reduzir {{c1::risco cardiovascular}}.', 'Risco cardiovascular', 'Não é orientação genérica; é tratamento de DAC.', 'estilo_de_vida', ['cm5', 'dac', 'tabagismo']),
    fc(2, 'Controle da angina trata sintoma; controle de LDL, PA, DM e tabaco trata {{c1::prognóstico}}.', 'Prognóstico', 'Separar sintoma de evento evita plano incompleto.', 'raciocinio', ['cm5', 'dac', 'prognostico']),
    fc(3, 'Dor torácica com troponina positiva e GRACE alto não é DAC crônica: é {{c1::SCA de alto risco}}.', 'SCA de alto risco', 'Esse padrão pede manejo agudo e estratégia invasiva conforme protocolo.', 'emergencia', ['cm5', 'sca', 'grace']),
  ];
}

function material() {
  return [
    '---',
    'aula_id: cm5_a5',
    'materia: clinica_medica5',
    'modulo: 5',
    'tema: Doença Arterial Coronariana Crônica',
    'versao_v3: 3.0.0',
    'status: published_local',
    'revisado_em: 2026-05-07',
    'checksum_lint: pass_pending',
    '---',
    '',
    '# Doença Arterial Coronariana Crônica',
    '',
    '**Disciplina:** Clínica Médica 5',
    '**Módulo:** 5 | **Referência principal:** AHA/ACC CCD 2023 + ESC CCS 2024',
    '**Tempo de estudo sugerido:** 25-35 min',
    '',
    '---',
    '',
    '## Relevância Clínica e Acadêmica',
    '',
    'Doença arterial coronariana crônica é a aula em que você precisa separar três coisas que o aluno mistura: **dor estável**, **risco cardiovascular** e **síndrome coronariana aguda**.',
    '',
    'A banca não quer que você mande todo mundo direto para cateterismo, nem que trate dor torácica progressiva como consulta de rotina. Ela quer saber se você reconhece angina típica, escolhe teste com lógica e não esquece prevenção secundária.',
    '',
    '> **Pegadinha de prova:** stent não cura aterosclerose. Se o paciente revascularizou e você abandonou estatina, tabaco, pressão e diabetes, você tratou a placa errada e deixou a doença viva.',
    '',
    '---',
    '',
    '## Caso da Semana',
    '',
    '**Ato 1 - Entrada:** mulher de 59 anos, diabética e ex-tabagista, relata aperto retroesternal ao caminhar rápido há 8 meses. A dor melhora em poucos minutos quando para. Sem dor em repouso.',
    '',
    '**Ato 2 - Virada:** na última semana, ela percebe que a dor começou a surgir com esforços menores. Hoje chegou ao pronto atendimento com dor em repouso há 35 minutos.',
    '',
    '**Ato 3 - Decisão:** o quadro começou como angina estável, mas mudou de padrão. Agora há sinal de instabilidade. A conduta deixa de ser investigação eletiva de DAC crônica e passa a ser avaliação de síndrome coronariana aguda.',
    '',
    '> **Moral da vinheta:** a mesma paciente pode atravessar a fronteira entre crônico e agudo. Dor que muda de padrão não é "só a angina de sempre".',
    '',
    '---',
    '',
    '## Conceito e Fisiopatologia',
    '',
    'A doença arterial coronariana crônica envolve aterosclerose coronária, disfunção endotelial, inflamação, trombose subclínica e desequilíbrio entre oferta e demanda de oxigênio.',
    '',
    'A isquemia aparece quando o fluxo coronariano não acompanha a demanda. Isso pode ocorrer por estenose fixa, vasoespasmo, doença microvascular ou combinação.',
    '',
    '**Macete MedGradPlus - placa é doença sistêmica:** a placa que você vê na coronária é só a ponta do problema. O tratamento precisa mirar artéria, sangue, metabolismo e comportamento.',
    '',
    '---',
    '',
    '## Angina: Típica, Atípica e Não Anginosa',
    '',
    '| Tipo | Critérios | Interpretação |',
    '|---|---|---|',
    '| **Angina típica** | retroesternal + esforço/estresse + alívio com repouso/nitrato | alta suspeita de isquemia |',
    '| **Angina atípica** | dois critérios | suspeita intermediária |',
    '| **Dor não anginosa** | zero ou um critério | procurar outros diagnósticos |',
    '',
    'Dor típica costuma ser pressão, aperto ou peso. Pode irradiar para braço esquerdo, mandíbula, dorso ou epigástrio. Falta de ar pode ser equivalente anginoso, especialmente em diabéticos, idosos e mulheres.',
    '',
    '> **Pérola Clínica:** dor em pontada de segundos, que muda com respiração ou é reprodutível à palpação, não é a apresentação clássica de angina. Mas fator de risco alto exige julgamento, não deboche.',
    '',
    '---',
    '',
    '## Crônico versus Agudo',
    '',
    '| Padrão | Sugere | Conduta |',
    '|---|---|---|',
    '| **Dor previsível ao esforço, igual há meses** | DAC crônica estável | avaliação ambulatorial estruturada |',
    '| **Dor nova ou em crescendo** | angina instável/SCA | avaliação aguda |',
    '| **Dor prolongada em repouso** | SCA até prova em contrário | ECG, troponina e protocolo |',
    '| **ST dinâmico ou troponina positiva** | injúria/isquemia aguda | estratificação de risco e manejo hospitalar |',
    '',
    'A maior falha é chamar dor progressiva de "angina estável". Estável significa previsível. Se mudou frequência, limiar, duração ou ocorre em repouso, mudou o jogo.',
    '',
    '**Macete MedGradPlus - estável é repeteco:** mesma dor, mesmo esforço, mesmo alívio. Se virou surpresa, pense em SCA.',
    '',
    '---',
    '',
    '## Probabilidade Pré-teste',
    '',
    'Antes de pedir exame, estime a chance de DAC obstrutiva com idade, sexo, tipo de sintoma e fatores de risco.',
    '',
    'Isso orienta a pergunta certa:',
    '',
    '- Probabilidade muito baixa: evite cascata de exames.',
    '- Probabilidade intermediária: teste anatômico ou funcional costuma ser útil.',
    '- Alto risco clínico ou sintomas graves: avaliação especializada e estratégia invasiva podem ser necessárias.',
    '',
    '| Variável | Aumenta suspeita | Observação |',
    '|---|---|---|',
    '| **Sintoma típico** | sim | principal pista clínica |',
    '| **Diabetes** | sim | pode ter equivalente anginoso |',
    '| **Tabagismo** | sim | acelera aterosclerose |',
    '| **ECG alterado** | depende | pode limitar teste ergométrico simples |',
    '| **Capacidade funcional** | orienta teste | define se consegue esforço |',
    '',
    '---',
    '',
    '## Exames na DAC Crônica',
    '',
    '| Teste | O que responde | Bom uso |',
    '|---|---|---|',
    '| **Teste ergométrico** | resposta ao esforço e ECG | ECG interpretável + consegue exercício |',
    '| **Eco estresse/cintilografia/RM estresse** | isquemia funcional | ECG basal ruim ou maior acurácia |',
    '| **Angiotomografia coronária** | anatomia e placa | suspeita selecionada, boa qualidade de imagem |',
    '| **Cateterismo** | anatomia invasiva e possível intervenção | alto risco, sintomas refratários, anatomia planejada |',
    '',
    'Troponina não é exame de triagem de angina estável sem suspeita aguda. Ela entra quando a história sugere injúria miocárdica recente.',
    '',
    '> **Armadilha de banca:** cateterismo não é "teste de entrada" para todo desconforto. Também não é proibido. O ponto é selecionar por risco, sintoma e resultado dos testes.',
    '',
    '---',
    '',
    '## Tratamento: Duas Metas',
    '',
    'O plano precisa responder duas perguntas:',
    '',
    '1. **Como aliviar angina?**',
    '2. **Como reduzir infarto, AVC e morte?**',
    '',
    '| Meta | Medidas |',
    '|---|---|',
    '| **Sintoma** | betabloqueador, bloqueador de canal de cálcio, nitrato, ranolazina em selecionados |',
    '| **Prognóstico** | estatina, antiagregante quando indicado, cessar tabaco, PA, diabetes, exercício, dieta |',
    '',
    'Remédio antianginoso pode melhorar muito a qualidade de vida, mas não substitui prevenção secundária. Estatina pode não aliviar dor hoje, mas reduz evento amanhã.',
    '',
    '---',
    '',
    '## Antianginosos',
    '',
    '| Classe | Uso | Cuidado |',
    '|---|---|---|',
    '| **Betabloqueador** | reduz FC e demanda | bradicardia, broncoespasmo, descompensação aguda |',
    '| **BCC diidropiridínico** | vasodilatação e PA | edema, cefaleia |',
    '| **Verapamil/diltiazem** | FC e angina | evitar em HFrEF/descompensação |',
    '| **Nitrato** | alívio e profilaxia de crise | não combinar com PDE5 |',
    '| **Ranolazina** | sintoma persistente selecionado | QT/interações |',
    '',
    'Nitrato sublingual é clássico para crise. Nitrato de longa ação exige intervalo livre para evitar tolerância. E nunca esqueça a pergunta da prova: usa sildenafila, tadalafila ou vardenafila?',
    '',
    '---',
    '',
    '## Prevenção Secundária',
    '',
    'Pilares práticos:',
    '',
    '- Estatina de alta intensidade ou máxima tolerada quando indicada.',
    '- AAS em baixa dose em muitos pacientes com DAC estabelecida, se não houver contraindicação.',
    '- Clopidogrel como alternativa em intolerância ao AAS ou conforme estratégia.',
    '- Controle de pressão arterial.',
    '- Controle de diabetes com drogas de benefício cardiovascular quando apropriado.',
    '- Cessar tabagismo.',
    '- Reabilitação cardíaca e exercício regular supervisionado quando indicado.',
    '- Vacinação e seguimento de adesão.',
    '',
    'A meta de LDL varia conforme diretriz e risco, mas a ideia de prova é constante: paciente com DAC é alto ou muito alto risco. LDL não é detalhe cosmético.',
    '',
    '---',
    '',
    '## Revascularização',
    '',
    'Revascularização não é prêmio para todo diagnóstico de DAC. Ela entra quando há:',
    '',
    '- Sintomas limitantes apesar de tratamento otimizado.',
    '- Anatomia de alto risco, como tronco de coronária esquerda.',
    '- Doença multiarterial com contextos de maior risco, como diabetes ou disfunção ventricular, conforme avaliação especializada.',
    '- Isquemia extensa ou alto risco em testes.',
    '',
    '| Método | Melhor pergunta |',
    '|---|---|',
    '| **ICP/stent** | lesão focal e estratégia percutânea plausível |',
    '| **CRM/cirurgia** | anatomia complexa, tronco, multiarterial, diabetes selecionado |',
    '| **Tratamento clínico otimizado** | sintomas controlados e ausência de alto risco |',
    '',
    '> **Pérola Clínica:** revascularizar sintoma não autoriza abandonar estatina, antiagregação indicada e reabilitação. A placa continua sendo doença sistêmica.',
    '',
    '---',
    '',
    '## Diagnóstico Diferencial da Dor Torácica',
    '',
    '| Diagnóstico | Pista | Perigo |',
    '|---|---|---|',
    '| **SCA** | repouso, troponina, ST dinâmico | morte/infarto |',
    '| **Dissecção de aorta** | dor súbita, migratória, assimetria | ruptura |',
    '| **TEP** | dispneia, pleurítica, risco trombótico | choque |',
    '| **Pericardite** | dor posicional, atrito, supra difuso | tamponamento raro |',
    '| **Parede torácica** | dor reprodutível | erro é ignorar risco alto |',
    '',
    '---',
    '',
    '## Ponte com próximas aulas',
    '',
    '- `cm5_a1`: HAS acelera aterosclerose e aumenta risco coronariano.',
    '- `cm5_a2`: ECG separa isquemia, cicatriz e mimetizadores.',
    '- `cm5_a3`: DAC é causa central de HFrEF.',
    '- `cm5_a4`: isquemia pode provocar FA, TV e bloqueios.',
    '- `cm5_a6`: diabetes e síndrome metabólica são motores de DAC.',
    '',
    '---',
    '',
    '## Pontos-Chave',
    '',
    '- Angina típica tem três critérios: local/qualidade, esforço e alívio.',
    '- Dor em repouso, progressiva, ST dinâmico ou troponina positiva é SCA.',
    '- Exame depende de probabilidade pré-teste e capacidade de exercício.',
    '- CCTA é anatômica; testes de estresse avaliam isquemia.',
    '- Cateterismo não é triagem universal, mas tem papel em alto risco.',
    '- Tratamento separa sintoma de prognóstico.',
    '- Estatina é prevenção, não analgésico.',
    '- Nitrato não combina com inibidor de PDE5.',
    '- Revascularização é seletiva e não substitui prevenção secundária.',
    '- Tabagismo, LDL, PA e diabetes precisam de ataque direto.',
    '',
    '---',
    '',
    '## Mini Quiz',
    '',
    '**1. Qual combinação define angina típica?**',
    '',
    '- [x] Retroesternal, esforço/estresse, alívio com repouso/nitrato',
    '- [ ] Pontada de segundos, inspiração, palpação',
    '- [ ] Dor apenas pós-prandial sem esforço',
    '- [ ] Dor lombar irradiada para perna',
    '',
    '> **Explicação:** três critérios fazem a dor ser típica para isquemia.',
    '',
    '**2. Qual achado muda DAC crônica para suspeita de SCA?**',
    '',
    '- [x] Dor em repouso com troponina em elevação',
    '- [ ] Dor igual há anos aos mesmos esforços',
    '- [ ] LDL alto sem sintomas',
    '- [ ] ECG antigo normal',
    '',
    '> **Explicação:** dor instável, ST dinâmico ou troponina positiva é fluxo agudo.',
    '',
    '**3. Em dor torácica estável, qual conceito vem antes do exame?**',
    '',
    '- [x] Probabilidade pré-teste',
    '- [ ] Cateterismo universal',
    '- [ ] Antibioticoterapia',
    '- [ ] Troponina como único marcador crônico',
    '',
    '> **Explicação:** idade, sexo, sintoma e risco guiam o teste.',
    '',
    '**4. Nitrato não deve ser associado a qual grupo?**',
    '',
    '- [x] Inibidores de PDE5',
    '- [ ] Estatinas',
    '- [ ] AAS',
    '- [ ] Metformina',
    '',
    '> **Explicação:** PDE5 + nitrato pode causar hipotensão grave.',
    '',
    '**5. Qual frase sobre revascularização na DAC crônica é correta?**',
    '',
    '- [x] Pode ser indicada em sintomas refratários ou anatomia de alto risco',
    '- [ ] Cura aterosclerose sistêmica',
    '- [ ] Dispensa estatina',
    '- [ ] É obrigatória para toda placa',
    '',
    '> **Explicação:** revascularização é seletiva e não substitui tratamento clínico.',
    '',
    '**6. Qual medida tem impacto real no prognóstico da DAC?**',
    '',
    '- [x] Cessar tabagismo e controlar LDL',
    '- [ ] Repouso absoluto vitalício',
    '- [ ] Corticoide crônico sem indicação',
    '- [ ] Suspender tratamento quando a dor melhora',
    '',
    '> **Explicação:** prevenção secundária contínua reduz eventos.',
    '',
    '---',
    '',
    '## Pré-Prova',
    '',
    '### Síntese para a prova',
    '',
    'DAC crônica cai como **dor típica + escolha racional de exame + prevenção secundária**. Se a dor é previsível e alivia com repouso, pense em angina estável. Se a dor ficou progressiva, em repouso, com ST ou troponina, mude para SCA. No tratamento, não confunda remédio de sintoma com remédio de prognóstico.',
    '',
    '### Macete-âncora',
    '',
    '**Angina estável repete; SCA surpreende. Sintoma alivia hoje; prevenção salva amanhã.**',
    '',
    '- Estável: mesmo esforço, mesma dor, mesmo alívio.',
    '- Instável: nova, crescente, repouso ou biomarcador.',
    '- Sintoma: beta bloqueador, BCC, nitrato.',
    '- Prognóstico: estatina, antiagregante quando indicado, tabaco, PA, diabetes.',
    '- Anatomia de alto risco ou sintoma refratário: discutir revascularização.',
    '',
    '### Erros que derrubam nota',
    '',
    '- Tratar dor em repouso com troponina positiva como consulta eletiva.',
    '- Pedir cateterismo para todo paciente sem estratificar risco.',
    '- Usar nitrato sem perguntar sobre PDE5.',
    '- Achar que stent dispensa estatina.',
    '- Controlar dor e esquecer LDL, tabagismo e diabetes.',
    '- Chamar toda dor torácica de ansiedade sem avaliar risco.',
    '',
    '---',
    '',
    '## Fontes',
    '',
    '- AHA/ACC/ACCP/ASPC/NLA/PCNA. **2023 Guideline for the Management of Patients With Chronic Coronary Disease**.',
    '- European Society of Cardiology. **2024 ESC Guidelines for the management of chronic coronary syndromes**.',
    '- Harrison Medicina Interna, 21ª edição, capítulos de cardiopatia isquêmica.',
    '- Cecil-Goldman Medicine, 26ª edição, capítulos de doença arterial coronariana.',
    '',
    '---',
    '',
    '## Questões mapeadas',
    '',
    '- **ENAMED 2025, Caderno preliminar, Q91** - dor torácica, infra de ST, troponina e GRACE alto; usada para diferenciar DAC crônica de SCA de alto risco, sem copiar enunciado.',
    '- **ENARE 2024, Acesso Direto Tipo 1** - caderno público revisado para termos de isquemia/dor torácica; usado como fonte de calibração temática, sem transcrição.',
  ].join('\n');
}

function updateFiles() {
  const md = material();
  writeText('data/materiais/clinica_medica5/cm5_a5.md', md);
  writeText('materiais/modulo5/clinica_medica5/cm5_a5.md', md);
}
function updateData() {
  const qData = readJson('data/questoes.json');
  let questoes = (qData.questoes || []).filter((item) => item.origem !== MARKER);
  const novos = questions();
  let maxQ = Math.max(0, ...questoes.map((item) => Number(item.id) || 0));
  for (const item of novos) item.id = ++maxQ;
  questoes.push(...novos);
  writeJson('data/questoes.json', { ...qData, questoes });

  const fcData = readJson('data/flashcards.json');
  let flashcards = (fcData.flashcards || []).filter((item) => item.origem !== MARKER);
  const novosCards = cards();
  let maxFc = Math.max(0, ...flashcards.map((item) => Number(item.id) || 0));
  for (const item of novosCards) item.id = ++maxFc;
  flashcards.push(...novosCards);
  writeJson('data/flashcards.json', { ...fcData, flashcards });
}
function updateRefs() {
  writeJson('data/refs/cm5_a5.refs.json', {
    aula_id: AULA,
    materia: 'clinica_medica5',
    tema: 'Doença Arterial Coronariana Crônica',
    generatedAt: '2026-05-07T18:15:00.000Z',
    marker: MARKER,
    fontes_base: [
      {
        tipo: 'diretriz',
        titulo: '2023 AHA/ACC/ACCP/ASPC/NLA/PCNA Guideline for the Management of Patients With Chronic Coronary Disease',
        url: 'https://www.acc.org/Guidelines/Guidelines/2023/07/20/12/34/Chronic-Coronary-Disease',
        uso: 'definição de CCD, metas terapêuticas, prevenção secundária e seleção de revascularização.',
      },
      {
        tipo: 'diretriz',
        titulo: '2024 ESC Guidelines for the management of chronic coronary syndromes',
        url: 'https://academic.oup.com/eurheartj/article/45/36/3415/7743115',
        uso: 'probabilidade pré-teste, testes anatômicos/funcionais e manejo de CCS.',
      },
    ],
    questoes_publicas: [
      {
        origem: 'ENAMED 2025',
        url: 'https://download.inep.gov.br/enamed/provas_e_gabaritos/2025_caderno_superampliado_preliminar.pdf',
        descricao: 'Questão pública com dor torácica, infra de ST, troponina positiva e GRACE alto; usada apenas como mapeamento para diferenciar DAC crônica de SCA.',
        copiar_enunciado: false,
      },
      {
        origem: 'ENARE 2024',
        url: 'https://mapa-vagas-enare-ebserh.conhecimento.fgv.br/provas-gabaritos-medica.html',
        descricao: 'Caderno público de acesso direto revisado por termos de isquemia/dor torácica; usado para calibração temática, sem transcrição.',
        copiar_enunciado: false,
      },
    ],
  });
}

updateFiles();
updateData();
updateRefs();

console.log('CM5 a5 atualizada com material, essenciais e flashcards.');
