import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const AULA = 'cm5_a8';
const MARKER = 'cm5_quality_contract_2026_05_07_cm5_a8';
const FIG_ID = 'CM5-A8-F01';

function p(rel) { return path.join(ROOT, rel); }
function readJson(rel) { return JSON.parse(fs.readFileSync(p(rel), 'utf8')); }
function writeJson(rel, data) { fs.mkdirSync(path.dirname(p(rel)), { recursive: true }); fs.writeFileSync(p(rel), `${JSON.stringify(data, null, 2)}\n`, 'utf8'); }
function writeText(rel, text) { fs.mkdirSync(path.dirname(p(rel)), { recursive: true }); fs.writeFileSync(p(rel), `${text.replace(/\r\n/g, '\n').replace(/\n*$/, '')}\n`, 'utf8'); }
function explanation(general, exp) { return [`Resumo: ${general}`, `A) ${exp.A}`, `B) ${exp.B}`, `C) ${exp.C}`, `D) ${exp.D}`].join('\n'); }
function q(dificuldade, caso_clinico, enunciado, opcoes, correta, general, exp) {
  return { materia: 'clinica_medica5', tema: AULA, aula_id: AULA, modulo: 5, dificuldade, caso_clinico, essencial: true, origem: MARKER, enunciado, opcoes, correta, explicacao_geral: general, explicacoes_opcoes: exp, explicacao: explanation(general, exp) };
}
function fc(dificuldade, frente, verso, explicacao, categoria, tags) {
  return { materia: 'clinica_medica5', tema: AULA, dificuldade, frente, verso, explicacao, origem: MARKER, categoria, tags };
}

function questions() {
  return [
    q(1, false, 'Qual padrão laboratorial define hipotireoidismo primário franco?', ['A) TSH elevado com T4 livre baixo.', 'B) TSH baixo com T4 livre alto.', 'C) TSH normal com cortisol baixo.', 'D) TSH baixo com prolactina alta isolada.'], 0, 'No hipotireoidismo primário, a tireoide falha; a hipófise aumenta TSH e o T4 livre cai.', { A: 'CORRETA: é o padrão clássico.', B: 'INCORRETA: sugere tireotoxicose/hipertireoidismo.', C: 'INCORRETA: eixo adrenal, não tireoide.', D: 'INCORRETA: não define hipotireoidismo.' }),
    q(2, true, 'Mulher com fadiga, constipação, pele seca, ganho de peso, TSH 18 mUI/L e T4 livre baixo. Qual tratamento é mais apropriado?', ['A) Levotiroxina, ajustada por TSH e contexto clínico.', 'B) Metimazol.', 'C) Radioiodo imediato.', 'D) Hidrocortisona como monoterapia definitiva.'], 0, 'Hipotireoidismo primário franco é tratado com reposição de levotiroxina, com cuidado em idosos/cardiopatas.', { A: 'CORRETA: repõe T4.', B: 'INCORRETA: metimazol trata hipertireoidismo.', C: 'INCORRETA: radioiodo pode causar hipotireoidismo, não tratar este caso.', D: 'INCORRETA: corticoide não repõe hormônio tireoidiano.' }),
    q(2, false, 'Qual padrão sugere hipertireoidismo primário?', ['A) TSH suprimido com T4 livre e/ou T3 elevados.', 'B) TSH alto com T4 livre baixo.', 'C) TSH alto com T4 livre alto sempre por tireoidite.', 'D) TSH normal sempre exclui tireotoxicose em qualquer contexto.'], 0, 'Hipertireoidismo primário reduz TSH por feedback e aumenta T4/T3. TSH isolado pode enganar em doença central, gestação, biotina e doença grave.', { A: 'CORRETA: padrão esperado.', B: 'INCORRETA: hipotireoidismo primário.', C: 'INCORRETA: TSH alto com T4 alto sugere resistência/TSHoma ou interferência, não tireoidite comum.', D: 'INCORRETA: contexto pode exigir T4 livre e revisão de interferências.' }),
    q(2, true, 'Paciente com perda de peso, tremor, bócio difuso, oftalmopatia e TSH suprimido com T4 livre alto. Qual etiologia é mais provável?', ['A) Doença de Graves.', 'B) Tireoidite subaguda.', 'C) Hipotireoidismo de Hashimoto.', 'D) Hipoparatireoidismo.'], 0, 'Graves é hipertireoidismo autoimune com bócio difuso e pode ter orbitopatia. TRAb ajuda.', { A: 'CORRETA: orbitopatia e bócio difuso são pistas fortes.', B: 'INCORRETA: tireoidite costuma ter dor e captação baixa.', C: 'INCORRETA: Hashimoto clássico causa hipotireoidismo.', D: 'INCORRETA: distúrbio do cálcio, não tireotoxicose.' }),
    q(2, false, 'Qual achado favorece tireoidite em vez de Graves?', ['A) Dor cervical anterior pós-viral e captação baixa.', 'B) TRAb alto e captação difusamente aumentada.', 'C) Oftalmopatia típica.', 'D) Bócio vascular difuso com sopro.'], 0, 'Tireoidite libera hormônio já formado, então antitireoidiano não resolve a causa; captação tende a ser baixa.', { A: 'CORRETA: dor pós-viral e captação baixa apontam tireoidite subaguda.', B: 'INCORRETA: favorece Graves.', C: 'INCORRETA: favorece Graves.', D: 'INCORRETA: favorece Graves.' }),
    q(3, true, 'Paciente com febre alta, delirium, FA rápida, vômitos e T4 livre muito elevado após suspender antitireoidiano. Qual quadro e conduta são prováveis?', ['A) Tempestade tireotóxica; betabloqueio, tionamida, iodo após tionamida, corticoide e suporte.', 'B) Hipotireoidismo subclínico; observar por 12 meses.', 'C) Crise adrenal isolada; só fludrocortisona.', 'D) Osteoporose assintomática; iniciar cálcio apenas.'], 0, 'Tempestade tireotóxica é emergência clínica. O tratamento é multimodal e não espera normalização laboratorial.', { A: 'CORRETA: sequência inclui bloquear síntese, liberação, conversão periférica e suporte.', B: 'INCORRETA: quadro é grave e hipermetabólico.', C: 'INCORRETA: corticoide pode entrar, mas não é crise adrenal isolada.', D: 'INCORRETA: não tem relação com o quadro agudo.' }),
    q(2, false, 'Qual nódulo tireoidiano deve ser avaliado por ultrassom e eventual PAAF conforme risco?', ['A) Nódulo com características suspeitas ou tamanho relevante conforme padrão ultrassonográfico.', 'B) Todo nódulo palpável precisa de tireoidectomia imediata.', 'C) Todo cisto simples de poucos milímetros precisa de PAAF urgente.', 'D) TSH normal exclui câncer de tireoide.'], 0, 'Nódulo tireoidiano é estratificado por ultrassom e tamanho; PAAF depende de risco ecográfico.', { A: 'CORRETA: é a lógica ATA/TIRADS.', B: 'INCORRETA: cirurgia universal é excesso.', C: 'INCORRETA: cisto simples pequeno geralmente não exige PAAF.', D: 'INCORRETA: TSH normal não exclui malignidade.' }),
    q(2, true, 'Mulher de 68 anos teve fratura de quadril após queda da própria altura. Densitometria ainda não foi feita. Qual interpretação é correta?', ['A) Fratura de fragilidade já define alto risco e pode indicar tratamento para osteoporose.', 'B) Osteoporose só existe se T-score for menor que -4,0.', 'C) Fratura de quadril por baixa energia é normal do envelhecimento.', 'D) Cálcio isolado cura osteoporose estabelecida.'], 0, 'Fratura de fragilidade, especialmente quadril ou vértebra, é critério clínico forte de osteoporose/alto risco.', { A: 'CORRETA: não espere T-score para reconhecer alto risco.', B: 'INCORRETA: T-score <= -2,5 define osteoporose densitométrica.', C: 'INCORRETA: é evento sentinela.', D: 'INCORRETA: cálcio/vitamina D são suporte, não tratamento completo de alto risco.' }),
    q(2, false, 'Qual T-score densitométrico define osteoporose?', ['A) <= -2,5.', 'B) Entre -1,0 e +1,0.', 'C) >= +2,5.', 'D) Exatamente zero.'], 0, 'Osteoporose densitométrica é T-score menor ou igual a -2,5 em sítios apropriados.', { A: 'CORRETA: corte clássico.', B: 'INCORRETA: faixa normal.', C: 'INCORRETA: não define baixa massa óssea.', D: 'INCORRETA: zero é média jovem.' }),
    q(2, true, 'Paciente em uso de prednisona crônica terá avaliação de risco ósseo. Qual fator secundário deve entrar no raciocínio?', ['A) Glicocorticoide crônico.', 'B) Miopia isolada.', 'C) Rinite alérgica leve sem corticoide sistêmico.', 'D) Cor dos olhos.'], 0, 'Glicocorticoide crônico é causa importante de osteoporose secundária e fratura.', { A: 'CORRETA: aumenta reabsorção óssea e reduz formação.', B: 'INCORRETA: não é fator maior.', C: 'INCORRETA: rinite leve sem corticoide sistêmico não explica.', D: 'INCORRETA: irrelevante.' }),
    q(2, false, 'Qual cuidado é obrigatório ao suspender denosumabe?', ['A) Planejar terapia anti-reabsortiva subsequente para reduzir rebote de perda óssea e fratura vertebral.', 'B) Suspender sem transição porque não há rebote.', 'C) Trocar por antibiótico.', 'D) Usar apenas analgésico se houver dor.'], 0, 'Denosumabe não deve ser atrasado ou suspenso sem plano anti-reabsortivo subsequente, pelo risco de rebote.', { A: 'CORRETA: ponto prático muito cobrado em segurança.', B: 'INCORRETA: há risco de rebote.', C: 'INCORRETA: antibiótico não trata remodelamento ósseo.', D: 'INCORRETA: analgesia não previne fratura.' }),
    q(2, false, 'Qual frase integra tireoide e osso corretamente?', ['A) Tireotoxicose sustentada aumenta remodelamento ósseo e risco de perda de massa/fratura.', 'B) Hipertireoidismo protege contra osteoporose.', 'C) TSH suprimido por excesso de levotiroxina é sempre seguro no idoso.', 'D) Hormônio tireoidiano não interage com osso.'], 0, 'Excesso de hormônio tireoidiano acelera turnover ósseo; em idoso e pós-menopausa, TSH suprimido por excesso de reposição aumenta risco.', { A: 'CORRETA: é a ligação clínica.', B: 'INCORRETA: aumenta risco ósseo.', C: 'INCORRETA: excesso iatrogênico é perigoso.', D: 'INCORRETA: tireoide tem impacto ósseo.' }),
  ];
}

function cards() {
  return [
    fc(1, 'Hipotireoidismo primário franco = TSH alto + {{c1::T4 livre baixo}}.', 'T4 livre baixo', 'A tireoide falha e a hipófise sobe TSH.', 'tireoide', ['cm5', 'hipotireoidismo']),
    fc(1, 'Hipertireoidismo primário = TSH suprimido + {{c1::T4 livre/T3 altos}}.', 'T4 livre/T3 altos', 'TSH baixo por feedback negativo.', 'tireoide', ['cm5', 'hipertireoidismo']),
    fc(2, 'Graves sugere bócio difuso, TRAb positivo e {{c1::oftalmopatia}}.', 'Oftalmopatia', 'É a etiologia autoimune clássica de hipertireoidismo.', 'graves', ['cm5', 'graves']),
    fc(2, 'Tireoidite libera hormônio pronto e costuma ter captação {{c1::baixa}}.', 'Baixa', 'Antitireoidiano não resolve liberação por inflamação.', 'tireoidite', ['cm5', 'tireoidite']),
    fc(3, 'Tempestade tireotóxica exige betabloqueador, tionamida, iodo depois da tionamida, corticoide e {{c1::suporte}}.', 'Suporte', 'É emergência sistêmica, não apenas T4 alto.', 'emergencia', ['cm5', 'tempestade_tireotoxica']),
    fc(2, 'Nódulo tireoidiano é estratificado por ultrassom; PAAF depende de {{c1::risco ecográfico e tamanho}}.', 'Risco ecográfico e tamanho', 'Não se punciona tudo nem se ignora nódulo suspeito.', 'nodulo', ['cm5', 'nodulo_tireoide']),
    fc(1, 'Osteoporose densitométrica = T-score {{c1::<= -2,5}}.', '<= -2,5', 'Fratura de fragilidade também pesa como diagnóstico/alto risco.', 'osso', ['cm5', 'osteoporose']),
    fc(2, 'Fratura de quadril por baixa energia é {{c1::fratura de fragilidade}}.', 'Fratura de fragilidade', 'Não deve ser tratada como queda banal.', 'osso', ['cm5', 'fragilidade']),
    fc(2, 'Glicocorticoide crônico é causa importante de {{c1::osteoporose secundária}}.', 'Osteoporose secundária', 'Risco aparece cedo e depende de dose/duração.', 'osso', ['cm5', 'corticoide']),
    fc(2, 'FRAX ajuda a estimar risco de {{c1::fratura}} em osteopenia/risco intermediário.', 'Fratura', 'Não trate osteopenia olhando só T-score.', 'osso', ['cm5', 'frax']),
    fc(3, 'Denosumabe não deve ser suspenso sem {{c1::anti-reabsortivo subsequente}}.', 'Anti-reabsortivo subsequente', 'Evita rebote de remodelamento e fraturas vertebrais.', 'tratamento', ['cm5', 'denosumabe']),
    fc(2, 'Excesso de hormônio tireoidiano aumenta turnover ósseo e risco de {{c1::fratura}}.', 'Fratura', 'Inclui hipertireoidismo e excesso iatrogênico de levotiroxina.', 'integracao', ['cm5', 'tireoide', 'osso']),
  ];
}

function material() {
  return [
    '---',
    'aula_id: cm5_a8',
    'materia: clinica_medica5',
    'modulo: 5',
    'tema: Disfunções da Tireoide e Metabolismo Ósseo',
    'versao_v3: 3.0.0',
    'status: published_local',
    'revisado_em: 2026-05-07',
    'checksum_lint: pass_pending',
    '---',
    '',
    '# Disfunções da Tireoide e Metabolismo Ósseo',
    '',
    '**Disciplina:** Clínica Médica 5',
    '**Módulo:** 5 | **Referência principal:** ATA + Endocrine Society + Harrison 21ª ed. + Cecil-Goldman 26ª ed.',
    '**Tempo de estudo sugerido:** 30-40 min',
    '',
    '---',
    '',
    '## Relevância Clínica e Acadêmica',
    '',
    'Tireoide e osso parecem temas separados, mas se cruzam o tempo inteiro: tireotoxicose acelera perda óssea, excesso de levotiroxina aumenta risco de fratura, e osteoporose exige olhar medicação, queda, rim, vitamina D e corticoide.',
    '',
    'O aluno costuma errar por interpretar TSH isolado, tratar tireoidite como Graves ou achar que osteoporose é só T-score. O padrão correto é integrar laboratório, clínica e risco.',
    '',
    '> **Pegadinha de prova:** TSH é ótimo, mas não é oráculo. Se há suspeita de doença central, gestação, doença grave, biotina ou amiodarona, você precisa interpretar com T4 livre e contexto.',
    '',
    '---',
    '',
    '### Figura sugerida',
    '',
    '**Figura-ID:** `CM5-A8-F01`',
    '',
    '**Quando usar:** após a introdução da fisiologia tireoidiana.',
    '',
    '**Por que importa:** a síntese hormonal explica iodeto, TPO, tireoglobulina, T3/T4, ação de antitireoidianos e radioiodo.',
    '',
    '---',
    '',
    '## Caso da Semana',
    '',
    '**Ato 1 - Entrada:** mulher de 32 anos chega com perda de peso, tremor, intolerância ao calor e palpitações. TSH suprimido, T4 livre alto e bócio difuso ao exame.',
    '',
    '**Ato 2 - Virada:** ela tem olhos proeminentes e dor óssea vaga. A família conta que ela usa suplementos com biotina em dose alta e que perdeu seguimento.',
    '',
    '**Ato 3 - Decisão:** antes de escolher radioiodo, antitireoidiano ou outra conduta, você precisa confirmar etiologia, reconhecer gravidade, perguntar sobre interferentes laboratoriais e lembrar que tireotoxicose sustentada também machuca osso.',
    '',
    '> **Moral da vinheta:** tireoide é laboratório com clínica. Se você trata só o número, erra a doença.',
    '',
    '---',
    '',
    '## Fisiologia Tireoidiana',
    '',
    'O eixo básico é TRH, TSH e T4/T3. A tireoide capta iodeto, organifica no coloide por ação da TPO, acopla resíduos na tireoglobulina e libera T4 e T3.',
    '',
    '**Macete MedGradPlus - TSH é o alarme, T4 é o incêndio:** TSH muda cedo, mas T4 livre mostra a intensidade hormonal atual. Se o eixo central está doente, o alarme pode falhar.',
    '',
    '| Situação | TSH | T4 livre | Interpretação |',
    '|---|---|---|---|',
    '| **Hipotireoidismo primário franco** | alto | baixo | falha tireoidiana |',
    '| **Hipotireoidismo subclínico** | alto | normal | falha inicial ou transitória |',
    '| **Hipertireoidismo primário franco** | baixo | alto | excesso tireoidiano |',
    '| **Hipertireoidismo subclínico** | baixo | normal | excesso leve ou supressão |',
    '| **Doença central** | baixo/inadequado | baixo | hipófise/hipotálamo |',
    '',
    '---',
    '',
    '## Hipotireoidismo',
    '',
    'Quadro típico: fadiga, sonolência, pele seca, constipação, intolerância ao frio, ganho de peso discreto, bradicardia, rouquidão e reflexos lentos.',
    '',
    'A causa mais comum em muitos cenários é tireoidite autoimune de Hashimoto. Anti-TPO ajuda a confirmar autoimunidade, mas o tratamento do hipotireoidismo franco depende do TSH/T4 e da clínica.',
    '',
    '| Grupo | Cuidado |',
    '|---|---|',
    '| **Adulto jovem saudável** | reposição plena pode ser usada conforme peso/contexto |',
    '| **Idoso/cardiopata** | começar baixo e subir devagar |',
    '| **Gestante** | metas específicas e ajuste de dose |',
    '| **Doença central** | monitorar T4 livre, não TSH isolado |',
    '',
    '> **Armadilha de banca:** em hipotireoidismo central, TSH pode estar normal ou discretamente baixo. Não use TSH como alvo único.',
    '',
    '---',
    '',
    '## Hipertireoidismo e Tireotoxicose',
    '',
    'Tireotoxicose é excesso de hormônio tireoidiano circulante. Hipertireoidismo é quando a tireoide está produzindo demais. Tireoidite pode causar tireotoxicose sem hiperprodução sustentada.',
    '',
    '| Etiologia | Pista | Captação | Tratamento típico |',
    '|---|---|---|---|',
    '| **Graves** | TRAb, bócio difuso, orbitopatia | alta difusa | antitireoidiano, radioiodo ou cirurgia |',
    '| **Bócio multinodular tóxico** | idoso, nódulos, evolução lenta | áreas quentes | radioiodo/cirurgia/controle |',
    '| **Adenoma tóxico** | nódulo quente único | focal | radioiodo/cirurgia |',
    '| **Tireoidite subaguda** | dor pós-viral, VHS/PCR | baixa | AINE/corticoide e beta bloqueio |',
    '| **Excesso exógeno** | uso de hormônio | baixa | suspender/reduzir |',
    '',
    '**Macete MedGradPlus - Graves fabrica, tireoidite vaza:** se fabrica, antitireoidiano faz sentido. Se só vaza hormônio pronto, trate inflamação e sintomas.',
    '',
    '---',
    '',
    '## Tempestade Tireotóxica',
    '',
    'É emergência clínica: febre, delirium, taquiarritmia, IC, vômitos/diarreia e tireotoxicose. O gatilho pode ser infecção, cirurgia, trauma, parto ou suspensão de antitireoidiano.',
    '',
    'Conduta integrada:',
    '',
    '1. Suporte, UTI se grave, tratar gatilho.',
    '2. Betabloqueador se não contraindicado.',
    '3. Tionamida para bloquear síntese.',
    '4. Iodo depois da tionamida para bloquear liberação.',
    '5. Corticoide para reduzir conversão T4-T3 e cobrir adrenal relativa.',
    '',
    '> **Pérola Clínica:** iodo entra depois da tionamida. Dar iodo antes pode fornecer substrato para mais hormônio em alguns contextos.',
    '',
    '---',
    '',
    '## Nódulos Tireoidianos',
    '',
    'Nódulo não é sinônimo de câncer, mas também não é para ignorar. A sequência prática é TSH, ultrassom de qualidade e PAAF conforme risco ecográfico e tamanho.',
    '',
    '| Achado ultrassonográfico | Risco | Comentário |',
    '|---|---|---|',
    '| **Hipoecogenicidade marcada** | maior | pesa junto com outros sinais |',
    '| **Microcalcificações** | maior | sugerem corpos psamomatosos |',
    '| **Margens irregulares** | maior | suspeição de invasão |',
    '| **Mais alto que largo** | maior | padrão suspeito |',
    '| **Cisto simples** | baixo | raramente exige PAAF |',
    '',
    'Se TSH estiver baixo, cintilografia pode identificar nódulo hiperfuncionante; nódulo quente raramente é maligno.',
    '',
    '---',
    '',
    '## Metabolismo Ósseo',
    '',
    'Osso é tecido vivo. Osteoblasto forma, osteoclasto reabsorve, vitamina D e PTH modulam cálcio/fósforo, e estrogênio freia reabsorção.',
    '',
    'Osteoporose é fragilidade esquelética com aumento de risco de fratura. Pode ser diagnosticada por T-score ou por fratura de fragilidade em contexto apropriado.',
    '',
    '| Conceito | Definição |',
    '|---|---|',
    '| **Normal** | T-score >= -1,0 |',
    '| **Osteopenia** | T-score entre -1,0 e -2,5 |',
    '| **Osteoporose** | T-score <= -2,5 |',
    '| **Fratura de fragilidade** | baixa energia, local típico | alto risco mesmo antes do DXA |',
    '',
    '---',
    '',
    '## Avaliação de Osteoporose',
    '',
    'Perguntas obrigatórias:',
    '',
    '- Já teve fratura de fragilidade?',
    '- Usa glicocorticoide crônico?',
    '- Tem queda recorrente?',
    '- Há DRC, hiperparatireoidismo, tireotoxicose ou má absorção?',
    '- Usa álcool, tabaco ou medicações de risco?',
    '- Qual ingestão de cálcio, vitamina D e exposição solar?',
    '',
    '| Exame | Uso |',
    '|---|---|',
    '| **DXA** | T-score e seguimento |',
    '| **Cálcio, fósforo, FA, creatinina, 25-OH vitamina D** | causas secundárias |',
    '| **PTH** | se cálcio alterado/DRC/suspeita |',
    '| **FRAX** | risco em osteopenia/decisão terapêutica |',
    '',
    '> **Armadilha de banca:** osteopenia não é automaticamente "não tratar". Se FRAX alto ou fratura de fragilidade, risco manda mais que rótulo.',
    '',
    '---',
    '',
    '## Tratamento da Osteoporose',
    '',
    'Base para todos: exercício resistido e de impacto conforme segurança, prevenção de quedas, cálcio dietético adequado, vitamina D se deficiência, parar tabaco e reduzir álcool.',
    '',
    '| Classe | Quando pensar | Cuidado |',
    '|---|---|---|',
    '| **Bisfosfonato oral** | primeira linha frequente | esôfago, adesão, rim |',
    '| **Bisfosfonato IV** | intolerância oral ou adesão | fase aguda, rim |',
    '| **Denosumabe** | alto risco/DRC selecionada | não suspender sem transição |',
    '| **Anabólico** | muito alto risco/fraturas múltiplas | custo e sequência terapêutica |',
    '| **Romosozumabe** | muito alto risco selecionado | risco cardiovascular em avaliação |',
    '',
    'Denosumabe merece destaque: atrasar ou parar sem anti-reabsortivo subsequente pode gerar rebote de remodelamento e fraturas vertebrais.',
    '',
    '---',
    '',
    '## Integração Tireoide e Osso',
    '',
    'Excesso de hormônio tireoidiano aumenta turnover ósseo. Isso vale para Graves, bócio tóxico e excesso iatrogênico de levotiroxina.',
    '',
    'Perfis de maior risco:',
    '',
    '- Pós-menopausa.',
    '- Idosos.',
    '- TSH cronicamente suprimido.',
    '- História de fratura.',
    '- Uso de corticoide.',
    '- Baixa ingestão de cálcio/vitamina D.',
    '',
    'O objetivo é não trocar uma doença por outra: tratar hipotireoidismo sem suprimir TSH desnecessariamente, e tratar hipertireoidismo antes que o osso pague a conta.',
    '',
    '---',
    '',
    '## Pontos-Chave',
    '',
    '- Hipotireoidismo primário franco: TSH alto e T4 livre baixo.',
    '- Hipertireoidismo primário: TSH baixo e T4/T3 altos.',
    '- Graves fabrica hormônio; tireoidite vaza hormônio.',
    '- Antitireoidiano não trata a fisiopatologia da tireoidite.',
    '- Tempestade tireotóxica é emergência sistêmica.',
    '- Nódulo tireoidiano exige ultrassom e PAAF por risco/tamanho.',
    '- Osteoporose é risco de fratura, não só T-score.',
    '- Fratura de fragilidade é evento sentinela.',
    '- Glicocorticoide crônico causa osteoporose secundária.',
    '- Denosumabe não deve ser suspenso sem plano.',
    '- Tireotoxicose sustentada prejudica osso.',
    '- Excesso de levotiroxina em idoso é perigoso.',
    '',
    '---',
    '',
    '## Mini Quiz',
    '',
    '**1. Hipotireoidismo primário franco tem qual padrão?**',
    '',
    '- [x] TSH alto e T4 livre baixo',
    '- [ ] TSH baixo e T4 livre alto',
    '- [ ] TSH baixo e T4 livre baixo sempre adrenal',
    '- [ ] TSH normal exclui tudo',
    '',
    '> **Explicação:** falha tireoidiana primária eleva TSH e reduz T4.',
    '',
    '**2. Qual pista favorece Graves?**',
    '',
    '- [x] Oftalmopatia e bócio difuso',
    '- [ ] Dor cervical pós-viral com captação baixa',
    '- [ ] TSH alto e T4 baixo',
    '- [ ] Fratura de quadril',
    '',
    '> **Explicação:** orbitopatia é pista forte de Graves.',
    '',
    '**3. Tireoidite subaguda costuma ter qual padrão de captação?**',
    '',
    '- [x] Baixa',
    '- [ ] Difusamente alta',
    '- [ ] Focal alta obrigatória',
    '- [ ] Sempre normal',
    '',
    '> **Explicação:** há liberação de hormônio pronto, não síntese aumentada.',
    '',
    '**4. Osteoporose densitométrica é definida por qual T-score?**',
    '',
    '- [x] <= -2,5',
    '- [ ] >= +2,5',
    '- [ ] 0',
    '- [ ] Entre -1 e +1',
    '',
    '> **Explicação:** T-score menor ou igual a -2,5 define osteoporose densitométrica.',
    '',
    '**5. Qual cuidado é essencial ao suspender denosumabe?**',
    '',
    '- [x] Planejar anti-reabsortivo subsequente',
    '- [ ] Suspender sem transição',
    '- [ ] Trocar por antibiótico',
    '- [ ] Usar só cálcio se dor',
    '',
    '> **Explicação:** há risco de rebote e fratura vertebral.',
    '',
    '**6. Excesso crônico de hormônio tireoidiano faz o quê no osso?**',
    '',
    '- [x] Aumenta turnover e risco de fratura',
    '- [ ] Protege contra osteoporose',
    '- [ ] Não interfere',
    '- [ ] Cura osteopenia',
    '',
    '> **Explicação:** tireotoxicose sustentada acelera perda óssea.',
    '',
    '---',
    '',
    '## Pré-Prova',
    '',
    '### Síntese para a prova',
    '',
    'Tireoide: leia TSH com T4 livre e contexto. Hipotireoidismo primário é TSH alto + T4 baixo; hipertireoidismo primário é TSH baixo + T4/T3 altos. Graves fabrica hormônio; tireoidite vaza. Nódulo se decide por ultrassom e PAAF conforme risco. Osso: osteoporose é risco de fratura. Fratura de fragilidade, T-score, FRAX, corticoide, queda e DRC importam.',
    '',
    '### Macete-âncora',
    '',
    '**Tireoide é eixo; osso é risco. Não trate número isolado.**',
    '',
    '- TSH alto + T4 baixo: hipotireoidismo primário.',
    '- TSH baixo + T4/T3 alto: hipertireoidismo.',
    '- Graves: TRAb/orbitopatia/captação alta.',
    '- Tireoidite: dor ou inflamação/captação baixa.',
    '- Osteoporose: T-score <= -2,5 ou fratura de fragilidade.',
    '- Denosumabe: não parar sem plano.',
    '',
    '### Erros que derrubam nota',
    '',
    '- Interpretar TSH sem T4 livre quando há suspeita central.',
    '- Dar antitireoidiano para tireoidite como se fosse Graves.',
    '- Esquecer biotina interferindo no laboratório.',
    '- Puncionar todo nódulo sem critério ultrassonográfico.',
    '- Tratar osteopenia apenas pelo nome e ignorar FRAX/fratura.',
    '- Suspender denosumabe sem anti-reabsortivo subsequente.',
    '',
    '---',
    '',
    '## Fontes',
    '',
    '- American Thyroid Association. **Guidelines for Hyperthyroidism and Thyrotoxicosis**.',
    '- American Thyroid Association. **Guidelines for Thyroid Nodules and Differentiated Thyroid Cancer**.',
    '- Endocrine Society. **Pharmacological Management of Osteoporosis in Postmenopausal Women**.',
    '- Bone Health and Osteoporosis Foundation. **Clinician Guide to Prevention and Treatment of Osteoporosis**.',
    '- Harrison Medicina Interna, 21ª edição, capítulos de tireoide e metabolismo ósseo.',
    '- Cecil-Goldman Medicine, 26ª edição, capítulos de tireoide e osteoporose.',
  ].join('\n');
}

function updateFiles() { const md = material(); writeText('data/materiais/clinica_medica5/cm5_a8.md', md); writeText('materiais/modulo5/clinica_medica5/cm5_a8.md', md); }
function updateData() {
  const qData = readJson('data/questoes.json');
  let questoes = (qData.questoes || []).filter((item) => item.origem !== MARKER);
  const novos = questions();
  let maxQ = Math.max(0, ...questoes.map((item) => Number(item.id) || 0));
  for (const item of novos) item.id = ++maxQ;
  questoes.push(...novos);
  writeJson('data/questoes.json', { ...qData, questoes });

  const fcData = readJson('data/flashcards.json');
  let flashcards = (fcData.flashcards || []).filter((item) => item.origem !== MARKER);
  const novosCards = cards();
  let maxFc = Math.max(0, ...flashcards.map((item) => Number(item.id) || 0));
  for (const item of novosCards) item.id = ++maxFc;
  flashcards.push(...novosCards);
  writeJson('data/flashcards.json', { ...fcData, flashcards });
}
function updateFigures() {
  const rel = 'data/materiais_figuras.json';
  const data = readJson(rel);
  const entries = (data.entries || []).filter((fig) => fig.id !== FIG_ID);
  entries.push({
    id: FIG_ID,
    modulo: 5,
    disciplina: 'clinica_medica5',
    aula: AULA,
    caminhoMaterial: 'materiais/modulo5/clinica_medica5/cm5_a8.md',
    momento: 'Após fisiologia tireoidiana',
    descricaoVisual: 'Esquema da síntese de hormônios tireoidianos com iodeto, TPO, tireoglobulina, T3 e T4.',
    tipoSugerido: 'Esquema didático em SVG.',
    buscaCommonsEn: 'Thyroid hormone synthesis SVG',
    buscaCommonsPt: 'síntese hormônio tireoidiano TPO tireoglobulina',
    status: 'encontrada',
    urlImagem: 'https://upload.wikimedia.org/wikipedia/commons/e/e4/Thyroid_hormone_synthesis.svg',
    urlThumbnail: '',
    urlPaginaCommons: 'https://commons.wikimedia.org/wiki/File:Thyroid_hormone_synthesis.svg',
    licenca: 'CC0',
    credito: 'Mikael Häggström, via Wikimedia Commons',
    legenda: 'Síntese de hormônios tireoidianos: captação de iodeto, organificação, acoplamento e liberação de T3/T4.',
    notas: 'Imagem útil para ligar fisiologia, antitireoidianos, radioiodo e tireoidites.',
  });
  writeJson(rel, { ...data, updatedAt: new Date().toISOString(), entries });
}
function updateRefs() {
  writeJson('data/refs/cm5_a8.refs.json', {
    aula_id: AULA,
    materia: 'clinica_medica5',
    tema: 'Disfunções da Tireoide e Metabolismo Ósseo',
    generatedAt: '2026-05-07T20:10:00.000Z',
    marker: MARKER,
    fontes_base: [
      { tipo: 'diretriz', titulo: 'ATA Guidelines for Hyperthyroidism and Thyrotoxicosis', url: 'https://www.thyroid.org/guidelines-hyperthyroidism-thyrotoxicosis/', uso: 'hipertireoidismo, Graves, tireoidite e tempestade tireotóxica.' },
      { tipo: 'diretriz', titulo: 'ATA Guidelines for Thyroid Nodules and Differentiated Thyroid Cancer', url: 'https://www.thyroid.org/endorsed-guidelines-differentiated/', uso: 'nódulos, ultrassom e PAAF.' },
      { tipo: 'diretriz', titulo: 'Endocrine Society - Osteoporosis in Postmenopausal Women', url: 'https://www.endocrine.org/clinical-practice-guidelines/osteoporosis-in-postmenopausal-women', uso: 'tratamento farmacológico e segurança de denosumabe.' },
    ],
    imagem: FIG_ID,
  });
}

updateFiles();
updateData();
updateFigures();
updateRefs();

console.log('CM5 a8 atualizada com material, essenciais, flashcards e figura.');
