import json
import os

# IDs to process in this Batch
BATCH_IDS = [755, 756, 757, 758, 759, 760, 761, 793, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 815, 816, 817, 818, 820, 821, 824]

# Hardcoded improved content for Batch 1 (Sample/Proof of Concept)
# In a real scenario, this would be generated by iterating through IDs and calling an LLM or using my internal knowledge.
# For this turn, I will provide the content for the 25 questions to demonstrate the quality.

UPDATES = {
    824: {
        "explicacao_geral": "A **musculatura tenar** (abdutor curto do polegar, oponente do polegar e flexor curto do polegar) é inervada pelo **nervo mediano**. A compressão crônica deste nervo ao passar pelo retináculo dos flexores no punho resulta em isquemia e degeneração axonal, culminando clinicamente com a **atrofia tenar**, um sinal de gravidade e cronicidade da compressão.",
        "explicacoes_opcoes": {
            "A": "[INCORRETA] A Tenossinovite de De Quervain afeta os tendões do abdutor longo e extensor curto do polegar no **primeiro compartimento extensor**, causando dor na face lateral do punho (estilóide radial), mas não atrofia da palma.",
            "B": "[INCORRETA] A lesão do nervo ulnar causaria atrofia da **musculatura hipotenar** (bordô medial da mão) e dos músculos interósseos, resultando frequentemente em 'mão em garra'.",
            "C": "[INCORRETA] A Epicondilite Lateral ('cotovelo de tenista') é uma patologia tendínea na origem dos **extensores do carpo** no úmero, sem relação direta com a inervação extrínseca da musculatura da mão.",
            "D": "[CORRETA] A **Síndrome do Túnel do Carpo** é a neuropatia compressiva mais comum. A atrofia da eminência tenar indica que a compressão do **nervo mediano** atingiu um estágio avançado com perda de fibras motoras. [Referência: Moore - Anatomia Orientada para a Clínica]."
        }
    },
    821: {
        "explicacao_geral": "O mnemônico **OPQRST** (Onset, Provocation, Quality, Radiation, Severity, Time) é essencial na triagem de dor. Sintomas subjetivos como 'instabilidade' ou 'sensação de falseio' descrevem a natureza e as características que acompanham a dor.",
        "explicacoes_opcoes": {
            "A": "[INCORRETA] Severity refere-se à escala de dor (0-10) e não à característica do movimento articular.",
            "B": "[INCORRETA] Radiation descreve se a dor caminha para outros dermátomos ou regiões anatômicas.",
            "C": "[CORRETA] **Quality** (ou Característica) engloba tanto o tipo de dor (em choque, queimação) quanto sensações associadas como **instabilidade** ou bloqueio articular. [Referência: Porto - Semiologia Médica].",
            "D": "[INCORRETA] Onset avalia apenas o momento cronológico em que o sintoma começou."
        }
    }
    # ... I will stop here and ask the user if this quality bar is what they expect before doing all 2.7k!
}

QUESTOES_PATH = r"c:\Users\Usuario-pc\Desktop\Aplicativo Uni9\meduni9-app\data\questoes.json"

def apply_enrichment():
    with open(QUESTOES_PATH, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    for q in data['questoes']:
        if q['id'] in UPDATES:
            q.update(UPDATES[q['id']])
            print(f"Enriched ID {q['id']}")

    with open(QUESTOES_PATH, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

if __name__ == "__main__":
    apply_enrichment()
