import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const file = path.join(__dirname, "..", "data", "questoes.json");
const novas = [
{id:432,materia:"bmf1",tema:"bmf1_a5",modulo:1,dificuldade:2,correta:0,enunciado:"A unidade estrutural do osso compacto organizada em lamelas concÃªntricas ao redor de um canal central Ã©:",opcoes:["A) Osteon (sistema de Havers)","B) Lacuna condrocitÃ¡ria","C) CorpÃºsculo renal","D) Disco intercalar"],explicacao_geral:"O osteon integra lamelas, canal vascular e comunicaÃ§Ã£o celular no osso compacto.",explicacoes_opcoes:{A:"Correta: essa Ã© a unidade clÃ¡ssica da cortical.",B:"Incorreta: refere-se Ã  cartilagem.",C:"Incorreta: pertence ao rim.",D:"Incorreta: pertence ao tecido cardÃ­aco."},explicacao:"A organizaÃ§Ã£o osteonal explica resistÃªncia e nutriÃ§Ã£o da cortical Ã³ssea."},
{id:433,materia:"bmf1",tema:"bmf1_a5",modulo:1,dificuldade:1,correta:1,enunciado:"Qual associaÃ§Ã£o estÃ¡ correta para osso compacto?",opcoes:["A) Rede trabecular frouxa como padrÃ£o dominante","B) PredomÃ­nio de osteons e maior resistÃªncia mecÃ¢nica","C) Matriz sem mineralizaÃ§Ã£o","D) AusÃªncia de vasos"],explicacao_geral:"Osso compacto tem organizaÃ§Ã£o densa voltada a suporte estrutural.",explicacoes_opcoes:{A:"Incorreta: padrÃ£o trabecular Ã© tÃ­pico da esponjosa.",B:"Correta: descreve a cortical corretamente.",C:"Incorreta: o tecido Ã³sseo Ã© mineralizado.",D:"Incorreta: hÃ¡ vascularizaÃ§Ã£o pelos canais."},explicacao:"A diferenÃ§a entre compacto e esponjoso Ã© morfolÃ³gica e funcional, nÃ£o apenas topogrÃ¡fica."},
{id:434,materia:"bmf1",tema:"bmf1_a5",modulo:1,dificuldade:2,correta:2,enunciado:"A adaptaÃ§Ã£o da arquitetura Ã³ssea Ã s cargas mecÃ¢nicas Ã© explicada por qual princÃ­pio?",opcoes:["A) Lei de Laplace","B) PrincÃ­pio de Starling","C) Lei de Wolff","D) Efeito Bohr"],explicacao_geral:"A remodelaÃ§Ã£o Ã³ssea depende do padrÃ£o de uso e tensÃ£o mecÃ¢nica.",explicacoes_opcoes:{A:"Incorreta: descreve outra relaÃ§Ã£o fisiolÃ³gica.",B:"Incorreta: refere-se a trocas capilares.",C:"Correta: princÃ­pio clÃ¡ssico de adaptaÃ§Ã£o Ã³ssea.",D:"Incorreta: relaciona-se a transporte de oxigÃªnio."},explicacao:"Wolff conecta estÃ­mulo mecÃ¢nico e remodelaÃ§Ã£o estrutural do osso."},
{id:435,materia:"bmf1",tema:"bmf1_a5",modulo:1,dificuldade:2,correta:3,enunciado:"Qual cÃ©lula sintetiza osteoide durante formaÃ§Ã£o Ã³ssea?",opcoes:["A) OsteÃ³cito","B) Osteoclasto","C) CondrÃ³cito","D) Osteoblasto"],explicacao_geral:"A deposiÃ§Ã£o de matriz orgÃ¢nica Ã³ssea Ã© funÃ§Ã£o do osteoblasto.",explicacoes_opcoes:{A:"Incorreta: osteÃ³cito Ã© cÃ©lula madura inserida na matriz.",B:"Incorreta: osteoclasto reabsorve osso.",C:"Incorreta: condrÃ³cito sintetiza matriz cartilaginosa.",D:"Correta: osteoblasto produz osteoide."},explicacao:"Na fisiologia Ã³ssea, formaÃ§Ã£o e reabsorÃ§Ã£o dependem de tipos celulares distintos e complementares."},
{id:436,materia:"bmf1",tema:"bmf1_a5",modulo:1,dificuldade:3,correta:0,enunciado:"Qual funÃ§Ã£o dos osteÃ³citos Ã© mais importante na resposta ao desuso prolongado?",opcoes:["A) Mecanossensibilidade e sinalizaÃ§Ã£o para remodelaÃ§Ã£o","B) ProduÃ§Ã£o principal de surfactante","C) SÃ­ntese de hemoglobina","D) SecreÃ§Ã£o de insulina"],explicacao_geral:"OsteÃ³citos atuam como sensores mecÃ¢nicos na matriz mineralizada.",explicacoes_opcoes:{A:"Correta: detectam carga e modulam atividade de osteoblastos/osteoclastos.",B:"Incorreta: funÃ§Ã£o pulmonar.",C:"Incorreta: funÃ§Ã£o hematolÃ³gica eritroide.",D:"Incorreta: funÃ§Ã£o pancreÃ¡tica."},explicacao:"A perda de estÃ­mulo mecÃ¢nico altera sinalizaÃ§Ã£o osteocitÃ¡ria e favorece perda de massa Ã³ssea."},
{id:437,materia:"bmf1",tema:"bmf1_a5",modulo:1,dificuldade:2,correta:1,enunciado:"O osteoclasto Ã© melhor caracterizado como:",opcoes:["A) CÃ©lula mononuclear formadora de osteoide","B) CÃ©lula multinucleada reabsortiva derivada da linhagem hematopoÃ©tica","C) CÃ©lula epitelial de revestimento","D) CÃ©lula nervosa especializada"],explicacao_geral:"ReabsorÃ§Ã£o Ã³ssea depende de cÃ©lulas gigantes multinucleadas da linhagem monÃ³cito-macrÃ³fago.",explicacoes_opcoes:{A:"Incorreta: essa descriÃ§Ã£o se aproxima do osteoblasto.",B:"Correta: define origem e funÃ§Ã£o do osteoclasto.",C:"Incorreta: osteoclasto nÃ£o Ã© epitelial.",D:"Incorreta: nÃ£o pertence ao tecido nervoso."},explicacao:"Conhecer a origem hematopoÃ©tica do osteoclasto ajuda a entender terapias anti-reabsortivas."},
{id:438,materia:"bmf1",tema:"bmf1_a5",modulo:1,dificuldade:1,correta:2,enunciado:"A ossificaÃ§Ã£o direta a partir de mesÃªnquima Ã© denominada:",opcoes:["A) Endocondral","B) Periosteal secundÃ¡ria","C) Intramembranosa","D) MetaplÃ¡sica"],explicacao_geral:"Na intramembranosa, nÃ£o hÃ¡ molde cartilaginoso prÃ©vio.",explicacoes_opcoes:{A:"Incorreta: endocondral envolve cartilagem inicial.",B:"Incorreta: nÃ£o Ã© o termo principal do mecanismo.",C:"Correta: nome correto do processo.",D:"Incorreta: nÃ£o Ã© classificaÃ§Ã£o padrÃ£o para o desenvolvimento Ã³sseo normal."},explicacao:"Ossos da calvÃ¡ria sÃ£o exemplos clÃ¡ssicos de formaÃ§Ã£o por via intramembranosa."},
{id:439,materia:"bmf1",tema:"bmf1_a5",modulo:1,dificuldade:2,correta:3,enunciado:"A maioria dos ossos longos se forma por:",opcoes:["A) OssificaÃ§Ã£o intramembranosa pura","B) MineralizaÃ§Ã£o direta de tendÃ£o","C) TransformaÃ§Ã£o de tecido muscular","D) OssificaÃ§Ã£o endocondral"],explicacao_geral:"O crescimento longitudinal dos ossos longos depende de modelo cartilaginoso inicial.",explicacoes_opcoes:{A:"Incorreta: nÃ£o Ã© a via predominante dos ossos longos.",B:"Incorreta: tendÃ£o nÃ£o Ã© molde fisiolÃ³gico padrÃ£o.",C:"Incorreta: nÃ£o ocorre no desenvolvimento normal.",D:"Correta: esse Ã© o mecanismo principal."},explicacao:"A placa epifisÃ¡ria e o molde cartilaginoso sÃ£o elementos-chave da ossificaÃ§Ã£o endocondral."},
{id:440,materia:"bmf1",tema:"bmf1_a5",modulo:1,dificuldade:3,correta:1,enunciado:"Qual distinÃ§Ã£o entre osteoporose e osteomalÃ¡cia estÃ¡ correta?",opcoes:["A) Osteoporose Ã© defeito primÃ¡rio de mineralizaÃ§Ã£o; osteomalÃ¡cia Ã© perda exclusiva de massa","B) Osteoporose envolve reduÃ§Ã£o de massa/arquitetura; osteomalÃ¡cia envolve mineralizaÃ§Ã£o inadequada da matriz","C) Ambas decorrem de mecanismo idÃªntico","D) OsteomalÃ¡cia aumenta densidade mineral em excesso"],explicacao_geral:"Uma condiÃ§Ã£o afeta quantidade e microarquitetura; a outra afeta qualidade de mineralizaÃ§Ã£o.",explicacoes_opcoes:{A:"Incorreta: as definiÃ§Ãµes estÃ£o invertidas.",B:"Correta: resume o contraste fisiopatolÃ³gico central.",C:"Incorreta: mecanismos nÃ£o sÃ£o idÃªnticos.",D:"Incorreta: osteomalÃ¡cia nÃ£o causa hipermineralizaÃ§Ã£o."},explicacao:"Diferenciar esses conceitos evita erro de interpretaÃ§Ã£o entre exame laboratorial e densitometria."},
{id:441,materia:"bmf1",tema:"bmf1_a5",modulo:1,dificuldade:3,correta:3,enunciado:"Na consolidaÃ§Ã£o de fratura sem complicaÃ§Ãµes, qual etapa representa o desfecho final esperado?",opcoes:["A) PersistÃªncia de hematoma sem reparo","B) FormaÃ§Ã£o exclusiva de tecido fibroso","C) Necrose infectada obrigatÃ³ria","D) FormaÃ§Ã£o de calo Ã³sseo com remodelaÃ§Ã£o progressiva"],explicacao_geral:"A cicatrizaÃ§Ã£o Ã³ssea evolui de inflamaÃ§Ã£o para reparo e remodelaÃ§Ã£o.",explicacoes_opcoes:{A:"Incorreta: hematoma Ã© etapa inicial.",B:"Incorreta: o reparo fisiolÃ³gico evolui para tecido Ã³sseo.",C:"Incorreta: infecÃ§Ã£o nÃ£o faz parte do curso esperado.",D:"Correta: este Ã© o resultado fisiolÃ³gico da consolidaÃ§Ã£o."},explicacao:"A remodelaÃ§Ã£o final restabelece progressivamente forma e resistÃªncia do segmento fraturado."}
];
function validar(a){const g=[0,1,2,3].map(k=>a.filter(q=>q.correta===k).length).join(",");const d={1:0,2:0,3:0};for(const q of a)d[q.dificuldade]++;if(g!=="2,3,2,3")throw new Error(g);if(`${d[1]}/${d[2]}/${d[3]}`!=="2/5/3")throw new Error(`${d[1]}/${d[2]}/${d[3]}`);}
function main(){validar(novas);const data=JSON.parse(fs.readFileSync(file,"utf8"));const map=Object.fromEntries(novas.map(q=>[q.id,q]));let n=0;for(let i=0;i<data.questoes.length;i++){if(map[data.questoes[i].id]&&data.questoes[i].tema==="bmf1_a5"){data.questoes[i]=map[data.questoes[i].id];n++;}}if(n!==10)throw new Error(`bmf1_a5 ${n}`);fs.writeFileSync(file,JSON.stringify(data,null,2)+"\n","utf8");JSON.parse(fs.readFileSync(file,"utf8"));console.log("bmf1_a5 OK");}
main();
