import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const file = path.join(__dirname, "..", "data", "questoes.json");

const novas = [
  { id: 372, materia: "bmf1", tema: "bmf1_a2", modulo: 1, dificuldade: 3, correta: 3, enunciado: "Em uma úlcera gástrica profunda, a perda do revestimento expõe tecido rico em matriz extracelular, vasos e células de defesa. Esse tecido é:", opcoes: ["A) Epitélio simples cilíndrico", "B) Tecido muscular estriado", "C) Cartilagem elástica", "D) Tecido conjuntivo"], explicacao_geral: "Abaixo do epitélio, o estroma conjuntivo oferece suporte, nutrição e resposta inflamatória.", explicacoes_opcoes: { A: "Incorreta: epitélio é tecido de revestimento.", B: "Incorreta: não é o tecido predominante no leito da úlcera.", C: "Incorreta: cartilagem não compõe a mucosa gástrica normal.", D: "Correta: o conjuntivo subjacente contém matriz, vasos e células imunes." }, explicacao: "Quando a mucosa se rompe, o compartimento exposto é o conjuntivo, não tecido muscular ou cartilaginoso." },
  { id: 373, materia: "bmf1", tema: "bmf1_a2", modulo: 1, dificuldade: 1, correta: 0, enunciado: "Qual característica é típica do epitélio de revestimento?", opcoes: ["A) Polaridade apical-basal e função de barreira", "B) Matriz mineralizada abundante", "C) Contração voluntária predominante", "D) Condução elétrica como função principal"], explicacao_geral: "Epitélios revestem superfícies e controlam trocas com o meio.", explicacoes_opcoes: { A: "Correta: polaridade celular e barreira são marcas do epitélio.", B: "Incorreta: isso descreve tecido ósseo.", C: "Incorreta: essa função é do músculo.", D: "Incorreta: essa função é típica do tecido nervoso." }, explicacao: "A função principal do epitélio é revestir e regular passagem de substâncias, com organização polarizada." },
  { id: 374, materia: "bmf1", tema: "bmf1_a2", modulo: 1, dificuldade: 2, correta: 2, enunciado: "Na cicatrização inicial, qual tipo de colágeno tende a predominar no tecido de granulação?", opcoes: ["A) Colágeno tipo II", "B) Colágeno tipo I exclusivo", "C) Colágeno tipo III", "D) Ausência de colágeno"], explicacao_geral: "A matriz inicial é mais imatura e rica em colágeno tipo III, com remodelação posterior.", explicacoes_opcoes: { A: "Incorreta: tipo II é mais associado à cartilagem.", B: "Incorreta: o tipo I aumenta mais na fase de maturação.", C: "Correta: é o padrão típico da fase proliferativa inicial.", D: "Incorreta: já há deposição de matriz nessa fase." }, explicacao: "A sequência comum é matriz inicial com colágeno III e, depois, reforço mecânico com maior proporção de colágeno I." },
  { id: 375, materia: "bmf1", tema: "bmf1_a2", modulo: 1, dificuldade: 2, correta: 3, enunciado: "Qual descrição corresponde ao músculo liso em comparação ao esquelético?", opcoes: ["A) Estriado e multinucleado periférico", "B) Voluntário e restrito aos membros", "C) Com discos intercalares típicos", "D) Não estriado, com núcleo central e controle involuntário"], explicacao_geral: "Músculo liso e esquelético diferem por morfologia, localização e controle neural.", explicacoes_opcoes: { A: "Incorreta: essa é a descrição do músculo esquelético.", B: "Incorreta: músculo liso é involuntário e visceral.", C: "Incorreta: discos intercalares são do músculo cardíaco.", D: "Correta: resume as características clássicas do músculo liso." }, explicacao: "No músculo liso, as células são fusiformes, sem estriações visíveis e com núcleo central." },
  { id: 376, materia: "bmf1", tema: "bmf1_a2", modulo: 1, dificuldade: 3, correta: 1, enunciado: "Na desmielinização do sistema nervoso central, qual célula é responsável pela mielina?", opcoes: ["A) Célula de Schwann", "B) Oligodendrócito", "C) Astrócito protoplasmático", "D) Micróglia"], explicacao_geral: "No SNC, a mielina é produzida por oligodendrócitos; no SNP, por células de Schwann.", explicacoes_opcoes: { A: "Incorreta: Schwann atua no sistema nervoso periférico.", B: "Correta: é a célula mielinizante do SNC.", C: "Incorreta: astrócitos têm função de suporte e homeostase.", D: "Incorreta: micróglia atua principalmente em vigilância imune." }, explicacao: "A distinção entre oligodendrócito (SNC) e Schwann (SNP) é central para interpretar doenças desmielinizantes." },
  { id: 377, materia: "bmf1", tema: "bmf1_a2", modulo: 1, dificuldade: 1, correta: 0, enunciado: "Nas primeiras horas da inflamação aguda em uma ferida, qual leucócito predomina?", opcoes: ["A) Neutrófilo", "B) Linfócito T", "C) Eosinófilo", "D) Plasmócito"], explicacao_geral: "A resposta inflamatória inicial é dominada por neutrófilos.", explicacoes_opcoes: { A: "Correta: neutrófilos chegam precocemente ao foco inflamatório.", B: "Incorreta: linfócitos predominam mais em respostas adaptativas ou crônicas.", C: "Incorreta: eosinófilos são mais relacionados a alergia e parasitose.", D: "Incorreta: plasmócitos são tardios e ligados à produção de anticorpos." }, explicacao: "A cronologia celular da inflamação aguda começa com neutrófilos e evolui para maior participação de macrófagos." },
  { id: 378, materia: "bmf1", tema: "bmf1_a2", modulo: 1, dificuldade: 2, correta: 1, enunciado: "Em urticária aguda mediada por hipersensibilidade imediata, qual célula libera histamina de forma central?", opcoes: ["A) Macrófago", "B) Mastócito", "C) Fibroblasto", "D) Célula endotelial"], explicacao_geral: "Mastócitos contêm grânulos com mediadores vasoativos, incluindo histamina.", explicacoes_opcoes: { A: "Incorreta: macrófagos participam da inflamação, mas não são a principal fonte imediata de histamina.", B: "Correta: desgranulação mastocitária explica edema e prurido rápidos.", C: "Incorreta: fibroblastos atuam sobretudo na matriz e reparo.", D: "Incorreta: endotélio responde aos mediadores, mas não é o principal efetor da fase imediata." }, explicacao: "A rápida instalação de urtica e angioedema é compatível com ativação e desgranulação de mastócitos." },
  { id: 379, materia: "bmf1", tema: "bmf1_a2", modulo: 1, dificuldade: 2, correta: 2, enunciado: "O endotélio dos capilares alveolares é classificado como:", opcoes: ["A) Epitélio estratificado pavimentoso", "B) Epitélio pseudoestratificado ciliado", "C) Epitélio simples pavimentoso", "D) Epitélio simples cúbico"], explicacao_geral: "A barreira alvéolo-capilar é extremamente delgada para favorecer difusão gasosa.", explicacoes_opcoes: { A: "Incorreta: múltiplas camadas dificultariam a troca gasosa.", B: "Incorreta: esse padrão é típico de vias aéreas condutoras.", C: "Correta: camada única de células achatadas.", D: "Incorreta: epitélio cúbico é mais espesso que o ideal para difusão alveolar." }, explicacao: "Endotélio capilar pulmonar e pneumócitos tipo I compartilham morfologia pavimentosa simples para maximizar eficiência de trocas." },
  { id: 380, materia: "bmf1", tema: "bmf1_a2", modulo: 1, dificuldade: 2, correta: 1, enunciado: "Sobre o epitélio do esôfago, qual afirmação está correta?", opcoes: ["A) Todo epitélio estratificado é necessariamente queratinizado", "B) O esôfago é revestido por epitélio estratificado pavimentoso não queratinizado", "C) O esôfago normal é revestido por epitélio simples colunar", "D) O epitélio esofágico normal possui cílios e células caliciformes abundantes"], explicacao_geral: "A mucosa esofágica precisa resistir à abrasão, sem o padrão de queratinização intensa da pele.", explicacoes_opcoes: { A: "Incorreta: estratificação e queratinização são conceitos diferentes.", B: "Correta: é o padrão histológico usual do esôfago.", C: "Incorreta: epitélio simples colunar predomina no estômago e intestino.", D: "Incorreta: esse padrão não corresponde ao esôfago normal." }, explicacao: "O revestimento estratificado não queratinizado oferece proteção mecânica em ambiente úmido." },
  { id: 381, materia: "bmf1", tema: "bmf1_a2", modulo: 1, dificuldade: 3, correta: 3, enunciado: "Qual diferença conceitual entre metaplasia e displasia está correta?", opcoes: ["A) São termos equivalentes para o mesmo processo", "B) Displasia é sempre fisiológica e reversível sem risco", "C) Metaplasia representa apenas aumento do número celular", "D) Metaplasia é substituição adaptativa de um tipo celular maduro por outro; displasia envolve atipia e desorganização arquitetural"], explicacao_geral: "Metaplasia e displasia podem coexistir, mas não são sinônimos.", explicacoes_opcoes: { A: "Incorreta: os conceitos são distintos.", B: "Incorreta: displasia pode ter significado pré-neoplásico.", C: "Incorreta: isso descreve hiperplasia.", D: "Correta: esta é a distinção fundamental entre os dois processos." }, explicacao: "Metaplasia é adaptação fenotípica; displasia é alteração de maturação e arquitetura celular com potencial de progressão neoplásica." }
];

function validar(arr) {
  const g = [0, 1, 2, 3].map((k) => arr.filter((q) => q.correta === k).length).join(",");
  const d = { 1: 0, 2: 0, 3: 0 };
  for (const q of arr) d[q.dificuldade]++;
  if (g !== "2,3,2,3") throw new Error(`Gabarito inválido: ${g}`);
  if (`${d[1]}/${d[2]}/${d[3]}` !== "2/5/3") throw new Error(`Dificuldade inválida: ${d[1]}/${d[2]}/${d[3]}`);
}

function main() {
  validar(novas);
  const data = JSON.parse(fs.readFileSync(file, "utf8"));
  const map = Object.fromEntries(novas.map((q) => [q.id, q]));
  let n = 0;
  for (let i = 0; i < data.questoes.length; i++) {
    if (map[data.questoes[i].id] && data.questoes[i].tema === "bmf1_a2") {
      data.questoes[i] = map[data.questoes[i].id];
      n++;
    }
  }
  if (n !== 10) throw new Error(`bmf1_a2: esperado 10, obtido ${n}`);
  fs.writeFileSync(file, JSON.stringify(data, null, 2) + "\n", "utf8");
  JSON.parse(fs.readFileSync(file, "utf8"));
  console.log("bmf1_a2 OK");
}

main();
