import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const file = path.join(__dirname, "..", "data", "questoes.json");
const novas = [
{id:442,materia:"bmf1",tema:"bmf1_a6",modulo:1,dificuldade:2,correta:0,enunciado:"Qual conjunto contÃ©m apenas estruturas do esqueleto axial?",opcoes:["A) CrÃ¢nio, coluna vertebral, costelas e esterno","B) EscÃ¡pula, clavÃ­cula e Ãºmero","C) FÃªmur, tÃ­bia e fÃ­bula","D) RÃ¡dio, ulna e carpos"],explicacao_geral:"O axial compÃµe o eixo central do corpo; membros e cinturas sÃ£o apendiculares.",explicacoes_opcoes:{A:"Correta: reÃºne exclusivamente componentes axiais.",B:"Incorreta: sÃ£o elementos do membro superior/cintura escapular.",C:"Incorreta: estruturas do membro inferior.",D:"Incorreta: estruturas do antebraÃ§o e mÃ£o."},explicacao:"A separaÃ§Ã£o axial/apendicular orienta descriÃ§Ã£o anatÃ´mica e anÃ¡lise de trauma."},
{id:443,materia:"bmf1",tema:"bmf1_a6",modulo:1,dificuldade:1,correta:1,enunciado:"As costelas verdadeiras correspondem, em geral, a quais pares?",opcoes:["A) 8 a 10","B) 1 a 7","C) 11 e 12","D) 6 a 12"],explicacao_geral:"Costelas 1-7 articulam-se diretamente ao esterno por cartilagem prÃ³pria.",explicacoes_opcoes:{A:"Incorreta: 8-10 sÃ£o costelas falsas.",B:"Correta: este Ã© o grupo das verdadeiras.",C:"Incorreta: 11-12 sÃ£o flutuantes.",D:"Incorreta: mistura grupos com articulaÃ§Ã£o diferente."},explicacao:"A classificaÃ§Ã£o costal Ã© Ãºtil para interpretar lesÃ£o torÃ¡cica e relaÃ§Ã£o com esterno."},
{id:444,materia:"bmf1",tema:"bmf1_a6",modulo:1,dificuldade:2,correta:2,enunciado:"Na posiÃ§Ã£o anatÃ´mica, em relaÃ§Ã£o Ã  ulna, o rÃ¡dio estÃ¡:",opcoes:["A) Medial e posterior","B) Medial e proximal","C) Lateral, no lado do polegar","D) Medial, no lado do quinto dedo"],explicacao_geral:"Com o antebraÃ§o em supinaÃ§Ã£o, o rÃ¡dio fica do lado lateral.",explicacoes_opcoes:{A:"Incorreta: nÃ£o ocupa essa posiÃ§Ã£o em referÃªncia anatÃ´mica.",B:"Incorreta: o rÃ¡dio nÃ£o Ã© medial Ã  ulna.",C:"Correta: lado do polegar corresponde ao rÃ¡dio.",D:"Incorreta: lado do quinto dedo corresponde Ã  ulna."},explicacao:"A relaÃ§Ã£o rÃ¡dio-ulna muda em pronaÃ§Ã£o/supinaÃ§Ã£o, mas a descriÃ§Ã£o padrÃ£o usa posiÃ§Ã£o anatÃ´mica."},
{id:445,materia:"bmf1",tema:"bmf1_a6",modulo:1,dificuldade:2,correta:3,enunciado:"A vÃ©rtebra proeminente palpÃ¡vel na base do pescoÃ§o Ã© geralmente:",opcoes:["A) C5","B) C1","C) T2","D) C7"],explicacao_geral:"C7 costuma ter processo espinhoso mais evidente ao exame fÃ­sico.",explicacoes_opcoes:{A:"Incorreta: nÃ£o Ã© o marco palpÃ¡vel mais tÃ­pico.",B:"Incorreta: atlas nÃ£o possui processo espinhoso proeminente.",C:"Incorreta: pode palpar-se, mas o marco clÃ¡ssico Ã© cervical.",D:"Correta: C7 Ã© a referÃªncia anatÃ´mica tradicional."},explicacao:"A identificaÃ§Ã£o da C7 auxilia contagem de nÃ­veis vertebrais em exame clÃ­nico."},
{id:446,materia:"bmf1",tema:"bmf1_a6",modulo:1,dificuldade:3,correta:0,enunciado:"Qual associaÃ§Ã£o entre forame craniano e estrutura Ã© correta?",opcoes:["A) Forame oval - nervo mandibular (V3)","B) Forame redondo - nervo facial (VII)","C) Forame Ã³ptico - nervo olfatÃ³rio (I)","D) Forame magno - nervo trigÃªmeo (V)"],explicacao_geral:"Os forames da base do crÃ¢nio tÃªm conteÃºdos neurovasculares especÃ­ficos.",explicacoes_opcoes:{A:"Correta: V3 atravessa o forame oval.",B:"Incorreta: V2 passa pelo forame redondo.",C:"Incorreta: o nervo Ã³ptico (II) passa pelo canal Ã³ptico.",D:"Incorreta: o trigÃªmeo nÃ£o atravessa o forame magno."},explicacao:"Conhecer mapeamento de forames evita erros de localizaÃ§Ã£o em correlaÃ§Ã£o clÃ­nica e radiolÃ³gica."},
{id:447,materia:"bmf1",tema:"bmf1_a6",modulo:1,dificuldade:1,correta:1,enunciado:"A coluna torÃ¡cica possui tipicamente:",opcoes:["A) 7 vÃ©rtebras com lordose","B) 12 vÃ©rtebras com cifose","C) 5 vÃ©rtebras com lordose","D) 12 vÃ©rtebras com lordose"],explicacao_geral:"A curvatura fisiolÃ³gica torÃ¡cica Ã© cifÃ³tica.",explicacoes_opcoes:{A:"Incorreta: sete vÃ©rtebras corresponde ao segmento cervical.",B:"Correta: nÃºmero e curvatura estÃ£o corretos.",C:"Incorreta: cinco vÃ©rtebras corresponde ao segmento lombar.",D:"Incorreta: a curvatura torÃ¡cica nÃ£o Ã© lordose."},explicacao:"O padrÃ£o de curvaturas fisiolÃ³gicas ajuda na anÃ¡lise postural e na interpretaÃ§Ã£o de imagem."},
{id:448,materia:"bmf1",tema:"bmf1_a6",modulo:1,dificuldade:2,correta:2,enunciado:"ApÃ³s queda sobre a mÃ£o espalmada com punho em extensÃ£o, qual osso do carpo Ã© classicamente fraturado?",opcoes:["A) Pisiforme","B) Hamato","C) Escafoide","D) Semilunar"],explicacao_geral:"O escafoide Ã© particularmente vulnerÃ¡vel nesse mecanismo de trauma.",explicacoes_opcoes:{A:"Incorreta: nÃ£o Ã© o mais frequente nesse mecanismo.",B:"Incorreta: fratura menos tÃ­pica para essa queda.",C:"Correta: Ã© o diagnÃ³stico clÃ¡ssico da queda sobre mÃ£o estendida.",D:"Incorreta: pode lesar-se, mas nÃ£o Ã© o mais caracterÃ­stico."},explicacao:"A suspeita clÃ­nica de fratura de escafoide exige atenÃ§Ã£o pelo risco de complicaÃ§Ãµes vasculares."},
{id:449,materia:"bmf1",tema:"bmf1_a6",modulo:1,dificuldade:3,correta:3,enunciado:"Em idoso com queda da prÃ³pria altura e dor no quadril, o local de fratura por fragilidade mais frequente Ã©:",opcoes:["A) TÃ­bia proximal","B) Corpo do Ã­lio","C) Patela","D) Colo do fÃªmur"],explicacao_geral:"Fraturas do colo femoral sÃ£o tÃ­picas em osteoporose apÃ³s trauma de baixa energia.",explicacoes_opcoes:{A:"Incorreta: nÃ£o Ã© o sÃ­tio mais comum nesse cenÃ¡rio.",B:"Incorreta: possÃ­vel, porÃ©m menos tÃ­pico.",C:"Incorreta: mecanismo e epidemiologia diferentes.",D:"Correta: Ã© o local clÃ¡ssico em fratura de quadril por fragilidade."},explicacao:"Esse padrÃ£o tem grande impacto funcional e prognÃ³stico, exigindo diagnÃ³stico e manejo precoces."},
{id:450,materia:"bmf1",tema:"bmf1_a6",modulo:1,dificuldade:2,correta:1,enunciado:"Na perna, qual osso suporta a maior parte da carga axial em ortostatismo?",opcoes:["A) FÃ­bula","B) TÃ­bia","C) CalcÃ¢neo","D) TÃ¡lus"],explicacao_geral:"A tÃ­bia Ã© o principal osso de transmissÃ£o de carga da perna.",explicacoes_opcoes:{A:"Incorreta: fÃ­bula participa mais da estabilidade lateral.",B:"Correta: a carga axial principal passa pela tÃ­bia.",C:"Incorreta: calcÃ¢neo recebe carga no retropÃ©, nÃ£o substitui a tÃ­bia.",D:"Incorreta: tÃ¡lus participa da articulaÃ§Ã£o do tornozelo, mas nÃ£o Ã© o principal osso da perna."},explicacao:"Diferenciar funÃ§Ã£o de tÃ­bia e fÃ­bula ajuda na interpretaÃ§Ã£o de padrÃµes de fratura e sobrecarga."},
{id:451,materia:"bmf1",tema:"bmf1_a6",modulo:1,dificuldade:3,correta:3,enunciado:"Comparando ombro e quadril, qual afirmaÃ§Ã£o estÃ¡ correta?",opcoes:["A) Ombro Ã© mais estÃ¡vel por ter cavidade mais profunda","B) Quadril apresenta maior amplitude global que o ombro","C) Ambos tÃªm estabilidade e mobilidade equivalentes","D) Ombro prioriza mobilidade; quadril prioriza estabilidade"],explicacao_geral:"A morfologia articular do ombro favorece amplitude, enquanto o quadril favorece contenÃ§Ã£o.",explicacoes_opcoes:{A:"Incorreta: a cavidade glenoidal Ã© relativamente rasa.",B:"Incorreta: o ombro costuma ter maior amplitude.",C:"Incorreta: hÃ¡ diferenÃ§a funcional importante entre eles.",D:"Correta: resume o principal contraste biomecÃ¢nico."},explicacao:"A relaÃ§Ã£o mobilidade-estabilidade explica a maior frequÃªncia de instabilidade glenoumeral em comparaÃ§Ã£o ao quadril."}
];
function validar(a){const g=[0,1,2,3].map(k=>a.filter(q=>q.correta===k).length).join(",");const d={1:0,2:0,3:0};for(const q of a)d[q.dificuldade]++;if(g!=="2,3,2,3")throw new Error(g);if(`${d[1]}/${d[2]}/${d[3]}`!=="2/5/3")throw new Error(`${d[1]}/${d[2]}/${d[3]}`);}
function main(){validar(novas);const data=JSON.parse(fs.readFileSync(file,"utf8"));const map=Object.fromEntries(novas.map(q=>[q.id,q]));let n=0;for(let i=0;i<data.questoes.length;i++){if(map[data.questoes[i].id]&&data.questoes[i].tema==="bmf1_a6"){data.questoes[i]=map[data.questoes[i].id];n++;}}if(n!==10)throw new Error(`bmf1_a6 ${n}`);fs.writeFileSync(file,JSON.stringify(data,null,2)+"\n","utf8");JSON.parse(fs.readFileSync(file,"utf8"));console.log("bmf1_a6 OK");}
main();
