import fs from "fs"; import path from "path"; import { fileURLToPath } from "url";
const __dirname = path.dirname(fileURLToPath(import.meta.url)); const file = path.join(__dirname, "..", "data", "questoes.json");
const novas = [
{id:422,materia:"bmf1",tema:"bmf1_a4",modulo:1,dificuldade:3,correta:3,enunciado:"Em carcinoma invasivo com estroma endurecido, a reaÃ§Ã£o fibrosa peritumoral Ã© chamada de:",opcoes:["A) Metaplasia","B) Hiperplasia nodular","C) Necrose caseosa","D) Desmoplasia"],explicacao_geral:"Desmoplasia representa produÃ§Ã£o estromal fibrosa reacional associada ao tumor.",explicacoes_opcoes:{A:"Incorreta: metaplasia Ã© substituiÃ§Ã£o de tipo celular.",B:"Incorreta: hiperplasia nÃ£o define o padrÃ£o estromal descrito.",C:"Incorreta: necrose caseosa Ã© outro processo patolÃ³gico.",D:"Correta: o termo descreve o estroma fibroso denso neoplÃ¡sico."},explicacao:"A rigidez tecidual em alguns tumores epiteliais decorre do aumento de matriz conjuntiva reacional."},
{id:423,materia:"bmf1",tema:"bmf1_a4",modulo:1,dificuldade:1,correta:0,enunciado:"Quais componentes formam a matriz extracelular do tecido conjuntivo?",opcoes:["A) Fibras e substÃ¢ncia fundamental","B) Apenas filamentos de actina","C) Somente queratina","D) Apenas lipÃ­dios neutros"],explicacao_geral:"A matriz combina fase fibrosa e fase amorfa hidratada.",explicacoes_opcoes:{A:"Correta: fibras colÃ¡genas/elÃ¡sticas/reticulares + substÃ¢ncia fundamental.",B:"Incorreta: actina Ã© citoesqueleto intracelular.",C:"Incorreta: queratina Ã© tÃ­pica de epitÃ©lio.",D:"Incorreta: lipÃ­dios nÃ£o definem matriz conjuntiva geral."},explicacao:"A diversidade de matriz explica funÃ§Ãµes de suporte mecÃ¢nico, hidrataÃ§Ã£o e troca molecular no conjuntivo."},
{id:424,materia:"bmf1",tema:"bmf1_a4",modulo:1,dificuldade:2,correta:1,enunciado:"Qual associaÃ§Ã£o entre tendÃ£o e derme reticular estÃ¡ correta?",opcoes:["A) Ambos sÃ£o conjuntivo frouxo","B) TendÃ£o Ã© denso regular e derme reticular Ã© denso irregular","C) TendÃ£o Ã© cartilagem hialina e derme Ã© epitÃ©lio","D) Ambos sÃ£o tecido adiposo especializado"],explicacao_geral:"A orientaÃ§Ã£o das fibras acompanha o padrÃ£o de carga mecÃ¢nica em cada tecido.",explicacoes_opcoes:{A:"Incorreta: conjuntivo frouxo nÃ£o descreve tendÃ£o.",B:"Correta: tendÃ£o tem fibras paralelas; derme, arranjo multidirecional.",C:"Incorreta: classificaÃ§Ã£o tecidual inadequada.",D:"Incorreta: nÃ£o corresponde Ã  histologia desses tecidos."},explicacao:"No tendÃ£o, o alinhamento paralelo favorece traÃ§Ã£o unidirecional; na derme, a rede irregular resiste forÃ§as variadas."},
{id:425,materia:"bmf1",tema:"bmf1_a4",modulo:1,dificuldade:2,correta:2,enunciado:"Na classificaÃ§Ã£o histolÃ³gica tradicional, o sangue Ã© considerado:",opcoes:["A) EpitÃ©lio especializado","B) Tecido muscular lÃ­quido","C) Tecido conjuntivo especializado","D) Tecido nervoso circulante"],explicacao_geral:"O plasma funciona como matriz fluida para os elementos celulares.",explicacoes_opcoes:{A:"Incorreta: sangue nÃ£o forma revestimento epitelial.",B:"Incorreta: nÃ£o hÃ¡ organizaÃ§Ã£o contrÃ¡til muscular no sangue.",C:"Correta: essa Ã© a classificaÃ§Ã£o mais adotada em histologia.",D:"Incorreta: nÃ£o corresponde a tecido nervoso."},explicacao:"A presenÃ§a de cÃ©lulas suspensas em matriz extracelular justifica sua inclusÃ£o no grupo dos tecidos conjuntivos."},
{id:426,materia:"bmf1",tema:"bmf1_a4",modulo:1,dificuldade:2,correta:3,enunciado:"Na contraÃ§Ã£o da ferida durante a cicatrizaÃ§Ã£o, qual cÃ©lula tem papel central?",opcoes:["A) Osteoclasto","B) NeutrÃ³filo","C) CÃ©lula endotelial","D) Miofibroblasto"],explicacao_geral:"Miofibroblastos combinam sÃ­ntese de matriz com capacidade contrÃ¡til.",explicacoes_opcoes:{A:"Incorreta: osteoclasto atua no osso.",B:"Incorreta: neutrÃ³filos sÃ£o predominantes na fase inflamatÃ³ria inicial.",C:"Incorreta: endotÃ©lio participa da angiogÃªnese, nÃ£o da contraÃ§Ã£o principal.",D:"Correta: essa cÃ©lula contribui diretamente para retraÃ§Ã£o da ferida."},explicacao:"A contraÃ§Ã£o cicatricial depende de cÃ©lulas com fenÃ³tipo fibroblÃ¡stico e proteÃ­nas contrÃ¡teis."},
{id:427,materia:"bmf1",tema:"bmf1_a4",modulo:1,dificuldade:2,correta:0,enunciado:"Qual funÃ§Ã£o descreve melhor o papel dos macrÃ³fagos no reparo tecidual?",opcoes:["A) Fagocitose de detritos e regulaÃ§Ã£o por citocinas","B) ProduÃ§Ã£o principal de hemoglobina","C) SÃ­ntese exclusiva de elastina dÃ©rmica","D) FormaÃ§Ã£o de osteoide"],explicacao_geral:"MacrÃ³fagos conectam limpeza inflamatÃ³ria e coordenaÃ§Ã£o da fase reparativa.",explicacoes_opcoes:{A:"Correta: removem debris e modulam outros tipos celulares.",B:"Incorreta: hemoglobina Ã© produzida por linhagem eritroide.",C:"Incorreta: nÃ£o Ã© funÃ§Ã£o exclusiva de macrÃ³fagos.",D:"Incorreta: osteoide Ã© sintetizado por osteoblastos."},explicacao:"A permanÃªncia de macrÃ³fagos no leito da lesÃ£o orienta a transiÃ§Ã£o entre inflamaÃ§Ã£o e reparo."},
{id:428,materia:"bmf1",tema:"bmf1_a4",modulo:1,dificuldade:1,correta:1,enunciado:"As fibras reticulares sÃ£o formadas predominantemente por:",opcoes:["A) ColÃ¡geno tipo I","B) ColÃ¡geno tipo III","C) Elastina pura","D) Queratina"],explicacao_geral:"Reticulina corresponde a uma rede fina de colÃ¡geno tipo III.",explicacoes_opcoes:{A:"Incorreta: tipo I predomina em fibras colÃ¡genas espessas.",B:"Correta: compÃµe a base das fibras reticulares.",C:"Incorreta: elastina Ã© outro sistema fibrilar.",D:"Incorreta: queratina Ã© proteÃ­na epitelial."},explicacao:"Em reparo inicial e em Ã³rgÃ£os linfoides, o padrÃ£o reticular depende do colÃ¡geno tipo III."},
{id:429,materia:"bmf1",tema:"bmf1_a4",modulo:1,dificuldade:2,correta:2,enunciado:"Qual mecanismo estÃ¡ mais relacionado a queloide e cicatriz hipertrÃ³fica?",opcoes:["A) Falha total de fibroblastos","B) DestruiÃ§Ã£o completa de matriz","C) DeposiÃ§Ã£o excessiva de colÃ¡geno e remodelaÃ§Ã£o desregulada","D) Metaplasia cartilaginosa universal"],explicacao_geral:"Nessas cicatrizes hÃ¡ produÃ§Ã£o de matriz acima do necessÃ¡rio para reparo funcional.",explicacoes_opcoes:{A:"Incorreta: o problema nÃ£o Ã© ausÃªncia celular.",B:"Incorreta: ocorre excesso, nÃ£o destruiÃ§Ã£o global.",C:"Correta: resume a fisiopatologia principal.",D:"Incorreta: nÃ£o Ã© o padrÃ£o tÃ­pico dessas lesÃµes."},explicacao:"O desequilÃ­brio entre sÃ­ntese e degradaÃ§Ã£o de matriz resulta em cicatriz exuberante."},
{id:430,materia:"bmf1",tema:"bmf1_a4",modulo:1,dificuldade:3,correta:3,enunciado:"Na cartilagem articular, quais componentes retÃªm Ã¡gua e contribuem para resistÃªncia Ã  compressÃ£o?",opcoes:["A) Discos intercalares","B) Filamentos de queratina","C) Mielina perifÃ©rica","D) Glicosaminoglicanos e proteoglicanos"],explicacao_geral:"A substÃ¢ncia fundamental rica em GAGs/proteoglicanos confere comportamento viscoelÃ¡stico.",explicacoes_opcoes:{A:"Incorreta: discos intercalares sÃ£o do miocÃ¡rdio.",B:"Incorreta: queratina nÃ£o Ã© o principal componente cartilaginoso.",C:"Incorreta: mielina pertence ao tecido nervoso.",D:"Correta: esses compostos atraem Ã¡gua e amortecem carga."},explicacao:"A alta hidrataÃ§Ã£o da matriz cartilaginosa depende de macromolÃ©culas aniÃ´nicas, essenciais para funÃ§Ã£o articular."},
{id:431,materia:"bmf1",tema:"bmf1_a4",modulo:1,dificuldade:3,correta:1,enunciado:"Na esclerodermia, qual alteraÃ§Ã£o tecidual Ã© mais compatÃ­vel com o quadro clÃ­nico de pele endurecida?",opcoes:["A) Perda global de matriz e vasodilataÃ§Ã£o persistente","B) Fibrose com acÃºmulo de matriz e alteraÃ§Ã£o microvascular","C) Necrose muscular aguda isolada","D) SubstituiÃ§Ã£o da derme por cartilagem"],explicacao_geral:"A doenÃ§a envolve processo fibroproliferativo e comprometimento vascular.",explicacoes_opcoes:{A:"Incorreta: o padrÃ£o Ã© de excesso de matriz, nÃ£o perda.",B:"Correta: integra os dois eixos principais da doenÃ§a.",C:"Incorreta: nÃ£o representa o mecanismo predominante.",D:"Incorreta: nÃ£o Ã© transformaÃ§Ã£o tÃ­pica da derme."},explicacao:"A manifestaÃ§Ã£o cutÃ¢nea reflete combinaÃ§Ã£o de microangiopatia e fibrose progressiva do tecido conjuntivo."}
];
function validar(a){const g=[0,1,2,3].map(k=>a.filter(q=>q.correta===k).length).join(",");const d={1:0,2:0,3:0};for(const q of a)d[q.dificuldade]++;if(g!=="2,3,2,3")throw new Error(g);if(`${d[1]}/${d[2]}/${d[3]}`!=="2/5/3")throw new Error(`${d[1]}/${d[2]}/${d[3]}`);}
function main(){validar(novas);const data=JSON.parse(fs.readFileSync(file,"utf8"));const map=Object.fromEntries(novas.map(q=>[q.id,q]));let n=0;for(let i=0;i<data.questoes.length;i++){if(map[data.questoes[i].id]&&data.questoes[i].tema==="bmf1_a4"){data.questoes[i]=map[data.questoes[i].id];n++;}}if(n!==10)throw new Error(`bmf1_a4 ${n}`);fs.writeFileSync(file,JSON.stringify(data,null,2)+"\n","utf8");JSON.parse(fs.readFileSync(file,"utf8"));console.log("bmf1_a4 OK");}
main();
