import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const file = path.join(__dirname, "..", "data", "questoes.json");
const novas = [
{id:412,materia:"bmf1",tema:"bmf1_a3",modulo:1,dificuldade:3,correta:3,enunciado:"No osso longo, qual componente forma a camada externa mais resistente Ã  flexÃ£o e torÃ§Ã£o?",opcoes:["A) Medula Ã³ssea amarela","B) Cartilagem articular","C) PeriÃ³steo isoladamente","D) Osso compacto (cortical)"],explicacao_geral:"A cortical concentra material mineralizado organizado para suportar carga mecÃ¢nica.",explicacoes_opcoes:{A:"Incorreta: a medula ocupa cavidades internas.",B:"Incorreta: cartilagem reveste superfÃ­cies articulares.",C:"Incorreta: periÃ³steo nÃ£o substitui a massa cortical.",D:"Correta: a cortical Ã© a principal estrutura de resistÃªncia externa."},explicacao:"A combinaÃ§Ã£o de densidade mineral e organizaÃ§Ã£o lamelar torna a cortical essencial para resistÃªncia estrutural do osso longo."},
{id:413,materia:"bmf1",tema:"bmf1_a3",modulo:1,dificuldade:1,correta:0,enunciado:"CrÃ¢nio, coluna, costelas e esterno pertencem a qual divisÃ£o do esqueleto?",opcoes:["A) Esqueleto axial","B) Esqueleto apendicular","C) Cintura escapular","D) Membro superior"],explicacao_geral:"O esqueleto axial constitui o eixo central do corpo.",explicacoes_opcoes:{A:"Correta: reÃºne cabeÃ§a e tronco Ã³sseo.",B:"Incorreta: apendicular inclui membros e cinturas.",C:"Incorreta: Ã© apenas parte do apendicular.",D:"Incorreta: nÃ£o inclui essas estruturas."},explicacao:"A distinÃ§Ã£o axial/apendicular Ã© base para descriÃ§Ã£o anatÃ´mica e raciocÃ­nio traumato-ortopÃ©dico."},
{id:414,materia:"bmf1",tema:"bmf1_a3",modulo:1,dificuldade:3,correta:1,enunciado:"Em fratura que compromete a placa epifisÃ¡ria de uma crianÃ§a, a principal preocupaÃ§Ã£o tardia Ã©:",opcoes:["A) SubstituiÃ§Ã£o do osso por tecido fibroso permanente","B) DistÃºrbio do crescimento longitudinal do osso","C) ConsolidaÃ§Ã£o imediata em 24 horas","D) AusÃªncia completa de dor"],explicacao_geral:"A fise Ã© determinante para crescimento em comprimento.",explicacoes_opcoes:{A:"Incorreta: nÃ£o Ã© a consequÃªncia tÃ­pica principal.",B:"Correta: dano fisÃ¡rio pode gerar encurtamento ou deformidade angular.",C:"Incorreta: consolidaÃ§Ã£o depende de tempo biolÃ³gico.",D:"Incorreta: lesÃµes fisÃ¡rias podem ser dolorosas."},explicacao:"O envolvimento da placa de crescimento exige seguimento porque a alteraÃ§Ã£o pode aparecer meses depois da fratura."},
{id:415,materia:"bmf1",tema:"bmf1_a3",modulo:1,dificuldade:2,correta:2,enunciado:"Qual alternativa diferencia ossificaÃ§Ã£o endocondral e intramembranosa?",opcoes:["A) Endocondral ocorre sem qualquer cartilagem","B) Intramembranosa exige placa epifisÃ¡ria","C) Endocondral substitui molde cartilaginoso; intramembranosa ocorre diretamente no mesÃªnquima","D) Ambas sÃ£o exclusivas do mesmo grupo de ossos"],explicacao_geral:"O ponto-chave Ã© a presenÃ§a ou ausÃªncia de modelo cartilaginoso inicial.",explicacoes_opcoes:{A:"Incorreta: a presenÃ§a de cartilagem Ã© central na endocondral.",B:"Incorreta: placa epifisÃ¡ria nÃ£o define a intramembranosa.",C:"Correta: descreve corretamente os mecanismos.",D:"Incorreta: os processos ocorrem em ossos diferentes."},explicacao:"Esse contraste explica por que ossos longos e ossos da calvÃ¡ria tÃªm vias de formaÃ§Ã£o distintas."},
{id:416,materia:"bmf1",tema:"bmf1_a3",modulo:1,dificuldade:2,correta:3,enunciado:"Em metÃ¡stase Ã³ssea lÃ­tica, qual alteraÃ§Ã£o estrutural contribui para dor mecÃ¢nica precoce?",opcoes:["A) Espessamento imediato da cortical","B) Aumento uniforme da mineralizaÃ§Ã£o","C) FormaÃ§Ã£o de cartilagem hialina no foco","D) Perda de trabÃ©culas com reduÃ§Ã£o da estabilidade interna"],explicacao_geral:"A desorganizaÃ§Ã£o trabecular reduz a capacidade de distribuir cargas.",explicacoes_opcoes:{A:"Incorreta: padrÃ£o lÃ­tico nÃ£o gera espessamento protetor inicial.",B:"Incorreta: esse padrÃ£o nÃ£o define lesÃ£o lÃ­tica.",C:"Incorreta: nÃ£o Ã© mecanismo tÃ­pico.",D:"Correta: a perda trabecular favorece fragilidade e dor Ã  carga."},explicacao:"A esponjosa Ã© determinante para sustentaÃ§Ã£o em vÃ¡rias regiÃµes; sua destruiÃ§Ã£o precoce tem impacto clÃ­nico relevante."},
{id:417,materia:"bmf1",tema:"bmf1_a3",modulo:1,dificuldade:2,correta:1,enunciado:"A lei de Wolff afirma que o osso:",opcoes:["A) MantÃ©m arquitetura fixa ao longo da vida","B) Adapta sua arquitetura Ã s cargas mecÃ¢nicas","C) Responde apenas a temperatura corporal","D) NÃ£o sofre influÃªncia do desuso"],explicacao_geral:"O tecido Ã³sseo remodela-se continuamente conforme estÃ­mulo mecÃ¢nico.",explicacoes_opcoes:{A:"Incorreta: o osso Ã© dinÃ¢mico.",B:"Correta: carga e uso modulam organizaÃ§Ã£o estrutural.",C:"Incorreta: nÃ£o Ã© o determinante principal.",D:"Incorreta: o desuso favorece perda de massa."},explicacao:"Esse princÃ­pio fundamenta reabilitaÃ§Ã£o, prevenÃ§Ã£o de osteopenia e interpretaÃ§Ã£o de adaptaÃ§Ã£o estrutural."},
{id:418,materia:"bmf1",tema:"bmf1_a3",modulo:1,dificuldade:1,correta:2,enunciado:"A patela Ã© classificada como osso sesamoide porque:",opcoes:["A) Possui cavidade pneumÃ¡tica","B) Ã‰ osso plano da cintura escapular","C) Desenvolve-se em tendÃ£o e melhora alavanca mecÃ¢nica","D) Ã‰ parte do esqueleto axial"],explicacao_geral:"Sesamoides surgem em tendÃµes e modificam o vetor de forÃ§a muscular.",explicacoes_opcoes:{A:"Incorreta: pneumÃ¡tica nÃ£o Ã© caracterÃ­stica da patela.",B:"Incorreta: nÃ£o pertence Ã  cintura escapular.",C:"Correta: funÃ§Ã£o mecÃ¢nica e localizaÃ§Ã£o tendÃ­nea definem sesamoide.",D:"Incorreta: integra o membro inferior."},explicacao:"A patela aumenta o braÃ§o de momento do quadrÃ­ceps e protege estruturas anteriores do joelho."},
{id:419,materia:"bmf1",tema:"bmf1_a3",modulo:1,dificuldade:2,correta:0,enunciado:"A regiÃ£o entre diÃ¡fise e epÃ­fise em ossos longos recebe o nome de:",opcoes:["A) MetÃ¡fise","B) EndÃ³steo","C) Linha Ã¡spera","D) Cavidade medular"],explicacao_geral:"MetÃ¡fise Ã© Ã¡rea de transiÃ§Ã£o anatÃ´mica e funcional do osso longo.",explicacoes_opcoes:{A:"Correta: Ã© a denominaÃ§Ã£o correta da zona de transiÃ§Ã£o.",B:"Incorreta: endÃ³steo Ã© revestimento interno.",C:"Incorreta: Ã© uma marca anatÃ´mica especÃ­fica do fÃªmur.",D:"Incorreta: cavidade medular Ã© outro compartimento."},explicacao:"Em pediatria e ortopedia, localizaÃ§Ã£o metafisÃ¡ria tem implicaÃ§Ãµes diagnÃ³sticas frequentes."},
{id:420,materia:"bmf1",tema:"bmf1_a3",modulo:1,dificuldade:3,correta:3,enunciado:"A perda de massa trabecular vertebral na osteoporose aumenta principalmente o risco de:",opcoes:["A) Broncoespasmo agudo","B) Glomerulonefrite","C) Arritmia supraventricular","D) Fraturas por compressÃ£o vertebral"],explicacao_geral:"Corpos vertebrais dependem de rede trabecular para resistÃªncia Ã  compressÃ£o axial.",explicacoes_opcoes:{A:"Incorreta: nÃ£o Ã© desfecho Ã³sseo direto.",B:"Incorreta: nÃ£o Ã© complicaÃ§Ã£o mecÃ¢nica do esqueleto.",C:"Incorreta: nÃ£o se relaciona ao mecanismo estrutural Ã³sseo.",D:"Correta: fragilidade trabecular predispÃµe a colapso vertebral."},explicacao:"A clÃ­nica tÃ­pica envolve dor axial e reduÃ§Ã£o de estatura por deformidade compressiva progressiva."},
{id:421,materia:"bmf1",tema:"bmf1_a3",modulo:1,dificuldade:2,correta:1,enunciado:"Em um osso longo, o termo 'diÃ¡fise' refere-se:",opcoes:["A) Ã€ extremidade articular recoberta por cartilagem","B) Ao corpo ou eixo central do osso","C) Ã€ membrana sinovial da articulaÃ§Ã£o prÃ³xima","D) Ã€ placa de crescimento ativa"],explicacao_geral:"DiÃ¡fise, metÃ¡fise e epÃ­fise sÃ£o divisÃµes clÃ¡ssicas do osso longo.",explicacoes_opcoes:{A:"Incorreta: isso descreve epÃ­fise.",B:"Correta: diÃ¡fise Ã© o segmento tubular central.",C:"Incorreta: membrana sinovial nÃ£o define regiÃ£o Ã³ssea.",D:"Incorreta: placa de crescimento estÃ¡ na transiÃ§Ã£o metafisÃ¡ria/epifisÃ¡ria."},explicacao:"A identificaÃ§Ã£o correta das regiÃµes Ã³sseas melhora a comunicaÃ§Ã£o em trauma, cirurgia e imagem."}
];
function validar(a){const g=[0,1,2,3].map(k=>a.filter(q=>q.correta===k).length).join(",");const d={1:0,2:0,3:0};for(const q of a)d[q.dificuldade]++;if(g!=="2,3,2,3")throw new Error(g);if(`${d[1]}/${d[2]}/${d[3]}`!=="2/5/3")throw new Error(`${d[1]}/${d[2]}/${d[3]}`);}
function main(){validar(novas);const data=JSON.parse(fs.readFileSync(file,"utf8"));const map=Object.fromEntries(novas.map(q=>[q.id,q]));let n=0;for(let i=0;i<data.questoes.length;i++){if(map[data.questoes[i].id]&&data.questoes[i].tema==="bmf1_a3"){data.questoes[i]=map[data.questoes[i].id];n++;}}if(n!==10)throw new Error(`bmf1_a3 ${n}`);fs.writeFileSync(file,JSON.stringify(data,null,2)+"\n","utf8");JSON.parse(fs.readFileSync(file,"utf8"));console.log("bmf1_a3 OK");}
main();
